### ISSUE TITLE
assistant-plugins

### ISSUE THREAD

**Issue by philoux811** [Aymkdn/assistant-plugins#1]
![erreur](https://user-images.githubusercontent.com/33841567/33032711-6437fe5e-ce22-11e7-92c7-6ce5ef4b268c.jpg)
je te remercie de faire partagé a tous ta solution ... elle est moins compliqué et elle m'interresse pour la freboox et pour un lapin karotz qui viellit et qui me fait un retour vocal sur certain evenement si je peux le faire aussi avec google home c'est interressant 
j'ai les 4 plugins qui se charge  air media sur la freebox avec les codes api de la freebox j'arrive a la piloter mais il me faut un scenario par chaine par action pour que google home la pilote ...ta solution est  meilleure. mais j'ai une erreur sur le serveur il me met "demande d'autorisation a echoue

**Comment by Aymkdn** [comment]
Tu as bien une Freebox Révolution ?

Lorsque tu lances le programme, tu dois avoir un message qui apparait sur la face avant de ta Freebox Serveur, et il faut appuyer sur la flèche de droite pour autoriser.

**Comment by philoux811** [comment]
oui je la commandais  avec ton plugin sur sarah et puis j'ai fait comme toi
un google home  je controle la domotique le thermostat et la facilité de
google assistant qui va evoluer avec du ifft qui envoi des requetes a ma
box qui elle meme enclenche un scenario et controle la box ou les autres
appareils  ca marche mais un scenario par commande pour la freebox

par contre mon serveur est peu accessible du coup je le vois pas mais je
vais regarder ...et appuyer sur la fleche de droite

je te tiens au courant merci de ton aimable temps

**Comment by Aymkdn** [comment]
Regarde mon commentaire que j'ai édité avec une information supplémentaire.

**Comment by philoux811** [comment]
http://mafreebox.freebox.fr/api/v3/ ceci ne marche pas 
http://hd1.freebox.fr/pub/remote_control?code=12345678&key=vol_dec&long=true  ceci marche tres bien... c'est de cette facon que je la pilote avec la box 
sur le navigateur mafreebox j'ai access 
je recois bien la notification de pusbullet 
mais sur le serveur le plugin freebox echoue 
effectivement j'ai due autoriser air media  sur le serveur pour l'avoir sur l'ordi ma mafreebox mais sur nodje ..ca marche pas j'ai pas la fleche qui clignote et dans parametre gestion des acces c'est permis

**Comment by Aymkdn** [comment]
Désolé, mais je n'ai rien compris... Relis toi, utilise la ponctuation, essaie de faire des phrases plus claires.

http://mafreebox.freebox.fr/api/v3/ devrait afficher quelque chose dans ton navigateur. C'est l'adresse de la Freebox Serveur. Si tu n'y accèdes pas, alors le plugin n'arrivera pas à s'identifier sur la Freebox Serveur... 

http://hd1.freebox.fr/ correspond au boîtier Freebox Player.

**Comment by philoux811** [comment]
je vais regarder pourquoi j'arrive pas y acceder ..par le site mafreebox je
peux

**Comment by philoux811** [comment]
avec un peu de bonne volonté tout marche le serveur a bien proposer
l'assocation dans air media ..cela marche tres bien avec un temps de
d'execution tres rapide je remercie ameyric d'avoir partagée son travail
..c'est une solution qui marche tres bien.
