### ISSUE TITLE
y

### ISSUE THREAD

**Issue by ipaq5876** [Aymkdn/assistant-plugins#10]
{
  "code_telecommande":"71686535",
  "box_to_control":"hd1",
  "search_path":"/Disque dur/Vidéos/",
  "use_Mon_Bouquet":false
}

**Comment by pixell60** [comment]
ok mais je comprend pas ou je doit rentrer ça

**Comment by Aymkdn** [comment]
@pixell60 > je ferai une vidéo la semaine prochaine, cela t'aidera à comprendre j'espère. Un peu de patience.

@ipaq5876 > pourquoi colles-tu ta configuration ici ?!...
