### ISSUE TITLE
Pb de code télécommande

### ISSUE THREAD

**Issue by natt02** [Aymkdn/assistant-plugins#100]
Bonjour,
Super tuto, merci.
J'ai tout configuré comme décrit dans votre vidéo. Les applets se lancent bien mais rien ne se passe. Apparemment, j'ai un problème de code de telecommande que j'ai vérifié à plusieurs reprises et c'est bien celui qui est indiqué sur ma télé dans code telecommande réseau. J'ai fait un redémarrage de ma freebox serveur puis playeur mais rien ne change. J'ai également vérifié qu'il n'y ait pas de mise à jour à faire sur la télécommande. Voici une capture de ma commande:
![image](https://user-images.githubusercontent.com/36511491/36267146-7e7ca8e2-1273-11e8-96b1-0ae17a2f94aa.png)

Pouvez vous m'aider svp?

**Comment by Aymkdn** [comment]
Essaie de changer `hd1` par `hd2` pour `box_to_control` dans le fichier `configuration.json` pour voir si ça change quelque chose.

**Comment by natt02** [comment]
Exceptionnel, ça marche...  merci beaucoup

**Comment by Aymkdn** [comment]
Cool 😀
