### ISSUE TITLE
Evolution ?

### ISSUE THREAD

**Issue by titithebad** [Aymkdn/assistant-plugins#101]
Est-ce que tu peux commander avec ton système d'autres fonctionnalités de la Freebox ? Je pense à des choses simples comme : 
 - éjecter le DVD
 - lis le DVD
 - va à la poste x
 - Mets le DVD en pause
 - Recommence la lecture

etc...

**Comment by Aymkdn** [comment]
Si ça se fait avec la télécommande, alors oui tu peux créer ta propre applet avec les touches télécommande qui correspondent aux actions que tu veux.

**Comment by titithebad** [comment]
Tu sais si quelqu'un l'aurait pas déjà fait ?

**Comment by Aymkdn** [comment]
Aucune idée. Mais c'est hyper simple à faire.

Suis les instructions ici : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#personnalisation

Exemple, pour éjecter le disque, il faut créer une applet comme expliqué ci-dessous et utiliser la commande : `Freebox_home,right,right,right,up,ok`

**Comment by Aymkdn** [comment]
T'as réussi ?

**Comment by Aymkdn** [comment]
Pas de réponse, je ferme le issue.

**Comment by titithebad** [comment]
Je vais commencer à regarder en fait en tache de fond. Je vais surtout faire ejecter le CD qui est le plus utile en fait.

**Comment by titithebad** [comment]
Tu veux dire plutot : Freebox_home,Freebox_right,Freebox_right,Freebox_right,Freebox_up,Freebox_ok

**Comment by Aymkdn** [comment]
Non. Ce que j'ai dit est correct.

**Comment by titithebad** [comment]
Ok, ca ne fonctionne pas. Le GH me dit bien qu'il execute la commande et il ne se passe rien...

**Comment by Aymkdn** [comment]
T'as bien mis "Assistant" dans le titre de la note Pushbullet ?

Que disent les logs de assistant-plugins ?

**Comment by titithebad** [comment]
C'est bon !
