### ISSUE TITLE
Temperature-local

### ISSUE THREAD

**Issue by titithebad** [Aymkdn/assistant-plugins#102]
C'est quoi le principe de ce logiciel ?

J'ai 1 station netatmo chez moi avec plusieurs modules.

**Comment by Aymkdn** [comment]
Comme expliqué, ça calcule la température moyenne dans une zone, en utilisant toutes les stations Netatmo dans la zone en question.

**Comment by titithebad** [comment]
Il y a un tuto ?

**Comment by Aymkdn** [comment]
Tu veux dire comme ça https://aymkdn.github.io/assistant-plugins/?plugin=temperature-local#utilisation   ?

**Comment by titithebad** [comment]
C'est celui que j'ai vu. Je ne comprends pas trop le principe en fait, tu pourrais me dire ? Je voudrais voir comment utiliser la station Netatmo...

**Comment by Aymkdn** [comment]
Tu définis une zone sur une carte. Le programme va chercher toutes les stations Netatmo dans la zone définie. Chaque station fournit une température. Le programme fait donc la somme de toutes les températures de la zone, puis divisent par le nombre de relevé, donnant ainsi la moyenne des températures mesurées dans une zone. Ainsi tu sais qu'elle est la température extérieure dans une zone...

Désolé je ne peux pas être plus clair que ça....

**Comment by titithebad** [comment]
Je pensais que ton application interrogeait une station Netatmo en particulier ?

**Comment by Aymkdn** [comment]
Non.... c'est pour ça que je dis une ZONE. Cela interroge TOUTES les stations dans la zone.
