### ISSUE TITLE
Root / profile

### ISSUE THREAD

**Issue by ebac1** [Aymkdn/assistant-plugins#103]
Bonjour
Quand j'edite root/ profile je n'ai pas la ligne :
ATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
comment puis-je faire, je suis débutant en ligne de commande

![image](https://user-images.githubusercontent.com/36691709/36468621-5e62c51c-16e4-11e8-978d-96b7f5969dd0.png)

**Comment by ebac1** [comment]
par contre j'ai cela dans etc/profile

**Comment by Aymkdn** [comment]
Et si tu le mets dans /etc/profile, est-ce que ça fonctionne ?

**Comment by ebac1** [comment]
Oui j'ai mis cela dans /etc/profile mais quand je tape

which opkg cela ne donne rien

**Comment by Aymkdn** [comment]
Tu as fait l'étape supplémentaire qui est indiqué dans la doc ? À savoir : 
```
PATH=$PATH:/opt/bin
export PATH
```

**Comment by ebac1** [comment]
Oui cela marche je n'avais pas vu, je te remercie d'avance pour ton 
aide, je vais continuer le tuto
