### ISSUE TITLE
Installation node

### ISSUE THREAD

**Issue by ebac1** [Aymkdn/assistant-plugins#104]
Bonjour,
J'ai des erreurs aprés l'installation de Node, dois-je recommencer l'installation?

make: *** [Makefile:90: node] Error 2
nvm: install v9.5.0 failed!

**Comment by Aymkdn** [comment]
Bhein tu ne me fournis que la fin... J'ai aucune idée des étapes que tu as faites (ou non) et des erreurs que tu as eu avant (ou non)....

Donc, je dirais, oui, recommence...

**Comment by ebac1** [comment]
ok je recommence je te tiens au courant

**Comment by ebac1** [comment]
Bon j'ai suivi les etapes depuis le passage sous batch, il y a eut quelques Warning, que faut-il que je te fournisse pour avoir la solution
[Nouveau document texte.txt](https://github.com/Aymkdn/assistant-plugins/files/1743941/Nouveau.document.texte.txt)

**Comment by Aymkdn** [comment]
Je vois c'est quoi le problème. Essaie ça : 
```
cd /root/
ln -s /opt/bin/gcc /opt/bin/cc
nvm install node
```

**Comment by ebac1** [comment]
il faut recommencer du debut à partir de grep

bash-4.4# cd /root/
bash-4.4# ln -s /opt/bin/gcc /opt/bin/cc
ln: /opt/bin/cc: File exists
bash-4.4# nvm install node
bash: nvm: command not found

**Comment by Aymkdn** [comment]
Bizarre... car il te dit `/opt/bin/cc: File exists`, pourtant dans ce que tu m'as envoyé ça dit : `make[1]: cc: Command not found`

Si tu tapes la commande ci-dessous te retourne quoi ?
```
cc -v
```

Pour `bash: nvm :command not found` il faut faire ça : 
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install node
```

**Comment by ebac1** [comment]
voici le retour

bash-4.4# cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/lto-wrapper
Target: arm-openwrt-linux-gnueabi
Configured with: /media/ware4/Entware-ng.2017.12/build_dir/target-arm_xscale_glibc-2.23_eabi/gcc-6.3.0/configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/opt --exec-prefix=/opt --bindir=/opt/bin --sbindir=/opt/sbin --libexecdir=/opt/lib --sysconfdir=/opt/etc --datadir=/opt/share --localstatedir=/opt/var --mandir=/opt/man --infodir=/opt/info --disable-nls --build=x86_64-pc-linux-gnu --host=arm-openwrt-linux-gnueabi --target=arm-openwrt-linux-gnueabi --enable-languages=c,c++ --with-bugurl=https://dev.openwrt.org/ --with-pkgversion='OpenWrt GCC 6.3.0' --enable-shared --enable-__cxa_atexit --with-default-libstdcxx-abi=gcc4-compatible --enable-target-optspace --with-gnu-ld --with-stage1-ldflags='-Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux.so.3' --with-specs='-Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux.so.3' --with-boot-ldflags='static-libstdc++ -static-libgcc -Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux.so.3' --disable-nls --disable-libsanitizer --disable-libvtv --disable-libcilkrts --disable-libmudflap --disable-multilib --disable-libgomp --disable-libquadmath --disable-libssp --disable-decimal-float --disable-libstdcxx-pch --with-host-libstdcxx=-lstdc++ --prefix=/opt --libexecdir=/opt/lib --with-local-prefix=/opt --with-float=soft --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 6.3.0 (OpenWrt GCC 6.3.0)
COMPILER_PATH=/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/:/volume1/@entware-ng/opt/bin/../lib/gcc/
LIBRARY_PATH=/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/:/volume1/@entware-ng/opt/bin/../lib/gcc/:/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-mfloat-abi=soft' '-mtls-dialect=gnu'
 /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/collect2 -plugin /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/liblto_plugin.so -plugin-opt=/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccYRwv6k.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr -dynamic-linker /lib/ld-linux.so.3 -X -m armelf_linux_eabi /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crt1.o /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crti.o /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crtbegin.o -L/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0 -L/volume1/@entware-ng/opt/bin/../lib/gcc -L/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/../../.. -rpath=/opt/lib --dynamic-linker=/opt/lib/ld-linux.so.3 -lgcc_s -lc -lgcc_s /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crtend.o /volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crtn.o
/volume1/@entware-ng/opt/bin/../lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/crt1.o: In function `_start':
(.text+0x34): undefined reference to `main'
collect2: error: ld returned 1 exit status
bash-4.4#

**Comment by Aymkdn** [comment]
OK étrange... et donc si tu tapes : 
```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install node
```

**Comment by ebac1** [comment]
idem

bash-4.4# export NVM_DIR="$HOME/.nvm"
bash-4.4# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
bash-4.4# nvm install node
Downloading and installing node v9.5.0...
Downloading https://nodejs.org/dist/v9.5.0/node-v9.5.0-linux-armv5tel.tar.xz...

curl: (22) The requested URL returned error: 404 Not Found
Binary download from https://nodejs.org/dist/v9.5.0/node-v9.5.0-linux-armv5tel.tar.xz failed, trying source.
grep: /root/.nvm/.cache/bin/node-v9.5.0-linux-armv5tel/node-v9.5.0-linux-armv5tel.tar.xz: No such file or directory
Provided file to checksum does not exist.
Binary download failed, trying source.
Local cache found: $NVM_DIR/.cache/src/node-v9.5.0/node-v9.5.0.tar.xz
Checksums match! Using existing downloaded archive $NVM_DIR/.cache/src/node-v9.5.0/node-v9.5.0.tar.xz
tar: invalid option -- 'J'
BusyBox v1.27.2 () multi-call binary.

Usage: tar -[cxtzhvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
        c       Create
        x       Extract
        t       List
        f       Name of TARFILE ('-' for stdin/out)
        C       Change to DIR before operation
        v       Verbose
        z       (De)compress using gzip
        O       Extract to stdout
        h       Follow symlinks
        X       File with names to exclude
        T       File with names to include
nvm: install v9.5.0 failed!
bash-4.4#

**Comment by Aymkdn** [comment]
Apparemment il essaie de télécharger une version pour processeur armv5 et cette version n'existe pas. C'est un très vieux Synology que tu as, non ?

Tu as quoi quand tu fais : 
```bash
cat /proc/cpuinfo
```

**Comment by ebac1** [comment]
voila
bash-4.4# cat /proc/cpuinfo
Processor       : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 1192.75
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1

Hardware        : Feroceon-KW
Revision        : 0000
Serial          : 0000000000000000
bash-4.4#

**Comment by Aymkdn** [comment]
Ouais il date donc de 2012 ton Synology ou quelque chose comme ça ? Node a arrêté de supporter les armv5 il y a 3 ans...

Ton matériel est trop vieux, désolé...

**Comment by ebac1** [comment]
Merci pour ton aide, je pensais aussi  cela, je vais acheté un raspberry et essayer
Tu as fait du tres bon boulot, car pour le neophyte que je suis, ce n'est pas évident, 
merci encore et bonne continuation
A bientôt
