### ISSUE TITLE
Assistant-Plugins et Plex : ce serait possible?

### ISSUE THREAD

**Issue by KaptainJP** [Aymkdn/assistant-plugins#106]
J'aimerais pouvoir commander Plex avec Google Home via Assistant-Plugins comme Freebox. As-tu déjà réfléchi à ce sujet et serait ce possible à ton avis?

**Comment by Aymkdn** [comment]
Oui ça serait possible. Faut "juste" chercher l'API de Flex et coder le plugin qui va bien ^^
