### ISSUE TITLE
Freebox player s'éteint !

### ISSUE THREAD

**Issue by Siphris02** [Aymkdn/assistant-plugins#108]
Bonjour à tous ! Excellent tuto ! Beau travail ! J'ai suivi à la lettre l'installation du plugin freebox avec commande IFTTT pour google home mais lorsque je demande à GH, la requête se fait correctement mais il m'éteins systématiquement le freebox player ! Je lui demande de zapper sur tel chaîne et il éteins la freebox player.

**Comment by Aymkdn** [comment]
Tu dois ajouter le paramètre `check_player_on` dans la configuration, comme expliqué dans la documentation : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#param-tre-check_player_on

**Comment by Siphris02** [comment]
Merci de ta réactivité ! Le paramètre "check_player_on" est mis mais ça ne change rien.

**Comment by Aymkdn** [comment]
Montre moi ce que tu as mis dans ton fichier de configuration.

**Comment by Siphris02** [comment]
Là maintenant je peux pas car je suis au boulot. Je l'enverrai ce soir ! Pour info l'installation est faite sur un raspberry.

**Comment by Siphris02** [comment]
Voici ma config :
{
  "main": {
    "pushbullet_token": "xxxxxxx"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "xxxxxx",
      "check_player_on": false,
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1",
      "app_token": "xxxxxxx"
    }
  }
}

**Comment by Aymkdn** [comment]
Ça m'a l'air bon... Tu as bien redémarré `assistant-plugins` après avoir changé la configuration ?

Si oui, fais moi voir les logs du programme lorsque tu demandes à la Freebox de s'allumer ou s'éteindre.

**Comment by Siphris02** [comment]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Zappe sur tf1 (1)
[assistant-freebox] Durée de la vérification de la Freebox allumée : 706ms
[assistant-freebox] La Freebox n'est pas allumée, donc on l'allume.
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=23468947&key=power
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=23468947&key=1

**Comment by Siphris02** [comment]
Par contre faut'il aussi changer le fichieer configuration.json qui se trouve dans le répertoire /home/pi/assistant-plugins/node_modules/assistant-freebox.

**Comment by Aymkdn** [comment]
Non, que celui à la racine, mais c'est bizarre qu'il fasse la vérification alors que ta configuration est bonne...

**Comment by Siphris02** [comment]
Tu sais quoi, je vais le taureau par les cornes ! Lol. Je dispose une autre carte Sim. Je vais réinstaller Raspbian et refaire ton installation. Je te tiens au courant dès que j'ai finis.

**Comment by Siphris02** [comment]
Par contre je ne suis pas obliger d'installer le version v9.3.0 de NodeJs. Il existe une version plus récente v9.6.1 ?

**Comment by Aymkdn** [comment]
Oui toute version supérieure à v8.0.

Donne moi 5 minutes je vérifie un truc ici et je te dis un truc à tester après

**Comment by Aymkdn** [comment]
Je viens de tester et chez moi le paramètre fonctionne...

Dans `node_modules/assistant-freebox/freebox.js`, rajoute cette ligne après la ligne 16 : 
```javascript
console.log("check_player_on => ",this.config.check_player_on)
```

![capture](https://user-images.githubusercontent.com/946315/36692823-74a68760-1b39-11e8-8c6c-6d1a540237fc.PNG)

Puis arrête et relance le programme. Tu devrais voir ça : 
![capture](https://user-images.githubusercontent.com/946315/36692870-aa2d7826-1b39-11e8-8dba-274764d77af9.PNG)

Pour confirmation : tu as activé (sans password) ton AirMedia Video ?

**Comment by Siphris02** [comment]
C'est bon ça marche ! Mais j'ai pas fait ta manip. Quand tu m'as demandé de patienter 5 min, il était trop tard, j'étais déjà entrain de réinstaller ton plugins. Alors je sais pas si c'est ça mais lors de la 1ère installation j'ai zappé la ligne (export PATH=$PATH:/home/pi/node-v9.3.0-linux-armv6l/bin) qui faut rajouter au /.bashrc ! Par contre la seul différence aussi c'est que j'ai installer la dernière version de NodeJs (v9.6.1) contrairement à la première fois ou j'étais en v9.3.0. J'ai essayé avec le commande check_player_on en false et ça fonctionne.

**Comment by Siphris02** [comment]
Merci Chef ! En tou ka, merci pour ta réactivité et de ton aide. Encore une fois c'est très appréciable de côtoyer des personnes qui s'investisse comme toi et qui font un travail remarquable ! Tu est plus q'un chef, tu est un killer ! A bientôt j'espère et bonne continuation à toi sur la route de l'informatique embarqué ! Encore merci.

**Comment by Aymkdn** [comment]
Cool 😊
