### ISSUE TITLE
Tout s'est bien installé mais le google home ne comprend pas mes demandes

### ISSUE THREAD

**Issue by sugardaddy78** [Aymkdn/assistant-plugins#109]
Bonjour à tous.
Voila, tout s'est bien installé, tout a l'air bien configuré, mais quand je lance une commande vocale, il me répond désolé je ne comprends pas votre demande !!
Merci d'avance

**Comment by Aymkdn** [comment]
Il faut activer les applets IFTTT des commandes souhaitées. Voir sur la page de documentation.

**Comment by sugardaddy78** [comment]
c'était exactement ça, j'ai voulu aller trop vite ^^ merci beaucoup de votre aide
