### ISSUE TITLE
probleme start.bat

### ISSUE THREAD

**Issue by skiman88** [Aymkdn/assistant-plugins#11]
salut, et merci pour tout ca mais j ai un petit probleme, j espere que tu pourras m aider, j ai normalement tout bien fait mais quand je lance start.bat voila ce qu il s affiche 
[1.txt](https://github.com/Aymkdn/assistant-plugins/files/1497578/1.txt)
merci d avance pour ton aide

**Comment by cottarelf** [comment]
Salut, 
d'aprés le message d'erreur, il y a un probléme avec une accolade dans le fichier "configuration.json".
Si tu veut l'envoyer ici (en enlevant les informations sensibles), on pourra te le corriger.

**Comment by la-breche** [comment]
Tu dois retirer la virgule en fin de ligne du "box_to_control"

**Comment by cottarelf** [comment]
Ha oui, problème de fichier, je vais faire une pull request pour le corriger.

**Comment by skiman88** [comment]
ok merci, ca marche sans la virgule, mais pare contre quand je parle a l assistant exemple "ok google zap sur m6", il me dit "ok je zap sur m6" mais rien ne se passe, désolé de vous embêter mais je suis novice
