### ISSUE TITLE
Echec de detection de l'état d'alimentation du Freebox Player.

### ISSUE THREAD

**Issue by Lilive45** [Aymkdn/assistant-plugins#110]
Bonjour,

Je voudrai signaler un cas particulier de dysfonctionnement sur le plugin Freebox.

J'ai pu installer et adapter la configuration à mon installation et tout fonctionnait parfaitement sauf la fonctionnalité de détection de l'état d'alimentation du FreeBox Player.

Tout d'abord je tiens à dire que je ne considère pas vraiment ceci comme un problème mais plus comme une demande d'évolution car si on utilise l'assistant dans des conditions plus "standard" on ne rencontre surement pas ce problème. Je tiens aussi à rappeler qu'on a toujours la possibilité de désactiver la fonctionnalité de détection avec le paramètre "check_player_on" si elle pose problème.

Ensuite pour préciser la cause du problème, que j'ai identifié (et peut être vous aussi déjà), cela vient du fait que dans mon cas, j'ai deux Freebox Player et pour facilement les différencier sur le réseau et dans toutes les applications qui les prennent en charge, j'ai changé leur noms par défaut

Je ne connais pas spécifiquement le language javascript mais je sais a peu près l'analyser et après avoir parcouru le code de la fonction "isPlayerOn" du fichier "freebox.js", j'ai remarqué que l'appel à airmedia s'effectue avec une URL comportant le nom du Freebox Player par défaut en dur.

Pour que la fonction retourne une valeur correcte de l'état de la Box, j'ai du adapter le nom du Player dans l'URL.

Vous serait il possible de variabiliser cette valeur via le fichier configuration.json ou de trouver un moyen de récupérer automatiquement le nom du player en fonction de la variable "box_to_control" ?

En vous remerciant par avance de votre attention sur ce point.

ps: je ne sais pas si vous envisagez une prise en charge de plusieurs FreeBox Player, et j'imagine qu'il y aurai pas mal d'impact et de travail à développer cette possibilité mais personnellement je suis preneur :-)

**Comment by Aymkdn** [comment]
Salut

Je suis en vacances au Brésil là jusqu'à la fin du mois. 

J'ai regardé vite fait le code, et la fonction isPlayerOn interroge le Freebox Serveur, et non le player. Donc quelle est l'URL que tu as changé en fait ? Et en quoi ? Si tu me donnes plus d'informations je pourrais regarder ça de plus près à mon retour de vacances !

Quant à un moyen de gérer plusieurs Freebox, j'ai peur que ça complique un peu trop les choses. Aussi, au niveau commandes vocales, faudrait spécifier la Freebox à chaque fois... T'es le premier à me demander donc pas sûr qu'il y ait un besoin important des utilisateurs. Mais j'y réfléchirai !

**Comment by Lilive45** [comment]
Bonjour,

La fonction fait appel à une URL qui fait référence spécifiquement au nom du Freebox Player:

url:_this.serverURL+"airmedia/receivers/**_Freebox%20Player_**/",

Personnellement j'ai changé le nom réseau de mon player par "FBX Player Salon" alors j'ai modifié la ligne comme suit:

url:_this.serverURL+"airmedia/receivers/**_FBX%20Player%20Salon_**/",

Bonne vacances.

**Comment by Aymkdn** [comment]
Je ne savais même pas qu'on pouvait changer ce nom ^^ OK je regarderai à mon retour. Merci !

**Comment by Aymkdn** [comment]
Je viens de mettre à jour `assistant-freebox` en v2.0.8 ; j'ai ajouté un paramètre (optionnel) qui est `player_name` et qui va te permettre de mettre "FBX Player Salon" comme valeur. Si tu veux mettre à jour : https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-

**Comment by Lilive45** [comment]
Bonsoir.

Super ça fonctionne parfaitement.

Merci et bonne continuation.
