### ISSUE TITLE
Pushbullet? --> Action failure message: Account has not been used for over a month.

### ISSUE THREAD

**Issue by Ancel1** [Aymkdn/assistant-plugins#111]
Bonjour,

ça fait maintenant 3 mois que j'utilise **_"assistant-plugins"_** sur un raspberry et tout marche parfaitement bien.
Mais j'ai régulièrement l'erreur **"Action failure message: Account has not been used for over a month."** visible dans l'onglet activity de **_"ifttt"_** --> je suis obligé de détruire mon compte **_"Pushbullet"_**, recréer un token et reconfigurer le fichier `json`...

Je pense que c'est après un certain nombre d'appels Pushbullet que j'ai le problème, ou alors comme j'utilise pushbullet uniquement pour **_"assistant-plugins"_** sans autre application, le compte pense ne pas avoir d’activité?

Avez vous déjà rencontré ce problème et comment pouvoir le corriger?
Merci
Ancelin

**Comment by Aymkdn** [comment]
Je n'ai jamais eu ce problème.... J'utilise Pushbullet pour transférer des liens de mes appareils mobiles vers mon PC de temps à autre, donc peut-être que ça crée de l'activité... Dur à dire.... Pour le moment ce problème ne m'a pas été retourné, donc je ne sais pas trop...

**Comment by Aymkdn** [comment]
Est-ce que tu as l'application mobile de Pushbullet installée sur ton téléphone? Essaie de l'installer si non, car les commandes envoyées via IFTTT s'affichent comme notification temporaire sur le téléphone quand tu as l'application, donc peut-être que ça fait l'illusion d'une utilisation...

**Comment by Ancel1** [comment]
Ok merci pour ton retour, je test d'installer l'application sur mon téléphone et je te dirai si ça corrige le problème dans 1 mois ;-) En tout cas super ton application !

**Comment by buggyboy** [comment]
A toutes fins utiles, j'ai le même problème. Je vais essayer l'installation de Pushbullet sur mon téléphone

**Comment by ABOATDev** [comment]
Il met arrivé le même problème
Il faut se connecter sur pushbullet et faire genre qu'on est actif (s'envoyé un message) 
https://www.pushbullet.com/
Et normalement problème résolu

**Comment by Aymkdn** [comment]
D'après [ce post](https://www.reddit.com/r/PushBullet/comments/7wzb1t/account_has_not_been_used_for_over_a_month_error/) PushBullet fait ça lorsqu'on n'utilise pas l'application : 

> This error means you haven't opened / used a Pushbullet app in over a month. We do this to prevent "dead" accounts from racking up tons of automated pushes. 

J'ai un addon Pushbullet sur mon Firefox, et j'ai l'app sur mon Android. Je l'utilise régulièrement pour transférer des liens de l'un à l'autre...

Du coup je viens de sortir la v2.0.3 d'`assistant-plugins` qui va envoyer un message vers PushBullet toutes les 24h... Pas sûr que cela empêchera cette erreur, mais on peut toujours tenter. Donc @Ancel1 tu peux essayer de [mettre à jour](https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-) si tu veux.

**Comment by Ancel1** [comment]
Hello,

Pour le moment ça ne fait pas encore un mois --> (24 jours) que j'ai l'application d'installée pour voir si ça fait office de présence pushbullet.

--> Je te propose tout de même d’attendre encore 10 jours pour voir si via l'application ça fonctionne.
Après je désinstallerai l'application pour passer à la version 2.0.3 d'`assistant-plugins`

**Comment by Whitou** [comment]
Hello, perso, j'ai toujours le problème. Je ne l'ai pas signalé avant car j'avais des soucis avec pm2, qui sont maintenant réglés.
Je suis pourtant bien sur la dernière version.

**Comment by Whitou** [comment]
Je vais tenter ça dès demain, et je te tiens au jus. Le facteur WAF commence à en prendre un coup ^^
Super boulot en tout cas, c'est en grosse partie à cause de toi et de ton plugin que j'ai commencé a domotiser la maison ! (Achat raspberry, jeedomisation et tout ce qui s'en suit...)

**Comment by Ancel1** [comment]
Avec l'application installée sur le tel je n'ai plus le problème.Je suis en dernière version et node js 9.5 installée et je n'ai pas rencontré de soucis depuis plusieurs mois. Pushbullet installée sur mon tel Android. 
Ps : pour pm2 je tape sudo avant chaque commande sinon ça ne fonctionnait pas.

**Comment by Whitou** [comment]
Hello, en effet, avec l'appli sur le tel ca roule.
