### ISSUE TITLE
Mon assistant ne répond pas

### ISSUE THREAD

**Issue by OptimaluS** [Aymkdn/assistant-plugins#112]
**Bonjour,**

J'ai suivit votre tutoriel à la lettre, je n'est aucune erreurs dans la console lorsque je lance "assistant-plugins" depuis windows 10 :
![nodejs](https://user-images.githubusercontent.com/28610694/37243901-4c4001d8-2481-11e8-96ce-70d5bedc6a1c.jpg)

Au niveau des Applets sur Iftt il fonctionne correctement:
![sans titre 2](https://user-images.githubusercontent.com/28610694/37243940-eca03bde-2481-11e8-9f4d-346318400234.jpg)

Par contre sur PushBullet je ne voit pas les bulles de messages:
![sans titre 3](https://user-images.githubusercontent.com/28610694/37243961-55375146-2482-11e8-8e79-0628a97e2994.jpg)

Voici pour commencer mes principal questions:

- Faut t'il bien l'application google assistant sur mon smarphone android ?
(J'ai bien essayé de dictée les phrases à google en vocale et tous ce qui fait c'est de m'afficher les résultats de ma requête sur le web et de plus aucun retour audio.)
- N'est t'elle pas déjà intégrer sur mon téléphone ?

**Merci d'avance pour votre aide.**
_Cordialement OptimaluS_

**Comment by Aymkdn** [comment]
> Faut t'il bien l'application google assistant sur mon smarphone android ?
> (J'ai bien essayé de dictée les phrases à google en vocale et tous ce qui fait c'est de m'afficher les résultats de ma requête sur le web et de plus aucun retour audio.)

Si Google ne reconnaît pas ce que tu dis c'est que le problème vient du lien entre IFTTT et Google. Utilises-tu bien le même compte Google sur ton téléphone et sur le Google Assistant que tu as configuré sur IFTTT ? 

Quelle phrase tu as essayé de dire à Google Assistant ? 

> N'est t'elle pas déjà intégrer sur mon téléphone ?

Oui, quand tu dis "OK Google" à ton téléphone

**Comment by MaturityTeam** [comment]
J'ai bien tout contrôlé et oui le compte google est bien le même partout (Téléphone, IFF, Pushbullet).
Par contre je n'est pas vu d'étape ou il fallait configurer mon téléphone avec IFF, Quelle est cette étape, Que faut'il faire s.v.p ?

Pour la phrase de test j'ai dit via Google assistant "Ok Google, Allume la Freebox"
Ou encore "Ok Google, éteins la Freebox"

**Comment by Aymkdn** [comment]
Tu n'as pas à configurer ton téléphone avec IFTTT.

Ce que tu peux essayer de faire : sur https://ifttt.com/services/google_assistant/settings clique sur "Disconnect Google Assistant" puis reconnecte ton compte. Ensuite sur https://ifttt.com/my_applets désactive puis réactive les applets.

Et enfin tu peux vérifier sur https://ifttt.com/activity si des erreurs apparaissent

**Comment by MaturityTeam** [comment]
J'ai installé IFF sur mon téléphone et sa fonctionne, pas contre OK Google, Allume la Freebox" s'exécute bien mais la Freebox ne s'allume pas. Et au niveau des erreurs dans le panel d'activité de IFF, aucune erreur pour cette commande.

**Comment by Aymkdn** [comment]
Donc maintenant les commandes sont reçues par le programme sur ton ordinateur ? Qu'est-ce que tu as dans la console ? Tu peux faire une capture d'écran ?

**Comment by MaturityTeam** [comment]
Oui les commandes sont bien reçût.

Quand j'exécute la commande "OK Google, Allume la Freebox" 
Ma freebox est actuellement en veille, donc elle devrait logiquement s'allumer et me mettre sur l'écran d'accueil.)
Donc après avoir essayer plusieurs fois elle ne s'allume pas.

Voici une capture de la console comme demandé:
![sans titre 2](https://user-images.githubusercontent.com/28610694/37246625-466c7e2c-24ad-11e8-8f48-2d662716774c.jpg)

**Comment by OptimaluS** [comment]
Oui cela fonctionne, d'ailleur j'ai pratiquement tout essayer et seul la commande "Ok Google, allume la freebox" ne marche pas.

**Comment by Aymkdn** [comment]
Une seule autre personne m'a rapporté le même soucis. Je suppose que c'est un bug du Free Player qui touche juste quelques personnes... Donc je n'ai pas de solution à ce problème.

**Comment by OptimaluS** [comment]
Ce n'est pas grave, je suis déjà très satisfait de résultat.
Je vous **remercie** pour ceux que vous faites et vous avez tous mon **soutien** @Aymkdn  👍

**Comment by Aymkdn** [comment]
Merci 😊
