### ISSUE TITLE
Ouvrir un dossier sur un nas WDMyCloud

### ISSUE THREAD

**Issue by softxpert2** [Aymkdn/assistant-plugins#113]
Bonjour, et surtout merci pour ce projet qui fonctionne très bien et surtout sur la mine d’enseignement qu'il apporte en même temps sur le fonctionnement de IFTT PushBulet Google Home Node Js et autres.

Il est possible de rechercher un répertoire sur le disque dur de la Freebox, ce qui est deja pas mal.
Par contre pour moi ça se complique parce que mes films sont stockés  sur un NAS 
WDMycloud, donc un répertoire en réseau, le montage du disque dur est donc different.
Dans ce cas, la modification du "search_path" dans "configuration.json" ne fonctionne pas.
y a t'il une syntaxe particulière dans ce cas ?

D'avance Merci

Jean philippe

**Comment by Aymkdn** [comment]
Tu ne peux pas utiliser search_path car le contenu de ton NAS est inconnu pour la Freebox. Cependant tu peux faire ce que j'indique ici : https://github.com/Aymkdn/assistant-plugins/issues/66

**Comment by Aymkdn** [comment]
Pas de réponse, donc je clos.
