### ISSUE TITLE
google home ne reconnait plus les commandes

### ISSUE THREAD

**Issue by zaza38** [Aymkdn/assistant-plugins#114]
Bonjour,

Je ne sais pas pourquoi (ça coincide avec la désinstallation de norton mais je ne vois pas le rapport) je n'arrive plus à utiliser le plugin freebox. Lorsque je donne une commande vocale (type "allume la télé") :

- google home dit "je ne peux pas vous aider"
- node affiche : 
![node](https://user-images.githubusercontent.com/37501946/37565273-a466a116-2aa6-11e8-9380-23f9c4d68981.png)
et rien ne se passe.

J'ai regardé sur https://www.pushbullet.com/#following/ et je n'ai pas l'onglet "ifttt". En revanche je l'ai trouvé sur l'appli pushbullet installée sur l'ordi, dans following, et je vois les bulles relatives aux instructions qui ont marché, avant le problème, et rien depuis.

Iftt/activity m'a montré des messages d'erreur : 
![ifttt_activity](https://user-images.githubusercontent.com/37501946/37565338-cd01c74e-2aa7-11e8-8faf-7a4ef4538d3b.png)

J'ai alors fait "Edit" dans https://ifttt.com/services/pushbullet/settings sans résultat, puis j'ai fait "disconnect". J'ai aussi re-demandé un token et modifié le fichier "confiuration" en fonction.

Alors maintenant google me dit toujours qu'il ne reconnait pas la commande, mais je ne vois rien de nouveau dans le following de pushbullet et ifttt/activity m'affiche uniquement :
![push_follow](https://user-images.githubusercontent.com/37501946/37565436-d699f34c-2aa9-11e8-9239-61eda3346b13.png)

J'ai alors désactivé le pare-feu, désinstallé puis réinstallé node, mis à jour le plugin freebox, re-changé le token et le configuration.json.  Aucun changement.

Help !!

**Comment by Aymkdn** [comment]
Essaie de détruire ton compte Pushbullet (comme expliqué là https://github.com/Aymkdn/assistant-plugins/issues/111) puis de le recréer et de réassocier dans IFTTT

**Comment by zaza38** [comment]
Merci, j'essaie ça tout de suite.

Je viens aussi de m'apercevoir que les applets dans ifttt avaient disparu.. normal que google home ne reconnaisse pas le commandes ! J'ai tout remis, google ne me dit plus d'erreur.

**Comment by zaza38** [comment]
Comment fait-on pour "réassocier" le compte pushbullet ? je ne trouve plus, et je ne vois pas ce que ça veut dire

**Comment by Aymkdn** [comment]
Là  : https://ifttt.com/services/pushbullet/settings

**Comment by zaza38** [comment]
Ca maaarche !!! Merci !!!!!

**Comment by Aymkdn** [comment]
@zaza38  si le problème se reproduit, je t'invite à lire ce que j'ai marqué là : https://github.com/Aymkdn/assistant-plugins/issues/111#issuecomment-378001028
