### ISSUE TITLE
Création Applet

### ISSUE THREAD

**Issue by Lolodu56** [Aymkdn/assistant-plugins#115]
Bonsoir,

Tout d'abord un grand merci à toi 👍 
Je n'arrive pas à créer une Applet qui donnerais ce qui suit 
Demander à ma Freebox d'aller dans l'onglet application puis ouvrir un lecteur multimédia installé (P2f)

D'avance merci

<img width="483" alt="capture d ecran 2018-03-20 a 21 03 36" src="https://user-images.githubusercontent.com/37596752/37679950-c08290fc-2c82-11e8-8542-e5b8de1988f3.png">
<img width="462" alt="capture d ecran 2018-03-20 a 21 03 45" src="https://user-images.githubusercontent.com/37596752/37679971-cc0861b8-2c82-11e8-8b03-f5a78d9a5b4d.png">

**Comment by Aymkdn** [comment]
Tu dois mettre un truc du genre : `freebox_home, left,left,ok`

Les termes "application" et "P2f" ne sont pas des commandes valides ! Les commandes valides sont  là : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#commandes

**Comment by Lolodu56** [comment]
Merci mais elle refuse encore :/

**Comment by Aymkdn** [comment]
Montre moi ce que tu as mis cette fois. 

Ensuite, qui refuse ? Google Home répond à ta demande ? Si oui, qu'est ce qui apparaît dans ta console ?

**Comment by Lolodu56** [comment]
La Google home ne comprends pas (je ne sais pas comment vous aider...) 

<img width="455" alt="capture d ecran 2018-03-20 a 21 39 11" src="https://user-images.githubusercontent.com/37596752/37681561-528bbe3e-2c87-11e8-87f0-e54623cf06a2.png">

**Comment by Aymkdn** [comment]
Y'a un espace de trop avant le deuxième "left", mais là j'ai donné une commande totalement aléatoire.... C'est à toi de voir les commandes nécessaires pour aller où tu veux dans les menus de la Freebox ! 

Questions :
1) Est-ce quand tu dis "aller dans applications" Google te répond "OK"?
2) qu'est ce qui apparaît dans ta console, c'est-à-dire dans la fenêtre où tu as lancé Assistant Plugin

**Comment by Aymkdn** [comment]
Donc Google ne te comprend pas ? Essaie de changer ta phrase par "va dans mes applications" par exemple. Essaie aussi de le dire à Google Assistant sur ton téléphone pour voir comment il comprend ce que tu dis

**Comment by Lolodu56** [comment]
Alors cela fonctionne en changeant la phrase comme tu à préconisé, par contre j'ai voulu ajouté "Down" et "OK" mais cela n'ai pas pris en compte

<img width="400" alt="capture d ecran 2018-03-20 a 21 57 18" src="https://user-images.githubusercontent.com/37596752/37682369-b059c040-2c89-11e8-8bea-4c63b6370b54.png">

**Comment by Aymkdn** [comment]
Tu es sûr de ne pas avoir d'espace entre "dow" et "n"? As-tu essayé plusieurs fois ?

**Comment by Lolodu56** [comment]
Oui sûr, essayé qu'une seule fois car madame viens de rentrer et du coup TL plus dispo ;)
Je teste ça plus tard ou demain, et je reviens te dire
Encore merci

**Comment by Aymkdn** [comment]
OK. Pour info, je suis en vacances au Brésil pour quelques jours encore, donc mes connexions ne sont pas fréquentes jusqu'à vendredi.

**Comment by Lolodu56** [comment]
Pas de soucis, c'est déjà sympa de ta part :)
Je viens d'essayer une nouvelle fois et fonctionne pas encore :/

@+

**Comment by Aymkdn** [comment]
Qu'indique ta console ? La console est la fenêtre où s'affiche les messages de Assistant Plugin 

![nodejs](https://user-images.githubusercontent.com/28610694/37243901-4c4001d8-2481-11e8-96ce-70d5bedc6a1c.jpg)

**Comment by Lolodu56** [comment]
<img width="871" alt="capture d ecran 2018-03-20 a 22 25 17" src="https://user-images.githubusercontent.com/37596752/37683666-a28bd36e-2c8d-11e8-9ec3-648efb4707ce.png">

**Comment by Aymkdn** [comment]
Aussi, avant de faire le "down" tu peux mettre un "wait3000" ou plus, car il est possible qu'il faille du temps à la Freebox pour lancer le menu Application

**Comment by Aymkdn** [comment]
Oui donc ajoute un délai de 3 secondes par exemple, ou plus, avec "wait3000"

**Comment by Lolodu56** [comment]
En ajoutant le "wait3000" cela fonctionne à merveille!!

**Comment by Aymkdn** [comment]
Cool!

**Comment by Lolodu56** [comment]
Plus qu'a installer tout ça sur mon Mac Mini car je l'ai fais en test sur mon MacBook pro

**Comment by Lolodu56** [comment]
Salut,

J’ai arrêté ma machine ou était installé le plugin et maintenant l’assistant ne fonctionne plus, que faut il faire pour relancer stp

**Comment by Aymkdn** [comment]
Il faut une machine qui tourne tout le temps car c'est le principe du truc (comme expliqué sur le site Web).

Donc tu dois rallumer ta machine et relancer Assistant Plugins

**Comment by Lolodu56** [comment]
Ouais je sais bien mais je l’ai installé sur mac portable pour essayer et maintenant que je suis conquis je vais installer sur mon Mac mini qui lui tourne H24, donc il faut que je redémarre mon MacBook pro puis relancer l’assistant (quelle manip pour relancer l’assistant stp)

**Comment by Aymkdn** [comment]
L'étape 9 de l'installation https://aymkdn.github.io/assistant-plugins/

**Comment by Lolodu56** [comment]
Parfait, ça fonctionne de nouveau :) 
Merci

**Comment by Lolodu56** [comment]
Re,

un petit renseignement stp, j’ai ajouté un chromecast audio à mon ampli HC et donc utilisable sur un autre canal que celui de la freebox 
Câble optique numérique TOSLINK (Fiche mâle TOSLINK > mini fiche mâle TOSLINK)
Peut on faire basculer le canal de l’ampli via le google home d’après toi?

Désolé si ma question peux te sembler bête mais je suis novice

**Comment by Aymkdn** [comment]
J'en ai aucune idée, désolé
