### ISSUE TITLE
 code telecommande

### ISSUE THREAD

**Issue by kevton26210** [Aymkdn/assistant-plugins#116]
slt a toi la video et simple je suis parvenu a tous faire mes par contre j'ai une mini 4k et elle n'a pas de code télécommande ou alor il n'ai plus visible contrairement a l'evolution du coup cela ne fonctionne pas comment faire

**Comment by Aymkdn** [comment]
Comme indiqué de partout, ce n'est QUE pour la Freebox Révolution.
