### ISSUE TITLE
Tuto Synology : installation nvm

### ISSUE THREAD

**Issue by macpoupou** [Aymkdn/assistant-plugins#118]
Un petit souci avec la commande suivante :
`wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash`

J'ai le message suivant :
`wget: not an http or ftp url: https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh`

**Comment by macpoupou** [comment]
Ok ça marche avec curl.

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash`

**Comment by Aymkdn** [comment]
Tu utilises une vieille version de Synology ?

Fais un : `wget -V`

Tu devrais avoir: 
![capture](https://user-images.githubusercontent.com/946315/37880406-42c145f0-3088-11e8-8ac5-fc5afff61b4e.PNG)

**Comment by macpoupou** [comment]
Ça peut...
```
wget -V
wget: invalid option -- 'V'
BusyBox v1.27.2 () multi-call binary.
```

**Comment by Aymkdn** [comment]
Si ça marche avec curl, c'est bon alors :)

**Comment by macpoupou** [comment]
En fait tu devrais aussi rajouter le wget dans la liste des opkg au début.
Ça résout les problèmes.

**Comment by Aymkdn** [comment]
Je n'ai pas eu besoin de l'installer car il y était déjà, et tu es le premier qui a ce soucis. Donc je préfère ne pas l'ajouter et seulement aider une personne au cas par cas.
