### ISSUE TITLE
assistant-plugins pour Alexa

### ISSUE THREAD

**Issue by macpoupou** [Aymkdn/assistant-plugins#119]
Voilà j'ai pu installer l'assistant sur mon synology.
Tout semble Ok.

J'ai reçu un pack de test pour Alexa en français et j'aimerai le tester avec.
Que faut-il faire pour rendre compatibles tes applets "Google Assistant" avec ?

**Comment by Aymkdn** [comment]
Il faut tout faire pareil que Google Assistant, sauf que pour les applets IFTTT il faut utiliser Alexa en entrée au lieu de Google Assistant.

**Comment by macpoupou** [comment]
Ok donc je n'ai plus qu'à attendre mon inscription comme partner pour créer une applet.
Je te tiens au courant.

**Comment by macpoupou** [comment]
Bon la fonction IFTTT n'est pas encore disponible dans la version béta française...
Wait & see...

**Comment by Aymkdn** [comment]
OK !

**Comment by Aymkdn** [comment]
Maintenant qu'Alexa est dispo en France, t'as pu voir si IFTTT permet de la personnaliser ?

**Comment by macpoupou** [comment]
Malheureusement le skill IFTTT d’Alexa n’est pas encore disponible en français.

**Comment by Aymkdn** [comment]
Un gars sur Twitter m'a dit que ça fonctionnait, mais il fallait dire "Alexa déclenche + l'action" au lieu de "Alexa trigger + action"
