### ISSUE TITLE
Installation sur Netger Readynas x86 / OS 6

### ISSUE THREAD

**Issue by ewidance** [Aymkdn/assistant-plugins#120]
Bonjour,

Juste un petit retour sur l'installation sur ReadyNas Netgear.  Je possède un RNDP4000 (Readynas Pro4) updaté avec la dernière version de l'OS (Readynas OS 6). Dessous c'est une debian X86, donc pas de problème particulier pour une installation sous Linux
L'installation a été réalisée de la façon suivante :
Installation de Node
* curl -sL https://deb.nodesource.com/setup_8.x > nodeinstall.sh
* chmod +x nodeinstall.sh
* ./nodeinstall.sh
* apt-get install nodejs

Etape optionnelle pour Node:
* apt-get install -y build-essential

Puis pour éviter une erreur au premier lancement d'assistant-plugins
* npm install request-promise-native
* npm install request

Puis installation de assistant-plugins comme indiqué dans la documentation...

Le démarrage automatique a ensuite été assuré par PM2.

Un grand merci à l'auteur pour ce logiciel et la qualité de la documentation...

**Comment by Aymkdn** [comment]
Cool :-) Merci pour ton retour.

Je ferme l'issue mais il reste disponible dans la recherche !
