### ISSUE TITLE
Erreur installation 

### ISSUE THREAD

**Issue by Eproms** [Aymkdn/assistant-plugins#122]
Bonjour quand je double clique sur install.bat j'ai une message d'erreur commande "npm" non reconnue .  a tu la solution a se probleme ?

merci pour le travail fournie

**Comment by Aymkdn** [comment]
Tu dois suivre toutes les étapes. Si tu as ce message d'erreur c'est que tu n'as pas installé Node (étape 1)

**Comment by Aymkdn** [comment]
Peut-être. Il faut faire une installation "globale" afin que npm et Node soit accessible de partout sur ton Windows. Si tu fais une installation personnalisée, alors il faut t'assurer que les commandes `node` et `npm` soient disponibles dans le `path` de Windows

**Comment by Eproms** [comment]
c'etait ca a installer sur C: 

merci

**Comment by Aymkdn** [comment]
OK cool.
