### ISSUE TITLE
[assistant-plugins] Erreur de connexion avec PushBullet

### ISSUE THREAD

**Issue by Eproms** [Aymkdn/assistant-plugins#123]
salut, j'ai une erreur récurrente avec le plugin , au bout d'un certain moment je rencontre cette erreur 👍 
**[assistant-plugins] Erreur de connexion avec PushBullet:  { Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read'**
a tu une idée d'ou peut bien venir le problème .
merci encore

**Comment by Aymkdn** [comment]
Tu utilises quelle version de assistant-plugins ?

Et cette erreur peut être dûe à un problème de connexion de ta machine je dirais. Genre une connexion instable ?  Moi ça tourne 24/24h pendant plusieurs jours sans aucun problème (sur fibre optique).

**Comment by Eproms** [comment]
J'utilise la dernière version, j'ai vérifié le log de connexion de mon pc et ma box il ont pas bronché. N'y a toujours il pas une autre piste ?

**Comment by Eproms** [comment]
Pas d'autre erreur dans la fenêtre du plug-in. Tout marche parfaitement avant le message d'erreur. Je suis sous Windows 10,j'utilise pas pm2

**Comment by Aymkdn** [comment]
Et t'as pas répondu : est-ce que ça te fait planter le programme (genre t'es obligé de le relancer), ou bien il continue à fonctionner ?

S'il plante, alors je te conseille d'utiliser `pm2` car ça va automatiquement le relancer et le maintenir.
S'il ne plante pas, alors c'est pas bien grave (mais a priori il doit planter au vue de l'erreur)

**Comment by Eproms** [comment]
non sa ne plante pas le programme  il continue mais plus aucune commande ne passe, je vai tester pm2

**Comment by Aymkdn** [comment]
Ça arrive tous les combien de temps à peu près ?

Si ça ne plante pas le programme, je ne suis pas sûr que pm2 sera utile. Tu peux toujours essayer.

Si ça ne fonctionne pas, dis le moi et je verrai ce que je peux faire.

**Comment by Eproms** [comment]
Je laisse tourner pm2 et reviens vers toi dans 24h. Merci pour ton aide

**Comment by Eproms** [comment]
bon bah sa a re bug, uptime 6h
 [assistant-freebox] Url => http://hd1.freebox.fr/pu  │
│                         ││ b/remote_control?code=21691480&key=1                         │
│                         ││ index > [assistant-freebox] Commande « zappe sur TF 1 »      │
│                         ││ exécutée                                                     │
│                         ││ index > [assistant-plugins] Erreur de connexion avec         │
│                         ││ PushBullet:  { Error: read ECONNRESET                        │
│                         ││ index >     at _errnoException (util.js:1022:11)             │
│                         ││ index >     at TLSWrap.onread (net.js:628:25) code:          │
│                         ││ 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by Aymkdn** [comment]
OK, donc probablement ta connexion qui merdouille. Je regarderai demain si je peux relancer la connexion même si ça échoue de cette façon

**Comment by Eproms** [comment]
ca marche merci pour ton aide

**Comment by Aymkdn** [comment]
Est-ce que tu utilises un proxy, ou VPN par exemple ? Ou alors un anti-virus/firewall agressif ? Y'a-t-il quoi que ce soit de non-classique dans ta configuration ?

Je n'arrive pas à reproduire ton erreur, même en coupant ma connexion wifi...

A priori ça serait dû à : *ECONNRESET means that the TCP conversation abruptly closed its end of the connection*

Étant donné que tu es le seul à rapporter cette erreur, j'imagine que cela vient de ta configuration et non du serveur de Pushbullet.

**Comment by Aymkdn** [comment]
Bon, ça fait plus d'une heure que je cherche un moyen... J'arrive à créer des erreurs *fake* qui vont me retourner, par exemple : 
```
[assistant-plugins] Erreur de connexion avec PushBullet:  Error: ECONNRESET
    at Timeout._onTimeout (D:\assistant-plugins\node_modules\pushbullet\lib\internal\stream.js:34:46)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

Mais après ça le programme continue à fonctionner et à recevoir les commandes de Pushbullet. Dans d'autres cas l'erreur m'arrête complètement le programme (ce que `pm2` pourrait gérer en le relançant automatiquement). **Alors que chez toi, si j'ai bien compris, le programme continue à tourner mais n'arrive plus à recevoir aucune commande,** et je n'arrive pas à reproduire ce comportement, et donc à trouver une solution.

**As-tu la possibilité de tester sur un autre ordinateur ?** Pour voir si ça vient de ton PC/Windows. À ce stade cela me semble la meilleure option.

Sinon, utilises-tu Windows 10 ? Si oui tu peux essayer d'activer Linux (comme [expliqué chez Korben](https://korben.info/installer-shell-bash-linux-windows-10.html)) puis installer `assistant-plugins` dans Linux sous Windows, pour voir si cela fonctionne mieux.

De mon côté, je ne peux rien de plus pour toi...

**Comment by Eproms** [comment]
alors oui le programme ne reponds plus une fois l'erreur apparu (est donc bloqué) je suis sur windows 10 je testerai de faire tourner via le lien que tu m'a fournie, merci encore pour ton aide . je te tien au courant

**Comment by Aymkdn** [comment]
Tu n'as pas la possibilité de tester sur un autre ordi ?

**Comment by Eproms** [comment]
Non malheureusement

**Comment by Eproms** [comment]
Dit moi n'y aurai t il pas un port à laissé ouvert par hasard ?

**Comment by Aymkdn** [comment]
Alors, t'as pu trouvé l'origine du problème ? Ou as-tu essayé de le lancer dans le Linux de Windows ?

**Comment by Aymkdn** [comment]
Je ferme ce ticket. Si tu as besoin d'aide n'hésite pas à continuer ici.

**Comment by SiddhyN** [comment]
En effet @Aymkdn c'est exactement la même erreur. Désolé de ne pas avoir vu cette issue avant ...

@Eproms as tu trouvé une solution ? Je pense avoir la même config que toi (windows10 / avast). Je n'ai pas encore tester avec le linux de windows10 non plus. 

Merci d'avance pour ton retour :)

**Comment by Eproms** [comment]
J'ai abandonné et est tout mis sur raspberry pi depuis plus de problème. DslEnvoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [Aymkdn/assistant-plugins] [assistant-plugins] Erreur de connexion avec PushBullet (#123)De : Siddhy À : Aymkdn/assistant-plugins Cc : Eproms ,Mention En effet @Aymkdn c'est exactement la même erreur. Désolé de ne pas avoir vu cette issue avant ...
@Eproms as tu trouvé une solution ? Je pense avoir la même config que toi (windows10 / avast). Je n'ai pas encore tester avec le linux de windows10 non plus.
Merci d'avance pour ton retour :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Aymkdn/assistant-plugins","title":"Aymkdn/assistant-plugins","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Aymkdn/assistant-plugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SiddhyN in #123: En effet @Aymkdn c'est exactement la même erreur. Désolé de ne pas avoir vu cette issue avant ...\r\n\r\n@Eproms as tu trouvé une solution ? Je pense avoir la même config que toi (windows10 / avast). Je n'ai pas encore tester avec le linux de windows10 non plus. \r\n\r\nMerci d'avance pour ton retour :)"}],"action":{"name":"View Issue","url":"https://github.com/Aymkdn/assistant-plugins/issues/123#issuecomment-417007635"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Aymkdn/assistant-plugins/issues/123#issuecomment-417007635",
"url": "https://github.com/Aymkdn/assistant-plugins/issues/123#issuecomment-417007635",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Aymkdn/assistant-plugins] [assistant-plugins] Erreur de connexion avec PushBullet (#123)",
"sections": [
{
"text": "",
"activityTitle": "**Siddhy**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SiddhyN",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Aymkdn/assistant-plugins\",\n\"issueId\": 123,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Aymkdn/assistant-plugins/issues/123#issuecomment-417007635"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 321626452\n}"
}
],
"themeColor": "26292E"
}
]
