### ISSUE TITLE
Applet pour la mozaique

### ISSUE THREAD

**Issue by Eproms** [Aymkdn/assistant-plugins#124]
hello aurai tu une applet fonctionnel pour la mosaïque j'ai test des applet avec "zappe sur 0" mais cela ne fonctionne pas .

encore merci pour ton aide

**Comment by Aymkdn** [comment]
Je regarde ça demain car faudra que je teste. Je te tiens au courant.

**Comment by Eproms** [comment]
Merci c'est super sympa de ta part

**Comment by Aymkdn** [comment]
Je viens d'ajouter le support de la chaine Mosaïque dans la version v2.0.9

Je t'invite à mettre à jour : https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-

Ensuite tu pourras dire : `zappe sur mosaïque` ou `zappe sur la zéro`

**Comment by Aymkdn** [comment]
Je ferme l'issue, si tu as un soucis, n'hésite pas à poster ici

**Comment by Eproms** [comment]
Super je met à jour. Merci beaucoup
