### ISSUE TITLE
Lancer le programme au démarrage et en arrière-plan

### ISSUE THREAD

**Issue by wave64** [Aymkdn/assistant-plugins#125]
J'ai bien procéder comme indiquer et d'ailleurs merci pour ce travail et partage cela fonctionne très bien seulement voilà comment supprimer ce lancement automatique via "pm2" car en fait il ne le fait pas en totalement en arrière plan à chaque démarrage PC une fenêtre de commande "npm" apparaît le temps de lancer le programme en plein milieu de l'écran ce qui est contraignant pour moi car ça ne se fait pas tout de suite et je ne pas poursuivre ce que je fais le temps qu'elle disparaisse alors certes ce délais est quand même assez court mais je préférerai revenir à un lancement manuel aux besoins.

Merci

**Comment by Aymkdn** [comment]
Voici comment procéder pour arrêter le programme au démarrage : 

Ouvre une console CMD et tape la commande suivante (comme expliqué dans [la doc de pm2](http://pm2.keymetrics.io/docs/usage/startup/)) : 
```bash
pm2 unstartup
```

Et au démarrage de ton ordi, pour avoir le programme en arrière-plan, tu devrais pouvoir taper (dans une console CMD) : 
```bash
pm2 resurrect
```

**Comment by wave64** [comment]
Bonjour,

 

Merci malheureusement aucun résultat positif avec ces 2 commandes la fenêtre npm s’affiche toujours au démarrage.

 

Cordialement,

 

De : Aymeric <notifications@github.com> 
Envoyé : dimanche 8 avril 2018 12:11
À : Aymkdn/assistant-plugins <assistant-plugins@noreply.github.com>
Cc : wave64 <pinlou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Aymkdn/assistant-plugins] Lancer le programme au démarrage et en arrière-plan (#125)

 

Voici comment procéder pour arrêter le programme au démarrage :

Ouvre une console CMD et tape la commande suivante (comme expliqué dans la doc de pm2 <http://pm2.keymetrics.io/docs/usage/startup/> ) :

pm2 unstartup

Et au démarrage de ton ordi, pour avoir le programme en arrière-plan, tu devrais pouvoir taper (dans une console CMD) :

pm2 resurrect

**Comment by Aymkdn** [comment]
Il n'y a qu'une commande .... l'autre c'est pour relancer le programme en arrière-plan après le redémarrage.

Questions : 
1. Quand t'as tapé `pm2 unstartup` ça a répondu quoi ? Tu peux me faire une capture d'écran pour voir ?
2. Après avoir redémarré, ouvre une console CMD puis tapes la commande ci-dessous, et montre moi le résultat : 
```bash
pm2 list
```

**Comment by Aymkdn** [comment]
Ah, en fait je me suis trompé, il faudrait taper la commande ci-dessous (comme indiqué dans la doc de [pm2-windows-startup](https://github.com/marklagendijk/node-pm2-windows-startup)) : 
```bash
pm2-startup uninstall
```

**Comment by wave64** [comment]
Alors pour la capture d'écran de pm2 unstartup et pm2 list trop rapide pas le temps de voir la fenêtre disparaît aussi vite qu'elle apparaît!!! désolé je ne sais pas comment remédier à cela...

Malgré tout bonne nouvelle pm2-startup uninstall ça fonctionne plus de lancement automatique, je peux donc relancer manuellement via start.bat dans mon dossier assistant-plugins sij'ai bien compris?

Encore merci!!!

**Comment by Aymkdn** [comment]
Oui tout à fait !
