### ISSUE TITLE
Demande d'autorisation échouée

### ISSUE THREAD

**Issue by fatexx** [Aymkdn/assistant-plugins#127]
Bonjour,

Suite au lancement de start.bat j'obtiens ce message d'erreur "La demande d'autorisation à La Freebox a échoué (voir screenshot)
Pourtant j'ai suivi à la lettre les instructions, configuré le fichier avec le bon code pushbullet et télécommande.

Avez-vous une idée?
Merci,
Fatex

![image](https://user-images.githubusercontent.com/38229194/38523395-a119a466-3c4b-11e8-95fa-ab34197bc7d6.png)

**Comment by Aymkdn** [comment]
Tu dois approuver le programme sur l'écran LCD de la Freebox Révolution. Tu dois avoir un message qui apparaît sur l'écran de la Freebox Serveur  lorsque tu lances assistant-plugins

**Comment by fatexx** [comment]
Merci pour la réponse rapide. Je n'arrive pas à l'étape d'approbation sur l'écran LCD. D'ailleurs rien ne s'affiche sur celui-ci

**Comment by Aymkdn** [comment]
Tu regardes bien la Freebox Serveur, celle qui indique l'heure ? Et tu as bien une Freebox Révolution ?

**Comment by fatexx** [comment]
Oui j'ai bien la Freebox Revolution et je regarde bien le Serveur qui garde l'heure affichée et ne propose rien au lancement de start.bat

**Comment by Aymkdn** [comment]
Connecte toi sur ta Freebox Serveur via http://mafreebox.freebox.fr/login.php puis va dans : 
**Paramètres de la Freebox** > **Mode Simplifié** > **Gestion des accès**

Puis dans la zone "Applications" vérifie que tu as coché la case **Permettre les nouvelles demandes d'association**

**Comment by fatexx** [comment]
La case "Permettre les nouvelles demandes d'association" est bien cochée.
J'ai aussi essayé de mettre player_ip avec l'adresse du player dans le fichier de config sans succès

**Comment by Aymkdn** [comment]
Non ce n'est pas lié au Player...

Essaie de redémarrer ta Freebox Serveur pour voir ?

**Comment by fatexx** [comment]
Même comportement.
J'ai lancé un wireshark sur ma machine et je remarque au lancement du start.bat une connexion vers une adresse publique qui est différente de celle que je vois sur whatsmyip. D'où est-ce que le script récupère l'adresse IP de la Freebox server? est-il en tran d'interroger la bonne IP?

**Comment by Aymkdn** [comment]
Il interroge mafreebox.freebox.fr

**Comment by fatexx** [comment]
Aymeric je viens de découvrir le problème. Mon disque sur la freebox était à 100%. J'ai libéré de la place et ça vient de fonctionner.
Je vais pouvoir m'amuser avec la config.
Merci pour ton aide et ta réactivité.

**Comment by Aymkdn** [comment]
Ah ok ! J'étais un peu à court d'idées ^^
