### ISSUE TITLE
Problème installation assistant freebox

### ISSUE THREAD

**Issue by darff** [Aymkdn/assistant-plugins#128]
Bonjour,

Je rencontre un problème lors de l'installation du plugin freebox + notifier. J'ai bien installer Node.js.

Quand je lance install.bat 

l'installation progresse puis arrivé à

![installation assistant plugin](https://user-images.githubusercontent.com/38245030/38548484-37d9f7b4-3cb2-11e8-8765-c8b4cecac425.png)

ça reste comme ça pendant au moins une bonne minute et puis

![assistant plugins](https://user-images.githubusercontent.com/38245030/38548558-5b38c0aa-3cb2-11e8-9007-563eddf471ed.png)

Est ce que quelqu'un aurait une piste ?

ps : Je suis sous Windows 10

En vous remerciant par avance 

Darff

**Comment by Aymkdn** [comment]
Salut,

Il est suggéré [là](https://github.com/npm/npm/issues/17444#issuecomment-373912286) que c'est dû à un logiciel AntiMalware (comme MalwareBytes) qui pourrait bloquer l'installation. Est-il installé ? Si oui, essaie de le [mettre à jour](https://forums.malwarebytes.com/topic/224958-blocks-npm-from-working/) en version 3.4.5.2467, ou de l'arrêter le temps de l'installation.

Sinon dans [ce post](https://github.com/npm/npm/issues/17444#issuecomment-311522791) il est suggéré de vérifier qu'il n'y a pas des instances de Node qui tournent dans le Gestionnaire des Tâches (et de les killer), ainsi que Visual Studio s'il est ouvert sur ton ordi.

CC @ABOATDev qui avait le même soucis.

**Comment by darff** [comment]
Merci de ta rapidité une fois malwarebytes désactivé plus aucun soucis, l'installation s'est déroulée sans problème et je peux parler a ma freebox via mon google home sans soucis. Je tiens a te remercier pour ton boulot et si jamais tu as une page de dons ça sera avec plaisir :)
Passe un bon après midi 
A la prochaine :)
Darff

**Comment by Aymkdn** [comment]
Cool :-)

**Comment by ABOATDev** [comment]
Je viens de désactivé MalwareBytes et comme par magie plus de problème aussi ! Merci

**Comment by Aymkdn** [comment]
> si jamais tu as une page de dons ça sera avec plaisir

Suite à ta suggestion @darff (et t'es le deuxième a m'en parlé) j'ai rajouté en bas de la documentation une section "Faire un don" avec un lien vers [paypal.me/aymkdn](https://www.paypal.me/aymkdn) ;-)
