### ISSUE TITLE
Docker integration ?

### ISSUE THREAD

**Issue by macpoupou** [Aymkdn/assistant-plugins#129]
Bonjour, 
pour simplifier l'intégration sur différentes plateformes, serait-il possible de faire une image Docker basée sur node.js d'assistant plugins ?
Il n'y aurait plus qu'à configurer l'image via des packages.json et config.json...

J'ai essayé d'en créer une mais n'étant pas familiarisé avec la techno j'ai un peu du mal.

**Comment by Aymkdn** [comment]
Je n'ai jamais utilisé Docker .... Donc je regarderai à l'occasion

**Comment by dmartinpro** [comment]
Hello, pour info, j'ai créé une image Docker avec le plugin freebox.
Pour le moment mon probleme est que quand je parle à Amazon Spot, il ne se passe juste rien...

**Comment by Aymkdn** [comment]
Tu peux ouvrir une issue dédiée en fournissant un maximum d'informations?

**Comment by dmartinpro** [comment]
Au temps pour moi, problème entre le clavier et la chaise :)

Container Docker opérationnel donc ! Je vais commiter cela sur Github prochainement et donnerait le lien vers le repo.

**Comment by dmartinpro** [comment]
Voici l'image Docker pour Assistant Plugins avec l'extension Freebox installée:
https://github.com/dmartinpro/assistant-plugins-docker

Le fichier Dockerfile est assez simple et devrait se comprendre seul (au besoin, je peux l'expliquer).

**Comment by dmartinpro** [comment]
N'étant pas familier de Node, si @macpoupou peut l'améliorer maintenant que la base est fonctionnelle, avec un support de package.json et config.json (je connais pas le foncitonnement), je suis preneur.

**Comment by Aymkdn** [comment]
Je ferme cette _issue_ comme je ne compte pas créer d'image Docker pour le moment, et que c'est déjà ouvert depuis 2 ans ^^
