### ISSUE TITLE
re probleme

### ISSUE THREAD

**Issue by skiman88** [Aymkdn/assistant-plugins#13]
ok merci, ca marche sans la virgule, mais pare contre quand je parle a l assistant exemple "ok google zap sur m6", il me dit "ok je zap sur m6" mais rien ne se passe, désolé de vous embêter mais je suis novice

**Comment by Aymkdn** [comment]
Regarder dans la fenêtre qui s'est ouverte ce qu'il se dit. Tu verras la commande reçue, et son interprétation.

**Comment by skiman88** [comment]
la fenetre dans ifttt applet ran?

google assistant
say a phrase with a text ingredient
trigger ran, 23 novembre a 11:57

Pushbullet
push a note
action ran, 23 novembre a 11:57

**Comment by Aymkdn** [comment]
Non la fenêtre sur l'ordinateur, là où tu lances le programme.

**Comment by skiman88** [comment]
heu vous allez me prendre pour je ne sais pas quoi mais quel programme? dsl

**Comment by cottarelf** [comment]
Salut,
Pour que l'application fonctionne correctement, tu doit lancer un serveur `nodejs` sur un ordinateur cher toi (windows, mac ou linux), sur windows c'est en lançant le fichier `start.bat` (sur linux et macOs en tapant la commande : `node index.js`) que tu verra des informations sur l'initialisation des plugins et sur leurs fonctionnement quand tu appel une fonction depuis ton téléphone, si tu pouvait envoyer le contenu de la console pour te dire d'où vient le problème.

**Comment by Aymkdn** [comment]
Tout est expliqué là https://github.com/Aymkdn/assistant-plugins/blob/master/Readme.MD ...

**Comment by skiman88** [comment]
ok j ai compris apres plusieur manip, la freebox s eteint apres ma commande depuis google home voici ce que ca a affiché
[2.txt](https://github.com/Aymkdn/assistant-plugins/files/1498948/2.txt)

**Comment by Aymkdn** [comment]
Donc c'est tout bon, non ?

**Comment by skiman88** [comment]
la free s eteint quand je fais une commande et peut tu me dire comment retirer les notification ifttt sur mes telephone a chaque commande

**Comment by skiman88** [comment]
a chaque fois que je dis quelque chose il allume la free et si elle est deja allumé il l eteint et il ne zape pas les chaines.
[3.txt](https://github.com/Aymkdn/assistant-plugins/files/1500587/3.txt)

**Comment by Aymkdn** [comment]
As-tu activé le AirMedia comme  indiqué sur https://github.com/Aymkdn/assistant-plugins/blob/master/assistant-freebox/Readme.md  (sans mot de passe) ? 

Car c'est cela qui permet de savoir si la Freebox est allumée ou éteinte. 

Pour les notifications sur ton téléphone, tu dois enlever l'application Pushbullet, ou alors si tu l'utilises pour d'autres choses, tu peux te créer un second compte et le dédier à IFTTT.

Pour ma part, j'ai laissé l'application mobile mais j'ai coupé le son des notifications. Au final ce n'est pas gênant car la notification du canal IFTTT disparaît immédiatement.

**Comment by skiman88** [comment]
je ne comprend pas ce matin ca a marché, d un coup d un seul voila que ca recommance les commandes se font mais la freebox s eteint, le airmedia est bien activé pourtant, je comprend rien
[4.txt](https://github.com/Aymkdn/assistant-plugins/files/1502881/4.txt)

**Comment by Aymkdn** [comment]
Essaie peut-être de redémarrer ton Freebox Player ?

**Comment by skiman88** [comment]
j ai tout redemarrer et la freebox player s eteint a chaque commande

**Comment by Aymkdn** [comment]
Tu dois avoir un problème avec ton AirMedia alors. Dès que j'ai le temps je regarderai comment tu pourras désactiver ça.

**Comment by skiman88** [comment]
c est gentil merci

**Comment by skiman88** [comment]
si ca peu t aider, la commande Allume la télé via la Freebox et zappe sur une chaine fonctionne quand la free et eteint

**Comment by Aymkdn** [comment]
La nouvelle version est disponible. Voir l'annonce : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0

J'en ai profité pour ajouter un paramètre pour désactiver la vérification que la Freebox est allumée ou éteinte. Je t'invite à installer la nouvelle version puis à lire la section dans [assistant-freebox](https://aymkdn.github.io/assistant-plugins/?plugin=freebox) qui parle du paramètre `check_player_on`

**Comment by skiman88** [comment]
Merci j essaie ça se soir

**Comment by skiman88** [comment]
hello, quand tu dis "ajouter le paramètre check_player_on en le mettant à la valeur false." tu veux dire a la place ou ailleur ? et bien dans configuration.json.  j ai essayé a la place est ca marche pas, j ai installé la nouvelle version, l applet allume la tele et zappe sur .. fonctionne toujours mais des que le freebox player est deja en marche cela me l arrete pour n importe quelle applet

**Comment by Aymkdn** [comment]
Pas la place, mais en plus.

Ton configuration.json (celui qui est à la racine) ressemblera à :  
```javascript
{
  "main": {
    "pushbullet_token": "o.szVtF0V3Mntw0AbTWWIUBBJ6rBpBU5k"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "97421754",
      "search_path": "/Disque dur/Vidéos/TV/",
      "use_Mon_Bouquet": true,
      "box_to_control": "hd1",
      "check_player_on":false,
      "app_token": "fbii+YS9sGkvGQb7123E3avpDbVbaJK7SMFkX+63PZKGj0+MUM7QpKaskd0Cu1X"
    }
  }
}

```

**Comment by skiman88** [comment]
toujours pareil je comprend pas j ai recopié comme ci dessus

**Comment by Aymkdn** [comment]
C'est impossible...

Tu as forcément mal fait quelque chose alors...

Tu as bien arrêté le programme puis relancé après avoir changé le fichier de configuration ?
Peux-tu me montrer ton fichier de config ?
Peux-tu me montrer la fenêtre de commandes ?

**Comment by skiman88** [comment]
![capture d ecran 8](https://user-images.githubusercontent.com/33912880/33528233-75f4a850-d85d-11e7-9f37-6a18abd2bcf7.png)
![capture d ecran 10](https://user-images.githubusercontent.com/33912880/33528234-7b8f8e9c-d85d-11e7-9c85-ce03d7fbf94a.png)

**Comment by skiman88** [comment]
j en profite pour te dire aussi que maintenant avec l applet allume la tele et zappe sur ..quand le player est eteind, ca allume bien mais ouvre mon bouquet

**Comment by Aymkdn** [comment]
Oui c'est normal car tu allumes "use_Mon_Bouquet" à true.

Quand as-tu téléchargé `assistant-plugins` ?

**Comment by skiman88** [comment]
maintenent mais j ai recopier betement ce que tu m as envoyé, je remet false

**Comment by Aymkdn** [comment]
Tu as donc un fichier `update.bat` dans ton répertoire ?

**Comment by skiman88** [comment]
oui

**Comment by Aymkdn** [comment]
Alors, au temps pour moi, je viens de regarder et en effet y'avait un bug.

Je viens de le modifier.

Procède ainsi : 

1. Arrête le programme
2. double-clique sur `update.bat`
3. relance le programme avec `start.bat`

Cette fois on doit être bon...

**Comment by skiman88** [comment]
yaouuuu, t es trop fort ca marche, t es un bon, grand merci
