### ISSUE TITLE
Problème bashrc

### ISSUE THREAD

**Issue by Lacertaenova** [Aymkdn/assistant-plugins#131]
Bonjour,

Je suis allé sur votre tuto disponible à cette adresse:
https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

J'ai une erreur à l'étape suivante :
 source ~/.bashrc

Voici la capture d'écran du programme :
![2018-04-23_15h36_37](https://user-images.githubusercontent.com/38660408/39130027-6c6c1336-470c-11e8-9166-4efa0b5465cb.png)

Et le message d'erreur qu'il y a après:
![2018-04-23_15h39_46](https://user-images.githubusercontent.com/38660408/39130120-a2846630-470c-11e8-986b-d84da48c41fe.png)

Je ne suis pas spécialiste de la chose, c'est pourquoi je vous demande de bien vouloir m'aider x)

Merci d'avance,
Cordialement,

**Comment by Aymkdn** [comment]
Supprime le `$` au début de ton fichier : 
![capture](https://user-images.githubusercontent.com/946315/39131826-af15dc86-4710-11e8-91de-86f0529ea869.PNG)

**Comment by Lacertaenova** [comment]
Ok, problème résolu, je vous remercie infiniment ;)

**Comment by Aymkdn** [comment]
Nickel !
