### ISSUE TITLE
configuration.json

### ISSUE THREAD

**Issue by bengero** [Aymkdn/assistant-plugins#132]
bonjour j'ai suivie le tuto installation plug in freebox pour raspberry a la lettre.

etape 6 : configuration : Se reporter à la documentation.
dans la doc : Tout se passe dans le fichier configuration.json qui contient toutes les éléments à configurer.

petit hic pour moi je na e sais pas ou trouver ce fichier config.json afin de poursuivre mon installation.

merci de votre aide

**Comment by bengero** [comment]
j'ai du manquer une étape...
dans le tuto pas-à-pas concernant raspberry je ne crée pas de dossier pour dézipper  assistant plugins, seulement de ligne de commande .
du coup je suis perdu.

**Comment by Aymkdn** [comment]
En fait, c'est à l'étape 5 que le fichier doit se créer (après l'ajout des plug-ins).

Tu as installé le plugin Freebox ? 

Tu as quoi dans ton répertoire assistant-plugins comme fichiers ?
