### ISSUE TITLE
explication commandes freebox

### ISSUE THREAD

**Issue by frcm5568** [Aymkdn/assistant-plugins#133]
Bonjour,
Je souhaiterais plus de précisions sur le fonctionnement des commandes envoyées à la Freebox.
Dans l'exemple donné dans le tuto, on trouve par exemple :
tv : envoie la séquence home, wait2000, right, left, red, ok, wait4000

Qui est censé si je ne me trompes pas :
Envoyer la Freebox sur le menu Home, puis sous-menu Télévision.
Hors dans l'interface de la Freebox, Home par défaut pointe sur télévision.
Right, Left me conforte dans l'interprétationais pourquoi ref, ok ? Et pas seulement ok ?

**Comment by Aymkdn** [comment]
Le `right,left` permet de s'assurer qu'on se replace au début de la liste du menu en cours. Par exemple si tu vas dans "Mes Enregistrements", puis que tu appuies sur "Home", alors tu reviens sur le menu "Mes Enregistrements". Si tu fais "right,left", ça va te replacer au début de la liste du menu (donc "Freebox TV").

C'est donc une astuce pour se retrouver en haut de la liste (et donc d'une position qu'on connait).

**Comment by frcm5568** [comment]
D'accord pour ce point mais la touche rouge ??

**Comment by Aymkdn** [comment]
Le `red` permet de retourner sur le menu "Télévision".

Par exemple tu vas dans "Freebox Replay" puis : 
  - `home` : retour sur la Home, le cursor est sur "Freebox Replay"
  - `right,left` : on se place au début de la liste (donc sur "Mes Vidéos")
  - `red` : on va sur "Freebox TV"

Sauf que, la documentation n'est pas à jour. Je ne fais plus ça maintenant pour `tv`. Je n'utilise plus `right,left`, mais juste `red`. Je mets à jour la doc immédiatement.

Mais bon, pour toi, si tu veux coder ta propre template tu as juste à utiliser `tv` (pas besoin de mettre la séquence).

**Comment by Aymkdn** [comment]
(commentaire ci-dessus mis à jour)

**Comment by frcm5568** [comment]
Merci de ces précisions, je vais me mettre sur ma question d'origine sur une autre issue pour les autres utilisateurs.
J'avais besoin de comprendre cela pour réaliser ma commande justement 😁
Je continuerai sur l'autre issue.
