### ISSUE TITLE
accès à un dossier partagé freebox

### ISSUE THREAD

**Issue by frcm5568** [Aymkdn/assistant-plugins#134]
Bonjour, le tuto est super bien fait pour la mise en place. J'ai tout mis sur mon raspberry domotique ça marche bien.

Cependant, comment accéder aux dossiers disques de la Freebox, j'ai un lien vers un serveur dlna et j'ai un peu tout essayé dans la variable search_path sans succès.

**Comment by frcm5568** [comment]
Réponse via tweeter :
Salut. Tu peux regarder là : https://t.co/Q1yDQ1Dgqv
Si ça ne répond pas à ton problème, merci d'ouvrir un nouvel issue sur le même lien !

**Comment by Aymkdn** [comment]
J'ai aussi rajouté ça dans la doc : 
![capture](https://user-images.githubusercontent.com/946315/39916308-5ae2ea98-550a-11e8-9f71-9e69a7945161.PNG)

**Comment by frcm5568** [comment]
En y réfléchissant, ça reste hasardeux comme technique en effet, certains partages peuvent apparaître et s'intercaler.
Il faudrait pouvoir créer un lien logique sur le disque dur de la Freebox vers le partage afin de travailler par nom. Mais je ne sais pas si c'est possible.

**Comment by Aymkdn** [comment]
Pour `search_path` j'utilise l'[API Freebox](https://dev.freebox.fr/sdk/os/fs/) qui permet de parcourir le disque dur de la Freebox.

Si le contenu est ailleurs sur le réseau, on ne peut pas utiliser cette même API car la Freebox est "aveugle" par rapport à ce qu'il y a sur le réseau.

Si le disque dur est branché directement sur la Freebox, ça pourrait peut-être fonctionner, mais s'il est en réseau, alors c'est plus compliqué (par exemple un lien logique ne marcherait pas à priori car on n'est plus sur sur `filesystem` mais sur du `network`).

Perso tout est sur mon disque dur de la Freebox ^^

**Comment by Aymkdn** [comment]
Du coup je ferme cet issue si tu n'as pas une question en particulier ;-)
