### ISSUE TITLE
Syntax error lors de l'installation de l'assistant pluggin sur mac

### ISSUE THREAD

**Issue by feligipsy** [Aymkdn/assistant-plugins#136]
Bonjour,

Je n'arrive pas à installer l'assistant pluggin sur mac, une fois avoir entrée l'accés token et le code télécommande freebox dans configuration.json

Je retourne sur le terminal et rentre bien évidemment "node index.js" voici le message d'erreur qui s'affiche 

SyntaxError: /Volumes/Untitled/assistant-plugins/configuration.json: Unexpected token « in JSON at position 145
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.exports.start (/Volumes/Untitled/assistant-plugins/node_modules/assistant-plugins/index.js:4:23)
    at Object.<anonymous> (/Volumes/Untitled/assistant-plugins/index.js:1:92)
    at Module._compile (module.js:652:30)

Une personne a t'elle déjà eu ce retour? Avez vous une solution ?

dans l'attente de votre réponse 
Cordialement

**Comment by Aymkdn** [comment]
Montre moi le contenu de ton configuration.json car tu as mal fait quelque chose dans ce fichier

**Comment by feligipsy** [comment]
{
  "main": {
    "pushbullet_token": "o.L2KTtHbt6asm1KidSMt1CylR8CXQoxMU"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": « 40269216 »,
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1 »
    }
  }

  }

**Comment by feligipsy** [comment]
merci de votre réponse super rapide j'ai simplement rempli le pushbullet et le code télécommande (que j'ai verifié 50 fois)

**Comment by Aymkdn** [comment]
Tu as mis des `«` et des  `»` au lieu de `"`

**Comment by feligipsy** [comment]
je vais changer et ré essayer ca c'est mis automatiquement merci

**Comment by feligipsy** [comment]
nouvelle erreur malgré modif

SyntaxError: /Volumes/Untitled/assistant-plugins/configuration.json: Unexpected  in JSON at position 266
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.exports.start (/Volumes/Untitled/assistant-plugins/node_modules/assistant-plugins/index.js:4:23)
    at Object.<anonymous> (/Volumes/Untitled/assistant-plugins/index.js:1:92)
    at Module._compile (module.js:652:30)


modif 

{
  "main": {
    "pushbullet_token": "o.L2KTtHbt6asm1KidSMt1CylR8CXQoxMU"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "40269216",
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1 »
    }
  }

  }

**Comment by Aymkdn** [comment]
T'en as oublié un... Après `hd1`...

**Comment by feligipsy** [comment]
ah oui au niveau hd1 aussi

**Comment by feligipsy** [comment]
oui merci je viens de voir je modifie

**Comment by feligipsy** [comment]
super ça marche sauf que si je peux t'embeter encore un peu

[assistant] Assistant v2.0.4 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'freebox' (v2.0.9)
[assistant-freebox] Demande d'autorisation auprès du Freebox Server...
[assistant-freebox] Approuvez le plugin en allant sur l'écran LCD de votre Freebox Serveur et en utilisant la flèche de droite sur celui-ci.

je suis sur l'écran de la freebox je comprends pas comment faire

**Comment by Aymkdn** [comment]
C'est tout bon ?

**Comment by feligipsy** [comment]
euh.... non un dernier petit probleme peut etre vs pouvez m aider

**Comment by feligipsy** [comment]
je suis en train de configurer ifTTT pour l'étape
llume la télé (https://ifttt.com/applets/tuKQJrnH-allume-la-tele-via-la-freebox) : allume la Freebox ET va mettre une chaine télé (via Freebox TV, ou via Mon Bouquet, ou via Les Chaines CANAL selon la configuration)

cependant après avoir appuyer sur on , il ne me propose que 

"IFTTT needs permission to access:
Pushbullet" 

et pas google assistant (comme sur votre vidéo)

est ce normal?

**Comment by Aymkdn** [comment]
Oui tu dois donner les permissions qu'il te demande

**Comment by feligipsy** [comment]
mais cela fonctionnera quand mm, mm s'il propose pas google assistant ?

**Comment by Aymkdn** [comment]
Oui. C'est possible que tu aies déjà accepté avant ou autre. Essaie, tu verras bien.

**Comment by feligipsy** [comment]
j'ai essayé et malgré bonne configuration google home me répond "je ne sais pas comment vs [aider"[]
<img width="1051" alt="capture d ecran 2018-05-12 a 00 37 39" src="https://user-images.githubusercontent.com/39203760/39949707-cc4c1e4e-557c-11e8-9db3-9b6eee678ea1.png">

**Comment by Aymkdn** [comment]
Répète plusieurs fois. Il faut quelques instants pour qu'il le prenne en compte

**Comment by feligipsy** [comment]
oui c'est ce que j'ai fais... alors par exemple maintenant je dis "dis google eteinds la freebox" elle me dit "j'éteinds la freebox" mais rien ne se passe... pareil pour l'allumage elle me répond mais y a rien qui marche

**Comment by Aymkdn** [comment]
Tu as quoi dans la console du programme sur ton Mac ? (le programme ne doit pas être arrêté sinon ça ne marchera pas)

**Comment by feligipsy** [comment]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 2057ms
[assistant-freebox] La Freebox n'est pas allumée, donc on l'allume.
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=40269216&key=power
[assistant] Commande reçue:  [ 'freebox_tv' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 533ms
[assistant-freebox] La Freebox n'est pas allumée, donc on l'allume.
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=40269216&key=power
[assistant-freebox] Erreur : le Freebox Player ne répond pas ! Essayer de changer le paramètre 'box_to_control' dans la configuration de 'hd1' à 'hd2', ou de vérifier votre réseau entre cet ordinateur et la Freebox Player.
[assistant-freebox] Commande « tv » exécutée
[assistant] Commande reçue:  [ 'freebox_off' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 564ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=40269216&key=power
[assistant-freebox] Erreur : le Freebox Player ne répond pas ! Essayer de changer le paramètre 'box_to_control' dans la configuration de 'hd1' à 'hd2', ou de vérifier votre réseau entre cet ordinateur et la Freebox Player.
[assistant-freebox] Commande « tv » exécutée
[assistant-freebox] Erreur : le Freebox Player ne répond pas ! Essayer de changer le paramètre 'box_to_control' dans la configuration de 'hd1' à 'hd2', ou de vérifier votre réseau entre cet ordinateur et la Freebox Player.
[assistant-freebox] Commande « off » exécutée
[assistant] Commande reçue:  [ 'freebox_off' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 916ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=40269216&key=power

**Comment by Aymkdn** [comment]
Tu peux regarder ce qui est expliqué ici pour t'aider : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

**Comment by Aymkdn** [comment]
Tu as donc la réponse. Remplace `hd1` par `hd2` dans configuration.json comme indiqué.

Arrête et redémarre ensuite le programme et retest

**Comment by feligipsy** [comment]
ok super je re teste merci

**Comment by feligipsy** [comment]
tout marche!!!! merciiiiii pour tout j'y suis depuis 21H a cause de la syntax donc vraiment contente merciiii

**Comment by Aymkdn** [comment]
Cool!
