### ISSUE TITLE
Bluetooth multi enceinte

### ISSUE THREAD

**Issue by Pr0killer** [Aymkdn/assistant-plugins#137]
Bonjour,

Tout d'abord merci pour tous ces plugins qui m'aident énormément dans la gestion de ma maison avec ma google home mini.

Je rencontre actuellement un problème avec le plugin bluetooth.
J'ai créé 2 applets IFTTT pour pouvoir connecter à l'une ou l'autre des enceintes en fonction de la pièce souhaitée et malgré le fait que dans la console je vois bien la bonne commande reçue (avec le bon nom de l'enceinte), la google home mini se connecte systématiquement à la dernière enceinte à laquelle elle a été connectée. Est-ce moi qui fait une fausse manip ou est-ce la google home mini qui ne permet pas cela ?

![bluetooth](https://user-images.githubusercontent.com/39240642/39968333-76252ba0-56cb-11e8-8efe-1db76fa2386f.png)

**Comment by Aymkdn** [comment]
Alors déjà, c'est pas `disconnect` tout seul, mais `disconnect NOM_ENCEINTE`. Ensuite je n'ai qu'une enceinte Bluetooth à la maison donc je ne peux pas en tester plusieurs, mais j'imagine que ça doit fonctionner. Je pense que cela fonctionne sans devoir passer par un `disconnect`.

Donc : 

1. Vérifie que tu as utilisé les bons noms d'enceintes (le nom doit être tel qu'il apparait dans l'application Google Home)
2. Crée 2 applets : une `bluetooth_connect V1-C` et l'autre `bluetooth_connect Poweradd`, puis teste.

Dis moi ce qu'il en est.

**Comment by Pr0killer** [comment]
Alors pour avoir tester le disconnect tout seul, ça fonctionne bien... même si cela n'était peut-être pas prévu... ça fonctionne aussi très bien avec le nom de l'enceinte derrière ;)

Pour la connexion par contre que j'utilise 1 des 2 applets, j'ai toujours la même enceinte qui prend la connexion malgré la bonne commande
![bluetooth1](https://user-images.githubusercontent.com/39240642/39968626-77c3973a-56d0-11e8-8742-94cdd4c78169.png)

**Comment by Aymkdn** [comment]
Est-ce qu'une des enceintes est tout le temps allumée et définie par défaut sur le Google Home ?

**Comment by Pr0killer** [comment]
à partir du moment ou le disconnect est effectué, j'ai vérifié il n'y en a plus.

Par contre je remarque que c'est la dernière utilisée dans l'application qui est prise en compte systématiquement peut importe la commande

**Comment by Aymkdn** [comment]
J'ai une piste... J'effectue quelques tests et je mettrai à jour le plugin si c'est concluant, et tu pourras tester

**Comment by Pr0killer** [comment]
Pas de problème, ça me soulage déjà pas mal ;)

C'était juste histoire de savoir si c'est moi qui faisait la boulette ;)

edit: ok pour ton second post ;)

**Comment by Aymkdn** [comment]
Je viens de publier la v1.1.0

Arrête `assistant-plugins` puis utilise `update.bat` qui devrait mettre à jour le plugin, puis relance `assistant-plugins` et dis moi ce que ça donne !

**Comment by Pr0killer** [comment]
Merci ça fonctionne bien.

Si on veut chipoter  ça fonctionne uniquement si on fait un disconnect (ça sera très rare dans mon cas que je passe de l'une à l'autre en direct) sinon j'ai l'erreur suivante `[assistant] Commande reçue:  [ 'bluetooth_disconnect V1-C' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Connexion à V1-C
V1-C 1e:44:25:e9:a1:36
[assistant] Commande reçue:  [ 'bluetooth_connect Poweradd' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Connexion à Poweradd
V1-C 1e:44:25:e9:a1:36
Poweradd f4:4e:fd:cd:6a:63
[assistant] Commande reçue:  [ 'bluetooth_connect V1-C' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Connexion à V1-C
Poweradd f4:4e:fd:cd:6a:63
V1-C 1e:44:25:e9:a1:36
[assistant-bluetooth] Erreur : la connexion au Google Home a eu un problème :  { StatusCodeError: 400 - undefined
    at new StatusCodeError (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
  name: 'StatusCodeError',
  statusCode: 400,
  message: '400 - undefined',
  error: undefined,
  options:
   { url: 'http://192.168.0.50:8008/setup/bluetooth/connect',
     method: 'POST',
     json: true,
     body: { connect: true, mac_address: '1e:44:25:e9:a1:36', profile: 2 },
     headers: { 'Content-Type': 'application/json' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 803,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 803,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'access-control-allow-headers': 'Content-Type',
        'cache-control': 'no-cache',
        'content-length': '0' },
     rawHeaders:
      [ 'Access-Control-Allow-Headers',
        'Content-Type',
        'Cache-Control',
        'no-cache',
        'Content-Length',
        '0' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 803,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'POST /setup/bluetooth/connect HTTP/1.1\r\nContent-Type: application/json\r\nhost: 192.168.0.50:8008\r\naccept: application/json\r\ncontent-length: 62\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/setup/bluetooth/connect',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        body: '{"connect":true,"mac_address":"1e:44:25:e9:a1:36","profile":2}',
        headers: [Object],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Url],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '8008',
        host: '192.168.0.50',
        path: '/setup/bluetooth/connect',
        _json: true,
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href: 'http://192.168.0.50:8008/setup/bluetooth/connect',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: '192.168.0.50:8008',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] } } } 400 undefined
`

**Comment by Aymkdn** [comment]
Remet à jour : c'est la v1.2.0 maintenant. Dis moi si tout fonctionne ?

**Comment by Pr0killer** [comment]
Toujours la même chose : 

[assistant] Commande reçue:  [ 'bluetooth_disconnect Poweradd' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Déconnexion de l'enceinte Bluetooth
[assistant] Commande reçue:  [ 'bluetooth_connect V1-C' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Connexion à V1-C
[assistant] Commande reçue:  [ 'bluetooth_connect Poweradd' ]
[assistant] Appelle du plugin 'bluetooth'
[assistant-bluetooth] Connexion à Poweradd
[assistant-bluetooth] Erreur : la connexion au Google Home a eu un problème :  { StatusCodeError: 400 - undefined
    at new StatusCodeError (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (D:\Bureau\assistant-plugins\assistant-plugins\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
  name: 'StatusCodeError',
  statusCode: 400,
  message: '400 - undefined',
  error: undefined,
  options:
   { url: 'http://192.168.0.50:8008/setup/bluetooth/connect',
     method: 'POST',
     json: true,
     body: { connect: true, mac_address: 'f4:4e:fd:cd:6a:63', profile: 2 },
     headers: { 'Content-Type': 'application/json' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 493,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 493,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'access-control-allow-headers': 'Content-Type',
        'cache-control': 'no-cache',
        'content-length': '0' },
     rawHeaders:
      [ 'Access-Control-Allow-Headers',
        'Content-Type',
        'Cache-Control',
        'no-cache',
        'Content-Length',
        '0' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 493,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'POST /setup/bluetooth/connect HTTP/1.1\r\nContent-Type: application/json\r\nhost: 192.168.0.50:8008\r\naccept: application/json\r\ncontent-length: 62\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/setup/bluetooth/connect',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        body: '{"connect":true,"mac_address":"f4:4e:fd:cd:6a:63","profile":2}',
        headers: [Object],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Url],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '8008',
        host: '192.168.0.50',
        path: '/setup/bluetooth/connect',
        _json: true,
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href: 'http://192.168.0.50:8008/setup/bluetooth/connect',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: '192.168.0.50:8008',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] } } } 400 undefined


désolé pour les pavés mais ça ne me parle pas ;)

**Comment by Aymkdn** [comment]
Donc c'est quand tu essaies de te connecter à Poweradd que ça fait ça, et seulement à celle-ci ?

Est-ce que malgré l'erreur ça fonctionne comme attendu ?

**Comment by Pr0killer** [comment]
Pas seulement, c'est quand je teste de passer de l'une à l'autre sans disconnect que ça plante, le son reste sur la première.
Si on disconnect, on peut passer de l'une à l'autre sans problème

**Comment by Aymkdn** [comment]
OK donc je vais ajouter un disconnect avant pour voir

**Comment by Pr0killer** [comment]
Ok, j'attends ton feu vert pour update et re-tester alors ;)

**Comment by Aymkdn** [comment]
v1.2.1 publiée ! :)

**Comment by Pr0killer** [comment]
Je viens de tester et ça déconnecte bien mais ça ne reconnecte pas sur l'autre enceinte et ça relance donc sur la GH

**Comment by Aymkdn** [comment]
Mmmhhh.... Peut-être faut-il un délai de quelques secondes entre les 2 commandes ? Je veux bien essayer de rajouter un délai entre les deux commandes...

**Comment by Pr0killer** [comment]
à mon avis il faut au moins 5 à 10 sec de délai si tel est le cas

**Comment by Aymkdn** [comment]
Je regarde d'abord si un appareil est connecté, et si c'est le cas je le déconnecte, puis j'attends 5 secondes, et je connecte l'appareil demandé.

S'il n'y a aucun appareil déjà connecté, alors cela se fait immédiatement.

Et si l'appareil demandé est déjà connecté, rien ne se passe.

**Comment by Pr0killer** [comment]
Perfect :D 

Un grand merci à toi pour ce boulot et cette réactivité ;)

[HS On]ps : j'ai installer le plugin bluetooth hier et ça m'a installer le template à la place, j'ai modifier le .bat pour installer le bon ;) je ne sais pas si tu l'avais vu ou pas...[HS Off]

**Comment by Aymkdn** [comment]
OK Cool !

(Merci, non j'avais pas vu !)

**Comment by Aymkdn** [comment]
Merci pour tes tests, ça m'a bien aidé ;-)

**Comment by Pr0killer** [comment]
Pas de problème ;) 

Si besoin de tester autre chose et que je peux aider hésite pas ;)
