### ISSUE TITLE
Appairage Freebox

### ISSUE THREAD

**Issue by T3iX** [Aymkdn/assistant-plugins#138]
Bonjour et merci pour ton travail,  

"Le SDK fourni par Free est sans procédure d’appairage et pourtant la quasi totalité des applications en demande une à ses utilisateurs. Les développeurs se contente de l’API HTTP, dont l’avenir a déjà été remis en cause par Free."

Une mise à jour de prévue avec l'intégration du SDK de Free qui nous permettrai de ne pas renseigner le code télécommande ?

**Comment by Aymkdn** [comment]
> Une mise à jour de prévue avec l'intégration du SDK de Free qui nous permettrai de ne pas renseigner le code télécommande ?

Non malheureusement pas pour le moment. La méthode que tu décris est beaucoup plus compliquée que la simple API HTTP, et donc demande beaucoup plus de temps.

Free avait supprimé l'API HTTP il y a quelques années, mais suite à la colère des développeurs ils l'ont remis en place.

**Comment by t3ix** [comment]
Ok merci pour ta réponse

**Comment by Aymkdn** [comment]
Bon, j'ai regardé et c'est au-delà de mes connaissances...

Free ne fournit [qu'une pauvre doc](https://dev.freebox.fr/sdk/telec.html) avec quelques fichiers en langage C, et aucune explication digne de ce nom pour quelqu'un qui chercherait à le faire fonctionner. Ils utilisent le propre protocole RUDP, pour envoyer des paquets HID (qui sont normalement envoyés sur du USB donc j'ai pas compris comment les envoyer sur une machine réseau).

Bref, ça me dépasse totalement.
