### ISSUE TITLE
Notifier sur plusieurs Google Home

### ISSUE THREAD

**Issue by smiley9** [Aymkdn/assistant-plugins#139]
Bonjour, 

Un grand merci pour le travail effectué!

je voulais savoir s'il est possible de modifier le plugin launch pour passer une variable au programme lancé.
comme par exemple: "augmente le volume de 10" où 10 serait la variable.

J'ai fait plusieurs tests mais sans succès, assistant-plugins reçois bien la commande avec la variable mais ne lance pas le script par après.

De plus pour le plugin notifier est-il possible de le paramétrer pour plusieurs google home?
Pour être franc, je ne vois pas comment ifttt pourrait savoir de quelle google home la requête est lancée pour ensuite rediriger notifier sur la bonne IP.
Mais si quelqu'un a une idée...

Voilà, encore merci pour assistant-plugin, il me simplifie grandement la vie!

**Comment by Aymkdn** [comment]
>je voulais savoir s'il est possible de modifier le plugin launch pour passer une variable au programme lancé. comme par exemple: "augmente le volume de 10" où 10 serait la variable.
> J'ai fait plusieurs tests mais sans succès, assistant-plugins reçois bien la commande avec la variable mais ne lance pas le script par après.

Montre moi ce que tu as mis dans ton applet. Tu le fais sûrement de la mauvaise façon.

> De plus pour le plugin notifier est-il possible de le paramétrer pour plusieurs google home?
> Pour être franc, je ne vois pas comment ifttt pourrait savoir de quelle google home la requête est lancée pour ensuite rediriger notifier sur la bonne IP.

En effet.... IFTTT ne sait pas quel Google Home lui demande l'action !

**Comment by smiley9** [comment]
N'ayant plus mes premiers applets de test, j'en ai refait.
Et forcement, ça fonctionne!

Je me suis effectivement raté, merci pour ton aide.

Pour notifier, à défaut de choisir le google home, peut on entrer plusieurs adresses IP? afin d'avoir la réponse sur tout les appareils?
Idealement pouvoir choisir via la note Pushbullet sur quel home répondre.

Encore merci pour ton aide.

**Comment by Aymkdn** [comment]
> Pour notifier, à défaut de choisir le google home, peut on entrer plusieurs adresses IP? afin d'avoir la réponse sur tout les appareils?
J'imagine que je devrais pouvoir modifier le plugin pour ça, oui.

> Idealement pouvoir choisir via la note Pushbullet sur quel home répondre.
Faut que je vois pour ça.

Je le tague comme une amélioration du plugin. Je verrai si j'ai du temps aujourd'hui ou un autre jour pour faire ça !

**Comment by smiley9** [comment]
super, merci!

bonne journée.

**Comment by smiley9** [comment]
je viens de penser, peut-être voir pour le choix du google-home aussi pour le plugin-bluetooth?

**Comment by Aymkdn** [comment]
Je viens de mettre en ligne la version 2.1.0 de `notifier` pour gérer plusieurs Google Home et j'ai mis à jour la [documentation](https://aymkdn.github.io/assistant-plugins/?plugin=notifier) pour expliquer comment configurer et utiliser le plugin (pour mettre à jour : https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-).

N'ayant qu'un seul Google Home je ne peux pas confirmer à 100% que tout fonctionne, donc je suis preneur de tes retours.

> je viens de penser, peut-être voir pour le choix du google-home aussi pour le plugin-bluetooth?

Oui je peux faire la même chose, mais ça me semble un peu chiant à gérer côté utilisateur ? Genre : "OK Google, connecte le salon à l'enceinte du jardin" ?

Pour info je pars en vacances à l'étranger vers 15h30, et jusqu'à vendredi.

**Comment by smiley9** [comment]
hello,
merci je vais voir pour tester cela.
pour le bluetooth, je pense que celui qui voudra l'utiliser le pourra, moi même je ne sais pas si je m'en servirai. Mais je n'ai pas notion de l'ampleur du travail.

Très bonne vacances, profites bien!

**Comment by smiley9** [comment]
je viens de tester pour une diffusion sur mes deux GH, ça marche, mais il y a un gros décalage entre les deux.
Je dirais de plusieurs seconde à l'oreille.
Pour la diffusion ciblé ça fonctionne parfaitement.

**Comment by Aymkdn** [comment]
C'est possible que Google n'autorise pas la diffusion simultanée sur ses appareils. Difficile à dire avec un seul à la maison ^^

Mais content que ça marche !

Pour le Bluetooth, je vais attendre qu'il y ait un véritable besoin de quelqu'un avant de modifier le plugin.
