### ISSUE TITLE
Pushbullet Promise rejection

### ISSUE THREAD

**Issue by mbl-35** [Aymkdn/assistant-plugins#140]
Bonjour et tout d'abord, merci pour cette initiative ainsi que pour les mécanismes mis en oeuvre (je ne suis pas partisant de l'ouverture de mon accès internet depuis Internet...). Donc la solution pushBullet et vraiment bien trouvée.

J'ai un petit soucis sur le fonctionnement **après** 24 heures. En effet, suite à la requête permettant de garder pushBullet 'en ligne', je n'arrive plus à activer les commandes (sur IFTT et pushBullet, les commandes sont bien tracées).

En regardant les logs PM2, je m'aperçois qu'il y a une erreur d'exécution lorsque la requête de 'réveil' est exécutée:
```javascript
0|assistan | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|assistan | TypeError: Cannot read property 'iden' of undefined
0|assistan |     at /home/jarvis/assistant-plugins/node_modules/assistant-plugins/index.js:26:39
0|assistan |     at Promise (/home/jarvis/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:161:12)
0|assistan |     at new Promise (<anonymous>)
0|assistan |     at PushBullet.handleError (/home/jarvis/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:149:9)
0|assistan |     at PushBullet.handleResponse (/home/jarvis/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:129:15)
0|assistan |     at request.(anonymous function).then.response (/home/jarvis/assistant-plugins/node_modules/pushbullet/lib/pushbullet.js:106:17)
0|assistan |     at <anonymous>
0|assistan |     at process._tickCallback (internal/process/next_tick.js:182:7)
```
Je suis obligé de relancer le processus pour que tout rentre dans l'ordre...
Est-ce que quelqu'un a le même comportement (v2.0.4)?

**Comment by Aymkdn** [comment]
Bizarre... Je suis encore en vacances à l'étranger là mais je rentre dans la journée. Je regarde ça au plus vite !

**Comment by Aymkdn** [comment]
(je mets des indications "techniques" car je vois que tu tournes sous Linux et que tu sembles savoir te débrouiller)

Est-ce que tu peux : 

1. arrêter le programme (`pm2 stop 0`) 
2. modifier le fichier `/home/jarvis/assistant-plugins/node_modules/assistant-plugins/index.js` en changeant la fonction `awakePushBullet()` par : 
```javascript
  function awakePushBullet() {
    pusher.devices(function(error, response) {
      console.log("response 1 = ",response);
      if (!response) return;
      var assistantDevice = response.devices.filter(function(device) { return device.nickname === "assistant-plugins" });
      console.log("assistantDevice =",assistantDevice)
      // on regarde si un "device" pour assistant-plugins existe, sinon on le crée
      if (assistantDevice.length===0) {
        pusher.createDevice({nickname:'assistant-plugins'}, function(error, response) {});
      } else {
        pusher.note(assistantDevice[0].iden, 'Note', 'Pour éviter la désactivation du compte par PushBullet', function(error, response) {
          console.log("response 2 = ",response)
          if (!response) return;
          pusher.dismissPush(response.iden, function(error, response) {
            if (response) pusher.deletePush(response.iden, function(error, response) {})
          });
        });
      }
    });
  }
```
4. lancer manuellement avec `node /home/jarvis/assistant-plugins/index.js`

Ça devrait te retourner des informations de debug. Pour `reponse 1` tu devrais avoir une liste de tous tes appareils qui ont Pushbullet d'installé, et au moins un device qui s'appelle `assistant-plugins` : 
```javascript
response 1 =  { accounts: [],
  blocks: [],
  channels: [],
  chats: [],
  clients: [],
  contacts: [],
  devices:
   [ { active: true,
       iden: 'abcdef123456',
       created: 1522690553.2110488,
       modified: 1522690553.2110531,
       nickname: 'assistant-plugins',
       pushable: true,
       icon: 'phone' },
     { active: true,
       iden: '123abc456efg',
       created: 1437513150.423888,
       modified: 1519598301.412499,
       type: 'ios',
       kind: 'ios',
       nickname: 'iPad',
       manufacturer: 'Apple',
       model: 'iPad Air 2 (Wi-Fi)',
       app_version: 8646,
       push_token: 'production:605abc',
       pushable: true,
       icon: 'phone' },
``` 

Ensuite tu devrais voir ce que `assistantDevice` retourne, à savoir le device `assistant-plugins` : 
```javascript
assistantDevice = [ { active: true,
    iden: 'abcdef123456',
    created: 1522690553.2110488,
    modified: 1522690553.2110531,
    nickname: 'assistant-plugins',
    pushable: true,
    icon: 'phone' } ]
```

Et pour finir `response 2` doit retourner un truc du genre : 
```javascript
response 2 =  { active: true,
  iden: 'abcdef123456',
  created: 1527178871.5494075,
  modified: 1527178871.5599365,
  type: 'note',
  dismissed: false,
  direction: 'self',
  sender_iden: 'abcd',
  sender_email: 'tonemail@gmail.com',
  sender_email_normalized: 'tonemail@gmail.com',
  sender_name: 'ton nom',
  receiver_iden: 'abcd',
  receiver_email: 'tonemail@gmail.com',
  receiver_email_normalized: 'tonemail@gmail.com',
  target_device_iden: 'abcdef123456',
  title: 'Note',
  body: 'Pour éviter la désactivation du compte par PushBullet' }
```

Si tout cela semble normal, attends 24h et vois ce que ça te retourne cette fois-là !

**Comment by mbl-35** [comment]
Merci @Aymkdn pour ta réactivité. Voici donc les traces demandées (anonymisées: compte `pushbullet` et identifiants `iden`) au lancement du process en manuel (il me semble que c'est cohérent avec l'exemple que tu m'as fourni ci-dessus):

**réponse 1:**
```javascript
response 1 =  { accounts: [],
  blocks: [],
  channels: [],
  chats: [],
  clients: [],
  contacts: [],
  devices: 
   [ { active: true,
       iden: 'abcdeghi1234',
       created: 1523728417.3322291,
       modified: 1523728417.332233,
       nickname: 'assistant-plugins',
       pushable: true,
       icon: 'phone' } ],
  grants: [],
  pushes: [],
  profiles: [],
  subscriptions: [],
  texts: [] }
```

**assistantDevice:**
```javascript
assistantDevice = [ { active: true,
    iden: 'abcdeghi1234',
    created: 1523728417.3322291,
    modified: 1523728417.332233,
    nickname: 'assistant-plugins',
    pushable: true,
    icon: 'phone' } ]
```

**réponse 2:**
```javascript
response 2 =  { active: true,
  iden: 'iden1toto',
  created: 1527227266.8438115,
  modified: 1527227266.874557,
  type: 'note',
  dismissed: false,
  direction: 'self',
  sender_iden: 'iden1',
  sender_email: 'toto@nowhere.fr',
  sender_email_normalized: 'toto@nowhere.fr',
  sender_name: 'mon nom',
  receiver_iden: 'iden1',
  receiver_email: 'toto@nowhere.fr',
  receiver_email_normalized: 'toto@nowhere.fr',
  target_device_iden: 'abcdeghi1234',
  title: 'Note',
  body: 'Pour éviter la désactivation du compte par PushBullet' }
```

Les commandes sont bien reçues par l'assistant pour le moment. Je vais attendre 24h (la trace de debug) et je posterai à suivre

**Comment by mbl-35** [comment]
J'ai exactement les mêmes traces  au bout de 24h sans activité `pushBullet` ...
L'anomalie ne s'est pas reproduite pour le moment  (pas d'erreurs dans les traces PM2, et les commandes type Freebox "Allume la télé" fonctionnent).
Je laisse tourner le we sans commande pour voir ...

Est-il possible qu'une intérruption réseau soit à l'origine du problème (reprise de l'écoute vers `pushBullet`) ? J'ai régulièrement des interruptions au niveau du FIA (ou suite à maj de la box...).

**Comment by Aymkdn** [comment]
Oui peut-être.... Laisse tourner puis on verra si on en apprend plus ces prochains jours 😉

**Comment by Aymkdn** [comment]
OK, tiens moi au courant
