### ISSUE TITLE
TTS très lent

### ISSUE THREAD

**Issue by adivincent** [Aymkdn/assistant-plugins#142]
Bonjour,

Tout fonctionne nickel chez moi. Cependant la vitesse d'élocution est très lente exemple :
Je dis : "Quelle est la température dans le quartier ?"
Google répond : "Je recherche des stations météos" >> OK
Attente le temps de trouver la température >> OK
Google dit : "La température extérieure est de 25 °C" >> très lent, j'ai envie de la passer par la fenêtre !
Voici un enregistrement de test : https://wetransfer.com/downloads/a3bc01b2325fb1684594a48509998f4520180525151025/86d4fb02f35e2f83f600151cd75b96fd20180525151025/678700

J'ai pris comme exemple température local mais c'est pareil avec tout les plugins.

Cordialement

Vincent

**Comment by Aymkdn** [comment]
Je ne vois pas ce qui est lent dans ton enregistrement ? La partie où elle dit "la température extérieure est de 25°C " ??? Je trouve qu'elle parle à une allure relativement normale....

J'utilise [GoogleTTS](https://github.com/zlargon/google-tts) qui, en fait, utilise le TTS produit par [Google Translate](https://translate.google.fr/) pour générer le texte. Il y a une option `ttsspeed` mais visiblement cela ne fonctionne plus (j'ai fait plusieurs tests, sans succès).

J'ai aussi cherché du côté de [Castv2](https://github.com/thibauts/node-castv2-client) qui est utilisé pour ensuite diffuser le son produit par Google Translate sur le Google Home, mais il n'y a pas l'air d'avoir une option pour accélérer la vitesse de lecture.

Bref, pour le moment ce n'est pas possible.

**Comment by adivincent** [comment]
Bonjour, 

Tant pis, cependant il y a une vraie différence de vitesse d'élocution entre "Je recherche des stations météos" et la reponse de la température. Vous ne pouvez pas dire que c'est normal.

Cordialement

**Comment by Aymkdn** [comment]
le "Je recherche des stations météo" est prononcée nativement par le Google Home, alors que le réponse de la température est un mp3 produit en utilisant Google Translate. Donc oui, il y a une différence entre les 2 voix car elles ne proviennent pas du tout du même endroit ! Je regarderai si je trouve un autre fournisseur de voix qui soit meilleur, mais en général ils sont payants...

**Comment by Aymkdn** [comment]
Alors j'ai regardé un peu ce qui est possible.... Les deux seules possibilités sont : 

- utiliser Google API mais la voix actuelle (sans réglage) n'est pas vraiment meilleure ; par contre on peut modifier la vitesse et le pitch pour la rendre plus agréable. Tu peux tester là : https://cloud.google.com/text-to-speech/ (en sélectionnant le français évidemment)
- utiliser Amazon AWS mais la voix n'est pas top non plus (il faut un compte Amazon pour pouvoir tester)

Dans les deux cas on est limité à 4 millions de caractères prononcés par mois (au-delà c'est payant), ce qui devrait être suffisant.

Bref, je regarderai un jour peut-être comment utiliser la voix via les Google API plutôt que celle de Google Translate, mais c'est clairement pas une priorité pour le moment :-)
