### ISSUE TITLE
Modifier la voix pour plugin Notifier

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-plugins#143]
Voir pour utiliser https://cloud.google.com/text-to-speech/ au lieu de Google Translate pour avoir une voix différente.

**Comment by smiley9** [comment]
sympa !
tu as une procédure pour la modif?

**Comment by Aymkdn** [comment]
Non... C'est justement une amélioration à faire, un jour, quand j'aurai du temps.

**Comment by jzarca01** [comment]
En expérimental je me suis servi de Watson pour générer une sortie plus humaine

Si vous voulez essayer https://github.com/jzarca01/assistant-notifier

Il faudra générer une clé d'api ici: [https://www.ibm.com/watson/services/text-to-speech/](https://www.ibm.com/watson/services/text-to-speech/) et eventuellement supprimer le fichier package-lock.json/yarn.lock du dossier assistant-plugins vu que le plugin porte le meme nom que celui de @Aymkdn 

Le rendu est disponible ici: https://file.io/DNHHTm

**Comment by Aymkdn** [comment]
Merci @jzarca01 ! J'ai, du coup, commencé à mettre à jour mon plugin pour incorporer le service d'IBM. Faut que je vois si je fais comme toi avec la création d'un Express le temps de diffuser le buffer, ou si je fais autrement. Mise à jour à venir très bientôt :-)

**Comment by Aymkdn** [comment]
Je viens de publier la nouvelle version du plugin : https://aymkdn.github.io/assistant-plugins/?plugin=notifier !

Il est donc maintenant possible d'utiliser la voix d'IBM. Si on me propose d'autres sites similaires, je pourrai les rajouter.

(à noter que NPM a un problème actuellement et il semble qu'on n'arrive pas à installer la dernière version du plugin... j'imagine que ce sera corrigé d'ici quelques heures)
