### ISSUE TITLE
Erreur Post installation

### ISSUE THREAD

**Issue by DoudouMaster** [Aymkdn/assistant-plugins#144]
Bonjour,

Première installation une dixaine de jour sans pb.
J'ai du reinstaller la babasse et la ca ne marche plus (machine tournant avec node v 8.x.x)--> erreur postintall
Je refais une nouvelle installation sur autre pi qui n'avait pas node et je tombe sur le mm message d'erreur

```
pi@raspberrypi:~/assistant-plugins $ npm install assistant-freebox@latest --save --loglevel error && npm run-script postinstall
+ assistant-freebox@2.0.9
added 1 package in 13.15s

> assistant-plugins-project@2.0.0 postinstall /home/pi/assistant-plugins
> node ./postinstall.js

[assistant] Configuration requise pour le plugin 'freebox'.
[assistant] Installation terminée.
module.js:557
    throw err;
    ^

Error: Cannot find module 'jsonfile'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/assistant-plugins/postinstall.js:34:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-plugins-project@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-06-15T02_27_26_643Z-debug.log
```
Le log en question : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/node-v9.3.0-linux-armv6l/bin/node',
1 verbose cli   '/home/pi/node-v9.3.0-linux-armv6l/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'postinstall' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose run-script [ 'postinstall' ]
5 info lifecycle assistant-plugins-project@2.0.0~postinstall: assistant-plugins-project@2.0.0
6 verbose lifecycle assistant-plugins-project@2.0.0~postinstall: unsafe-perm in lifecycle true
7 verbose lifecycle assistant-plugins-project@2.0.0~postinstall: PATH: /home/pi/node-v9.3.0-linux-armv6l/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/assistant-plugins/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/pi/node-v9.3.0-linux-armv6l/bin
8 verbose lifecycle assistant-plugins-project@2.0.0~postinstall: CWD: /home/pi/assistant-plugins
9 silly lifecycle assistant-plugins-project@2.0.0~postinstall: Args: [ '-c', 'node ./postinstall.js' ]
10 silly lifecycle assistant-plugins-project@2.0.0~postinstall: Returned: code: 1  signal: null
11 info lifecycle assistant-plugins-project@2.0.0~postinstall: Failed to exec postinstall script
12 verbose stack Error: assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/home/pi/node-v9.3.0-linux-armv6l/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
12 verbose stack     at EventEmitter.emit (events.js:159:13)
12 verbose stack     at ChildProcess.<anonymous> (/home/pi/node-v9.3.0-linux-armv6l/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:159:13)
12 verbose stack     at maybeClose (internal/child_process.js:943:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid assistant-plugins-project@2.0.0
14 verbose cwd /home/pi/assistant-plugins
15 verbose Linux 4.9.41+
16 verbose argv "/home/pi/node-v9.3.0-linux-armv6l/bin/node" "/home/pi/node-v9.3.0-linux-armv6l/bin/npm" "run-script" "postinstall"
17 verbose node v9.3.0
18 verbose npm  v5.5.1
19 error code ELIFECYCLE
20 error errno 1
21 error assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
21 error Exit status 1
22 error Failed at the assistant-plugins-project@2.0.0 postinstall script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```
Merci d'avance pour le retour

**Comment by Aymkdn** [comment]
Tu as bien fait un `npm install` *avant* de commencer à installer les plugins ?

Si oui, essaie alors d'installer le module `jsonfile` : 
```
npm install jsonfile
```

**Comment by DoudouMaster** [comment]
J'ai pu installer l'assistant sans pb, l'erreur survenant lors de l'enregistrement du plugin freebox. (attention, noob inside)

Quoiqu'il en soit, je vérifie ce soir et reviens vers toi.

Merci de ton retour en tout cas et du boulot effectuer

Cordialement




Le 15 juin 2018 9:07 AM, Aymeric <notifications@github.com> a écrit :

Tu as bien fait un npm install avant de commencer à installer les plugins ?

Si oui, essaie alors d'installer le module jsonfile :

npm install jsonfile

**Comment by Aymkdn** [comment]
Alors ? T'as réussi ?

**Comment by DoudouMaster** [comment]
Mmmm… en toute franchise, j’ai eu a reinstallé mon serveur de Aa Z et maintenant je rencontre de pb de permission qd j’envoie npm install assistant-freebox -- save
Le msg me dit que je n’ai pas les droits d’acces au dossier assistant-plugins…

Alors honnêtement, je m’occupe de remettre la babasse d’equerre (elle gère mes téléchargements, ma médiathèque et ha-bridge) et je reviendrais en dernier lieu sur le plugin Freebox. Je te solliciterais a ce moment la si je bloque de nouveau

Merci en tt cas

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Aymeric <notifications@github.com>
Envoyé : Saturday, June 16, 2018 12:04:10 PM
À : Aymkdn/assistant-plugins
Cc : DoudouMaster; Author
Objet : Re: [Aymkdn/assistant-plugins] Erreur Post installation (#144)


Alors ? T'as réussi ?

**Comment by Aymkdn** [comment]
Oki!

**Comment by DoudouMaster** [comment]
Et donc j’ai eu a chmoder en 777 le dossier assistant-plugins pour terminer les installations de plugins

Pour info, crontab est plus « accessible » que pm2,marche sans pb.

Le plugin Freebox fonctionne nickel avec la google home.
J’essaye de mettre en place les applets avec alexa et si ca t’intéresse, je te fais un retour

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Aymeric <notifications@github.com>
Envoyé : Saturday, June 16, 2018 12:17:05 PM
À : Aymkdn/assistant-plugins
Cc : DoudouMaster; Author
Objet : Re: [Aymkdn/assistant-plugins] Erreur Post installation (#144)


Oki!

**Comment by Aymkdn** [comment]
Je veux bien un retour pour les applets Alexa. Demain je compte les créer et les partager comme j'ai fait pour Google Home

**Comment by Aymkdn** [comment]
En effet, pas d'ingrédients pour Alexa encore....

Et faut dire "Alexa déclenche allume la Freebox" par exemple. Donc bien pourri ^^ (il faut utiliser le mot clé "déclenche") 

Google Home est plus souple de ce point de vue.
