### ISSUE TITLE
Questions sur Alexa

### ISSUE THREAD

**Issue by bobkelso974** [Aymkdn/assistant-plugins#145]
Bonjour,

Comme je l'avais indiqué sur Twitter cela fonctionne également avec Alexa
Sur ifttt, le service sera Alexa/"say a specific phrase"-> l'action (allume/éteins la freebox"...etc)
L'"action service" sera via pushbullet->push a note ,ensuite on suit ton tuto : 
Title: Assistant
Message : freebox_"commande"
Alors j'ai réussi à allumer , éteindre et mettre la TV
Par contre sera sur la fonction de zapper
Dois je faire un applet ifttt par chaine ? ou puis je dire zappe sur "la chaine" mais dans ce cas ,que je dois mettre dans "Message"
Merci d'avance

**Comment by Aymkdn** [comment]
J'ai fait quelques recherches et apparemment Alexa ne permet pas la reconnaissance de mot ou chiffre comme le permet Google.... Avec Google on peut créer une seule applet IFTTT `zappe sur {{text}}` et on récupère le contenu de `{{text}}` (exemple `M6`, `TMC`, etc).

Du coup il faudra, en effet, faire une applet par chaine pour Alexa, malheureusement...

**Comment by Aymkdn** [comment]
Demain je vais essayer de prendre du temps pour pré-créer des applets (comme je l'ai fait pour Google Home), ce qui devrait simplifier les choses.

Par contre je créerai seulement les applets pour les chaines "principales".

**Comment by bobkelso974** [comment]
OK! effectivement ça devrait être plus simple
Merci

**Comment by Aymkdn** [comment]
J'ai mis les applets dans la documentation : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#utilisation

Je veux bien que tu les testes toute et que tu me dises celles qui fonctionnent / ne fonctionnent pas !

**Comment by bobkelso974** [comment]
Ok, j'essaye ça ce soir et je te tiens au courant
Merci

**Comment by bobkelso974** [comment]
Voici les résultats pour Alexa : 
Allume/éteins : OK
Zappe : ça ne fonctionne pas , j'ai du modifier en "met france 4" et là OK
Met pause : OK
Reviens au direct OK
Va dans mes Vidéos /Enregistrements : NOK
Peut etre que j'articule mal, il faudrait que je change le texte
Je testerais les autres applets plus tard
Sinon en attendant que Free sorte un Skill sur Alexa , ton tuto est le meilleur moyen de controler la Freebox via Alexa
Merci encore
J'ai testé via Windows, cette semaine je vais tenter de l'installer sur un Raspberry

**Comment by Aymkdn** [comment]
Regarde si tu as accès à l'historique de tes tentatives vocales, pour voir ce qu'Alexa comprend. Et si tu peux me dire les bonnes orthographes, alors je modifierai les applets. 

C'est vraiment dommage que ce soit si limité par rapport au Google Home !

Merci en tout cas

**Comment by bobkelso974** [comment]
un petit retour 
finalement il ne fallait pas dire "Alexa déclenche zappe sur TF1" mais "Alexa déclenche TF1" et ça fonctionne
idem pour Mes Videos
Je fais actuellement tourner le plugin sous Raspberry et ça fonctionne bien
Eencore Merci

**Comment by Aymkdn** [comment]
Très bizarre...

**Comment by bobkelso974** [comment]
effectivement, j'ai regardé l'historique d'Alexa pour déclenche tf1:
"Alexa a compris : déclenche t.f.un" -> "zappe sur tf1" envoyé à IFTTT
c'est vrai que c'est bizarre

**Comment by Aymkdn** [comment]
C'est franchement chelou ! Comme tu le sais, je n'ai pas d'Echo chez moi, donc je ne peux pas faire des tests, et donc je n'ai aucune idée du pourquoi et du comment.

Si jamais tu arrives à investiguer, cela pourra toujours servir à d'autres ;-)

**Comment by bobkelso974** [comment]
J'ai regardé vite fait et je ne comprend pas qui interprète l'action
quand je dis à " Alexa déclenche Vidéos"....IFTTT comprend "va dans mes Vidéos" . 
en tout cas , le terme "zappe" ne fonctionne pas avec moi...je dis toujours "Alexa déclenche TF1"
Je n'ai pas plus d'idée..
Désolé ...va falloir que tu craques pour Alexa ;)

**Comment by Aymkdn** [comment]
Ahah, je préfère mon Google Home :-p

Bon tant pis.... Pour d'autres, apparemment, ça marche de dire "Alexa déclenche zappe sur TF1". Grand mystère donc !

Merci quand même. Le plus important est que ça fonctionne ^^
