### ISSUE TITLE
Lancer assistant-plugins au démarrage de MacOSX

### ISSUE THREAD

**Issue by Vinsyl33** [Aymkdn/assistant-plugins#147]
Bonsoir Aymkdn, je ne sais pas si on t'a déjà dit ou si c'est seulement moi qui est ce problème mais je n'arrive pas à lancer automatiquement assistant-plugins avec pm2 (sous Mac OSX) enfin pour être exact, le script est bien lancé mais il n'arrive pas à se connecter à Pushbullet car la connexion wifi du Mac n'est pas encore établi. J'imagine qu'il y a une solution dans pm2 pour ajouter un délai avec l'exécution du script mais je n'ai pas trouvé comment faire. J'ai également un soucis quand je sors de la mise en veille ou je dois stopper et relancer pm2...
Si cela peut aider, j'ai trouvé une solution en créant une application avec automator (exécution d'un script Shell) et en y insérant le code suivant:
_export PATH=/usr/local/bin/:$PATH
cd /Applications/assistant-plugins
sleep 10
forever start index.js_
Il a fallut que j'installe forever (_sudo npm install forever -g_) et ensuite j'ai enregistré l'application que j'ai ajouté dans la partie "Ouverture" de l'utilisateur actuel.
Depuis cela fonctionne bien.
Si mon post est inutile, libre à toi de le supprimer:-).
En tout cas un grand bravo pour le boulot accompli et me permettre de piloter ma Freebox avec mon Google Home :-).

**Comment by Aymkdn** [comment]
Merci pour ton retour, ça peut toujours servir :-)

**Comment by Aymkdn** [comment]
J'ai rajouté un lien, en bas de la doc, vers ce sujet.
