### ISSUE TITLE
Problème avec les applets IFTTT "baisse le son"/"augmente le son" de la Freebox

### ISSUE THREAD

**Issue by Vinsyl33** [Aymkdn/assistant-plugins#148]
Re,
J'ai un petit soucis avec ces deux applets probablement parce que j'utilise la fonction CEC de l'HDMI.
Voici la description de mon installation: ma Freebox est connecté en hdmi sur une barre de son et ma télé également. Dans les options de la Freebox, j'ai modifié les options CEC pour que le périphérique utilisé pour le son soit mon "amplificateur". Quand j'augmente ou je baisse le son avec la télécommande, c'est le volume de ma barre de son qui est changé.
Donc quand je passe une commande via ma Google Home, je vois bien sur l'écran de ma télé, le "petit rond" indiquant la réception de la commande mais il n'y a pas d'impact sur ma barre de son.
Petit détail qui a probablement son importance:-), j'ai souvent le même problème avec la télécommande et je suis obligé d'appuyer plusieurs fois sur volume + ou - pour qu'il y est un impact. Quand penses-tu et peut-on y faire quelque chose? Merci pour ton aide.

**Comment by Aymkdn** [comment]
Essaie de voir si ça aide ça : https://github.com/Aymkdn/assistant-freebox/issues/7

**Comment by Vinsyl33** [comment]
Bonsoir Aymkdn, effectivement cela fonctionne beaucoup mieux mais j'ai maintenant un autre "petit" problème. Quand le volume est à 10, le son est déjà fort donc quand j'utilise la commande baisse ou monte la différence est trop élevée. Peut-on changer le paramètre pour que cela ne monte ou baisse que de 2 chiffres? J'espère que tu me comprends ;-). Merci encore pour aide.

**Comment by Vinsyl33** [comment]
J'essaye de trouver tout seul:-) donc j'ai créé un nouvel applet IFTTT en suivant ta documentation mais je n'arrive pas à passer un paramètre comme ton *15.
Je cherche je cherche:-)

**Comment by Aymkdn** [comment]
Merci pour ton don !

Je suis parti en week-end dans un camping avec une très mauvaise réception internet...

Si tu regardes la documentation il y a plusieurs paramètres pour modifier les délais. T'as essayé de jouer sur ça ?

D'après ton edit3 il semble que ça soit bonne maintenant ?

**Comment by Vinsyl33** [comment]
On peut dire que c'est bon effectivement car le souci de descendre de 1 en 1 avec la commande est le même qu'avec la télécommande donc l'imprécision est du probablement à l'HDMI CEC. Tu peux fermer l'issue si tu veux:-). Bon weekend et c'est peut être pas plus mal de ne pas avoir un bon accès à internet. On peut faire autre chose:-).
