### ISSUE TITLE
probleme entre IFTTT et pusbullet

### ISSUE THREAD

**Issue by f-claudel** [Aymkdn/assistant-plugins#149]
bonjour j'ai tt parametré comme il faut mais rien ne ce passe... c'est a dire que je n'ai aucune interaction entre IFTTT et pusbullet. j'ai essayé avec une autre applet (Rent reminder via Pushbullet) et avec elle j'ai bien un suivi dans pusbullet.
pouvez vous m'aider
ps je ne suis pas tres fort en informatique je decouvre au travers de mes tests et des sites commele tiens (d'ailleur un grand merci pour ton travail)

Fred

**Comment by Aymkdn** [comment]
Est-ce que tu as regardé sur [cette page](https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes) les conseils qui y sont donnés pour résoudre le problème ? Si oui, dis moi les résultats des différents tests qui y sont expliqués

**Comment by f-claudel** [comment]
alors pour le premier test tt est bon le message est pret a ecouter les commande via pusbullet.
pour le deuxieme c'est la que ce trouve mon probleme je pense j'ai beau essayer allume le livebox eteint la livebox ou baisse le son de la livebox rien ne ce passe dans pusbullet

![1](https://user-images.githubusercontent.com/40489719/41779793-2c2b0574-7633-11e8-9c0f-b84c4a9a2b0e.png)

**Comment by Aymkdn** [comment]
Tu utilises quel assistant ? Google Home ? Amazon Echo ? Cortana ?

**Comment by f-claudel** [comment]
et mes applet fonctionnent bien!!!

j utilise
![2](https://user-images.githubusercontent.com/40489719/41779898-8368ea22-7633-11e8-9866-68759504f41c.png)
 amazon Echo

**Comment by f-claudel** [comment]
par contre comme tu peux le voir l'applet rent reminder fonctionne

**Comment by Aymkdn** [comment]
OK tu utilises Alexa.... Alors avec Alexa la commande devrait être : 

> Alexa déclenche baisse le son de la Livebox

Il faut utiliser le mot clé **déclenche**, mais ce n'est pas très clair sur comment Alexa fonctionne pour le moment (voir [cette conversation](https://github.com/Aymkdn/assistant-plugins/issues/145) par exemple)

**Comment by f-claudel** [comment]
ok mais il faut changer la phrase dans l'applet sur ifttt?

**Comment by Aymkdn** [comment]
Non, tu dois utiliser les applets que j'ai créées. C'est juste qu'Alexa actionne les applets IFTTT si on dit « Alexa déclenche » en premier.

**Comment by f-claudel** [comment]
merci ca marche cest effectivement bizarre

**Comment by f-claudel** [comment]
dit moi tu sentirais tu capable ou du moins motive par les vieux comme moi qui on besoin d'explication pour faire une fiche explicative du cursus de fonctionnement de tt c'est commandes quand je cherhce sur google je trouve beaucoup d'explication mais tres flou ou qui s'adresse a des non novice voir des expert comme toi

**Comment by Aymkdn** [comment]
Qu'est-ce que tu cherches à savoir **exactement** ?

**Comment by f-claudel** [comment]
avec mes mots a moi... que ce passe t'il entre mes cordes vocale et une commande executée ... a partir de la reconnaissance vocale jusque l’exécution et quelle sont les differents moyens ...jai vu  ifttt, pushbullet, jeedom etc mon intérêt est de concevoir le pilotage de ma tv lg (web os) de ma freebox(je vais changer d'operateur dans un mois) de mes lumières (j'ai deja mes module wifi type wemo d'ailleur en electronique je suis plutot bon du moins meilleur que dans l'internet )...

**Comment by Aymkdn** [comment]
Je veux essayer d'expliquer...

Quand tu parles à ton Echo, il va regarder si la commande vocale demandée existe dans les applets IFTTT que tu as activées. Si c'est le cas il va déclencher l'applet en question.

IFTTT prend donc le relai à ce moment et envoie un message à Pushbullet avec l'instruction / commande qui a été définie dans l'applet.

Ton ordinateur, sur lequel tu as installé assistant-plugins, a donc le programme assistant-plugins qui écoute les commandes venant de Pushbullet. Il va voir que Pushbullet a reçu une commande depuis IFTTT. Il va alors regarder s'il connait cette commande (via les plugins installés) et va exécuter l'action associée. Par exemple, pour allumer la Livebox, le programme va lancer une requête HTTP/Web vers la Livebox pour lui dire de s'allumer.

Tu comprends ?

Moi j'utilise IFTTT car c'est personnalisable et souple, et fonctionne avec Google Home, Cortana, et maintenant Alexa (et pourquoi pas Siri dans le futur ?).
J'utilise ensuite Pushbullet car le service est gratuit, et cela permet d'éviter de lourdes configurations pour les utilisateurs (sans Pushbullet il faudrait configurer ton routeur, ouvrir les accès à l'extérieur, et faire plein de manipulations techniques).

Il existe des solutions de domotique, comme Jeedom, Domoticz, et autres. Mais je ne les utilise pas.

**Comment by f-claudel** [comment]
oui jai bien compris ....il nest donc pas idiot de croire que je puisse commander ma tele lg en webos avec ton principe finalement c'est juste des code de télécommande a modifier pour faire simple

**Comment by Aymkdn** [comment]
N'ayant pas de Livebox, j'ai indiqué ce qu'on m'a dit.

**Comment by f-claudel** [comment]
puis je te demander une autre chose ?

**Comment by Aymkdn** [comment]
Oui ?

**Comment by f-claudel** [comment]
avec quel logiciel fabriques tu tes templates en java et l'orsque tu crée une applet sur ifttt c'est bien dans la note que tu envois a pushbullet que tu ecris ta commande (ex livebox_soundDown*3 pour baisse le volume)

**Comment by Aymkdn** [comment]
Pour les plugins en javascript, n'importe quel éditeur de texte suffit. J'utilise SublimeText.

Concernant les applets, tout est bien expliqué sur le site. Donc oui c'est une Note Pushbullet, avec "Assistant" dans le sujet, et la commande dans le corps du message.

**Comment by f-claudel** [comment]
ok je croyais pour java que tu avais un logiciel pour te donner la structure de ton répertoire avec les librairies ..etc

**Comment by f-claudel** [comment]
et pour finir tu as une idée de comment on peu faire repondre alexa l'orsque elle a recu une commande...ex (alexa allume la tele).... retour de alexe (la tele est allumé)

**Comment by Aymkdn** [comment]
Je ferme cet issue. Si tu as d'autres questions tu peux les poser ici
