### ISSUE TITLE
Search Option

### ISSUE THREAD

**Issue by adrienvia** [Aymkdn/assistant-plugins#15]
salut, tout d'abord merci pour tous ces tutos et programmes, c'est impeccable !

j'avais juste une question concernant la fonction search,  "va dans le dossier $" c'est plus un soucis de mon coté, car à cause d'un autre programme automatique, j'ai du modifier le nom du dossier vidéos en videos (sans accent) sur la freebox et du coup pour y accéder je suis obligé de passer par disque => disque dur freebox... au lieu de "mes vidéos" du menu freebox, et du coup ma question, était comment tu as fait pour programmer les applets IFTTT pour que ça recherche exactement? parce que j'arrive pas à trouver exactement les commandes à mettre en créant l'applet avec IFTTT (j'ai regardé, et je peux pas modifier un applet de quelqu'un d'autre, mais juste en créer un autre) et du coup je vois pas ce que tu as mi exactement dans les paramètres.

**Comment by adrienvia** [comment]
ah, je crois que j'ai trouvé, finalement, c'est plus le fichier freebox.js que je dois modifier, avec les commandes de la télécommandes, plus que l'applet en lui-même. je vais checker ça ;)

**Comment by adrienvia** [comment]
mouais, après avoir lancer la commande va dans le dossier $, il fait la manip pour aller dans videos, mais après, ça s'arrête et ça met une erreur, et coupe le script dans le terminal:
"events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8009
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)"

**Comment by Aymkdn** [comment]
En effet, c'est le Freebox.js qu'il faut changer pour la commande "folder"

Pour ton erreur, je ne sais pas trop...
