### ISSUE TITLE
Live box/ Alexa/ zaper sur des chaine >10

### ISSUE THREAD

**Issue by wambagilles** [Aymkdn/assistant-plugins#150]
Les scripts fontionnent pour zaper les chaine avec alexa, ça marche bien avec toutes les chaine dont le channel est inférieure à 10. tf1, france2, ... W9. Mais à partir de TMC en montant ça ne marche marche plus, ci dessous un exemple pour BFM

![screen shot 2018-06-22 at 21 43 21](https://user-images.githubusercontent.com/617465/41796144-a3bb3974-7665-11e8-8fb3-a195a165eedc.png)

l'adresse de la requette est: http://192.168.1.11:8080/remoteControl/cmd?operation=01&key=513517&mode=0

quand je tape dans un navidateur j'ai le message d'erreur visible à la capture

![screen shot 2018-06-22 at 21 46 38](https://user-images.githubusercontent.com/617465/41796177-c49631e4-7665-11e8-8a84-a35b483f0697.png)

**Comment by Aymkdn** [comment]
Ah....?! 

Je suis en week-end en camping là. Je regarderai ça lundi !

**Comment by wambagilles** [comment]
D'accord merci :)

**Comment by Aymkdn** [comment]
Voilà j'ai corrigé !

Je te laisse [mettre à jour](https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-) et me confirmer que c'est bon :-)

**Comment by wambagilles** [comment]
Hello, je viens de mettre à jour, c'est super merci!!
