### ISSUE TITLE
Dysfonctionnement

### ISSUE THREAD

**Issue by ravayou** [Aymkdn/assistant-plugins#151]
Bonjour

Je m'excuse si ce n'est pas la place de ce genre de message mais je n'arrive pas à faire fonctionner assistant plugins. J'ai un Mac mini sous OS X El capitan. J'ai Alexa et je souhaitais gérer la freebox via asisstant-plugins.

J'ai suivi les explications pour tout installer. J'ai également lu la FAQ et fais les vérifications tel que préconisé. A priori  la communication entre pushbullet et IFTTT fonctionne car je vois les bullets lorsque je lance des ordres à Alexa.

Voici une copie de la console lorsque je lance un ordre d'allumage de la freebox:

Last login: Sun Jun 24 17:59:18 on ttys000
mac-mini-de-christophe-henry:assistant-plugins christophehenry$ node index.js
[assistant] Assistant v2.0.4 : Chargement en cours...
[assistant] 2 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.9)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'temperature-local' (v1.0.2)
[assistant-temperature-local] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 3663ms
[assistant-freebox] Url => http://82.66.188.175/pub/remote_control?code=95572661&key=power
(node:8103) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at /Users/christophehenry/Downloads/assistant-plugins/node_modules/assistant-freebox/freebox.js:402:117
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Pourriez-vous m'aider?

Par avance merci.

**Comment by Aymkdn** [comment]
Tu utilises un vpn ?

**Comment by Aymkdn** [comment]
Je te demande ça car on dirait que tu as spécifié l'adresse IP de ta box dans le fichier de configuration. Tu ne dois le faire que si tu utilises uniquement vpn.

En l'occurrence tu as mis ton IP externe, ce qui est incorrect. Il faut mettre l'IP interne (qui ressemble à 192.168.x.x) de la Freebox.

**Comment by ravayou** [comment]
Merci pour ta réponse rapide.
Effectivment j'ai spécifié l'adresse IP mais par pure "sur spécification" :-). Je n'ai pas de VPN. Je retire l'adresse IP et je regarde ce que cela donne

**Comment by ravayou** [comment]
Super! merci cela fonctionne parfaitement. Est- ce que tu saurais par contre, s'il est possible de sortir la télé du mode veille?
En tous le cas, merci pour ta réponse

**Comment by Aymkdn** [comment]
Quand tu appuies sur le bouton On de la télécommande de la Freebox, est-ce que ça allume ta TV (il faut [activer le mode CEC](https://www.freebox-v6.fr/index.php/tutoriel/fiche/23/Configurer-le-HDMI-CEC-sur-votre-Freebox-Rvolution) dans les paramètres de la Freebox)?

**Comment by ravayou** [comment]
Je viens de contrôler mes paramètres CEC et en fait c’était le téléviseur qui n'était pas bien paramétré. C'est parfait. Merci beaucoup à toi!
