### ISSUE TITLE
Question lancement de process sur Raspberry

### ISSUE THREAD

**Issue by bobkelso974** [Aymkdn/assistant-plugins#152]
Bonjour,
Je reviens vers toi concernant l'assistant plugin sur Raspberry
Ma question: est il possible avec Alexa/Google Home de demander à lancer une commande ou un process sur raspberry
En fait j'ai motion (surveillance) installé sur mon Rasp et j'aimerai dire à Alexa "déclenche ma webcam"
merci d'avance

**Comment by Aymkdn** [comment]
Regarde le [plugin `launch`](https://aymkdn.github.io/assistant-plugins/?plugin=launch)

**Comment by bobkelso974** [comment]
OK merci
Je vais tester ça
