### ISSUE TITLE
Plusieurs Google Home

### ISSUE THREAD

**Issue by nico0709** [Aymkdn/assistant-plugins#153]
Bonjour,
Est-il possible de faire fonctionner le plugin Bluetooth avec plusieurs Google Home, au lieu d'un seul?
Merci

**Comment by Aymkdn** [comment]
Non, pas en l'état actuel

**Comment by nico0709** [comment]
Je crois que j'aurai un moyen de faire ça manuellement, mais ça nécessiterai de changer le titre de la notif Pushbullet attendu par assistant-plugins... Ou puis-je modifier cela?

**Comment by Aymkdn** [comment]
Explique moi ton idée avant....

Car `assistant-plugins` ne regarde que les notifications qui ont le titre "Assistant", donc si tu changes ça, il ne va plus les détecter.

**Comment by nico0709** [comment]
Je me demandais si, pour un autre Google Home, il était possible de faire tourner un second serveur de assistant-plugins, dont l'adresse IP du Google Home pour le plugin Bluetooth serait donc différente, mais il faudrait pour cela qu'il puisse réagir avec une autre commande que "Assistant", qui serait interceptée par assistant-plugins 1...

**Comment by Aymkdn** [comment]
Oui, tu peux essayer. Tu devras l'installer, puis modifier le fichier qui se trouve dans `node_modules/assistant-plugins/index.js`.

À [la ligne 87](https://github.com/Aymkdn/assistant-plugins/blob/master/index.js#L87) tu dois remplacer `"Assistant"` par ce que tu veux dans `if (push.sender_name === "IFTTT" && push.title === "Assistant" && !push.dismissed) {`

Ensuite, tu suis [les instructions](https://aymkdn.github.io/assistant-plugins/?plugin=bluetooth#utilisation) sauf qu'à l'étape 9 tu utilises le nouveau mot clé que tu as défini ci-dessus.

**Comment by nico0709** [comment]
Merci beaucoup pour ta réactivité et pour ton travail! :)
