### ISSUE TITLE
Fonctionnement Freebox google home

### ISSUE THREAD

**Issue by mbombonjoya** [Aymkdn/assistant-plugins#155]
bonjour j'ai de nouveau un soucis: ma google home reçoit les infos pour changer de chaine ou éteindre la Freebox mais rien ne se passe hier tout fonctionnait normalement....je ne comprend pas

**Comment by Aymkdn** [comment]
Il faut écrire quelque chose ici sinon c'est inutile....

**Comment by Aymkdn** [comment]
Tu as consulté la page https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes ?

Bien entendu, tu as `assistant-plugins` qui tourne sur ta machine 24h/24?

**Comment by Aymkdn** [comment]
Je ne comprends pas ta question.... C'est toi qui a l'as téléchargé sur ton ordinateur.... Je ne sais pas ce que tu en as fait....

**Comment by mbombonjoya** [comment]
En fait tout fonctionnez normalement hier soir et j’ai éteins mon iMac et cela ne fonctionne pas ma google home reçoit les infos mais rien ne se passe

**Comment by Aymkdn** [comment]
Comme expliqué à plusieurs endroits, ton iMac doit être allumé et faire tourner `assistant-plugins` sinon ça ne marchera pas. C'est ton iMac qui pilote la Freebox.

**Comment by mbombonjoya** [comment]
Il faut donc que je recommence toute la procédure

**Comment by Aymkdn** [comment]
Non... Tu dois juste relancer le programme.... Étape 9 de [l'installation](https://aymkdn.github.io/assistant-plugins/)
