### ISSUE TITLE
Pb google home pour prise de controle freebox

### ISSUE THREAD

**Issue by Ghyghy31** [Aymkdn/assistant-plugins#157]
Bonjour

Comme évoquer sur ta chaine you tube, j'ai suivi les démarches pour prendre le contrôle de ma Freebox via mon Google home. J'ai suivi tes instructions et tout fonctionnait parfaitement.
Or depuis quelques mois ca ne fonctionne plus et je ne vois pas pourquoi.
![start](https://user-images.githubusercontent.com/41872290/43408370-b12dd38c-9410-11e8-8338-358dd47c4331.png)
quand je lance le start (cf photo jointe ci dessus) il m'affiche qu'il reconnait le plugin Freebox, qu'il charge bien les chaines etc...
Quand je lance ma commande vocale, mon Google home recoit l'info puisqu'il me répond. mais la manip ne s'effectue pas.
Exemple : quand je demande a mon Google : Zappe sur TF1 il me répond bien qu'il zappe sur TF1 mais rien ne se passe sur ma TV.
pareil pour le son etc etc.

Mes commandes IFTTT sont bien en ON.

Je précise au cas ou ca joue dessus que dans un premier temps j'avais fait l'installation sur mon PC fixe tout fonctionnait. Par la suite j'ai acheté un petit pc tout petit pour le laisser allumer derriere la TV 24h/24 et j'ai refait l'installation sur ce dernier et tout fonctionnait.

Voila je te cache pas que d'avoir gouter à ces fonctionalités est difficile aujourd'hui pour moi de m'en passer c'est pourquoi un peu d'aide me serait fort utili.

En attente de te lire

Cordialement Ghyghy31

-->

**Comment by Aymkdn** [comment]
Est-ce que tu peux essayer ce qui est indiqué dans le **1)** ici : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes

Et me dire ce que tu as pour Pushbullet.

**Comment by Ghyghy31** [comment]
Tout fonctionne à merveille
