### ISSUE TITLE
suite changement de FreeBox 

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#158]
Bonjour, j'ai changer ma FreeBox suite a un orage ( elle a grillé ... plus d'affichage ni rien !)
le SAV Free m'en a renvoyer une toute neuve ( j'ai changer uniquement le serveur )
celui ci fonctionne parfaitement , avec la vielle télécommande ( le code télécommande est in-changer )

mais l'assistant ne fonctionne plus lui

**Comment by Aymkdn** [comment]
Ouvre le fichier configuration.json et supprime le `app_token` puis relance le programme. Il devrait te demander l'autorisation sur ta Freebox Serveur lors du lancement du site programme.

**Comment by nusmiaf** [comment]
super c'était bien le app_token qui ne matchait pas  
Merci
