### ISSUE TITLE
Pas de fichier configuration.json

### ISSUE THREAD

**Issue by Ayme1** [Aymkdn/assistant-plugins#159]
Bonjour ,

Suite à l'installe de "assistant-plugins, je n ai pas de fichier configuration.json
Je ne peux donc passer à la suite.

![image](https://user-images.githubusercontent.com/42123159/43690158-901d07f4-9905-11e8-821b-40e86f206631.png)

Merci de ton aide 
Aymeric aussi :)

**Comment by Aymkdn** [comment]
Tu n'as pas lancé `install.bat ` on dirait....

**Comment by Ayme1** [comment]
hello 

si justement mais le fichier n'est pas généré....

**Comment by Aymkdn** [comment]
Tu devrais avoir un dossier `node_modules` si tu as fait l'installation aussi, et il n'y est pas. Quand tu lances l'installation, ça t'affiche quoi?

**Comment by Ayme1** [comment]
la meme chose que toi dans la vidéo mais le rep et le fichier ne sont pas générés

**Comment by Aymkdn** [comment]
Tu peux me faire une copie d'écran de ce qu'indique la fenêtre ?

**Comment by Ayme1** [comment]
![image](https://user-images.githubusercontent.com/42123159/43690508-81b5b908-990b-11e8-895d-ba5c76957660.png)
je vies de le refaire mais avant j ai comparé a la videoo et exactement la meme

**Comment by Aymkdn** [comment]
Étrange.... Et tu peux me remontrer le contenu de ton dossier C:\assistant-plugins  ?

**Comment by Ayme1** [comment]
![image](https://user-images.githubusercontent.com/42123159/43690538-eaccf334-990b-11e8-8db1-d376d7de63ad.png)

**Comment by Aymkdn** [comment]
C'est vraiment très bizarre...

Essaie d'ouvrir une fenêtre Cmd dans ton répertoire et de taper : `npm install assistant-plugins jsonfile`

**Comment by Ayme1** [comment]
et voila : 
![image](https://user-images.githubusercontent.com/42123159/43690596-e0de5498-990c-11e8-8a96-3bc329be463a.png)

**Comment by Aymkdn** [comment]
Est ce que le contenu de ton répertoire a changé ? Si non, est-ce que tu as un antivírus d'installé qui pourrait perturber l'installation d'une programme ?

**Comment by Ayme1** [comment]
j ai relance ta commande et çà me semble ok now
![image](https://user-images.githubusercontent.com/42123159/43690629-5bf46230-990d-11e8-8a82-62642e3a22ff.png)
je te tiens au courant si tu veux de la suite je continurai demain

**Comment by Ayme1** [comment]
merci bcp en tout cas
