### ISSUE TITLE
Node !?

### ISSUE THREAD

**Issue by Nilssous** [Aymkdn/assistant-plugins#160]
Bonjour  Aymeric,
Je découvre tes tutoriels et le fonctionnement "Ok Google" ---> "IFTTT" ---> "Pushbullet"  Je trouve ça excellent! Tu expliques super bien.
Mais je rencontre un blocage... depuis mon smartphone je dis "OK Google, coupe le son du pc" je reçois une notification dans pushbullet sur mon PC  de IFFT "Assistant" .... "control-windows_mute" mais l'action ne s'exécute pas, le son du pc n'est pas coupé. (J'ai relue plein de fois tes tutos)
Je sens que je ne suis pas loin :) mais je ne comprends pas trop la dernière partie: intéraction entre pushbullet et windows. J'imagine que Node doit jouer un rôle la dedans, j'ai donc laissé une fenêtre Node.js ouverte sur Windows; je pensais que Pusbullet écrirai dans Node ou qqch comme ça... donc là tu peux voir mon inculture informatique!
Voilà si tu as 5min et la patience de m'expliquer ce que je n'ai pas compris, je procéderai à un virement de 10 millions d'euros sur ton compte ou je te dirai merci... comme tu préfères :)
![assisatnt](https://user-images.githubusercontent.com/42314776/44000909-a273571e-9e28-11e8-8d76-afc5b4d9d14a.png)
![push](https://user-images.githubusercontent.com/42314776/44000927-ea2139d2-9e28-11e8-849b-24e89ae730c1.jpg)

**Comment by Nilssous** [comment]
Excellent! Merci beaucoup et bonne vacances.

**Comment by Aymkdn** [comment]
Le programme n'est pas lancé puisque tu as une erreur qui s'affiche et te dit ce qu'il ne va pas.... Corrige l'erreur, puis laisse le programme tourner !

**Comment by Nilssous** [comment]
![cmd](https://user-images.githubusercontent.com/42314776/44034106-9b10e088-9f0c-11e8-9d7a-0cb970a1db53.png)
Voilà, j'ai refait l'install sans "bluetooth".
Je lance la commande "coupe le son du PC" depuis mon tel, elle arrive bien dans Pushbullet sur le PC
![pushb](https://user-images.githubusercontent.com/42314776/44034435-61b71036-9f0d-11e8-9bee-8aadd6d221fc.png)
mais la commande n'est pas effective:
![son](https://user-images.githubusercontent.com/42314776/44034505-8c6a368c-9f0d-11e8-90db-e07aff9bb39b.png)
C'est là que qqch m'échappe. C'est Windows 7. 
En gros si je comprends pushbullet travaille avec NODE qui, lui, écrit une ligne de commande dans une fenêtre CMD. Si j'écris moi même la ligne de commande dans 1 fenêtre cmd.exe "control-windows_mute" ça ne fonctionne pas 
![cmd exe](https://user-images.githubusercontent.com/42314776/44034951-9f20dffa-9f0e-11e8-9aab-0a423d6adc9e.png)

AHHHHHHHHHHHHH; Ça y est ! Il faut que je laisse la fenêtre cmd ouverte et ça m'a bien coupé le son!!! Quand on connaît pas, des choses très simples peuvent tout bloquer. 
Désolé pour le dérangement!
![reussi](https://user-images.githubusercontent.com/42314776/44035437-cd73c79a-9f0f-11e8-8cda-b128ac15695c.png)


Trop content. 
Maintenant je vais m'attaquer à la Freebox.
Encore un énorme merci pour ton partage, c'est génial des gens comme toi!
A bientôt.
Nils

**Comment by Aymkdn** [comment]
Content que tu aies réussi !
