### ISSUE TITLE
timer sur commande

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#161]
bonjour ,
est il possible d’intégrer un " timer " sur un commande Launch ou juste sur un Push (pushbullet)..
avec la fonction wait ou d'une autre façon
pour obtenir :
ok google , "fait ceci " [dans 30min]   ...ou 1h ou plus

Merci

**Comment by Aymkdn** [comment]
Tu peux combiner tes commandes avec le plugin wait : https://aymkdn.github.io/assistant-plugins/

**Comment by nusmiaf** [comment]
en fait
j'ai fait un applet type:

say a simple phrase ( fait ceci dans x temps ) / assistant ( wait_30 secondes ) / webhock  ( ma commande )

évidement ça fonctionne pas enfin pas le timer

**Comment by Aymkdn** [comment]
Ça ne fonctionne pas comme ça. Tu dois mettre : `wait_30 secondes,autre plugin`. Une fois le timer écoulé il fera ce qui suit via "autre plugin". Comme tu veux faire une requête, tu dois installer le plugin IFTTT et créer une applet Webhook. L'exemple suivant montre bien comment procéder : https://aymkdn.github.io/assistant-plugins/?plugin=ifttt#exemple

**Comment by nusmiaf** [comment]
bonjour , merci pour ton aide ,
il y a encore des choses qui m’échappent .. ..
( la fonction " éteindre" ou "mettre" la clim est la même ( switch on/on))

![sans titre](https://user-images.githubusercontent.com/33859641/44086761-df39ef00-9fbd-11e8-86dd-ce1c54e87613.jpg)

**Comment by Aymkdn** [comment]
Tu vois que IFTTT n'a pas converti {{NumberField}} et {{TextField}} avec leurs équivalents mais les envoyer en brut (comme indiqué dans la console de assistant-plugins), du coup le timer ne va pas fonctionner...

Ensuite, tu appelles le plugin IFTTT, mais tu ne l'as pas installé (comme indiqué dans la console de assistant-plugins)...

**Comment by Aymkdn** [comment]
Aussi le trigger de Ifft "mets la clim" n'est pas un Webhook. Relis l'exemple que je t'ai donné un peu plus haut !

**Comment by nusmiaf** [comment]
Comme a chaque fois je ne comprend pas tout désolé..

> Tu vois que IFTTT n'a pas converti {{NumberField}} et {{TextField}} avec leurs équivalents mais les a envoyés en brut (comme indiqué dans la console de assistant-plugins), du coup le timer ne va pas fonctionner...

quand je donne l'ordre " eteins dans 30 secondes " , GH comprend bien  et me repond bien ok ..blabla dans 30 secondes .
c'est mal argumenté ? ou c'est le plugin IFTTT qui ne reçois pas la commande ?

>Ensuite, tu appelles le plugin IFTTT, mais tu ne l'as pas installé (comme indiqué dans la console de assistant-plugins)...

pourtant si il est installé  et charger puisque il apparait quand l'assistant est charger 
j'ai faux  ?? :( 

>Aussi le trigger de Ifft "mets la clim" n'est pas un Webhook. Relis l'exemple que je t'ai donné un peu plus haut !

c'est " une simple phrase qui lance un webhock , ça doit être un webhook /note  ?

![sans titre21](https://user-images.githubusercontent.com/33859641/44090395-505f692e-9fca-11e8-9ea8-4c8d8bcaf3c5.jpg)

**Comment by Aymkdn** [comment]
Je n'ai pas accès à mon ordinateur avant jeudi donc je ne peux pas te faire des captures d'écran pour te montrer/mieux t'expliquer... Là je te réponds depuis mon téléphone donc pas très pratique... Faudra sinon attendre donc mon retour de vacances pour des explications plus précises !

**Comment by nusmiaf** [comment]
en tout cas le plugin IFTTT  est bien installer rassure moi ?

**Comment by nusmiaf** [comment]
ok ça , le plugin iftt ..c'est résolu 
par contre le text brut je voit pas la subtilité  , j'ai bien mis # $  dans la commande et wait_{{NumberField}} {{TextField}} en suite 
![image](https://user-images.githubusercontent.com/33859641/44091613-53df24b4-9fce-11e8-9b58-aa224a7bd101.png)

**Comment by Aymkdn** [comment]
Dans l'application iftt et dans la version mobile, les mots clés n'apparaissent pas comme sur ta capture d'écran :
![screenshot_20180814-154348__01](https://user-images.githubusercontent.com/946315/44095455-27cd8e6e-9fd9-11e8-9542-8c39be868eb2.jpg)

**Comment by Aymkdn** [comment]
Dans IFTTT si tu cliques sur le bouton Add Ingredient il t'affiche les mots clés que tu peux insérer

**Comment by nusmiaf** [comment]
c'est bon j'ai trouver , l'erreur viens de moi , j'ai crée un applet depuis zéro sur la plateforme IFTTT en mode Private  a cause de mes requêtes avec user/mdp
et j'ai édité sans le vouloir la partie du formulaire ou il y a {{NumberField}} {{TextField}}  
du coup  ça pouvait pas fonctionner....
la je viens de recrée a partir de iftt en mode " new applet " normal  et la ca fonctionne

![image](https://user-images.githubusercontent.com/33859641/44096218-0cac2a1c-9fdb-11e8-9a1c-1eb6263360f8.png)

**Comment by nusmiaf** [comment]
donc je doit recrée l'applet  en private sans faire de bêtises !

un grand merci a toi , pour ton aide et ta patience avec moi  :p
bonnes vacances
