### ISSUE TITLE
DSM 6.2

### ISSUE THREAD

**Issue by Tntn10** [Aymkdn/assistant-plugins#164]
Bonsoir,
Je viens d'installer assistant-plugin pour une livebox avec succès sur un synology DS215j dans un environnement DSM 6.2-23739 Update 2.
Tout fonctionne parfaitement sauf au moment de redémarrer le NAS. Le redémarrage met le NAS en mode Installation et il me propose de migrer mes données...Je ne perds aucune donnée (ouf), mais bien évidemment le répertoire /opt se réinitialise ..et du coup retour à la case départ....

Bien cordialement,

**Comment by Aymkdn** [comment]
Aucune idée... T'es le premier qui me rapporte un tel problème...

**Comment by Tntn10** [comment]
Merci quand meme....et chapo pour le W ;-)

**Comment by lenain71** [comment]
Je confirme, je viens d'avoir la même chose après avoir modifier le crontab pour lancer le plugin !!

**Comment by Aymkdn** [comment]
N'utilisant absolument pas de DSM, je ne sais malheureusement pas comment aider @lenain71 .... mais si tu trouves ce qui cause ça, n'hésite pas à partager l'information !

**Comment by lenain71** [comment]
Je vais déjà refaire redémarrer mon NAS et si je trouve je fais signe
