### ISSUE TITLE
Erreur dans le fichier de log

### ISSUE THREAD

**Issue by Nemesis24** [Aymkdn/assistant-plugins#167]
```
[assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 1 plugin trouv  .
[assistant] Chargement du plugin 'notifier' (v2.1.0)
[assistant-notifier] Plugin charg   et pr  t.
[assistant] Pr  t      couter les commandes via PushBullet
[assistant-plugins] Erreur de connexion avec PushBullet:  { Error: getaddrinfo $
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: '443' }
```

J'ai suivi le tuto et tout c''est bien déroulé

**Comment by Aymkdn** [comment]
Visiblement y'a un problème de connexion avec Pushbullet. Réessaie demain pour voir ?

**Comment by Nemesis24** [comment]
ok merci de ta réponse rapide

**Comment by Aymkdn** [comment]
Alors, ça donne quoi aujourd'hui ?

Si le problème persiste, vérifie que tu n'as pas un antivirus/firewall/VPN qui bloquerait la connexion à Pushbullet.

**Comment by Nemesis24** [comment]
Bonsoir,même chose aujourd'hui. je n'ai rien qui bloque la connexion.

**Comment by Nemesis24** [comment]
Bonjour oui désolé je me suis trompé pour le bouton, c'est toujours pareil, et non je n'ai rien de bloquant en apparence.

**Comment by Aymkdn** [comment]
Essaie d'ouvrir la page web https://stream.pushbullet.com/

Tu devrais voir : 
![capture](https://user-images.githubusercontent.com/946315/44616665-31bd2a00-a854-11e8-9c8b-9457988f7c42.PNG)

**Comment by Aymkdn** [comment]
Aussi, sur quel appareil as-tu installé / lancé `assistant-plugins` ? Un PC Windows ? Linux ? MacOS ? Raspberry ? Etc...

**Comment by Nemesis24** [comment]
c'est le cas

**Comment by Nemesis24** [comment]
sur une framboise 3

**Comment by Aymkdn** [comment]
OK donc un Raspberry Pi, du coup le test que tu as fait (ouvrir la page web) devrait être fait sur ton Framboise.... J'imagine que tu n'as qu'un accès en console (type SSH) à cet appareil ?

**Comment by Nemesis24** [comment]
Tu imagines bien c'est en ssh.

**Comment by Aymkdn** [comment]
Tu peux essayer déjà de pinguer l'adresse pour voir : 
```bash
ping stream.pushbullet.com
```

**Comment by Nemesis24** [comment]
--- stream.pushbullet.com ping statistics ---
90 packets transmitted, 90 received, 0% packet loss, time 89022ms
rtt min/avg/max/mdev = 130.629/131.083/139.494/0.934 ms

**Comment by Aymkdn** [comment]
OK. Quelle version de node as-tu installé ? 
```
node --version
```

**Comment by Nemesis24** [comment]
arm v71

**Comment by Aymkdn** [comment]
Cela dit le problème semble toucher plusieurs utilisateurs de Node : https://github.com/nodejs/node/issues/5436 ou https://github.com/nodejs/node/issues/5436 et autres...

Ça a l'air très spécifique à chaque personne / configuration. Donc je ne pense pas que je vais pouvoir t'aider beaucoup plus que cela. Il faudrait que tu regardes ce que tu trouves en ligne et les différentes aides qui sont proposées.

En tout cas le problème n'est pas spécifique à `assistant-plugins` !

Si tu trouves une solution je veux bien que tu la partages : cela pourrait toujours en aider d'autres.

**Comment by Nemesis24** [comment]
Avec la modif c'est pareil, ok je vais tenter de chercher, cependant y a til moyen d'utiliser en local l'envoi d'un message via notifier, je souhaiterai me rendre compte.

**Comment by Aymkdn** [comment]
En local, non. Par contre si tu as Windows (ou autre), tu peux l'installer sur cette machine pour tester. Si tu vois que ça te convient tu peux ensuite chercher à débugger ta version Raspberry

**Comment by Nemesis24** [comment]
ok merci

**Comment by SiddhyN** [comment]
Bonsoir à vous,

J'ai également la même erreur que @Nemesis24 à savoir "Erreur de connexion avec PushBullet"
Je suis sous windows10 et je lance assistant plugins en tache de fond avec pm2.
Tout fonctionne correctement pendant un certain temps, puis l'erreur survient.

J'ai une version inférieure de node (v8.11.4)

Si vous trouvez une solution je suis preneur :)

Merci pour le taf en tous cas @Aymkdn !

**Comment by SiddhyN** [comment]
Ah non en effet je n'ai pas exactement la même erreur.. (et oui je redémarre le processus (avec un stop start mais c'est equivalent je pense)

Voila mon erreur : 
![capture](https://user-images.githubusercontent.com/3406408/44767134-e01ae500-ab5c-11e8-8642-a1a7f43b637f.PNG)

Il faut peut être que j'ouvre une nouvelle issue non @Aymkdn ?

**Comment by Aymkdn** [comment]
@SiddhyN regarde là : https://github.com/Aymkdn/assistant-plugins/issues/123
