### ISSUE TITLE
installation package via opkg failed

### ISSUE THREAD

**Issue by lenain71** [Aymkdn/assistant-plugins#168]
J'essai de configurer mon NAS 213j pour faire fonctionner node JS et lancer les plugins. en suivant le wiki, je reste bloqué sur l'installation des packages gcc make tar et wget avc cette erreur : 

bash-4.3# opkg install gcc make tar wget
Unknown package 'gcc'.
Unknown package 'make'.
Unknown package 'tar'.
Unknown package 'wget'.
Collected errors:
 * opkg_install_cmd: Cannot install package gcc.
 * opkg_install_cmd: Cannot install package make.
 * opkg_install_cmd: Cannot install package tar.
 * opkg_install_cmd: Cannot install package wget.
bash-4.3#

Une petite idée ??

Pour info opkg opérationnel et connecté en SSH en root

**Comment by Aymkdn** [comment]
Aucune idée désolé.... Je n'utilise pas de NAS (j'ai juste installé un simulateur pour faire le tuto).

T'as cherché sur le Net ? C'est bizarre qu'opkg ne reconnaisse aucun de ces paquets...

**Comment by lenain71** [comment]
Oui je trouve rien. Tu me confirmes qu'il suffit d'avoir node ? Je vais essayé de l'installer en direct.

**Comment by Aymkdn** [comment]
J'ai rapidement regardé sur le net.

Essaie de taper `opkg update` et aussi `opkg list` et vois ce que ça donne.

Aussi la commande précédente du tuto, à savoir `opkg install bash nano grep busybox`, avait fonctionné ?

**Comment by Aymkdn** [comment]
Oui il suffit d'avoir Node, mais pas une trop vieille version...

**Comment by lenain71** [comment]
en effet, il avait surement un soucis avec opkg. J'avais rien dans la liste de package dispo. Après un opkg update c'est mieux. Je continue et reviens si il y a soucis. 

Merci !
