### ISSUE TITLE
Pb accès Freebox avec VPN sur Synology

### ISSUE THREAD

**Issue by sej75** [Aymkdn/assistant-plugins#169]
Bonjour,
Je n'arrive plus à accéder à ma Freebox depuis que j’utilise un VPN sur Synology. Avant tout se passait bien mais depuis l'installation du VPN, j'ai un "time out" lorsque je lance mes commandes.
J'ai bien ajouté le paramètre "player_ip" avec l'adresse ip de mon "Freebox Player" comme indiqué dans la documentation, mais cela ne change rien. Lorsque j'arrête le VPN, cela marche, lorsque je le relance, cela ne fonctionne plus.
Je joins les logs du pb ainsi que les paramètres de mon fichier "configuration.json".
Merci pour vos retours,
![2018-08-29](https://user-images.githubusercontent.com/42809240/44793913-a1f6e300-aba7-11e8-8615-0b01bc02aa2c.png)
![2018-08-29 1](https://user-images.githubusercontent.com/42809240/44793917-a6bb9700-aba7-11e8-882b-10eb679b2d60.png)

**Comment by Aymkdn** [comment]
Dans ton cas, il n'arrive pas à accéder à mafreebox.freebox.fr (212.27.38.253)...

Peut-être en utilisant l'IP local de ta Freebox Serveur... Qui doit être 192.168.0.254 par défaut.

Tu peux essayer d'ouvrir le fichier `node_modules/assistant-freebox/freebox.js`  et remplacer [la ligne suivante](https://github.com/Aymkdn/assistant-freebox/blob/master/freebox.js#L18) : 
```javascript
  this.serverURL = "https://mafreebox.freebox.fr/api/v4/";
```
Par : 
```javascript
  this.serverURL = "https://192.168.0.254/api/v4/";
```

Puis reteste et dis moi si ça fonctionne.

**Comment by sej75** [comment]
Super ! Ça fonctionne !!!
un grand merci !

**Comment by Aymkdn** [comment]
OK. Je vais ajouter une option alors pour que ça puisse se changer depuis le fichier de configuration.

**Comment by Aymkdn** [comment]
Voilà j'ai publié la version 2.0.10

Tu peux mettre à jour et dans ton `configuration.json` tu peux y ajouter : 
```javascript
   "server_ip": "192.168.0.254"
```

**Comment by sej75** [comment]
C'est fait, ca fonctionne impeccable ! Génial !!!
