### ISSUE TITLE
Launch sans erreur mais ne fonctionne pas

### ISSUE THREAD

**Issue by anterta** [Aymkdn/assistant-plugins#170]
L'installation c'est entièrement bien passé, lorsque je demande à mon google home une action elle arrive bien jusqu'à mon pc : 
[assistant] Assistant v2.0.5 : Chargement en cours... 
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'control-windows' (v1.0.0)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"C:\\GoogleHome\\GoogleHome.vbs" coupe le son' ]
[assistant] Appelle du plugin 'launch'

Mais rien ne passe après...

**Comment by Aymkdn** [comment]
Ta commande me semble bizarre... Tu appelles le script C:\GoogleHome\GoogleHome.vbs avec un paramètre `coupe le son` sans incollade ?
Si tu lances la même chose dans une console X cela fait quoi? 

Et si ton but est de couper le son regarde plutôt ce plugin  : https://aymkdn.github.io/assistant-plugins/?plugin=control-windows

**Comment by anterta** [comment]
Je veux pouvoir contrôler entièrement l'ordinateur.
Tu veux que lance quoi comme requête exactement?

**Comment by Aymkdn** [comment]
1. Est-ce que tu peux partager le contenu du fichier `GoogleHome.vbs` ?
  2. Est-ce que tu as essayé ce plugin qui permet de contrôler son ordinateur ? https://aymkdn.github.io/assistant-plugins/?plugin=control-windows

**Comment by anterta** [comment]
Pour le GoogleHome.vbs je l'ai téléchargé hier ... (je pourrais l'envoyer
demain)
Et le plugin control-window est installé, je devrais désinstaller le plugin
launch?

**Comment by Aymkdn** [comment]
Ce sont 2 plugins différents. Tu peux conserver les deux, mais le `launch` peut être inutile si tu utilises `control-window` pour contrôler ce que tu souhaites contrôler....

Que cherches-tu à faire exactement ?

**Comment by Aymkdn** [comment]
Donc oui tu peux faire tout ça avec `control-window` normalement, sans utiliser un fichier .vbs

**Comment by anterta** [comment]
Et dans ifttt? ça utilise pas le .vbs?

**Comment by Aymkdn** [comment]
Non ça n'utilise pas de .vbs

Tu dois juste passer des commandes depuis IFTTT, comme `control-windows_mute`. Comme expliqué dans la documentation: https://aymkdn.github.io/assistant-plugins/?plugin=control-windows#utilisation

**Comment by anterta** [comment]
Donc je dois rentrer toute les commandes ifttt moi même? Bouh :'(

**Comment by Aymkdn** [comment]
C'est le plus efficace / propre.

Sinon tu dois te dépatouiller avec ton .vbs en utilisant `launch`.

**Comment by anterta** [comment]
Psq avec le googlehome.vbs j'ai le fichier text avec la liste des commandes
possible et tout y est :/

**Comment by anterta** [comment]
Merci, en effet je viens de tester et cela fonctionne. Par contre, j'ai
testé un peu tout et les applications win10 comme netflix ou spotify ne
semble pas fonctionner.

Le 4 sept. 2018 4:55 PM, "no-response[bot]" <notifications@github.com> a
écrit :

Cette *issue* a été automatiquement fermée car il n'y a eu aucune réponse
complémentaire de la part de l'auteur. N'hésite pas à reposter ici si tu as
d'autres questions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Aymkdn/assistant-plugins/issues/170#issuecomment-418398581>,
or mute the thread
