### ISSUE TITLE
Probleme Livebox

### ISSUE THREAD

**Issue by P0luX3882** [Aymkdn/assistant-plugins#171]
Bonjour,
J'e suis récemment passé d'une freebox à une livebox et je rencontre un probleme pour utiliser le plugin assistant-livebox.
Je m'explique : Lorsque je demande a Google Home de Zapper sur une chaine supérieur a 9 elle coupe le nombre en deux avec une virgule. Par exemple pour la "10" elle fait "1,0".

Voir la capture d’écran ci-joint

![error](https://user-images.githubusercontent.com/18376782/44953897-a585b500-ae9a-11e8-98c0-8dab95eab55b.png)

Cordialement,
P0luX

**Comment by Aymkdn** [comment]
Tu as quelle version du plugin ? Car j'ai corrigé ça le 25 juin dernier  : 
https://github.com/Aymkdn/assistant-livebox/blob/master/changelog.md

**Comment by P0luX3882** [comment]
Je l'ai installé hier donc je pense que c'est la dernière j'ai tenté un npm update dans le doute mais le problème persiste.

**Comment by Aymkdn** [comment]
Donc quand tu lances assistant-plugins tu vois bien v1.1.0 pour la version du plugin livebox ?

**Comment by Aymkdn** [comment]
Je ne suis pas chez moi aujourd'hui. Je regarde ça demain du coup !

**Comment by P0luX3882** [comment]
Oui, je te laisse en jugé par toi même ...

![erro1](https://user-images.githubusercontent.com/18376782/44954250-850c2980-ae9f-11e8-8c9c-bf829d08210d.png)

**Comment by Aymkdn** [comment]
J'ai trouvé un ordi pour regarder ça !

Est-ce que tu peux modifier le fichier `node_modules/assistant-livebox/livebox.js` sur la [ligne 202](https://github.com/Aymkdn/assistant-livebox/blob/466b658245ba1068db19c005f11255f38332d0fe/livebox.js#L202) en remplaçant ça : 
```javascript
            key = nom.match(/la(\d+)/)[1].split("");
```

Par : 
```javascript
            key = nom.match(/la(\d+)/)[1];
```

Puis relance assistant-plugins et teste. N'ayant pas de livebox je ne peux pas tester moi-même.

Si ça fonctionne je modifierai et publierai une nouvelle version.

Merci

**Comment by P0luX3882** [comment]
Ok merci,
Je viens de tester et ça fonctionne. :)

**Comment by Aymkdn** [comment]
OK super !

Je viens de publier la v1.1.1 donc si tu mets à jour ça doit fonctionner.
