### ISSUE TITLE
Bugg pour module freebox " Zape sur la 9" action zappe sur la 99

### ISSUE THREAD

**Issue by valentin44** [Aymkdn/assistant-plugins#175]
Bonjour à toi , 
Déjà dans un premier temps : Un grand merci pour ton travail , c'est la première fois que je me lance dans un tuto aussi simple coté informatique le rendu est vraiment sympa

Je te remonte quand même quelque chose :
Aout 2018 je me suis offert la Google Home pour le coupler avec mon système "Domoticz" Sur un Rpi 3

Du coup étant sur free j'ai suivi ton tuto pour connecter ma google home à ma freebox => tout impeccable pendant 1 mois . Allume Eteint Zappe coupe le son 

je ne l'ai pas utilisé régulièrement donc je ne peux pas te dire depuis quand , mais quand je lui demande de zapper sur la 9 il m'envoie sur la 99 et quand je lui demande la 99 il m'envoie sur la 9 
c'est comme cela avec toutes les chaines .

j'ai rien installé depuis sur mon RPI 3 donc la je suis un peu perdu , je lui ai fait une MAJ mais c'est la même.

si tu as des idées je suis preneur 

je te remercie d'avance

cordialement 

Valentin

**Comment by Aymkdn** [comment]
Tu as regardé ce qu'indique la console/log du programe? Le bon chiffre s'affiche-t-il ? Tu peux faire un copié collé ici ?

**Comment by Aymkdn** [comment]
Je pense que tu as le programme qui est lancé deux fois sur ton ordinateur, non ? Ça expliquerait ce comportement (j'imagine que ça fait ça pour toutes les chaînes ?)

**Comment by valentin44** [comment]
Effectivement d'ou les doubles lignes , 
comment je peux voir la double Exécution sur Raspberry ?

**Comment by Aymkdn** [comment]
OK cool !
