### ISSUE TITLE
Les commandes Freebox  "zappe" ne fonctionnent pas sur Alexa

### ISSUE THREAD

**Issue by Frabok** [Aymkdn/assistant-plugins#176]
Bonjour,

Tout d'abord, Bravo et Merci pour votre travail. j'imagine la persévérance qu'il vous a fallu pour arriver à créer ces applets.
Mon souci qui n'en est plus vraiment un, mais je souhaitais le partager.

La plupart des commandes  pour la freebox fonctionnent depuis mon Alexa à l’exception des commandes "zappe".
Après pas mal d'essais, j'en arrive à la conclusion que c'est le mot zappe qui est mal compris.  
La réponse est immédiate "Désolé, je ne trouve pas ce déclencheur IFTTT"
J'ai remplacé le mot "zappe" par "go" ou "va" et ça fonctionne. Donc toute la chaîne fonctionne y compris lorsqu'on épelle le nom des chaînes par exemple 'T' 'M' 'C'.
dommage, j'aimais bien l'ordre zappes!
Avez-vous rencontré le même souci? 

Frabok

**Comment by Aymkdn** [comment]
Merci pour l'info, ça me permettra d'aider d'autres personnes. Pour le moment ça ne m'a été remonté.

J'ai un Google Home à la maison et j'ai développé développé la version Alexa pour ceux qui l'auraient mais je ne l'utilise pas 😉

**Comment by Aymkdn** [comment]
J'ai rajouté l'info dans la doc !
