### ISSUE TITLE
utiliser launch avec un parametre

### ISSUE THREAD

**Issue by softxpert2** [Aymkdn/assistant-plugins#177]
Bonjour et surtout merci pour votre travail.

j'ai un doute sur la syntaxe a employer pour utiliser launch_

je souhaiterai utiliser cette instruction pour compléter mon installation freebox
un petit module récupère le volume sonore et ajuste le son de ma freebox
il évite ainsi de me faire casser les les oreilles par les pubs
mais pour le compléter j'aimerai ajouter un contrôle verbale, j'ai besoin de lui envoyer un paramètre
un simple nombre entier.

j'utilise donc If you say then push a note et _launch dans message

mon test en local :
              node /home/pi/DocumentJS/executer.js    (sans parametre)
avec un parametre:
             node /home/pi/DocumentJS/executer.js 5 (suivi d'un entier)
test sur ifttp: 
             launch_"/home/pi/Documents/dev/NodesJS/executer.js"

tout fonctionne bien jusque la
mais curieusement 

test sur ifttp: 
          launch_"/home/pi/Documents/dev/NodesJS/executer.sh" {{NumberField}} 
          launch_"/home/pi/Documents/dev/NodesJS/executer.sh {{NumberField}}"
 
ces 2 dernieres syntaxes ne fonctionnent pas, même si elles semblent bien présentés
dans le moniteur pm2 monit sans message d'erreur apparent

est ce que launch ne prend pas en compte les paramètres ?

D'avance merci

**Comment by Aymkdn** [comment]
Le `{{NumberField}}` a bien été généré par IFTTT (quand tu cliques sur "Add Ingredient")? 

Ensuite, pm2 monit devrait indiquer : `[assistant-launch] Lancement du programme : /home/pi/Documents/dev/NodesJS/executer.sh 5`

Est-ce le cas ? 

(sinon oui la dernière syntaxe avec tout entre guillemets devrait être la bonne)

**Comment by softxpert2** [comment]
oui, exacte

**Comment by Aymkdn** [comment]
J'imagine que ton "oui exact" correspond à ce qu'affiche pm2 monit ? Peux tu faire une capture d'écran ?

Je suis en vacances à l'étranger là, donc je ne peux pas faire de tests jusqu'à mon retour, dimanche.

**Comment by softxpert2** [comment]
![image](https://user-images.githubusercontent.com/36131603/46754568-15216800-ccc3-11e8-93f8-6d38524d871d.png)
ici j'utilise blink.js
mon fichier est un script js

**Comment by Aymkdn** [comment]
Tu appelles un fichier JS qui n'est pas exécutable. C'est `node` qui execute le JS...

Donc ça devrait être `launch_"/path/to/node /path/to/blink.js {{NumberField}}"`

**Comment by softxpert2** [comment]
ok, j'essaie ça de suite, autant pour moi, j'etais passé pas loin avec
launch_"node /path/to/blink.js {{NumberField}}"

**Comment by softxpert2** [comment]
Non, ça ne passe pas non plus dés que je fait suivre par un entier
Alors qu'en console, ça passe bien avec ou sans entier an argument

**Comment by Aymkdn** [comment]
Fais voir ton monit ?

**Comment by softxpert2** [comment]
![image](https://user-images.githubusercontent.com/36131603/46756851-b9f27400-ccc8-11e8-8458-037266ee1698.png)

**Comment by Aymkdn** [comment]
Mmmhhh... Là je sais pas. Faudrait que je fasse des tests pour voir... Donc ça ne sera pas avant dimanche.

**Comment by softxpert2** [comment]
Merci c'est sympas, d'avoir débroussaillé un peu, parce que j'avais des doutes sur la syntaxe de launch
je vais me pencher sur une version en script sh pour vérifier.
En attendant, bonne soirée.

**Comment by softxpert2** [comment]
Et bonne vacances ;)

**Comment by Aymkdn** [comment]
Alors, je viens de tester ça : 
![capture](https://user-images.githubusercontent.com/946315/46916082-f1f20380-cfb5-11e8-831a-7d8dc581dc52.PNG)

Soit : 
```
launch_node D:\assistant-plugins\launch_test.js 2
```

Dans ma console j'ai bien : 
```
[assistant] Commande reçue:  [ 'launch_node D:\\assistant-plugins\\launch_test.js 2' ]
[assistant] Appel du plugin 'launch'
[assistant-launch] Lancement du programme : node D:\assistant-plugins\launch_test.js 2
```

Et j'ai bien mon paramètre `2` qui est reconnu par mon fichier `launch_test.js` ... son contenu est le suivant : 
```javascript
var fs = require('fs');
fs.writeFile("./test.txt", process.argv.join("\r\n"), function(err) {
  if(err) {
    return console.log(err);
  }
});
```

C'est-à-dire que j'écris dans le fichier `test.txt` tous les "arguments" (fournis par `process.argv`) et j'ai bien : 
```
C:\Program Files\nodejs\node.exe
D:\assistant-plugins\launch_test.js
2
```

Donc le problème vient de ton `blink.js` je pense.

Je t'invite à faire le même test que moi pour prouver que cela fonctionne.

**Comment by softxpert2** [comment]
Ok, cette fois, ça fonctionne très bien.
-Ayant au départ omis le fait que les fichiers résultants du script seraient créés dans 
le dossier "assistant-plugin", je me suis enfoncé dans une succession
d'erreurs en voulant corriger mon script.
-Dans le message j'utilisais des guillemets qui ne semblent pas utiles même avec un num field

Donc merci, beaucoup pour cette avancée, bonne soirée ;)

**Comment by Aymkdn** [comment]
OK cool :)
