### ISSUE TITLE
lancement du programme au démarrage du PI ?

### ISSUE THREAD

**Issue by alexbi91** [Aymkdn/assistant-plugins#18]
salut

je voulais savoir deja ou faut il que je copie le fichier assistant plugin master ? Dans un dossier en particulier ?
par contre je peux l'utiliser en faisant node index.js mais  après quand je ferme putty le programme se ferme aussi donc je voulais savoir comment le lancer au démarrage du PI

merci pour ton aide

**Comment by Aymkdn** [comment]
Tu peux le copier où tu le souhaites, ça n'a pas d'importance.

Pour le lancer au démarrage et qu'il soit autonome, tu peux utiliser une solution comme [pm2](http://pm2.keymetrics.io/)

Cela fait partie des choses que je détaillerai mieux ces prochaines semaines.

**Comment by alexbi91** [comment]
OK merci pour ton aide je vais regarder tout ça.
Mais c'est sûre que pour les novices comme moi il manque cette partie dans tes explications, en tout cas c'est cool ton projet.

dernière question :
on est pas limité au niveau de pushbulet pour le nombre de commande envoyé avec une version non pro ?

**Comment by Aymkdn** [comment]
Comme ça passe via IFTTT, je ne pense pas... À vérifier dans le temps ^^

**Comment by alexbi91** [comment]
je dis ça car j'ai remarqué un bloquage quand je l'utilisais avec les notifications sur mon tél après un certain temps ça bloquait

**Comment by Aymkdn** [comment]
D'après ce site (http://www.androidpolice.com/2016/07/27/pushbullet-will-limit-api-based-pushes-500-per-month-free-accounts-starting-august-1/)  ça devrait aller :  « Importantly, this only applies to custom apps and services that use the Pushbullet public API. It won't affect Channels, IFTTT, manual pushes, and so on. »

**Comment by alexbi91** [comment]
ok cool merci a toi pour tes réponses

j'ai installé p2m ça fonctionne bien !

**Comment by alexbi91** [comment]
http://pm2.keymetrics.io/docs/usage/quick-start/

https://futurestud.io/tutorials/pm2-restart-processes-after-system-reboot

voici les 2 liens qui m'ont servit pour pm2

**Comment by Aymkdn** [comment]
Pour info je viens de mettre en ligne la v2. Je l'annonce là : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0

Dans la doc j'ai rajouté une petite partie sur pm2 :-)
