### ISSUE TITLE
Code erreur au lancement de la Freebox

### ISSUE THREAD

**Issue by sej75** [Aymkdn/assistant-plugins#180]
Bonjour,
J'ai un message d'erreur au lancement de la freebox (voir la copie d'écran jointe). J'ai joint également le fichier de configuration.
A noter que j'utilise un NAS Synology et un VPN, d'où les paramètres player_ip et server_ip qui fonctionnaient parfaitement auparavant.
Je ne sais pas ce qui a changé ? J'ai ré-installé, mis à jour et vérifié toutes les connexions avec pushbullet, ifttt, il n'y a pas d'erreur ...
Ci-dessous les copies d'écrans :
![2018-10-31](https://user-images.githubusercontent.com/42809240/47802377-6952c180-dd30-11e8-814e-dd7d2437f437.png)
![2018-10-31 1](https://user-images.githubusercontent.com/42809240/47802409-7a033780-dd30-11e8-8dab-190979f13b44.png)

Merci pour ton retour, et bravo pour ce plugin que j'adore !!!

Serge

**Comment by Aymkdn** [comment]
Salut.

As-tu vérifié que l'IP de ta Freebox Player n'a pas changé ? Car il n'arrive plus à y accéder...

**Comment by sej75** [comment]
Effectivement, tu as raison, c’est un problème chez moi de Freebox Player. Je vais arranger ça.

 

Un grand merci et continue, c’est super !

 

Par ailleurs, sais-tu s’il existe un plugin pour lancer automatiquement un café sur la machine Nespresso connectée Prodigio ? Je peux le lancer à partir de mon appli IOS Nespresso J

 

Serge

 

De : Aymeric <notifications@github.com> 
Envoyé : mercredi 31 octobre 2018 17:37
À : Aymkdn/assistant-plugins <assistant-plugins@noreply.github.com>
Cc : sej75 <sej75@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Aymkdn/assistant-plugins] Code erreur au lancement de la Freebox (#180)

 

Salut.

As-tu vérifié que l'IP de ta Freebox Player n'a pas changé ? Car il n'arrive plus à y accéder...

**Comment by Aymkdn** [comment]
Non... Pas avec `assistant-plugins` en tout cas. Il faut regarder si un des [services de IFTTT ](https://ifttt.com/services) pourrait le faire, ou même s'il existe un service avec Google Assistant pour gérer ça... J'ai rapidement cherché sur Internet, mais je n'ai rien trouvé de spécial.
