### ISSUE TITLE
Demande d'ajout d'un plugin

### ISSUE THREAD

**Issue by launay12u** [Aymkdn/assistant-plugins#181]
Bonjour,

Tout d'abord félicitation pour ton travail 😄Je viens d'installer assistant plugin pour mon Google Home et j'en ai profité pour développer un petit plugin pour les horaires de tram sur Nancy. Je me suis servi de ton template, c'était parfait 👍 Je sais pas si d'autres personnes seront intéressées par ce plugin mais on sait jamais 😃Je te mets le lien du github et du package NPM, si il faut faire des modifications n'hésites pas à me le dire, je dois mettre à jour le README pour la configuration de la clé d'API Navitia

Lien Github : https://github.com/launay12u/assistant-tram-nancy
Lien NPM : https://www.npmjs.com/package/assistant-tram-nancy

**Comment by Aymkdn** [comment]
Super, merci ! Je regarde ça un peu plus en détails ces prochains jours et je te dis ! Si tout bon, je l'ajouterai aux plugins, sinon je te demanderai des modifs ;-)

**Comment by Aymkdn** [comment]
Ça m'a l'air pas mal ! J'ai fait des pull requests pour quelques modifications !

Je te laisse le republier en 2.0.3 et je l'ajoute sur le site principal 👍  Merci !

**Comment by launay12u** [comment]
Voilà j'ai merge tes PR :) Merci !

**Comment by Aymkdn** [comment]
J'ai fait un pull request pour que ton README soit bien lu par la page du plugin : https://aymkdn.github.io/assistant-plugins/?plugin=tram-nancy !

Sinon, c'est bon il est dispo sur le site
