### ISSUE TITLE
Plugin Lilo Pret a pousser

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-plugins#183]
Hello,

Un nouveau plugin pour contrôler le potager connecté [Lilo](https://pretapousser.fr/)

[Assistant-lilo](https://github.com/jzarca01/assistant-lilo) 

Il y a un script de preinstall car il requiert des packages Linux pour interagir avec le bluetooth

**Comment by Aymkdn** [comment]
Tu es prolifique dis donc ^^

J'ai complété ton README. Une fois corrigé, tu pourras publier sur NPM le plugin afin qu'il puisse être utilisé !

**Comment by jzarca01** [comment]
C'est bon pour LILO ;) https://www.npmjs.com/package/assistant-lilo

**Comment by Aymkdn** [comment]
Publié : https://aymkdn.github.io/assistant-plugins/?plugin=foodcheri
