### ISSUE TITLE
Plugin Franprix

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-plugins#184]
Hello,

Voici un nouveau plugin pour consulter le solde de sa carte de fidélité Franprix et y ajouter automatiquement toutes les promotions disponibles.

[assistant-franprix](https://github.com/jzarca01/assistant-franprix)

**Comment by Aymkdn** [comment]
Idem que pour Lilo ! Merci :-)

**Comment by jzarca01** [comment]
C'est bon pour Franprix ;) https://www.npmjs.com/package/assistant-franprix

**Comment by Aymkdn** [comment]
Publié : https://aymkdn.github.io/assistant-plugins/?plugin=franprix
