### ISSUE TITLE
Plugin Foodchéri

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-plugins#185]
Hello,

Voici un plugin pour suivre l'état de sa commande Foodchéri

[assistant-foodcheri](https://github.com/jzarca01/assistant-foodcheri)

**Comment by Aymkdn** [comment]
Merci ! Idem que les deux autres ;-)

**Comment by jzarca01** [comment]
C'est bon c'est publié ;) https://www.npmjs.com/package/assistant-foodcheri

**Comment by Aymkdn** [comment]
Je fermerai l'issue quand j'aurai ajouté le plugin sur le site !

**Comment by Aymkdn** [comment]
Publié également : https://aymkdn.github.io/assistant-plugins/?plugin=foodcheri
