### ISSUE TITLE
Pas de demande de permission dans Pushbullet

### ISSUE THREAD

**Issue by maxime2935** [Aymkdn/assistant-plugins#186]
Bonjour à tous,
Bon, je suis novice... Mais bravo pour tout ce qui est proposé, et en plus c'est hyper clair sur le site, vraiment génial et bravo!! Je voulais utiliser le plugin pour la Freebox Revolution.
Mais j'ai bien un problème. Je fais tout ce qui est demandé... Il me semble avoir suivi les tutos à la lettre (tutos écrits + vidéos). Mais lorsque je rentre les commandes sur IFTTT en cliquant sur les liens, aucune demande de permission n'apparaît. Et bien sûr, les commandes ne fonctionnent pas avec le google home, et, comme le montre la copie d'écran suivante, IFPTT n'apparaît pas dans les devices de Pushbullet... Aurais-je oublié une étape??... Savez-vous d'où peut venir le problème? Je n'ai pas de VPN à ma connaissance (désactivé celui de windows 10). J'ai installé Pushbullet uniquement sur le PC, Google Home uniquement sur mon téléphone, créer des comptes IPPS et Pushbullet, utilisé le code comme demandé, etc... Merci d'avance pour votre aide!
![image](https://user-images.githubusercontent.com/44927488/48303754-be4fbe00-e50e-11e8-85c0-d36a8abb5e08.png)
Et la fenêtre reste coincée sur cette image. Sans jamais évolué, quoi que je fasse...
![image](https://user-images.githubusercontent.com/44927488/48303794-45049b00-e50f-11e8-9a23-0f5537e84b94.png)
J'ai en parallèle j'utilise pour info un NAS Synology DS213+, mais il est juste branché à ma freebox et je ne m'en sers que comme disque dur sécurisé. Je ne pense pas que sa présence soit un problème dans la configuration.

**Comment by Aymkdn** [comment]
Salut

Si tu vas là https://ifttt.com/services/pushbullet/settings est ce que ça dit que tu es connecté au service Pushbullet ?

**Comment by Aymkdn** [comment]
Quand tu vas là https://ifttt.com/my_applets tu as quoi comme applets ? Les as-tu activé ?

**Comment by Aymkdn** [comment]
A priori, je dirais que tu n'as pas activé les applets pour la Freebox sur IFTTT

**Comment by maxime2935** [comment]
Oui, tout a été activé, mais rien ne fonctionnait (jai essayé : le son, allumer et éteindre). J'ai tout supprimé pour tout remettre, mais toujours pareil. Il ne reste plus que l'applet "allumer". Mais elle ne fonctionne toujours pas... J'ai créer une autre applet tout à l'heure différent de Pushbullet (m'envoyer un mail) donc, de Google Assistant à Gmail, et ça ne marchait pas non plus. Je pense que le problème vient du fait que mon Google Home (version mini) ne s'est pas connecté à IFTTT...
![image](https://user-images.githubusercontent.com/44927488/48304314-235be180-e518-11e8-9cfd-7110ae226a34.png)

**Comment by Aymkdn** [comment]
Tu t'es connecté à IFTTT (et le service Google Assistant de IFTTT) avec le même compte Google que celui Google Home ?

**Comment by Aymkdn** [comment]
Tu peux voir ça là https://ifttt.com/services/google_assistant/settings

Si c'est la bonne adresse, essaie de déconnecter le service et de le reconnecter

**Comment by maxime2935** [comment]
Oui, bien sûr c'est la meêm adresse. J'ai quand même vérifié, mais c'est bien le cas. J'ai fait disconnect et reconnecter. J'ai entré à nouveau l'applet "allumer" et l'applet "m'envoyer un mail sur gmail" en disant une phrase toute bête. Mais Google Home ne reconnaît toujours aucune des 2 commandes

**Comment by Aymkdn** [comment]
Et t'as quoi là https://ifttt.com/activity/service/google_assistant ?

**Comment by maxime2935** [comment]
N'apparaîssent seulement que des création ou des suppressions d'applets que j'ai fait. 
![image](https://user-images.githubusercontent.com/44927488/48304564-a92d5c00-e51b-11e8-890d-91faef3c6a34.png)
![image](https://user-images.githubusercontent.com/44927488/48304566-b8aca500-e51b-11e8-9edc-00a09551ec9e.png)

**Comment by Aymkdn** [comment]
Bon bhein, si c'est bien maxime2935 qui est aussi utilisé sur le Google Home.... Alors là je ne sais pas...

**Comment by maxime2935** [comment]
Merci. Je viens de régler le problème en réinitialisant le Google Home... Merci en tout cas, car vous m'avez donné la piste!! Et encore bravo pour tout le boulot!

**Comment by Aymkdn** [comment]
Ok cool!

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
