### ISSUE TITLE
Commandes vocales sans PC allumé

### ISSUE THREAD

**Issue by guillaumepie** [Aymkdn/assistant-plugins#189]
Bonjour, 
Tout est installé, du moins je pense. 
Tout fonctionne très bien, par contre je suis obligé d'avoir le PC allumé avec le script qui s'exécute. Dès que j’éteins le PC ou que j’arrête le script les commandes vocales ne fonctionne plus. 
J'ai installé également Pushbullet sur le smartphone. Les commandes s'affichent bien, mon Google home dit les actions, mais sur la télé rien ne se passe. (une fois l'ordi éteint, sinon tout marche bien lorsqu'il est allumé)

Est il possible d'avoir le PC éteint, et de lancer des commandes vocales ?

**Comment by ericarel** [comment]
...avec un raspberry ou odroid ça doit etre possible

**Comment by Aymkdn** [comment]
Oui, avec un Raspberry c'est possible (comme indiqué sur le site), mais ça oblige à acheter ce type de dispositif
