### ISSUE TITLE
liaison freebox/PC avec VPN

### ISSUE THREAD

**Issue by monsieurbug** [Aymkdn/assistant-plugins#19]
Avant tout bravo!

J'ai un peu bataillé car je manque d'expérience, mais à force de recherche, ça marche, et pas qu'un peu!
Par contre je bute sur deux points (et ce n est pas faute d'avoir cherché!):

-mon "assistant plugin" est installé sur un petit serveur linux qui me sert à faire des téléchargements (légaux!!!) et qui est derrière un VPN...et évidemment l'assistant ne connecte que lorsque le VPN est mis HS...voyez vous une solution?
-A chaque relance de l'assistant, il faut appuyer sur la flèche sur le freebox server...y a t'il un moyen de s'en affranchir? (ca ne me gène pas outre mesure, mais quand une chose ne fonctionne pas totalement, ma moitié a tendance à y renoncer...)

Quoi qu'il en soit, encore merci pour le boulot et le partage! C'est avec des petites choses comme celle ci que j'ai vraiment le sentiment de vivre au 21eme siècle!  ;-)

@++

**Comment by Aymkdn** [comment]
En général la connexion via VPN est assez transparente et ne nécessite pas de configuration particulière... Dur à dire comme ça, donc... Ton logiciel torrent ou autre est configuré d'une façon particulière ? 

Pour la deuxième question, retélécharge le fichier freebox.js car j'ai corrigé ce problème mercredi.

**Comment by Aymkdn** [comment]
Pour le VPN, j'ai pu tester et je viens de mettre en ligne une nouvelle version du plugin (v2.0.5). 

Il te faudra ensuite ajouter le paramètre `player_ip` dans ton fichier de configuration. Reporte toi à la [documentation de l'assistant-freebox](https://aymkdn.github.io/assistant-plugins/?plugin=freebox#param-tre-player_ip-) pour savoir quoi faire exactement !

**Comment by monsieurbug** [comment]
Salut,

Je t'avoue qu'avec les fêtes j'avais laissé le problème de côté, mais je ne
manquerais pas de me pencher dessus avec ces nouveaux éléments!

Merci pour l'info et félicitations pour ton investissement dans cet
excellent projet!

Seb.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
