### ISSUE TITLE
Zappe sur "la une"

### ISSUE THREAD

**Issue by ericarel** [Aymkdn/assistant-plugins#191]
Bonjour,

Tout dabord merci pour votre travail.

Lorsque l'on dit "zappe sur tf1" ou "zappe sur la un" cela marche très bien, mais pas lorsque l'on dit zappe sur "la une" ou même zappe sur "la lune" pour les enfants qui ne parlent pas bien, comme moi :-)
Je pense, sauf erreur de ma part, qu'il ya certainement un moyen de mapper de nouveaux mots dans un fichier .json ?

Merci d'avance de votre réponse.
Eric

**Comment by ericarel** [comment]
Ah oui ok, je viens de comprendre, je vais pouvoir me faire des commandes personnalisées.

Merci beaucoup pour ta réponse illico, tu peux fermer la discussion.

Bravo à toi et continue dans ce sens tu iras loin.....

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
