### ISSUE TITLE
Petits problèmes avec freebox

### ISSUE THREAD

**Issue by histoirede** [Aymkdn/assistant-plugins#193]

**Comment by Aymkdn** [comment]
Aucun message laissé ni information fournie....

**Comment by histoirede** [comment]
Bonsoir,
merci pour tout votre travail, j'ai tout installé en suivant votre tuto, çà fonctionne parfaitement lorsque j'utilise vos applets. 2 petits problèmes:
1) Tout d’abord, dans le fichier configuration.json, que je mette
      "use_Mon_Bouquet": false, (ou true)
      ou "use_Chaines_CANAL": false (ou true)
      ou "use_Freebox_TV": false (ou true)
  je tombe toujours sur l'écran d'accueil et sur Freebox TV.
2) Je souhaite créer des applets personnalisés, mais je n'arrive pas à trouver les bonnes commandes.
  Par exemple:, pour aller dans Les Chaines Canal et la chaine 9
                       ou pour aller dans Freebox TV sur TF1.
J'arrive à faire des applets simples allumer et fermer, mais je bute sur l'écran d'accueil que je n'arrive pas à dépasser par les commandes, que je ne dois pas écrire correctement.
J'ai essayé par exemple "freebox_on, Chaines CANAL, wait7000, ok, zappe sur la 9". ça ne fonctionne pas.
Pouvez vous me donner les principes de base. 
Je vous remercie.
Cordialement.
