### ISSUE TITLE
Erreur installation Synology

### ISSUE THREAD

**Issue by riwoo06** [Aymkdn/assistant-plugins#196]
Bonjour ,

Tout d'abord merci pour le travail accompli !

J'ai un NAs DS 212 j , pas de nodeV8 d'aprés le site de Synology,j'ai donc tenter avec le paquet nodeJS qui était dispo chez le centre de paquet Synology 

node -v    :   v0.10.48

Voici l'erreur à l'installation : 

![node](https://user-images.githubusercontent.com/45531022/49337773-ebc4ee80-f618-11e8-9f84-9198a4914882.PNG)

je suppose qu'il faut que je supprime le package Node De synology et que je suive le tuto ?

Merci pour ton aide

**Comment by Aymkdn** [comment]
Tu supposes bien :-)

**Comment by riwoo06** [comment]
Ok merci pour ton retour

J'ai donc suivi l'install,mais au dernier moment node refuse de s'installer ...

nvm install node : 

![image](https://user-images.githubusercontent.com/45531022/49369397-9c9ebc80-f6f1-11e8-8b95-010e89b8f046.png)

**Comment by Aymkdn** [comment]
Il est possible que ton Synology soit trop vieux. Je ne peux malheureusement pas t'aider plus que cela... Il va falloir que tu bidouilles par toi-même pour voir si tu arrives à installer Node (au moins la version 8) sur ton Syno.

Sinon, il faudra te tourner vers un autre système (un PC ou un raspberry par exemple, ou un Syno plus récent ^^)

**Comment by riwoo06** [comment]
Ok je vais me prendre un Raspberry et faire l'install qui va avec !

Merci pour ton retour.
