### ISSUE TITLE
Source de l'évènement envoyé à IFTTT

### ISSUE THREAD

**Issue by Ludwig151** [Aymkdn/assistant-plugins#198]
Bonjour,
Est ce que tu sais si IFTTT a connaissance de la l'émetteur du Trigger, c'est à dire est-ce que c'est Google Home qui envoie la demande ou Google Assistant à partir d'un smartphone, car en fonction de l'émetteur, on peut peut-être le récupérer dans une Applet et faire des actions différentes, ou même passer l'info à Assistant-Plugins pour qu'il lance un programme avec des paramètres différents...
J'ai cherché partout sur le web, en français, en anglais, mais je ne trouve rien
Merci si tu as une idée ou si tu peux me dire où chercher
Bonne Journée

**Comment by Aymkdn** [comment]
Non, on ne peut pas connaitre la source.
