### ISSUE TITLE
Commande Mes musique et augmentation du son

### ISSUE THREAD

**Issue by andurilmike** [Aymkdn/assistant-plugins#199]
Bonsoir,

J'aurai aimé savoir comment je pouvais créer un applet qui permet d'aller dans Mes Musiques sur la freebox?

Et d'ailleurs est ce que je peux créer un applet qui augmente de x % le son de la freebox ?

Merci beaucoup

**Comment by Aymkdn** [comment]
> J'aurai aimé savoir comment je pouvais créer un applet qui permet d'aller dans Mes Musiques sur la freebox?

Alors tu dois d'abord créer une applet (j'explique [les étapes dans la documentation](https://aymkdn.github.io/assistant-plugins/?plugin=freebox#personnalisation)).
Ensuite, dans le Message de la Note Pushbullet il faudra mettre : 
`freebox_home,right,right,ok`

Il suffit de reproduire ce que tu ferais avec la télécommande.

> Et d'ailleurs est ce que je peux créer un applet qui augmente de x % le son de la freebox ?

Elle existe déjà : 
  - Pour augmenter le son : https://ifttt.com/applets/UuDGXdmL-augmente-le-son-de-x-barres-sur-la-freebox
  - Pour baisser le son : https://ifttt.com/applets/cbeL79cW-baisse-le-son-de-x-barres-sur-la-freebox

Utilisation : `OK Google, augmente le son de la Freebox de 20` pour voir le son augmenté de 20 barres.

Par contre on ne peut pas lui dire `mets le son à 50%` puisqu'on n'a aucun retour sur le niveau actuel du son (sinon il faudrait descendre le son à 0, donc 100 appels, puis faire X appels correspondants au pourcentage... pas top donc !)

**Comment by andurilmike** [comment]
Merci pour la réponse.

J'aurais voulu aussi créer un système de contrôle(morceaux suivant,stop,play,etc...) dans Mes Musiques sur la freebox ?

**Comment by Aymkdn** [comment]
Comme indiqué, il faut faire comme si tu utilisais ta télécommande (et en se basant sur les [commandes disponibles](https://aymkdn.github.io/assistant-plugins/?plugin=freebox#commandes))

**Morceau Suivant** : `freebox_fwd`
**Morceau Précédent** : `freebox_bwd`
**Stop** : `freebox_red`
**Pause** : `freebox_pause`
**Lecture** : `freebox_play`

Etc...

**Comment by andurilmike** [comment]
Merci.

J'ai une autre petite question.

Est ce que c'est possible avec la freebox et le google home de lui dire par exemple "ok google lis le 3 éme morceau" ?

**Comment by Aymkdn** [comment]
Oui. Toujours la même chose... tu dois faire comme si tu utilisais la télécommande et donc mettre les commandes correspondantes.
