### ISSUE TITLE
plugin freebox

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#2]
bonjour ,
j'ai une freebox revolution ,
j'ai bien suivi la procédure d'installation du plugin et l'aplet , mais cela ne fonctionne pas ,
c'est possible d'avoir de l'aide 
merci

**Comment by Aymkdn** [comment]
Oui c'est possible d'avoir de l'aide, mais il me faut plus d'informations...

Peux-tu faire une capture d'écran de ce qu'indique la fenêtre lorsque tu lances le programme ? Et aussi indiquer toutes les informations qui pourraient permettre de t'aider...

**Comment by nusmiaf** [comment]
![sans titre](https://user-images.githubusercontent.com/33859641/33062766-bedf3a60-cea0-11e7-8636-ea804d4a43a4.png)

IP statique ok
d'autres aplets fonctionne pour les lumières via IFTTT
de quelles autres information a tu besoin ? je suis totalement novice :/

**Comment by Aymkdn** [comment]
Tout a l'air d'être bon.

Tu as activé l'applet sur IFTTT ?
Quand tu dis, par exemple, "OK Google, allume la Freebox", est-ce que le Google Home te répond ?
Et vois-tu quelque chose dans la fenêtre du programme ?

Tu devrais voir:
```
[assistant] Commande reçue:  [ 'freebox_on' ]                                                              │
[assistant] Appelle du plugin 'freebox'                                                                    
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=123456&key=power
```

**Comment by nusmiaf** [comment]
![sans titre2](https://user-images.githubusercontent.com/33859641/33064112-f1d4b3f6-cea4-11e7-8181-6645cf62ae9f.png)


l'applet est activée , GHome répond "j'allume.."

mais rien

**Comment by Aymkdn** [comment]
Tu as une erreur dans ta console. Il semble que ton code télécommande n'est pas le bon.... Tu n'as pas oublié des chiffres, non ?

**Comment by nusmiaf** [comment]
exacte ,


![sans titre3](https://user-images.githubusercontent.com/33859641/33064534-4acca51c-cea6-11e7-9add-5ba82808d6c1.png)


 je viens de m'en rendre compte il y a 2 min manquait 2 chiffres a la fin du code

là ca fonctionne !
par contre la free s'allume et ce met sur la page d’accueil 
![angrytv](https://user-images.githubusercontent.com/33859641/33064610-991f1eca-cea6-11e7-9696-b818f9740d49.jpg)
 
c'est possible d'ajouté a la commande le " OK " qui bascule sur la TV ( dernière chaine consulté ) 

merci de ton aide

**Comment by Aymkdn** [comment]
Faut dire `allume la télé` pour ça :-)

`allume la Freebox` c'est juste pour arriver sur le home. Je t'invite à relire [la documentation](https://github.com/Aymkdn/assistant-plugins/blob/master/assistant-freebox/README.md).

**Comment by nusmiaf** [comment]
enfin je voulais dire que la commande qui soit envoyer  = power + ok   
pour que j'ai directement la télévision sur une chaine quelconque et non sur la page d'accueil 
tu voit ?

**Comment by nusmiaf** [comment]
ok ne pas tenir compte de ce que je viens de dire plus haut  ( sorry )
tellement axé sur la box que je n'ai pas vue le reste.....

ça fonctionne  bien avec allume la télé via  la box

en tous cas merci beaucoup pour ton aide et pour ton plugin

**Comment by Aymkdn** [comment]
Salut. Pour info je viens d'annoncer la v2 : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0

J'ai également fait 2 vidéos pour aider à l'installation :-)
