### ISSUE TITLE
Problème lors de l'installation d'assistant-plugins

### ISSUE THREAD

**Issue by ThoomZ** [Aymkdn/assistant-plugins#20]
En suivant les instructions, je tape "npm install" avec une console ouvert depuis le dossier "assistant-plugins-master"

Voici ce que m'affiche mon Raspberry :

pi@raspberrypi:~/Desktop/assistant-plugins-master $ npm install
npm WARN package.json assistant-plugins@1.0.0 No repository field.
 
> websocket@1.0.25 install /home/pi/Desktop/assistant-plugins-master/node_modules/pushbullet/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

promise@8.0.1 node_modules/promise
└── asap@2.0.6

grunt-contrib-copy@1.0.0 node_modules/grunt-contrib-copy
├── file-sync-cmp@0.1.1
└── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)

grunt-notify@0.4.5 node_modules/grunt-notify
├── stack-parser@0.0.1
├── semver@5.4.1
└── which@1.3.0 (isexe@2.0.0)

google-tts-api@0.0.2 node_modules/google-tts-api
└── isomorphic-fetch@2.2.1 (whatwg-fetch@2.0.3, node-fetch@1.7.3)

request@2.83.0 node_modules/request
├── aws-sign2@0.7.0
├── oauth-sign@0.8.2
├── forever-agent@0.6.1
├── tunnel-agent@0.6.0
├── is-typedarray@1.0.0
├── caseless@0.12.0
├── safe-buffer@5.1.1
├── stringstream@0.0.5
├── aws4@1.6.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.1
├── performance-now@2.1.0
├── uuid@3.1.0
├── qs@6.5.1
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.17 (mime-db@1.30.0)
├── tough-cookie@2.3.3 (punycode@1.4.1)
├── form-data@2.3.1 (asynckit@0.4.0)
├── hawk@6.0.2 (boom@4.3.1, sntp@2.1.0, hoek@4.2.0, cryptiles@3.1.2)
├── http-signature@1.2.0 (assert-plus@1.0.0, jsprim@1.4.1, sshpk@1.13.1)
└── har-validator@5.0.3 (har-schema@2.0.0, ajv@5.4.0)

pushbullet@2.1.0 node_modules/pushbullet
├── clone@2.1.1
├── mime@1.5.0
├── node-forge@0.7.1
└── websocket@1.0.25 (yaeti@0.0.6, typedarray-to-buffer@3.1.2, debug@2.6.9, nan@2.8.0)

castv2-client@1.2.0 node_modules/castv2-client
├── debug@2.6.9 (ms@2.0.0)
└── castv2@0.1.9 (protobufjs@3.8.2)

grunt-replace@1.0.1 node_modules/grunt-replace
├── file-sync-cmp@0.1.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── lodash@4.17.4
└── applause@1.2.2 (cson-parser@1.3.5, js-yaml@3.10.0, lodash@3.10.1)

grunt@1.0.1 node_modules/grunt
├── grunt-known-options@1.1.0
├── eventemitter2@0.4.14
├── path-is-absolute@1.0.1
├── rimraf@2.2.8
├── exit@0.1.2
├── nopt@3.0.6 (abbrev@1.1.1)
├── iconv-lite@0.4.19
├── coffee-script@1.10.0
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── findup-sync@0.3.0 (glob@5.0.15)
├── glob@7.0.6 (inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0)
├── grunt-cli@1.2.0 (resolve@1.1.7)
├── js-yaml@3.5.5 (esprima@2.7.3, argparse@1.0.9)
├── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)
├── grunt-legacy-util@1.0.0 (async@1.5.2, getobject@0.1.0, hooker@0.2.3, which@1.2.14, underscore.string@3.2.3, lodash@4.3.0)
└── grunt-legacy-log@1.0.0 (hooker@0.2.3, colors@1.1.2, underscore.string@3.2.3, lodash@3.10.1, grunt-legacy-log-utils@1.0.0)

request-promise-native@1.0.5 node_modules/request-promise-native
├── stealthy-require@1.1.1
├── tough-cookie@2.3.3 (punycode@1.4.1)
└── request-promise-core@1.1.1 (lodash@4.17.4)

grunt-contrib-watch@1.0.0 node_modules/grunt-contrib-watch
├── async@1.5.2
├── tiny-lr@0.2.1 (parseurl@1.3.2, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── lodash@3.10.1
└── gaze@1.1.2 (globule@1.2.0)**

Ensuite je tape "node index.js" 
Mais rien ne se passe 

Débutant avec mon Raspberry et ayant peu de connaissance sur la console de Linux, je demande de l'aide
Merci d'avance !

**Comment by Aymkdn** [comment]
As-tu installé Node récemment ou utilises-tu une version ancienne ?

Quand tu lances `node index.js` tu n'as rien ? Mais, genr, absolument rien du tout qui apparaît ?? Aucun message ?

**Comment by ThoomZ** [comment]
Pour Node j'ai tout réinstaller et j'ai tout vérifier en terme de mise a jour
Et Oui quand je tape "node index.js" sur la ligne 
pi@raspberrypi:~/Desktop/assistant-plugins-master $ sa me r'affiche la ligne pi@raspberrypi:~/Desktop/assistant-plugins-master $

**Comment by ThoomZ** [comment]
Il ne se passe rien

**Comment by ThoomZ** [comment]
En faisant "nodejs -v"
Version 4.8.2

**Comment by Aymkdn** [comment]
La version actuelle de Node est la 8.9.1...

**Comment by ThoomZ** [comment]
Ah oui effectivement 
Je vais mettre a jour puis je re si sa ne va pas

**Comment by ThoomZ** [comment]
C'est tout bon quelques manip en enlevant Nodejs et en le remettant et puis le programme se lance correctement
Merci pour l'aide

**Comment by fred3b12** [comment]
Bonjour je rebondi sur ce poste car j'ai sensiblement la même chose avec mon NAS Syno  DS213Air :
Version installée de node JS :  0.10.48 (dernière version disponible via l'installeur.)
Par contre pour moi il ce passe la chose suivante lorsque je tape "node index.js" j'ai le message :
<<
fred3b12@JARVIS:/volume1/Download/assistant-plugins-master$ sudo node index.js
Password:

/volume1/Download/assistant-plugins-master/index.js:47
              let plugin = commande.split("_")[0];
                  ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
>>

En ligne 47, j'ai ceci 
let plugin = commande.split("_")[0];

Merci de votre aide.

**Comment by Aymkdn** [comment]
0.10.48 c'est beaucoup trop vieux... Tu devrais installer la dernière version.

Tu peux essayer de remplacer `let` par `var` sur la ligne indiquée, mais avec une si vieille version de Node j'ai du mal à croire que quoique ce soit fonctionne...

**Comment by fred3b12** [comment]
Ok merci,
Je reviens dès que j'ai trouvé comment installer manuellement ceci : 
node-v8.9.1-linux-arm64 ...  car je n'ai pas trouvé de .spk  (d'ici là, si quelqu'un à l'info, je prends...)

**Comment by fred3b12** [comment]
Verdict, J'ai un processeur Marvell Kirkwood mv6282 ARM, je ne trouve pas de version node plus ressente pour cette architecture :( 👎  spk ici pour ceux qui auraient besoin ;)
https://archive.synology.com/download/Package/spk/Node.js/ 
Frustré, mes investigations vont s'arrêter là, sauf si quelqu’un à une piste pour moi et autres possesseurs de NAS Synology DS213
Merci d'avances.

**Comment by Aymkdn** [comment]
Sur le site de Synology on trouve ça : https://www.synology.com/fr-fr/dsm/packages/Node_js_v8

**Comment by fred3b12** [comment]
Merci mais c'est pas de bol;  j'ai le 213Air, il ne figure pas dans la liste de compatibilité :( seul le213J est compatible car il a une archi : Marvell Armada 370 88F6707  c'est les boules...

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une documentation dédiée pour l'installation sur RaspberryPi : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

Pas sûr que ça puisse t'aider, mais bon ;-)

**Comment by Aymkdn** [comment]
@fred3b12 Pour info j'ai fait une documentation dédiée à Synology : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-Synology

Si jamais tu peux regarder et me donner tes commentaires !

Si ça ne fonctionne toujours pas pour toi, ouvre un nouvel issue et j'ai une autre option à te proposer !

**Comment by fred3b12** [comment]
Ok je regarde ça des que j'ai un moment...
