### ISSUE TITLE
Notifier et Raspberry Pi

### ISSUE THREAD

**Issue by Ybbet** [Aymkdn/assistant-plugins#200]
bonjour,

J'utilise assistant-plugins sur un Raspberry Pi. Ayant une Freebox, j'ai installé assistant-freebox. Avec ce dernier, notifier envoie les bonnes infos à mon Google Home mini.

Pour des besoins très précis, j'ai créé un applet sur IFTTT où le _"this"_ est "_tous les jours à XXhXX"_ et le _"that"_ est un "Push a note". Le titre est `Assistant` et le message `notifier_{salon} Mon message à annoncer`

Sur le Raspberry, je peux voir dans les logs (cf. `pm2 monit`) que la notification est bien reçue par notifier. Malheureusement, aucun son ne sort du Google Home.

Pour tester plus aisément, j'ai installé `assistant-plugins` sur mon Mac (Mojave) avec les mêmes réglages que sur le Raspberry Pi. Et là, pas de soucis. La notification est bien reçue, mon Google Home énonce bien mon message.

N'y aurait-il pas un souci sur le Raspberry Pi ? Une particularité ?

**Comment by Aymkdn** [comment]
Quelques pistes :
- es-tu sûr d'avoir utilisé la même configuration sur les deux machines ?
- utilises-tu la voix par défaut ou celle d'IBM ? 
- as-tu mis à jour récemment ? Car la semaine dernière Google a modifié son api et il faut mettre à jour le plugin pour que ça refonctionne 
- si tu *ping* l'IP du Google Home depuis ton RPi est-ce que ça fonctionne ?

**Comment by Ybbet** [comment]
J'ai la même configuration. J'ai réalisé à 2 minutes d'intervalle un `npm install`.
J'utilise la voix par défaut.
Quand je fais un ping depuis le raspberry vers mon Google Home, j'ai bien une réponse.

La seule différence est le ping translate.google.com. Sur le Raspberry j'ai par10s33-in-x0e.1e100.net. Et sur le mac, j'ai une adresse IP changeante (selon la charge serveur certainement).

Bon, je tente un `npm update` et je verrai ce que ça donne.
