### ISSUE TITLE
Erreur sur l'applet éteint la freebox 

### ISSUE THREAD

**Issue by Romain91610** [Aymkdn/assistant-plugins#201]
Bonjour, 
Je commence tout juste à utiliser les applets, celle pour démarrer la freebox fonctionne correctement, par contre quand je lance la commande pour l'éteindre l'écran passe au noir quelques secondes et l'interface de la tv s'affiche de nouveau, j'en comprends pas d'où vient l'erreur. 

Romain

**Comment by Aymkdn** [comment]
La commande pour éteindre fait la même chose que si tu appuies sur le bouton on/off de ta télécommande de la Freebox.

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
