### ISSUE TITLE
Freebox

### ISSUE THREAD

**Issue by Maxime02100** [Aymkdn/assistant-plugins#202]
Bonjour mon google home transmet ma demande '' Allume la freebox " il me répond " j'allume la freebox" mais le soucis c'est que rien ne se passe .. 
Donc j'aimerais savoir si vous pouvez m'aider car je suis un "débutant"

**Comment by Maxime02100** [comment]
![capture d ecran 6](https://user-images.githubusercontent.com/45971400/50159588-593e7380-02d7-11e9-9e44-da6becd3d078.png)
![capture d ecran 7](https://user-images.githubusercontent.com/45971400/50159592-5b083700-02d7-11e9-9c8b-d8166b92a3df.png)

**Comment by Aymkdn** [comment]
Salut,

Est-ce que tu peux regarder le 1) qui est décrit sur cette page stp : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

Et dis moi ce que tu trouves par rapport à ces indications.

**Comment by Aymkdn** [comment]
Ce n'est pas la seule chose à regarder... j'y parle de https://www.pushbullet.com/#following/ et https://ifttt.com/activity par exemple

**Comment by Maxime02100** [comment]
![capture d ecran 8](https://user-images.githubusercontent.com/45971400/50160976-d15a6880-02da-11e9-9be6-6bd8546122f9.png)
![capture d ecran 9](https://user-images.githubusercontent.com/45971400/50160977-d3242c00-02da-11e9-8980-1a215b643182.png)

la aussi je ne voit pas de problème comme dans vos instructions

**Comment by Aymkdn** [comment]
En effet, tout semble correct, pourtant l'information n'arrive pas jusqu'au programme....

N'aurais-tu pas un firewall ou antivirus qui bloquerait la connexion sur ton ordinateur ? Hormis ça j'avoue que je ne vois pas pourquoi ça ne fonctionne pas...

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
