### ISSUE TITLE
Freebox & Alexa

### ISSUE THREAD

**Issue by maxime15** [Aymkdn/assistant-plugins#203]
Bonjour,

Tout d'abord merci pour ce boulot immense, je découvre et j'ai tout installé pour Alexa sauf pour la plupart du temps, les commandes ne s'éxécutent pas correctement. Exemple quand je change de chaine (j'ai créé des applets pour changer de chaine), je lui demande de mettre bfm, il me met la 155 ou parfois la 5 ou parfois la 1. On dirait qu'on reste appuyer sur la télécommande et au final je ne tombe pas sur la bonne chaîne. J'ai essayé les commandes de zappe long, zappe avec le numéro, zappe avec le nom de la chaine mais rien y fait. Idem pour l'allumage, éteindre la freebox etc, l'envoie de la commande se fait bien mais au final ça bug les 3/4 du temps. Peut-être une mAj ? J'ai suivi les deux tutos via tes vidéos youtube et le site pour les liens et les explications.

Merci :)

**Comment by Aymkdn** [comment]
Est-ce que tu n'aurais pas le programme `assistant-plugins` qui est lancé plusieurs fois sur ton ordinateur ? Qui causerait l'envoi de plusieurs fois la même commande, et donc ce genre de réaction...

**Comment by maxime15** [comment]
Tout à fait c'était ça... j'ai pas réfléchi. Merci !
Du coup on est obligé d'avoir la commande et l'ordinateur d'allumé pour que cela fonctionne on est d'accord ?

**Comment by Aymkdn** [comment]
> Du coup on est obligé d'avoir la commande et l'ordinateur d'allumé pour que cela fonctionne on est d'accord ?

Oui, tout à fait.
