### ISSUE TITLE
Connexion Freebox serveur

### ISSUE THREAD

**Issue by R113** [Aymkdn/assistant-plugins#204]
Bonjour je n'ai pas le message approuver le plugin en allant sur l 'ecran lcd de votre freebox server et en utilisant la fleche de droite sur celui ci.
Merci
![image](https://user-images.githubusercontent.com/46137878/50426185-88308880-0887-11e9-969a-7867e26a4c1f.png)

**Comment by Aymkdn** [comment]
Tu as bien une Freebox Révolution ?

Ton disque dur de la Freebox n'est pas plein ?

Tu as bien autorisé les applications? Pour cela, Connecte toi sur ta Freebox Serveur via http://mafreebox.freebox.fr/login.php puis va dans :
**Paramètres de la Freebox > Mode Simplifié > Gestion des accès**

Puis dans la zone "Applications" tu dois cocher la case **Permettre les nouvelles demandes d'association**

**Comment by R113** [comment]
Oui j ai bien une Freebox révolution.
Non mon disque dur n 'est pas plein.
Par contre je n'ai pas paramétrer la Freebox serveur, mais je n arrive pas a aller sur le lien.

**Comment by Aymkdn** [comment]
Tu dois être connecté à ton réseau WiFi de la Freebox.... Essaie en https peut-être ? https://mafreebox.freebox.fr/

**Comment by R113** [comment]
Je suis obligé d’être en wifi? je suis connecté directement en câble ethernet.

**Comment by Aymkdn** [comment]
Non, peu importe, wifi ou Ethernet.

Si ça ne marche pas, essaie l'IP de ta Freebox directement... Dans ton navigateur Web.

**Comment by R113** [comment]
Je voulais pas dire ça c'est le site qui a marché, sinon j'ai toujours le même problème.

**Comment by Aymkdn** [comment]
L'IP a marché ? Alors essaie de modifier le fichier de configuration de `assistant-plugins` pour y mettre `server_ip:"192.168.0.254"`

Voir https://aymkdn.github.io/assistant-plugins/?plugin=freebox#configuration

Et retente de lancer `assistant-plugins`

Si ça ne marche toujours pas, essaie de mettre `check_player_on:false` dans le fichier de configuration.

Si rien ne marche, il va falloir que je t'aide à debugger... Mais là je suis dans un train, donc pas avant demain.

**Comment by R113** [comment]
A quel endroit il faut que je mette server_ip:"192.168.0.254
![image](https://user-images.githubusercontent.com/46137878/50426438-f0826880-088d-11e9-99f8-186abe307c4f.png)

**Comment by Aymkdn** [comment]
Tu mets une virgule après `"box_to_control":"hd1" ` puis tu ajoutes ce que je t'ai dit sur la ligne suivante.

**Comment by R113** [comment]
C'est bon ca marché en mettant server ip.
merci c'est tres sympa de m avoir aidé

**Comment by Aymkdn** [comment]
Ok cool!

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
