### ISSUE TITLE
a l'aide

### ISSUE THREAD

**Issue by matttttttttttttttttttttts** [Aymkdn/assistant-plugins#205]
bonjour, je pense avoir tout installer mais cela ne fonctionne pas 

![node](https://user-images.githubusercontent.com/46222291/50516763-fa35e700-0aac-11e9-86dc-58cc86424237.png)

en allant  https://www.pushbullet.com/#following/ puis dans le canal IFTTT. je ne vois pas les bulles

![pushbullet](https://user-images.githubusercontent.com/46222291/50516792-23567780-0aad-11e9-84c5-130a70ec3189.png)

je suis aller sur  https://ifttt.com/activity pour regarder si tu as des erreurs.

![ifttt](https://user-images.githubusercontent.com/46222291/50516814-3b2dfb80-0aad-11e9-8eb8-563b25bc9f48.png)

apparemment non
 je sui_s aller sur  https://ifttt.com/services/pushbullet/settings puis cliquer sur Edit pour approuver une nouvelle fois. j'ai aussi tenter de Disconnect le service puis le réactiver.

je ne sais plus quoi faire

**Comment by Aymkdn** [comment]
Quand tu lances un ordre à Alexa, est-ce qu'elle te répond ?

Qu'as-tu dans https://ifttt.com/activity ?

**Comment by Aymkdn** [comment]
Tu lui dis quoi à Alexa ? Il faut dire un truc du genre "Alexa déclenche allume la Freebox"

Alexa a besoin du mot clé "déclenche" pour que ça fonctionne (ouais je sais c'est nul.... Perso j'utilise le Google Home ^^)

**Comment by matttttttttttttttttttttts** [comment]
ah merci
forcement je disais pas déclenche ^^
oui c'est nul lol
avec la venue de la freebox delta y a bien un développeur qui va nous pondre autre chose ^^
un grand merci pour ton tuto en tout cas
j'ai d’abord voulu l'installer sur mon syno, mais impossible, le pc fera bien l'affaire
bonne fin d'année

**Comment by Aymkdn** [comment]
Pour la Delta y'a déjà un assistant intégré qui se déclenche avec "OK Freebox" et qui permet de faire la même chose (de ce que j'ai compris en tout cas)

**Comment by matttttttttttttttttttttts** [comment]
y a aussi un alexa integré

**Comment by matttttttttttttttttttttts** [comment]
comment on fait pour créer les autres chaine ?

**Comment by Aymkdn** [comment]
Tout est assez bien expliqué sur le site https://aymkdn.github.io/assistant-plugins/?plugin=freebox

**Comment by matttttttttttttttttttttts** [comment]
merci pour tout ;)
