### ISSUE TITLE
Utiliser notifier dans assistant_launch

### ISSUE THREAD

**Issue by superiuspi** [Aymkdn/assistant-plugins#207]
Bonjour,
comment peux-t-on intégrer assistant notifier dans le plugin  launch?
merci pour votre aide

**Comment by Aymkdn** [comment]
Pour mettre à jour :
- arrête assistant-plugins 
 - tape `npm update`

Et c'est tout.

**Comment by superiuspi** [comment]
J'ai essayé mais cela ne fonctionne pas sur mon Pizéro sur lequel est installé nodejs .J'ai un message sommaire du style Action arrêtée .
Mais j'ai re-testé ce matin et cela semble avoir fonctionné ... Par contre aucune action visible , je lance la commande et au bout d'un petit moment ca rends la main sans message ... 
Comment vérifier la version en cours d'assitant -plugins ?
quand je fait un display de package.json j'ai:
 "name": "assistant-plugins-project",
  "version": "2.0.0",

**Comment by Aymkdn** [comment]
il suffit de le lancer : 
```
D:\assistant-plugins>node index.js
[assistant] Assistant v2.0.7 : Chargement en cours...   <---- ICI c'est la v2.0.7
[assistant] 9 plugins trouvés.
[assistant] Chargement du plugin 'bluetooth' (v1.2.2)
[assistant-bluetooth] Plugin chargé et prêt.
```

**Comment by superiuspi** [comment]
OK donc je confirme je suis pas à jour ... 
Quant je lance npm update sous assistant plugins j'ai un message : Processus arrêté
J'ai résolu mon problème en re-faisant un installe à blanc de assistant plugin puis l'update et ensuite l'ajout des plugins freebox, launch etc ...
Merci pour ton aide . Je vais maintenant tester l'utilisation en ligne de commande .
