### ISSUE TITLE
Bug plugin-assistant

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-plugins#208]
Bonjour,
je viens de constater le problème suivant.

1) je lance NodeJS
2) je simule une panne internet (coupure réseau).
3) je rétablis le réseau
4) je donne un ordre à la google Home (IFTTT puis pushbullet)

et je constate que NodeJS n'écoute plus le pushbullet......
il faut relancer le nodeJS...

Constatez-vous le même problème ?
Peut on faire un script qui détecte la coupure réseau/internet et relance le système NodeJS ?

Cordialement.

**Comment by rick443** [comment]
Merci

**Comment by Aymkdn** [comment]
J'ai du mal à reproduire cela. Comment simules-tu une panne réseau ? J'ai essayé sur mon ordi portable en coupant le Wifi puis en le remettant, et le programme continue à écouter les nouvelles commandes.

**Comment by Aymkdn** [comment]
Voilà, je viens de publier la version 2.0.8 qui reconnecte le flux en cas de déconnexion. Je t'invite donc à mettre à jour.

Concernant PushBullet, le système marche dans le sens inverse : c'est IFTTT qui envoie des notifications vers PushBullet, et non l'inverse. Donc ça n'utilise pas ton crédit. En l'occurrence la limite de 100 correspond plutôt à des SMS ou similaires à priori. En tout cas, je l'utilise intensivement depuis plusieurs mois sans jamais avoir eu aucun soucis.

**Comment by rick443** [comment]
Super ! Merci bcp...
J'installe cela....et je te tiens informé de la stabilité de NodeJS.

Cdlt.
