### ISSUE TITLE
Erreur :EAI_AGAIN sur pushbullet

### ISSUE THREAD

**Issue by ZatchBell68** [Aymkdn/assistant-plugins#209]
Bonjour depuis quelque jour j'ai cette erreur qui empeche le plugin de fonctionner

```
Erreur de connexion avec PushBullet:  { Error: getaddrinfo EAI_AGAIN stream.pushbullet.com stream.pushbullet.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: 443 }
```

Une personne avait le même problème mais il n'y a pas eu de réponse a la correction de cette erreur.

J'ai déjà ping pushbullet et j'ai aucun problème, j'ai égalemetn reset les token et ajouté un nouveau token mais pareil pas de connexion.

Merci

**Comment by Aymkdn** [comment]
> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error

Je pencherais vers un problème avec ton serveur DNS ou ta connexion internet...

Cela arrive de façon aléatoire quand le programme est lancé (genre au bout d'un moment le programme meurt et retourne cette erreur) ? Ou bien dès que tu le lances ça indique ça ?

**Comment by ZatchBell68** [comment]
Des que je le lance j'ai ce problème, j'ai déjà redemarré mon serveur plusieurs fois et j'ai jeedom dessus et j'arrive a accéder de l'intérieur comme de l’extérieur.

**Comment by ZatchBell68** [comment]
Super merci je vais regarder ça de suite avec sleep.
Problème réglé merci de ton aide :)
