### ISSUE TITLE
connection google homme / sarah / liveboxtv

### ISSUE THREAD

**Issue by dsuper1973** [Aymkdn/assistant-plugins#21]
bonjour à tous ,

Alors voici mon probleme , je penses sincerement a un soucis de mauvaise adresse url dans le ifttt qui part vers mon server nobejs .
la commande fonctionne bien , mon google home reponds et j'ai un message d erreur dans mon serveur , ce qui veut dire que la commande part et arrive à Sarah.
Mais je ne sais pas traduire et ecrire le dialogue jason.

voici mon message : (recopier , impossible de le copier)

error:invalid json
at objet.export.error (E/SARAH1/ExpressJS/nobe-modules/express/nobe-modules/connect/lib/utils.js:44:13)
at incomingMessage.anonymous(E/SARAH1/ExpressJS/nobe-modules/express/nobe-modules/connect/lib/middeware/json.js:68:73)
at incomingMessage.EventEmetteur.emit(event.js:92:17)
at-stream-readable.js:910.16
at proces.tickcaliback(nobe.js:415.13).

voici mon ifttt : (je ne peux pas faire de copier coller ou capture écran ?) 

Google assistant:

met sur  $

Webhnoks:

http://xxxxx-xxxxx.dtdns.net:8080/out.action._attributes.uri="http://127.0.0.1:8080/sarah/liveboxtv" {{TextField}}

get

Application/Jason

Merci de ton aide

a+
cedric

**Comment by Aymkdn** [comment]
Oulala... De quoi tu parles ?? Ce projet n'a aucun rapport avec Sarah, ni avec la livebox... Je pense que tu t'es trompé de projet ^^

Ce projet est avant tout pour la Freebox et tout est expliqué là : https://github.com/Aymkdn/assistant-plugins/blob/master/README.md

**Comment by Aymkdn** [comment]
Je viens de relire ce que tu as dit sur Google+

Mais j'ai du mal à voir comment tu peux garder Sarah et utiliser assistant-plugins... Surtout que tu n'as pas l'air de t'y connaître, donc ça va être compliqué pour toi. 

Tu fais ça pour contrôler la livebox ? Si oui, ça ne devrait pas être compliqué de faire un plugin dédié pour la livebox (le problème est que je n'ai pas de livebox donc pour tester c'est compliqué ^^). S'il existe un plugin Sarah pour livebox je peux regarder à l'occasion pour l'adapter...

**Comment by dsuper1973** [comment]
salut

oui , le soucis de la livebox c'est que tu ne peux pas la contrôler directement avec le port , en ip local tout fonctionne et bien sur avec Sarah (il y a un plugin liveboxtv dans le store) , mais comme google home passe en extérieur je dois trouver une solution pour avoir un pont entre google et Sarah. chose faite puisque je vois que le serveur Sarah réagis a la demande , mais il est vraie que je ne maîtrise pas du tout le language Jason .
donc l’idée serait d'utiliser Sarah comme un serveur proxy , puisque mon plugin livebox fonctionne .
j’espère avoir était claire !! 

a+
cedric

**Comment by Aymkdn** [comment]
Quand j'ai le temps je regarderai pour faire un plugin pour la livebox et tu pourrais être le testeur du coup.

**Comment by dsuper1973** [comment]
Ok pas de soucis merci J'ai cocouplé ier la chromecast avec google home .C'est assez bluffant de balancer la music et youtube sur la télé avec la voie .C'est dommage que orange ne laisse pas le couplage avec google home .


Envoyé de mon Galaxy S8+ Orange
-------- Message d'origine --------De : Aymeric <notifications@github.com> Date : 25/11/2017  10:40  (GMT+01:00) À : Aymkdn/assistant-plugins <assistant-plugins@noreply.github.com> Cc : dsuper1973 <cedric.guelle@free.fr>, Author <author@noreply.github.com> Objet : Re: [Aymkdn/assistant-plugins] connection google homme / sarah /
  liveboxtv (#21) 
Quand j'ai le temps je regarderai pour faire un plugin pour la livebox et tu pourrais être le testeur du coup.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Aymkdn/assistant-plugins","title":"Aymkdn/assistant-plugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Aymkdn/assistant-plugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Aymkdn in #21: Quand j'ai le temps je regarderai pour faire un plugin pour la livebox et tu pourrais être le testeur du coup. "}],"action":{"name":"View Issue","url":"https://github.com/Aymkdn/assistant-plugins/issues/21#issuecomment-346929965"}}}

**Comment by ABOATDev** [comment]
J'ai fais des commandes via assistant-launch pour contrôler son décodeur Orange (du basic : éteindre, allumer, monté le sons, descendre le son et changer de chaines) si sa t'intéresse ;)

**Comment by Aymkdn** [comment]
Merci @ABOATDev  ... en fait j'ai un code existant que je pourrais réutiliser, mais j'ai pas pris le temps de m'y pencher dessus encore. Mais si c'est le cas, je te contacterai pour effectuer des tests, si ça t'intéresse :-)

**Comment by ABOATDev** [comment]
Avec plaisir, voici mon [script](https://github.com/ABOATDev/Control-Google-Home/blob/master/DecodeurOrange.vbs) marche avec un applet seulement se qui est fort pratique mais seulement pour windows
Oui nécessite pas a me faire signe pour tester quoi que se soit.

**Comment by Aymkdn** [comment]
@ABOATDev j'ai commencé à créer un truc. Regarde là : https://github.com/Aymkdn/assistant-livebox/issues/1

Et on va discuter sur cet autre fil de discussion pour la suite :-)

Merci !

**Comment by Aymkdn** [comment]
Une version est maintenant disponible pour la Livebox : https://aymkdn.github.io/assistant-plugins/?plugin=livebox

Un grand merci à @ABOATDev  pour ses tests !!!
