### ISSUE TITLE
controle PC 

### ISSUE THREAD

**Issue by caq0450** [Aymkdn/assistant-plugins#210]
bonjour 
j'essaie d'utiliser Plugin "control-Windows-shutdown " (v1.0.0)"  ( voir plugin ci dessous)

[assistant-plugins.zip](https://github.com/Aymkdn/assistant-plugins/files/2763244/assistant-plugins.zip)

j'ai suivi à la lettre vos directives , tout se passe normalement à savoir requêtes IFTTT , pushbullet  , …
A ma demande sur google home "éteindre PC " , la réponse est là , je reçois les messages , mais la commande ne s'exécute pas !!!
[demande iftt.pdf](https://github.com/Aymkdn/assistant-plugins/files/2763273/demande.iftt.pdf)
[pushbullet.pdf](https://github.com/Aymkdn/assistant-plugins/files/2763300/pushbullet.pdf)
d'autre part est il possible de développer un plugin pour une box Numéricâble ?
quels sont les indispensables pour essayer ce développement ?
Merci à vous
Cordialement,

**Comment by caq0450** [comment]
Bonjour, 
Merci pour cette réponse rapide .
Ci-joint fichier START et Install  
Dois je être dans une directory spécifique pour l’assistant plugin ?
J’ai bien téléchargé node.js .. y a-t-il un service qui tourne en background … le problème peut venir de là ….
Merci
Cordialement, 
Nota : je vais regarder d’un peu plus près avec Numéricâble, c’est pas gagné ….
[install+start.pdf](https://github.com/Aymkdn/assistant-plugins/files/2763497/install%2Bstart.pdf)

**Comment by Aymkdn** [comment]
On n'est d'accord que tu laisses cette fenêtre ouverte quand tu lances une commande au Google Home ?
![capture](https://user-images.githubusercontent.com/946315/51240928-0e1e8b80-197d-11e9-9055-85ffc6c9ec8e.PNG)

Si oui, aucune commande n'est détectée, ce qui est étrange.
Dans https://www.pushbullet.com/#following/ tu as bien quelque chose qui ressemble à : 
![capture](https://user-images.githubusercontent.com/946315/51241131-740b1300-197d-11e9-8a62-7bac6435c290.PNG)

Si oui, peux-tu me montrer toute la page ?

**Comment by caq0450** [comment]
![image](https://user-images.githubusercontent.com/46722248/51241731-b1bc6b80-197e-11e9-9a62-ef0822b16c88.png)
![image](https://user-images.githubusercontent.com/46722248/51241802-de708300-197e-11e9-9996-60c411724213.png)
reste sur la commande , mais ne s'éteint pas .
il est vrai que le start.bat n'était pas actif !!! je vais le mettre dans le démarrage au chargement Windows 
rien dans le Following 
je te remercie

**Comment by caq0450** [comment]
![image](https://user-images.githubusercontent.com/46722248/51242600-aa965d00-1980-11e9-8d6a-7b288631f1df.png)
après vérif. j'ai bien message mais toujours pas arrêt  
merci

**Comment by Aymkdn** [comment]
Il a bien reçu la commande (puisqu'il indique `commande reçue`).

Alors, est-ce que tu peux tester avec un truc moins violent que le shutdown, par exemple couper le son de l'ordinateur : `control-windows_mute`, pour voir si cette commande fonctionne. Cela fonctionne ?

Ensuite, tu peux te rendre dans ce répertoire : 
`assistant-plugins\node_modules\assistant-control-windows\bin`

Puis dans la barre de navigation (comme indiqué ci-dessous) : 
![capture1](https://user-images.githubusercontent.com/946315/51242511-6e62fc80-1980-11e9-9e0c-24df6afcc47f.PNG)

Tape le mot `cmd` (comme ci-dessous) puis appuie sur la touche Entrée : 
![capture2](https://user-images.githubusercontent.com/946315/51242517-715ded00-1980-11e9-84be-3dd5b602b97e.PNG)

Cela va t'ouvrir une fenêtre de commande dans le répertoire en question. Dans cette fenêtre, tape : 
`nircmd.exe exitwin poweroff`
![capture](https://user-images.githubusercontent.com/946315/51242657-d0236680-1980-11e9-8232-44e37dc30b9f.PNG)

Et regarde ce qu'il se passe.

**Comment by caq0450** [comment]
re bonjour , 
je me suis absenté . 
j'ai trouvé le problème .
j'avais mis assistant_plugin dans E:\téléchargement temporaire 
l'accès à la directory ne se faisait pas sous dos 
Si mes souvenirs sont exacts , je pense qu'il ne faut pas d'espace ou bien le mettre entre " " ? 
j'ai déplacé la directory sous un autre lecteur .
je vous remercie pour votre aide .
je vais maintenant voir dans le bios si je dispose de la  fonction WOL (Wake On Lan) pour allumer PC
A bientôt

**Comment by caq0450** [comment]
bonjour, 
je reviens vers toi pour que tu m' éclaires sur l'erreur ci dessous . 
La commande éteindre mon ordinateur fonctionne très bien . 
Je souhaite donc rajouter d'autres commandes pour control-Windows .
Il me semble tout avoir fait dans l'ordre 
Merci
Cordialement, 
![image](https://user-images.githubusercontent.com/46722248/52132654-e6e3e180-263f-11e9-9839-57aca5316295.png)
![image](https://user-images.githubusercontent.com/46722248/52132802-40e4a700-2640-11e9-9c83-9a601dc3ed54.png)
![image](https://user-images.githubusercontent.com/46722248/52132831-53f77700-2640-11e9-89ce-2970554c5182.png)
![image](https://user-images.githubusercontent.com/46722248/52133000-c5cfc080-2640-11e9-944b-32eb7eb255ff.png)

**Comment by Aymkdn** [comment]
Tu as écrit `control-Windows` au lieu de `control-windows` (c'est sensible à la casse)

**Comment by caq0450** [comment]
bien vu !!!
En informatique , on bute toujours sur le plus facile !!!
A titre d'infos On ne peut pas passer de variable dans le Pushbullet ? 
Super pm2  qui tourne en arrière plan 
j'avais fait un script au démarrage Windows ,j'annule
![image](https://user-images.githubusercontent.com/46722248/52136242-e4858580-2647-11e9-9685-f8e55772857a.png)
Par contre , je voyais de suite l'erreur dans la fenêtre  de cmd . 
je pense qu'il me faut aller voir des  logs autrement (pm2 monit) . Où sont ils stockés ?
merci

**Comment by Aymkdn** [comment]
> A titre d'infos On ne peut pas passer de variable dans le Pushbullet ?

Que veux-tu dire ? Les paramètres tu les passes avec `control-windows_`. Par exemple, pour lancer Chrome : `control-windows_cmd exec max "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"`

> Par contre , je voyais de suite l'erreur dans la fenêtre de cmd .
> je pense qu'il me faut aller voir des logs autrement (pm2 monit) . Où sont ils stockés ?

Oui il faut utiliser `pm2 monit` pour voir en live les logs...

Pour voir les logs, je t'invite à regarder la documentation de `pm2` : https://pm2.io/doc/en/runtime/guide/log-management/
