### ISSUE TITLE
Assistant Control Windows10

### ISSUE THREAD

**Issue by alexgiraudi** [Aymkdn/assistant-plugins#212]

**Comment by alexgiraudi** [comment]
Bonjour, Apres le control de ma Freebox, je passe maintenant au control de mon PC WIN10. L'assitant est configuré et pushbullet & applet IFTTT ok.
Je tente de lancer Chrome dans ton tuto. je vois bien sur la console la commande être reue de pushbullet et le lancement de l'application Chrome, mais l'application ne se lance pas, j'ai essayé avec une autre application et cela faire pareil. 
Aurais tu une idée pour débugger plus loin ?
Merci pour ton aide

**Comment by Aymkdn** [comment]
Essaie de lancer la commande manuellement (cf ce commentaire https://github.com/Aymkdn/assistant-plugins/issues/210#issuecomment-454728106) pour voir si ça fonctionne déjà !

**Comment by Aymkdn** [comment]
> Y a t'il moyen de voir plus de log et voir le resultat de la commande ?

Non... 

Demain j'essaierai et je te dirai ce que ça donne chez moi cette commande.

**Comment by alexgiraudi** [comment]
çà marche c'est sympa !
je viens d'installer le pluggin Launcher et lui fait le boulot il lance bien les applications.
j'ai fait une nouvelle applet Shtutdon sur le plugin Control-windows et çà fait pareil il capture bien les commandes mais il n'execute pas correctement le pc ne s'éteint pas !
j'ai l'impression que ce plugin sur Windows 10 n'a pas les droits !

**Comment by Aymkdn** [comment]
Je viens de tester en passant par IFTTT et ça fonctionne chez moi (`control-windows_cmd exec max "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"`). J'ai Windows 10 64 bits Professionnel. Je n'ai pas d'anti-virus (à part celui intégré à Windows).

Donc je ne sais pas trop....

Après, si `launch` fonctionne tu peux toujours créer des scripts batch qui vont exécuter la commande nircmd voulue, ou carrément exécuter la commande native Windows.
