### ISSUE TITLE
Freebox, les actions Google home ne s’effectuent pas.

### ISSUE THREAD

**Issue by Lodoxx** [Aymkdn/assistant-plugins#217]
Bonjour,

pour piloter la Freebox v6 a la voix avec Google Home , j'ai suivi votre tuto:

https://www.youtube.com/watch?v=Gmt4tIPH_fk
https://www.youtube.com/watch?v=g-KuRk0oYSg&t=21s

J'ai aussi activé l'option "zappe sur....." je dis zappe sur M6, Google
me répond, ok je zappe sur M6", mais rien n' est fait. 
Quelque soit l’option que j'active, c'est pareil.

Je suis allé ici: https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

Sur le lien, j'ai tout vérifié, c'est ok,  il me restait la dernière solution, voir si IFTTT est bloqué par l'antivirus ou le par-feu, pour moi Windows. J'ai désactivé le deux. ça marche toujours pas, mon Google home effectue des actions dans le vent.

D'ou pourrait venir le problème ?

Merci d'avance.

**Comment by Aymkdn** [comment]
Qu'est-ce qui s'affiche dans ta console d'`assistant-plugins` ? 
La console ressemble à ça : 
![capture](https://user-images.githubusercontent.com/946315/52006345-2c7f9d80-24cc-11e9-9ceb-7189186d175a.PNG)

Peux-tu faire une capture d'écran et la mettre ici ?

**Comment by Aymkdn** [comment]
Et ensuite quand tu demandes une commande au Google Home, il n'y a rien qui apparaît de plus dans cette fenêtre ?

**Comment by Lodoxx** [comment]
Mes excuse, en fait, je ne savais pas qu'il fallait que cette fenêtre reste ouverte pour pouvoir exécuter les commandes. Merci, c'est ok ça fonctionne, mais pour certaines chaines ça ne fonctionne pas, exemple "zappe sur Bein Sports 1, Bein Sports 1" Comment faire pour ces chaines ?

Capture: https://www.noelshack.com/2019-05-6-1549104048-fbx-week-end.png

L'application doit resté ouverte en performance ? donc impossible de laisser le pc en veille ?

**Comment by Aymkdn** [comment]
L'application doit toujours rester ouverte en effet. Je travaille sur une version dans le cloud qui évitera ça pour ceux qui veulent juste contrôler la Freebox (j'ai bientôt fini le développement).

Concernant la chaîne, elles ne sont pas toutes reconnues / correctement reconnues. Dans ce cas il est mieux de dire "zappe sur la 128" (je ne connais pas le numéro de la chaîne en question, mais tu vois l'idée).

**Comment by Lodoxx** [comment]
Ok, ça marche  "zappe sur 31"
Cool pour la nouvelle version. Encore merci pour tout le travaille.

**Comment by Aymkdn** [comment]
Normalement faut dire "zappe sur LA 31" (en utilisant l'article "la"). Mais si ça marche, tant mieux !

**Comment by Lodoxx** [comment]
Oui, j'avais oublié, j'ai dit "la" S
ur 31, ça ne marche pas.

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
