### ISSUE TITLE
IFTTT n'envoye pas les assets à Puhbullet

### ISSUE THREAD

**Issue by MARGOProd** [Aymkdn/assistant-plugins#219]
Bonjour,

En avant tout merci et félicitation pour ton travail.

Malheureusement de mon coté je ne parviens pas à faire fonctionner ton plugin. Aucune erreur ne s'affiche dans mon terminal et pour cause, lorsque je le lance une commande ex : "OK google allume la freebox" il ne se passe rien.

Suite à la consultation de ta page d'aide j'ai regardé du coté de IFTTT qui me dit que mes asset sont correctement installées. Mais lorsque je vais sur l'interface PushBullet > following > IFTTT tout est vide.

J'ai bien essayé de ré-éditer la connexion et de me déconnecter mais rien ne change.

Aurais-je oublié une étape pour que le communication entre ces deux services se passent bien ?

Par avance merci de ton retour

Bien cordialement

**Comment by MARGOProd** [comment]
Hello.Merci pour ta réactivité !Suite au lancement de l'utilitaire update.bat  le problème s'est résolu.Très bonne idée le cloud je pense que tu vas pouvoir toucher un plus large public 😉Bon courage et encore une fois félicitation pour tout ce travail !P. S. Juste pour info ton dev. permet à mon grand père mal voyant de changer de chaîne sans se galèrer avec sa télécommande ! Donc merci pour lui ! Le 31 janv. 2019 16:29, Aymeric <notifications@github.com> a écrit :Salut,

Question sûrement bête, mais tu utilises bien le même compte Pushbullet entre là où tu regardes dans le navigateur, là où tu es connecté avec IFTTT, et la clé mise dans assistant-plugins ? À ce stade, ce serait la seule explication: deux comptes différents qui sont utilisés.

Je viens de tester et la connexion entre IFTTT et PushBulet fonctionne, donc on peut à priori éliminer un problème temporaire entre les deux services...

Dans https://ifttt.com/activity tu vois bien l'appel de tes applets, avec un "Applet Ran" ?

Pour info je suis en train de travailler sur une version dans le cloud du plugin Freebox qui évitera aux gens de devoir installer tout ce bazar juste pour commander la Freebox !

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1

**Comment by MARGOProd** [comment]
Hello! Je ne pourrais pas le tester avec deux semaines mais si tu peux patienter ça m'intéresse grandement ! 😊Merci pour ton taffLe 6 févr. 2019 20:10, Aymeric <notifications@github.com> a écrit :Pour info, j'ai créé une version super simplifiée de assistant-freebox qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : Aymkdn/assistant-freebox-cloud#1
