### ISSUE TITLE
Assistant Freebox en erreur sur Synology

### ISSUE THREAD

**Issue by alexgiraudi** [Aymkdn/assistant-plugins#220]
Bonjour, quand je lance node index.js et j'ai l'erreur suivante au lancement ?
![capture](https://user-images.githubusercontent.com/26151578/52074040-47fcae00-2589-11e9-846e-f17d48153b62.PNG)

j'ai effectué à nouveau l'installation depuis le début. mais l'erreur persiste.
Alors que jusqu'à présente cela fonctionnait bien 

Bien cordialement

**Comment by Aymkdn** [comment]
Je pense que ta version de `node` est trop ancienne...

Du coup, pour éviter ce problème, je viens d'apporter une correction avec la version v2.0.12.

Je t'invite donc à taper : 
`npm update` 

Tu devrais alors voir :
> D:\assistant-plugins>npm update
> \+ assistant-plugins@2.0.12

Puis tu peux faire `node index.js`

**Comment by alexgiraudi** [comment]
Merci pour ta réactivité 
Mais je viens de faire le npm update mais c'est toujours la version 2.0.11 en cours ! donc du coup j'ai la même erreur.

**Comment by Aymkdn** [comment]
Essaie : `npm install assistant-plugins@2.0.12`

Si ça ne veut toujours pas le mettre à jour, tu peux simplement remplacer le contenu de `node_modules/assistant-plugins/index.js` par https://raw.githubusercontent.com/Aymkdn/assistant-plugins/master/index.js ... ou alors réessayer dans un moment la mise à jour !

**Comment by alexgiraudi** [comment]
Eh eh C'est perfect ! t'es un chef Merci à toi

**Comment by alexgiraudi** [comment]
Merci Aymkdn

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
