### ISSUE TITLE
plugin freebox - la tv s'allume avec la telecommande mais pas via Google Home

### ISSUE THREAD

**Issue by AbouArez** [Aymkdn/assistant-plugins#221]
Bonjour,

Tout d'abord, un grand merci pour le partage de ce code !

L'unique soucis est le suivant : lorsque j'utilise la commande google home 'allume la freebox', le player demarre (le voyant passe bien du rouge au bleu), mais, la tv reste en mode repos.

Si j'utilise la télécommande de la freebox : le player, et, la tv demarre.

![capture - assistant](https://user-images.githubusercontent.com/47090804/52119024-21d21f00-2618-11e9-8940-be872677a6c8.JPG)

Une idée pourquoi la télécommande démarre la tv, mais, pas le google home ?

Encore une fois, merci !

**Comment by Aymkdn** [comment]
Donc si tu allumes ta TV avec la télécommande de la TV, tu vois bien que la Freebox a été allumée ?

Je ne sais pas... Avec le HDMI CEC activé, normalement ça doit t'allumer la TV en même temps que la Freebox (c'est le comportement chez moi et chez tout le monde). Donc j'avoue que là je coince...

**Comment by AbouArez** [comment]
En effet, si j'allumes la TV avec la télécommande de la TV, la Freebox s'allume.

De plus, si la TV est sur une autre source (HDMI de la console de jeux), et, je dis 'ok google, allume la Freebox', il allume la Freebox, et, bascule sur la source HDMI de la Freebox...

Je me demandais s'il existait une autre commande que key=power pour allumer la Freebox ?
Sais-tu quelle est la commande utilisée par la télécommande ?

Sinon, pas de soucis... car tout le reste fonctionne parfaitement !

**Comment by Aymkdn** [comment]
"power" est l'unique commande, et comme je t'ai dit, ça fonctionne chez les autres :-/

Je ferme ton issue du coup !

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
