### ISSUE TITLE
Erreur sur le host

### ISSUE THREAD

**Issue by Ybbet** [Aymkdn/assistant-plugins#222]
Bonjour,

Avec assistant-plugins@2.0.11 et assistant-notifier@2.1.6, pm2@3.2.9, node@9.9.0, npm@6.5.0, sur un Raspberry Pi 3, j'ai l'erreur suivante : 
```bash
1|assistan |     at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:78:15
1|assistan |     at Array.forEach (<anonymous>)
1|assistan | (node:2768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
1|assistan | (node:2768) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received type function
1|assistan |     at lookupAndConnect (net.js:1026:13)
1|assistan |     at TLSSocket.Socket.connect (net.js:1001:5)
1|assistan |     at Object.exports.connect (_tls_wrap.js:1144:12)
1|assistan |     at Client.connect (/home/pi/assistant-plugins/node_modules/castv2/lib/client.js:35:21)
1|assistan |     at PlatformSender.connect (/home/pi/assistant-plugins/node_modules/castv2-client/lib/senders/platform.js:27:15)
1|assistan |     at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:33:13
1|assistan |     at new Promise (<anonymous>)
1|assistan |     at AssistantNotifier.prom (/home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:28:10)
1|assistan |     at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:78:15
1|assistan |     at Array.forEach (<anonymous>)
1|assistan | (node:2768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

Ma configuration pour notifier est : 
```json
    "notifier": {
      "host": {
        "salon": "192.168.X.XX",
        "chambre garcons": "192.168.Y.YY"
      }
    }
```
Et du fait de l'erreur, notifier ne fonctionne plus. J'ai l'impression que depuis la v2.1.6, quelque chose a été cassée. 
J'ai également le plugin assistant-freebox et je n'ai pas de problème de fonctionnement.

Une idée du souci ?

Amicalement,

**Comment by Aymkdn** [comment]
Aucun problème chez moi...

Question stupide, mais tu as bien des nombres à la place des `X` dans `192.168.X.XX` ? ^^

**Comment by Aymkdn** [comment]
Si oui, ce que tu peux essayer de faire (afin de débugguer), entre ces deux lignes : https://github.com/Aymkdn/assistant-notifier/blob/master/notifier.js#L77-L78 (qui sont dans le fichier `node_modules/assistant-notifier/notifier.js`)

Tu peux mettre : 
```javascript
        currentVolume[host] = -1;
        console.log("[DEBUG] ",host); // cette ligne à rajouter
        _this.prom(client, 'connect', host)
```

Et dans le fichier `node_modules/castv2/lib/client.js` (juste avant https://github.com/thibauts/node-castv2/blob/master/lib/client.js#L28) tu peux mettre : 
```javascript
  console.log("[DEBUG castv2] ",options); // cette ligne à rajouter
  options.port = options.port || 8009;
```

Puis reteste et vois ce que ça te dit dans la console.

**Comment by Ybbet** [comment]
Bonjour,

Oui, bien sûr les XX sont bien les numéros de l'adresse IP.
Je vais voir pour rajouter ces lignes de logs dans notifier ce soir. Là, je n'ai pas accès dans l'immédiat à mon installation.
Je te tiens au courant.

**Comment by Ybbet** [comment]
Re,

J'ai modifié un peu tes commandes de log : 
`
        currentVolume[host] = -1;
        console.log("[DEBUG] "+host); // cette ligne à rajouter
        _this.prom(client, 'connect', host)
`
et 
`
  console.log("[DEBUG castv2] "+options); // cette ligne à rajouter
 console.debug(options);
  options.port = options.port || 8009;
`

Voici ce que j'ai au final : 
`
1|assistant  | [assistant] (2019-02-03 14:52:52) Appel du plugin 'wait'
1|assistant  | [assistant] (2019-02-03 14:53:22) Appel du plugin 'notifier'
1|assistant  | [assistant-notifier] (salon,chambre garcons) Lecture du message : Mon message ici
1|assistant  | [DEBUG] 192.168.0.29
1|assistant  | [DEBUG castv2] [object Object]
1|assistant  | { host: '192.168.0.29' }
1|assistant  | [DEBUG] 192.168.0.25
1|assistant  | [DEBUG castv2] [object Object]
1|assistant  | { host: '192.168.0.25' }
`

Les messages se lancent correctement aujourd'hui. Je ne vois qu'une seule raison : il faut que tous les mois je me connecte sur mon compte pushbullet pour ne pas avoir de "compte inactif".
Mais j'ai toujours l'erreur pour client.js
