### ISSUE TITLE
Zapping

### ISSUE THREAD

**Issue by alcaz33** [Aymkdn/assistant-plugins#223]

**Comment by Aymkdn** [comment]
As-tu changé le nom de ta Freebox ?

Peux tu me montrer la console de assistant-plugins afin de voir ce que ça indique ?

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une version super simplifiée de `assistant-freebox` qui permet de contrôler sa Freebox à la voix sans devoir installer quoi que ce soit, ni avoir son ordinateur qui tourne 24h/24. Je cherche des testeurs pour ces prochaines semaines. Si ça t'intéresse, je t'invite à lire ce message : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
