### ISSUE TITLE
Problème controle windows 

### ISSUE THREAD

**Issue by lufykun** [Aymkdn/assistant-plugins#226]
bonjour 
Pour commencer un grand merci pour le travaille.Super facile et surtout en **français** 

1) le plugin contrôle Windows  ne fonctionne pas chez moi (w10-pro)
pourtant j'ai effectué le test comme dans l'issue 210 tous fonctionne 
et il fonctionne via cmd et aucune erreur détecter 
![assistant png](https://user-images.githubusercontent.com/6830174/52518401-4f3b5000-2c4a-11e9-8711-2bcf92f1b76a.jpg)
![ouvrir png](https://user-images.githubusercontent.com/6830174/52518403-54000400-2c4a-11e9-8657-e4fea954f16c.jpg)
le plugin launch marche parfaitement  grâce a des vbs je peut effectuer ce que je veux ,mais je trouve dommage que lui ne fonctionne pas. 

2) je souhaiterais pouvoir commande ma samsung tv 
voici deux lien en js 
[https://www.npmjs.com/package/samsung-remote](url)
[https://www.npmjs.com/package/samsung-tv-control](url)
possible de créer un plugin pour ça ?

3)je trouve génial ton vbs (start hide ) serait il possible de le transformer afin qu'il puisse afficher ou cacher la fenêtre  en le lançant ?

4) un autre plugin qui ferait plaisir a des millier de français serait pour plex media player
pour ma part j'utilise des vbs pour naviguer dans l'application et  des enregistrements de macro grâce tiny task
la ou je bute c'est pour la recherche.
Préférez vous que j'ouvre plusieurs issue  afin d'avoir plus de clarté pour les autres utilisateur  ?

**Comment by Aymkdn** [comment]
Salut,

1. le truc c'est que chez moi ça fonctionne... donc c'est compliqué de chercher pourquoi ça ne marche pas chez certains autres... Je viens de publier la version 1.0.1 (je t'invite à mettre à jour) dans laquelle j'ai rajouté de la détection d'erreur (pas sûr que cela indique quoi que ce soit, mais cela peut-être un début pour trouver l'origine du problème). Réessaie et dis moi si une erreur apparait dans la console.

2. Si ta TV est compatible avec ces packages, alors oui, tu peux créer un plugin : https://github.com/Aymkdn/assistant-template 

3. Tu veux parler de ça https://github.com/Aymkdn/assistant-plugins/issues/83 ? Ce n'est pas moi qui ai proposé cette solution. Aussi, je n'ai pas compris le sens de ta question ?! Ce vbs sert à cacher la fenêtre. Pour l'afficher, il suffit de ne pas lancer ce programme...

4. Le truc c'est que je ne peux pas créer tous les plugins du monde... Je crée ceux qui me sont utiles, mais il ne faut pas s'attendre à ce que je crée tout, pour tout le monde... Actuellement je suis sur le plugin [Freebox dans le cloud](https://github.com/Aymkdn/assistant-plugins/issues/224) qui me demande déjà énormément d'investissement (et que je fais pour ceux qui ne veulent pas s'ennuyer avec NodeJS).
   
     Plusieurs des plugins actuels ont été créés par d'autres utilisateurs, au grès de leur besoin. Et j'invite ceux qui veulent de nouveaux plugins à faire de même.
   
    Après, tu peux toujours te lancer dans la création d'un plugin simple (par exemple celui de la TV Samsung ne devrait pas être trop compliqué), et je peux t'aider / te corriger durant ta progression.
N'étant pas un utilisateur de Plex, et n'ayant pas de TV Samsung, je n'ai ni l'envie, ni le temps, ni les objets pour les tester et voir si le plugin fonctionne.
J'espère que tu comprendras.

**Comment by lufykun** [comment]
bonjour merci de votre réponse 
1)j'ai mis a jour controle windows 
![ouvrir png](https://user-images.githubusercontent.com/6830174/52519164-9c71ee80-2c57-11e9-8458-5779df17d611.jpg)
voila l'erreur que j'ai 
3) le but étant de caché ou d'afficher la fenêtre en lançant ce fichier  
2) et 4) je comprend  je vais deja esayer de creer le plugin tv ensuite je me pencherais sur plex

**Comment by Aymkdn** [comment]
Ah ! Il y a un espace dans le chemin d'accès.... Intéressant...

Peux-tu modifier le fichier `C:\google home\assistant-plugins\node_modules\assistant-control-windows\control-windows.js` en remplaçant [la ligne 92](https://github.com/Aymkdn/assistant-control-windows/blob/master/control-windows.js#L92) par : 
```javascript
exec('"'+nircmd+ '" ' +args, {windowsHide:true}, function(error, stdout, stderr) {
```

Relance et dis moi si ça marche.

Pour ton 3), je n'ai toujours pas compris ce que tu veux dire ?!?!

**Comment by lufykun** [comment]
j'ai simplement renommer mon dossier en GoogleHome et tous fonctionne Nickel
3) le but étant d' afficher la fenêtre dans la barre des taches  ou de la caché pour évite de fermer la fenêtre par inadvertance

**Comment by Aymkdn** [comment]
> j'ai simplement renommer mon dossier en GoogleHome et tous fonctionne Nickel

Sauf que moi je voulais que tu testes... Bon, tant pis, j'ai testé chez moi, et ma correction fonctionne. J'ai donc publié la version v1.0.2 qui supporte les chemins d'accès avec des espaces.

> le but étant d' afficher la fenêtre dans la barre des taches ou de la caché pour évite de fermer la fenêtre par inadvertance

Si tu parles de lancer `assistant-plugins`, je conseille plutôt d'utiliser un programme comme `pm2` pour le lancement en arrière plan.

Si tu veux le lancer manuellement, alors tu te fais 2 lanceurs : un qui le lance et le cache, et un qui le lance sans le cacher. Ensuite à toi d'utiliser le lanceur que tu souhaites selon ce que tu veux faire.

**Comment by lufykun** [comment]
pour  le plugin tv  comment faire exactement 
en tapant la commande npm install samsung-tv-control --save
ça ma créer ça
![plugin png](https://user-images.githubusercontent.com/6830174/52519463-e361e300-2c5b-11e9-913c-fd0fab4d2c6d.jpg)
dans le dossier node_modules
![ouvrir png](https://user-images.githubusercontent.com/6830174/52519479-215f0700-2c5c-11e9-8b7e-079e7ea9d448.jpg)
peut tu m'expliquer la marche a suivre ensuite

**Comment by Aymkdn** [comment]
C'est un peu long à expliquer, et je dois partir là. J'essaie de faire un tuto plus tard dans la journée ou dans le week-end.

**Comment by lufykun** [comment]
merci

**Comment by Aymkdn** [comment]
Voilà, j'ai essayé d'expliquer au mieux : https://github.com/Aymkdn/assistant-template/wiki
