### ISSUE TITLE
Commandes de control-windows non exécutées

### ISSUE THREAD

**Issue by DarkMoon35** [Aymkdn/assistant-plugins#228]
Bonjour,

Je vois des choses étranges dans la console. Certes, au début on voit "2 plugins trouvés", mais après, lors de l'exécution : 
IFTTT envoie correctement le pushbullet
le pushbullet s'exécute et je vois bien les notifs dans le flow
le pc reçoit la notif
MAIS
rien ne se passe sur le pc. J'ai testé *mute* et *screensaver*, aucun des deux n'a fonctionné. C'est compréhensible car la console écrit ça :
![bugs_controlwindows](https://user-images.githubusercontent.com/5653200/52899242-20901d00-31e8-11e9-80a9-06c43fb7bcd0.png)
J'ai l'impression qu'il prend ce que je *dis* dans sa commande à exécuter. Voici la config de l'applet (désolé pour la taille) :
![configapplet](https://user-images.githubusercontent.com/5653200/52899254-57663300-31e8-11e9-9e53-6813a9988b34.png)

**Comment by Aymkdn** [comment]
Il reçoit les commandes `launch` dans ton screenshot, mais pas la commande `control-windows`.... N'as-tu pas deux applets avec les même commandes vocales ?

**Comment by DarkMoon35** [comment]
Merci pour la réponse rapide
J'ai plusieurs applets en effet, et elles n'ont pas les mêmes commandes vocales.

**Comment by Aymkdn** [comment]
Donc, comment se fait-il qu'il exécute une commande `launch` alors que ton screenshot de l'applet montre du `control-windows`... Y'a quelque chose qui ne va pas dans ce que tu me montres...

**Comment by DarkMoon35** [comment]
Je dis juste ce que j'ai fait. Je n'en sais pas plus, et je n'ai pas été voir le code des plugin donc aucune idée du fonctionnement interne. J'espérais avoir un indice ici, ou permettre du débug.

**Comment by Aymkdn** [comment]
Quand tu utilises `control-windows` dans une applet, alors c'est `control-windows` qui doit apparaître dans la console. Là tes deux screenshots n'ont aucun rapport : l'un fait apparaître `launch` (donc tu as une applet qui doit appeler `launch`), l'autre fait apparaître `control-windows`. 

Donc je ne comprends pas ce que tu me montres... À ce stade je ne peux donc pas t'aider.

**Comment by DarkMoon35** [comment]
Ah :/ dommage
Cependant comme tu peux le voir mon applet n'utilise que `control-windows_screensaver` et l'autre `control-windows_mute` ... Qu'est-ce qui pourrait être la source du problème ? C'est nécessaire d'investiguer ça tout de même (sans offense) car j'ai simplement suivi le tuto. Si ça ne fonctionne pas en suivant le tuto, je ne peux pas utiliser le soft. Est-ce que ça pourrait venir de la machine ? De la config serveur ?

**Comment by Aymkdn** [comment]
On reprend...

1. Dis : "OK Google, PC en veille"
2. Va sur https://www.pushbullet.com/#following/ puis clique sur "IFTTT" et fais une capture d'écran que tu mettras ici
3. Va dans ta console de `assistant-plugins` puis fais une capture d'écran que tu mettras ici

**Comment by DarkMoon35** [comment]
Ok, encore un nouveau comportement :o
Je dis la phrase
Je ne reçois pas de notification sur le pc, cette fois. Mais j'ai quand même ceci qui apparaît dans le flux pushbullet :
![pushbullet](https://user-images.githubusercontent.com/5653200/52917780-ac40a100-32ef-11e9-9da4-2639864509ae.png)
et rien dans la console !
![cmd_assisantcontrolwindows](https://user-images.githubusercontent.com/5653200/52917793-c37f8e80-32ef-11e9-9148-72fc26bf66e4.png)

**Comment by Aymkdn** [comment]
Tu peux me montrer le contenu de ton applet "PC en veille" ?

**Comment by DarkMoon35** [comment]
J'avais mis la screen dans un message plus haut : 
![image](https://user-images.githubusercontent.com/5653200/52917917-dcd50a80-32f0-11e9-8ca6-e9b8a94e509d.png)
Je n'ai rien modifié.

**Comment by Aymkdn** [comment]
Non, ce n'est pas la bonne. Vérifie **TOUTES** tes applets, tu en as forcément une autre qui a le même trigger ("PC en veille"), mais qui aura dans le message Pushbullet `launch_"C:\GoogleHome\GoogleHome.vbs" en veille`.

Une fois que tu l'as trouvé, désactive-la, puis recommence le test.

**Comment by Aymkdn** [comment]
Probablement un trigger **Say a phrase with a text ingredient** dans lequel tu aurais mis `PC $`. C'est elle qui capture ce que tu dis...

**Comment by DarkMoon35** [comment]
ok, j'ai trouvé, merci
il y avait une applet par défaut qui effectivement passait au-dessus, de toute évidence. Cependant on ne voit pas directement ce qu'elle fait :
![confignondispo](https://user-images.githubusercontent.com/5653200/52917997-f6c31d00-32f1-11e9-8434-08c0c6f2124d.png)
Du coup je l'ai désactivée. Le flux pushbullet est correct, maintenant.
![pushbullet](https://user-images.githubusercontent.com/5653200/52918004-12c6be80-32f2-11e9-8e70-b7e48df262af.png)
Cependant, toujours rien dans la console (j'ai essayé de quitter et relancer le programme, même comportement).
![cmd_assisantcontrolwindows](https://user-images.githubusercontent.com/5653200/52918015-60dbc200-32f2-11e9-8798-b3c3bb6bbb51.png)

**Comment by Aymkdn** [comment]
OK, donc déjà on a la bonne applet.

Ensuite, comme indiqué dans la documentation, le **Title** du message envoyé à Pushbullet doit être **Assistant**.
Donc dans ton applet, remplace "Veille PC" par "Asssitant" :
![capture](https://user-images.githubusercontent.com/946315/52918039-d051b180-32f2-11e9-89a0-7ceb80c36478.PNG)

Et cette fois il devrait voir la commande.

**Comment by DarkMoon35** [comment]
Haaaa le titre est obligatoire. Je pensais que c'était juste une fioriture, vu que c'est marqué 'optional'.
Bon, du coup l'appli le voit :
![cmd_assisantcontrolwindows](https://user-images.githubusercontent.com/5653200/52918085-5110ad80-32f3-11e9-8d56-157c25543f95.png)
Cependant, aucun effet sur le pc, si ce n'est la notif windows.

(Un problème à la fois, mais l'assistant ne voit pas "pc muet" alors que le titre est bien "assistant", et que pushbullet reçoit la notif dans son flux :
![pushbullet](https://user-images.githubusercontent.com/5653200/52918121-d5fbc700-32f3-11e9-9b5b-17390f4008f4.png)
Mais c'est un autre problème que le 1er.)

**Comment by Aymkdn** [comment]
Pour le `screensaver`, la documentation est incorrecte (je viens de la modifier). La commande devrait être : 
`control-windows_cmd screensaver`

À noter que je ne suis pas certain que le `screensaver` va marcher. Si cela ne fonctionne toujours pas, tu peux ouvrir une fenêtre CMD et taper (en supposant que **assistant-plugins** se trouve dans le répertoire GoogleHome de C) : 
```
C:\GoogleHome\assistant-plugins\node_modules\assistant-control-windows\bin\nircmd.exe screensaver
```

Et voir si ça fonctionne. Si cela ne marche pas, alors le plugin ne fonctionnera pas pour cette commande non plus. Par exemple, chez moi cela ne fonctionne pas car je n'ai pas de screensaver et qu'il est même désactivé dans Windows.

Concernant `control-windows_mute` qui n'est pas reconnu, vérifie que tu n'as pas mis des espaces en trop dans le titre de la notification.

**Comment by DarkMoon35** [comment]
En effet, il n'a pas voulu exécuter le screensaver.
Pour le mute, il y avait apparemment conflit entre les titres des deux applets. Je viens de m'en rendre compte en désactivant mon applet "screensaver" et en re-testant.

Est-il donc actuellement impossible d'avoir plusieurs applets actives pour l'assistant ? Ou peut-on contourner en mettant des titres comme "Assistant 1","Assistant 2","Assistant_1" etc ? (je veux dire, au niveau du test sur le titre de la notif dans le flux).

En tout cas, merci beaucoup pour le temps accordé à ce problème.

**Comment by Aymkdn** [comment]
> Pour le mute, il y avait apparemment conflit entre les titres des deux applets

Euh non... Le titre permet juste à `assistant-plugins` de ne lire que les notifications qui le concernent, et pas les autres. Tu peux avoir autant d'applets actives que tu veux (j'en ai une bonne vingtaine).

**Comment by DarkMoon35** [comment]
Quelle serait la raison, dans ce cas ? Je n'ai pas touché à la config, j'ai juste désactivé l'applet screensaver et l'applet mute a fonctionné. Je viens de créer une applet "unmute" (titre Assistant également) et aucune des deux n'a d'effet dans la console. J'ai désactivé l'applet "unmute" que je viens de créer, et l'applet "mute" ne fonctionne pas toujours. En relançant l'`assistant-plugins`, c'est plutôt efficace, mais ce n'est pas très pratique de devoir fermer la console et relancer l'appli à chaque fois.

Par contre, tant que les deux applets sont activées en même temps, `assistant-plugins` ne fait rien. J'ai fait une dizaine d'essais, en relançant l'appli à chaque fois, en activant l'applet 1 puis l'applet 2, la 2 puis la 1, la 1 - relancer assistant - la 2 - relancer assistant ... Rien n'y fait.

**Comment by Aymkdn** [comment]
Tu n'as pas besoin de fermer/relancer `asssitant-plugins` à chaque fois.

Les étapes sont toujours les mêmes : 

1. Vérifier que tu n'as pas mis des trigger trop similaires entre plusieurs applets (qui pourraient faire que IFTTT s'embrouille et active la mauvaise applet)
2. Regarder dans https://ifttt.com/activity si l'applet s'est bien exécutée
3. Regarder dans https://www.pushbullet.com/#following/ que Pushbullet a bien reçu la commande
4. Regarder ce qui s'affiche dans la console

**Comment by DarkMoon35** [comment]
C'est pas du 100% mais j'arrive à avoir le scénario complet parfois. Unmute, même quand il s'exécute (jusque dans la console) n'a pas d'effet, je suppose que c'est la même chose qu'avec screensaver ..? Une config windows qui bloque ?

**Comment by Aymkdn** [comment]
Alors, il y avait un problème avec la commande `unmute`. Je viens de publier la version v1.0.3 du plugin. Il te faut donc mettre à jour pour corriger le problème du `unmute` !

**Comment by DarkMoon35** [comment]
Ah ouais c'est bon, nice ! Merci pour tout.
Je vais jouer un peu avec le plugin, notamment `_cmd` pour par exemple lancer des logiciels sur le pc, ou `_key` (je pense qu'il y a des choses à faire).
