### ISSUE TITLE
Communication ok, aucune exécution 

### ISSUE THREAD

**Issue by franck92230** [Aymkdn/assistant-plugins#229]
Bonjour,
J’ai suivi la procédure pour pouvoir contrôler avec mon Google home, la Freebox. Mais j’ai un souci, sur lappli pushbullet, menu following/ ifttt j’ai bien les notifications qui apparaissent, lorsque je demande à Google d’exécuter allumer ou éteindre freebox, la commande est bien lancé et j’ai un retour mais rien ne se passe ??

**Comment by Aymkdn** [comment]
Qu'est ce qui apparaît dans la console de `assistant-plugins`?

**Comment by franck92230** [comment]
bonsoir,
Voici les 2 fichier, start et config.
la commande est bien reconnue et transféré sur IFTTT mais rien de se fait
au niveau de la freebox

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Aymkdn** [comment]
Merci de répondre sur le site Web Github via https://github.com/Aymkdn/assistant-plugins/issues/229 plutôt qu'en répondant à l'email.

Tu as du lancer le fichier `start.bat` et donc tu dois avoir une fenêtre ouverte sur ton bureau. Lorsque tu demandes une commande tu dois voir apparaitre des choses dans ta fenêtre ouverte (ce que j'appelle *la console d'assistant-plugins*).
J'ai besoin que tu me fasses une capture d'écran de ce qui apparait dans cette fenêtre quand tu lances une commande vocale, et que tu attaches cette capture d'écran ici...

Je t'invite à regarder le point 1 de la FAQ : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes

**Comment by Aymkdn** [comment]
Aussi, comme indiqué dans la question 11 de la FAQ (https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#11-la-console-retourne-lerreur--code-econnreset-errno--econnreset) : 
> Si tu as l'anti-virus Avast d'installé, essaie de le supprimer car il semble être à l'origine de ce problème. Windows 10 intègre déjà un anti-virus gratuit et performant, aucun autre anti-virus n'est donc nécessaire.

En effet, j'ai vu dans ton email que tu as Avast, et celui-ci cause de nombreux problèmes. Il est donc recommandé de le supprimer.

Pour info, si tu cherches juste à commander ta Freebox, je t'invite à lire ça : https://github.com/Aymkdn/assistant-freebox-cloud/issues/1

**Comment by franck92230** [comment]
Je suis sur un Windows 7, et même avec Avast desinstallé je n’ai toujours pas la commande qui s’execute. Je ne comprend pas pourquoi cela ne fonctionne pas.

**Comment by Aymkdn** [comment]
J'ai besoin que tu suives toutes le étapes du 1) de ce lien : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes et que tu me fasses des captures d'écran... Sinon je vais pas pouvoir t'aider...

**Comment by Aymkdn** [comment]
Pas de réponse, donc je clos.
