### ISSUE TITLE
PLugin Notifer?

### ISSUE THREAD

**Issue by silverspur79** [Aymkdn/assistant-plugins#23]
Bonjour,

Le plugin notifier est fonctionnel. Cependant deux questions:

1- il ne répéte que des phrases courtes? une idée sur la limitation des mots?
2 - J'ai essayer de l'utiliser avec les assistant mobile que sont:
 - Allo pour le web
- Allo sur mon smartphone

Si l'assistant répète dans l'appli, le GH lui reste silencieux.

d'avance merci pour ton aide

**Comment by Aymkdn** [comment]
1) j'arrive à lui faire dire des phrases assez  longues comme : "le prochain tram est dans X minutes, le suivant dans X minutes, et celui d'après dans X minutes".... Je n'ai pas tenté de lui faire lire un roman donc  je ne sais pas les limites ^^

2) Je ne sais pas comment fonctionne Allo. Mais si tu utilises Google Assistant directement sur ton téléphone, ça devrait fonctionner.

**Comment by silverspur79** [comment]
OK merci pour ta réponse.

Pour la phrase ta réponse me fait comprendre que l'on  pourrais en effet faire de longue phrase... Je n'y arrive pas pour le moment. C'est peu être ma prononciation le problème...

Le n'ai pas la bonne version d'Android pour utiliser google assistant. J'utilise celui qui est intégré a  Allo. Je vais devoir patienter alors pour avoir une mise a jour sur mon Wikio ( c'est mal barré....) 

Merci pour les réponses
