### ISSUE TITLE
Erreur de connexion avec PushBullet:  { Error: connect ETIMEDOUT 1

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-plugins#231]
bonjour , j'ai aussi un problème de communication , la console me dit ça =>

[assistant] Assistant v2.0.12 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'control-windows' (v1.0.2)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'freebox' (v2.0.11)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.6)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-02-27 23:14:01) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-28 02:34:32) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] (2019-02-28 02:34:33) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-28 02:43:34) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Erreur de connexion avec PushBullet:  { Error: connect ETIMEDOUT 1
04.154.164.197:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.154.164.197',
  port: 443 }
[assistant] (2019-02-28 02:43:55) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...

_Originally posted by @nusmiaf in https://github.com/Aymkdn/assistant-plugins/issues/225#issuecomment-468230985_

**Comment by Aymkdn** [comment]
@nusmiaf je t'ai créé ta propre *issue*.

Si jamais tu veux tester le patch que j'ai fait, tu peux suivre ces étapes : 
  1) arrêter `assistant-plugins`
  2) remplacer le fichier `répertoire_assistant-plugins\node_modules\assistant-plugins\index.js` avec celui-là : https://gist.githubusercontent.com/Aymkdn/aebc659db14b8cd4e1e9b1b4b80074a4/raw/6af172db37761b2660e766ed4807d106d8487728/index.js
  3) relancer `assistant-plugins`

Si tu essaies, merci de me tenir au courant si ça fonctionne chez toi (j'ai qu'une connexion tous les 3 jours ici).

Autre chose, tu utilises Windows ? Tu n'as pas **Avast** d'installé au moins ?

**Comment by nusmiaf** [comment]
ok j'ai fait la modif la console répond =>
[assistant] Assistant v2.0.12 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'control-windows' (v1.0.2)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'freebox' (v2.0.11)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.6)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-02-29 13:21:51) Connecté ! Prêt à exécuter les ordres.


je te donne le rendu dans quelques jours

**Comment by nusmiaf** [comment]
alors 1er retour ça coupe  mais ça se reconnecte apparemment =>

[assistant] (2019-02-29 17:39:22) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Erreur de connexion avec PushBullet:  { Error: getaddrinfo ENOTFO
ND stream.pushbullet.com stream.pushbullet.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: 443 }
[assistant] (2019-02-29 17:39:33) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Reconnexion....
[assistant] Erreur de connexion avec PushBullet:  { Error: getaddrinfo ENOTFO
ND stream.pushbullet.com stream.pushbullet.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stream.pushbullet.com',
  host: 'stream.pushbullet.com',
  port: 443 }
[assistant] (2019-02-29 17:40:22) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Reconnexion....
[assistant] (2019-02-29 17:40:33) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-29 17:46:34) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Erreur de connexion avec PushBullet:  { Error: connect ETIMEDOUT
04.154.164.197:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.154.164.197',
  port: 443 }
[assistant] (2019-02-29 17:46:55) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] Reconnexion....
[assistant] (2019-02-29 17:47:35) Connecté ! Prêt à exécuter les ordres.

**Comment by Aymkdn** [comment]
Ok

**Comment by nusmiaf** [comment]
non pas de doubles commandes
log de cette nuit =>


[assistant] (2019-02-29 22:43:34) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-03-02 04:50:05) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] (2019-03-02 04:50:05) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-03-02 07:21:36) Le flux avec Pushbullet a été déconnecté...
Tentative de reconnexion...
[assistant] (2019-03-02 07:21:37) Connecté ! Prêt à exécuter les ordres.

**Comment by Aymkdn** [comment]
Les déconnexions que tu as eu cette nuit sont des micro-coupures qui sont déjà gérées. Là le patch que j'ai fait est pour les plus grosses coupures (comme `Error: connect ETIMEDOUT`).

Donc pour le moment tout semble bon ?

J'attends lundi puis je publierai la nouvelle version si tout est OK d'ici là :-)

**Comment by Aymkdn** [comment]
Salut @nusmiaf on peut dire qu'on est bon ? Rien à signaler ?

**Comment by nusmiaf** [comment]
Et bien si ça coupe  , ça ce reconnecte   il n'y a plus de timeout... donc c'est bon 😉

**Comment by Aymkdn** [comment]
OK cool ! Je viens de publier la v2.0.13 avec le patch :)
