### ISSUE TITLE
commandes exécutées plusieurs fois

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-plugins#232]
Bonjour Aymeric,
Tout d'abord braco pour ce programme.
Je rencontre un petit problème avec  plugin assistant que je vais vous exposez.
Je suis novice dans ce domaine. J'ai un raspberry avec google assistant, ca fonctionne bien mais lorsque je dis zappe sur la 1, la commande est éxécuté 2 fois. Je pense avoir installer le programme 2 fois mais je ne sais pas comment le désinstaller. Pouvez vous m'aider car je galère depuis 1 mois?

merci d'avance

_Originally posted by @micky1183 in https://github.com/Aymkdn/assistant-plugins/issues/215#issuecomment-469842359_

**Comment by Aymkdn** [comment]
Bonsoir.

J'ai créé une *issue* séparée pour ta question.

Alors, j'imagine que tu utilises `pm2` ? Si oui, ce programme permet de lancer `assistant-plugins` en arrière plan. Si non, est-ce que tu as lancé un script de démarrage qui lance `assistant-plugins` automatiquement ?

En gros, il doit être lancé en backgroup et tu le lances peut-être aussi en manuel en plus ?

**Comment by micky1183** [comment]
non j'utilise pm2

**Comment by Aymkdn** [comment]
Alors qu'est-ce que donne la commande : `pm2 list` ?

**Comment by micky1183** [comment]
pi@raspberrypi:~/assistant-plugins $ pm2 list
┌───────┬────┬───────┬────────┬────────┬─────┬────────┬───────────┐
│ Name  │ id │ mode  │ status │ ↺      │ cpu │ memory │
├───────┼────┼───────┼────────┼────────┼─────┼────────┼───────────┤
│ index │ 0  │ 2.0.0 │ fork   │ online │ 0   │ 0.1%   │ 54.1 MB   │
└───────┴────┴───────┴────────┴────────┴─────┴────────┴───────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by Aymkdn** [comment]
OK. Vérifie dans tes scripts de démarrage que tu n'as pas mis quelque chose en rapport avec `assistant-plugins` ?

Tu as forcément 2 versions qui sont lancées. Je ne peux pas t'aider beaucoup plus, ne sachant pas ce que tu as fait sur ta machine...

**Comment by micky1183** [comment]
merci quand meme pour ton aide, je verifie comment?

**Comment by micky1183** [comment]
déja j'ai tout ca dans mes répertoire, je pense que c'est pas normal deja

pi@raspberrypi:~ $ ls
assistant-plugins      node-v9.3.0-linux-armv6l
assistant-plugins.log  node-v9.3.0-linux-armv6l.tar.gz
domoticz
pi@raspberrypi:~ $ cd assistant-plugins
pi@raspberrypi:~/assistant-plugins $ ls
configuration.json  index.js.3      package.json.2     postinstall.js.1
index.js            node_modules    package.json.3     postinstall.js.2
index.js.1          package.json    package-lock.json  postinstall.js.3
index.js.2          package.json.1  postinstall.js
pi@raspberrypi:~/assistant-plugins $

**Comment by Aymkdn** [comment]
> déja j'ai tout ca dans mes répertoire, je pense que c'est pas normal deja

En effet, tu as dû télécharger le programme plusieurs fois. En soit, ça ne devrait pas être trop gênant.

Tu peux tenter de tout supprimer et de recommencer une installation propre.

**Comment by micky1183** [comment]
c'est ce que je me disais je veux bien repartir à 0 mais je ne sais pas comment tout supprimer

**Comment by Aymkdn** [comment]
Tape : 
```
cd ~
pm2 stop 0
pm2 remove 0
pm2 save
rm -rf assistant-plugins
```

Puis tu reprends à l'étape 4 de l'installation : https://aymkdn.github.io/assistant-plugins/#-installation

**Comment by micky1183** [comment]
ok je vais réessayer et je viens de redemarrer j'ai bien toutes les chaines qui s'affiche en double
la 1 sur 11 
la 2 sur 22...

**Comment by micky1183** [comment]
alors du coup je vais repondre à tes questions
- je n'ai pas d'interface graphique
-quand je redemarre le probleme persiste
- j'ai taper pm2 stop 0 et la ca fonctionne...

**Comment by micky1183** [comment]
j'avais essayer avec contrab avant ca ne serai pas ca le soucis?

**Comment by Aymkdn** [comment]
> j'avais essayer avec contrab avant ca ne serai pas ca le soucis?

Ah bhein oui ! En effet... du coup y'a pm2 ET crontab qui le lancent :-)

**Comment by micky1183** [comment]
Comment puis-je faire pour couper l'un ou l'autre?

**Comment by Aymkdn** [comment]
Tape : 
`crontab -e`

Puis supprime la ligne que tu avais ajouté. Sauve, et redémarre.

**Comment by micky1183** [comment]
merci j'avance 
J'ai taper pm2 unstartup comme indiquer au dessus
J'ai redemarrer raspberry et ca fonctionne.

J'avais essayer  la methode 1 avec contab mais au bout de 24h le programme ne redémarrai plus
donc j'avais essayer avec pm2

Je laisse comme ca et je recommancerai demain

**Comment by micky1183** [comment]
merci beaucoup Aymeric pour ton efficacité et ta réactivité
