### ISSUE TITLE
Disque réseau

### ISSUE THREAD

**Issue by fabbrossier** [Aymkdn/assistant-plugins#233]
Bonjour

pour commencer merci pour ce super boulot.
free devrai te recruter :-)

j'ai tout installé sur un raspbpi et ca fonctionne plutot bien !!!! Bravo à toi.

j'essaye d'utilisé le plugin pour naviguer dans les dossier , si je comprend bien ca ne fonctionne pas avec les disque connecter sur le free server?

Il faut créer son propre applet ifttt ?  le miens est \\FREEBOX\Expansion Drive 
je doit pointer vers lui en modifiant ton applet?

merci pour ton aide

**Comment by Aymkdn** [comment]
>  si je comprend bien ca ne fonctionne pas avec les disque connecter sur le free server?

Tout à fait, la commande `folder` ne fonctionne qu'avec `Mes Vidéos`, `Ma Musique` ou `Mes Photos`

> Il faut créer son propre applet ifttt ? le miens est \FREEBOX\Expansion Drive
> je doit pointer vers lui en modifiant ton applet?

La commande `folder` ne peut pas prendre en charge ce dossier/disque dur externe. La seule chose que tu peux faire c'est créer une applet pour, par exemple, dire *"va dans mon disque dur"* et ensuite indiquer les bonnes commandes pour s'y rendre. Mais tu ne peux pas y faire une recherche.

**Comment by fabbrossier** [comment]
Ok merci
