### ISSUE TITLE
Problème Nas synology

### ISSUE THREAD

**Issue by romain211289** [Aymkdn/assistant-plugins#236]
Hello,

Cela fait plusieurs semaines que j'utilise l assistant, vraiment super!

Par contre, je bloque sur quelque chose et je voudrais savoir si il existe une solution..

J'ai stocké l assistant sur mon NAS syno, tout fonctionne nickel, j ai même créé la tâche pour que le script se lance au démarrage.. bref jusque là rien à dire ! Sauf que au bout d'un moment je suis obligé de relancer l assistant en manuel. Je me suis dit que cela venait du fait que le syno se mette en hibernation, mais j'ai arrêté le mode hibernation, et 2 jours après plus d'assistant fonctionnel, obligé de le relancer manuellement

Aurais tu une solution à mon problème ?

Merci

**Comment by Aymkdn** [comment]
Qu'indique les logs de l'assistant ? S'il plante il y a des chances qu'il indique la raison du plantage :-)

**Comment by romain211289** [comment]
Comment puis-je voir les log de l'assistant ? (avec putty?)

**Comment by Aymkdn** [comment]
Ouais, en te connectant à ton NAS puis après ça va dépendre de comment tu as lancé le programme...

Si tu l'as lancé avec un script au démarrage, tu as peut-être indiqué de rediriger les logs dans un fichier ? Par exemple si tu as un cron qui dit : 
> @reboot /opt/bin/node /root/assistant-plugins/index.js > /var/log/assistant-plugins.log &

Alors les logs sont dans `/var/log/assistant-plugins.log`

**Comment by romain211289** [comment]
Je n'ai pas réussi à accéder au dossier des log, il me dit "Permission denied"... pourtant je suis passé en root avec sudo-i

désolé je débute dans l'utilisation de putty..
à noter j'ai juste enregistrer une tache dans le planificateur au démarrage "node /volume1/Assistant-plugins/index.js > Assistant-plugins.log &" (le script fonctionne très bien, car au redémarrage du NAS l'assistant fonctionne) .

**Comment by Aymkdn** [comment]
Regarde si tu as un fichier `Assistant-plugins.log` dans le répertoire `/volume1/Assistant-plugins/` ...

Si non, dans ton script de démarrage, change :
> node /volume1/Assistant-plugins/index.js > Assistant-plugins.log &

par :
> node /volume1/Assistant-plugins/index.js > /volume1/Assistant-plugins/assistant-plugins.log &

Et redémarre, puis vérifie que le fichier `/volume1/Assistant-plugins/assistant-plugins.log` a bien été créé et qu'il contient les logs de lancement.

Ensuite il te faudra attendre la prochaine fois que ça plante et regarder dans ce fichier ce qui y est indiqué.

**Comment by romain211289** [comment]
Ok merci, je viens de faire cela et j'ai bien le fichier Assistant-plugins.log.
Je regarde les log dans quelques jours et je reviens vers toi !

Merci
