### ISSUE TITLE
[HowTo] Comment lancer spotify par Assistant-Plugins

### ISSUE THREAD

**Issue by Ybbet** [Aymkdn/assistant-plugins#237]
Bonjour,

Actuellement, je peux lancer des messages audio sur mon/mes Google Home (mini) par le calendrier (couplage avec IFTTT, Pushbullet). Le titre de mon événement est le texte retranscris sur Google Home.

J'ai envie d'aller plus loin : depuis mon calendrier, lancer de la musique sur mes Google Home. 
Est-ce que quelqu'un a déjà mis cela en place ?
:-D

**Comment by Aymkdn** [comment]
Il est possible de faire lire un mp3 au Google Home (avec le plugin notifier), mais lui faire lire Spotify, ça je ne sais pas. Il faudrait chercher sur le net si quelqu'un a déjà réussi à faire ça.

**Comment by Ybbet** [comment]
Oui, c'est bien ce qu'il me semblait. En recherchant un peu "launch spotify from nodejs google home" j'ai trouvé ceci : https://github.com/actions-on-google/actions-on-google-nodejs
Mais cela rejoint une conversation précédente sur "Dialogflow".

**Comment by Aymkdn** [comment]
À mon avis c'est plutôt ce package qu'il faut utiliser : https://github.com/thelinmichael/spotify-web-api-node

Avec la fonction [`transferMyPlayback`](https://github.com/thelinmichael/spotify-web-api-node/blob/37a78656198185776ca825b37e2de4a31c2ae5de/src/spotify-web-api.js#L1072) (voir la [documentation de Spotify](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-transfer-a-users-playback))

**Comment by Ybbet** [comment]
J'ai regardé ce package et malheureusement, non, ça ne fonctionnera pas.
Le but principal de ce package est de lancer Spotify dans un browser en local. Pour la fonction, elle a besoin d'un id du device… Sauf que les Google Home ne sont pas enregistrés dans le compte Spotify mais l'accès au compte Google.
Avec le package actions-on-google-nodejs, il est possible de simuler une conversation device par device. Il est possible de passer l'adresse IP du Google Home. A creuser peut-être.

**Comment by Aymkdn** [comment]
Ok. Bon courage alors. Si tu trouves quelque chose, n'hésite pas à partager ici 😉
