### ISSUE TITLE
Box SFR

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#238]
Bonjour Aymeric ,
suite déménagement ( adios ma bonne vielle freebox révolution )
et passage a la fibre  SFR ( contraint par le lieu )
je ne connais pas du tout cette box..
y a t'il une possibilité d'y adapté l'assistant ?

Merci

**Comment by Aymkdn** [comment]
Non, il n'y a pas d'API avec la box de SFR (de ce que je sais).

**Comment by nusmiaf** [comment]
ok tan-pi :(
