### ISSUE TITLE
Assistant-plugins : Faire jouer un son mp3

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-plugins#239]
Bonjour,
est il possible d'inclure dans  l'assistant-plugins un moyen faire jouer un son sur la google home ?
il y a deja la fonction notifier.js qui permet de faire parler le google home ... mais je ne vois rien qui pourrait faire jouer un son mp3.

Merci

**Comment by Aymkdn** [comment]
Il suffit de passer une URL (avec httplqui pointe vers un mp3 plutôt que du texte à `notifier` et le Home va le jouer.
