### ISSUE TITLE
Enchaîner des commandes de plusieurs plugins avec une seule commande vocale

### ISSUE THREAD

**Issue by ant1fr** [Aymkdn/assistant-plugins#240]
Hello,
Je cherche à enchaîner une commande pour le plugin yahama et une pour le plugin freebox avec la même commande vocale.
Mais dans le corps de la note Pushbullet, je ne sais quel formalisme suivre.

Et énorme merci pour ce lien manquant avec différents objets de la maison et Google Assistant !

.ant

**Comment by Aymkdn** [comment]
De mémoire, tu peux les séparer avec un `|`

`yamaha_xyz|freebox_abc`

**Comment by ant1fr** [comment]
J'ai tenté :
yamaha_powerOn,*2,setInputTo#4#1,freebox_on

Mais à l'évidence il entre dans le contexte du plugin yamaha et ne comprends pas la commande freebox :
[assistant] (2019-04-15 17:52:49) Appel du plugin 'yamaha'
     >>
          cmd  non trouvée
     powerOn>>
     *2 >>
          Pause de 2 sec
     setInputTo#4#1>>
     freebox_on>>
          cmd freebox_on non trouvée
[assistant-yamaha] Commande « ,powerOn,*2,setInputTo#4#1,freebox_on » exécutée(s)

**Comment by Aymkdn** [comment]
Tu peux aussi créer une applet IFTTT qui execute plusieurs actions en la créant via https://platform.ifttt.com

**Comment by ant1fr** [comment]
Le pipe fonctionne parfaitement ;)
