### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-plugins#241]
Bonjour,
je cherche un moyen d'envoyer une notification sur mon téléphone depuis le PC par une ligne de commande DOS ou lien HTTP.

Avez-vous une solution ?

j'au vu sur le net :
curl -s -u "<token>:" "https://api.pushbullet.com/v2/pushes" -d device_iden="<device_id>" -d type=note -d title="<titre>" -d body="Hello World"

mais visiblement un message d'erreur m'indique qu'il faut la version pro de pushbullet.

(le plugin-assitant est aussi installé sur mon serveur)
Cordialement

**Comment by Aymkdn** [comment]
Tu pourrais créer une applet IFTTT qui reçoit un Webhook puis qui envoie un Pushbullet ou un Pushover vers ton téléphone.

Pour cela, tu peux utiliser le [plugin IFTTT](https://aymkdn.github.io/assistant-plugins/?plugin=ifttt).

Et pour lancer un plugin depuis une ligne de commande : https://github.com/Aymkdn/assistant-plugins/wiki/Utiliser-le-programme-en-ligne-de-commande

**Comment by rick443** [comment]
on, je viens  de créé un applet sur IFTTT qui me permet d'envoyer via pushbullet une notification... 
ça fonctionne.
Par contre, j'ai un peu de mal à comprendre comment exectuer cet applet avec la ligne de commande 
node ./node_modules/assistant-plugins/assistant-cli.js CommandeÀÉxécuter

si mon applet s'appelle "TEST", tu peux m'écrire la ligne avec la bonne syntaxe ?

Merci

**Comment by Aymkdn** [comment]
Donc, en supposant que l'`Event Name` de ton applet s'appelle `TEST`, et que tu utilises l'*ingrédient* `Value1` et `Value2` dans ta notification, alors :

```
node ./node_modules/assistant-plugins/assistant-cli.js "ifttt_TEST#Value1#Value2"
```

**Comment by rick443** [comment]
ok, j'ai paramétré dans le fichier configuration jsgon la Key (IFTTT)....
quand j'execute la ligne de commande, je vois bien 
1) chargement du plugin 'ifttt (v2.0.1)'
2) Commande reçue : [' ifttt_Notification']
3) Appel du plugin 'ifttt'

mais je ne reçois aucune notification ! ?

Merci pour votre aide

**Comment by rick443** [comment]
ok, c tout bon....
je n'avais pas compris l'utilisation de webhook...
ça fonctionne

Merci bcp

**Comment by rick443** [comment]
encore une petite question....
je reçois toujours une notification Pushbullet quand j'utilise assistant-plugin.
D'après pushbullet, on peut notifier en fonction de l'importance du message.
peut on avoir un parametre dans cette fonction d'appel de plugin qui permet de selectionner ce mode ?

J'explique mon cas:
quand je demande à Google Assistant de passer l'aspirateur, je reçois dans un premier temps une notification (IFTTT ==> pushbullet ==> notification)..... 
cette notification je souhaite ne pas l'avoir sur le telephone (Priorité faible d'après pushbullet)
le pushbullet permet a mon serveur de lancer un .bat qui donne l'ordre à l'aspirateur de fonctionner.
Et c'est ce fameux fichier .bat qui après avoir donné l'ordre de passer l'aspi qui execute la ligne de cmde
ifttt_Notification   (Priorité haute) .... et la la notification m'interesse.


Est-ce faisable ?


Cordialement

**Comment by Aymkdn** [comment]
Je pense que la notification est due à IFTTT. Édite ton applet et uncheck ça :
![Screenshot_20190425-175938__01](https://user-images.githubusercontent.com/946315/56750469-2411c880-6784-11e9-857e-6b4ed88b5af7.jpg)

**Comment by rick443** [comment]
non, cela ne change rien....c'est bien Pushbullet qui envoie la notification....

**Comment by Aymkdn** [comment]
Dans ce cas, je pense qu'il n'y a rien à faire... À moins d'installer une application sur ton téléphone qui ignore les notifications qui contiennent certains termes par exemple (j'imagine que ça existe)

**Comment by rick443** [comment]
j'ai une autre piste....
je desactive les notif sur pushbullet...et je les envoie via pushover.....

je teste.....
