### ISSUE TITLE
Ajout de Plugin Synology

### ISSUE THREAD

**Issue by Cyril32340** [Aymkdn/assistant-plugins#242]
Bonjour et un grand merci pour tes plugins qui fonctionnent admirablement bien.
Saurais-tu par ailleurs expliquer la démarche à suivre afin d'ajouter des plugins lorsque l'on passe par un synology et que l'on à déjà installé un ou plusieurs plugins une première fois?

Merci d’avance pour ton support,

Cdlt,
Cyril

**Comment by Aymkdn** [comment]
Bonjour. Synology est du Linux. C'est donc la même démarche qu'il faut suivre. Celle-ci est expliquée dans la section "installation" de chaque plugin !

**Comment by Cyril32340** [comment]
Merci beaucoup pour ton retour, je vais tester ça.
Par ailleurs, une idée fonctionnelle afin de faire tourner node en tâche de fond sur le syno? J'utilise livebox assistant, qui est fonctionnelle lorsque je le lance dans une fenêtre SSH, par contre dés que je la ferme, il s'arrete.
Avec `ps aux` pas de node index.js, et la avec la commande `/opt/bin/node /root/assistant-plugins/index.js > /var/log/assistant-plugins.log &` j'ai le message suivant:
admin@DiskStation:~$ -sh: /var/log/assistant-plugins.log: Permission denied

Pour l'instant j'utilise node v8 et ai utilisé le planificateur de tâche comme indiqué dans ton tuto:
![image](https://user-images.githubusercontent.com/50156685/57012264-d1ae2d00-6c05-11e9-84af-559b26354f3c.png)

Merci,
Cyril

**Comment by Aymkdn** [comment]
Faut lancer la commande en `root`

**Comment by Cyril32340** [comment]
Malheureusement déjà testé :
![image](https://user-images.githubusercontent.com/50156685/57012773-7a5d8c00-6c08-11e9-985f-d3b86d451705.png)

**Comment by Aymkdn** [comment]
Différente erreur cette fois... Il doit qu'il ne trouve pas Node dans le répertoire indiqué...

**Comment by Cyril32340** [comment]
Il fallait installer assistant plugin en mode root? Si oui, le soucis vient de la je pense.

**Comment by Cyril32340** [comment]
L’installation de node v8 quant à elle s'est fait automatiquement en utilisant le package de Syno.

**Comment by Aymkdn** [comment]
Ah je sais. Le problème est le répertoire des logs. L'utilisateur par défaut ne doit pas pouvoir écrire dedans. Donc au lieu de ` /var/log/assistant-plugins.log` tu peux essayer `~/assistant-plugins.log` qui va mettre les logs dans le répertoire courant de l'utilisateur.

**Comment by Cyril32340** [comment]
Pas mieux, en root et non root:
![image](https://user-images.githubusercontent.com/50156685/57015358-c7dff600-6c14-11e9-9b04-c5d6cc8bb42a.png)

**Comment by Aymkdn** [comment]
Regarde où est installé ton Node.... Peut-être avec `which node` (pas sûr de la commande)

**Comment by Cyril32340** [comment]
La commande a l'air OK:

![image](https://user-images.githubusercontent.com/50156685/57016969-404ab500-6c1d-11e9-871d-da10d0c69a58.png)

Aprés dans la directorie:

![image](https://user-images.githubusercontent.com/50156685/57017022-856ee700-6c1d-11e9-9cf1-6771a7700794.png)

**Comment by Aymkdn** [comment]
Donc faut lancer `/usr/local/bin/node` au lieu de `/opt/bin/node`

**Comment by Cyril32340** [comment]
Ok, c'est à dire dans la tache planifié du syno je remplace 
`/opt/bin/node /root/assistant-plugins/index.js > /var/log/assistant-plugins.log &`

par `/usr/local/bin/node /root/assistant-plugins/index.js > /var/log/assistant-plugins.log &`

**Comment by Cyril32340** [comment]
Quand je lance depuis PuTTY:

![image](https://user-images.githubusercontent.com/50156685/57017581-062ee280-6c20-11e9-909f-3626e2cff6f0.png)

**Comment by Cyril32340** [comment]
On avance...
Il le lance avec la commande suivante:
`/usr/local/bin/node /volume1/homes/admin/assistant-plugins/index.js`

![image](https://user-images.githubusercontent.com/50156685/57018068-2fe90900-6c22-11e9-979e-08aac92bc67a.png)

Aprés, ca ne marche pas en ajoutant ni:
`> /var/log/assistant-plugins.log &`
ni
`> ~/assistant-plugins.log &`

Une idée pour le lancer en tâche de fond?

**Comment by Cyril32340** [comment]
Je viens de tester un redemarrage, a priori ça marche nickel en ne mettant que cette ligne dans la tâche planifiée du Syno:

`/usr/local/bin/node /volume1/homes/admin/assistant-plugins/index.js &`

![image](https://user-images.githubusercontent.com/50156685/57019216-22358280-6c26-11e9-8dc0-be4072613bdb.png)

Merci beaucoup pour ton support, c'est appréciable!

**Comment by Aymkdn** [comment]
Désolé, journée bricolage dans la nouvelle maison (emménagé cette semaine ^^).

Pour la commande ça serait mieux de faire : 
`/usr/local/bin/node /volume1/homes/admin/assistant-plugins/index.js > /volume1/homes/admin/assistant-plugins/logs.txt &`

Afin d'avoir les logs visibles dans `/volume1/homes/admin/assistant-plugins/logs.txt` si t'as des soucis plus tard. À toi de voir !
