### ISSUE TITLE
Question sur notifier.

### ISSUE THREAD

**Issue by babassdu22** [Aymkdn/assistant-plugins#243]
Bonjour et tout d’abord merci pour ton travail!

J’ai le plugin pour contrôler la livebox qui me sert tout les jours!

Je cherche une solution pour faire tourner une routine Google home mini suite à une action ifttt, j’ai trouvé ton plugins notifier intéressant car on peut interagir avec le Google home en tant que client. 

Ma question est: serait il possible de lancer une routine Google home tout comme il est possible de lui faire lire un texte?

Mes connaissance en programmation étant quasiment proche du néant, je t’avoue que je rame beaucoup pour trouver une solution et je sais même pas si c’est possible.

Merci d’avance et encore bravo pour les plugins!!

**Comment by Aymkdn** [comment]
Tu entends quoi par "faire tourner une routine"?

**Comment by babassdu22** [comment]
Tu peux programmer des routines sur le Google home qui se déclenche à la voix ou à une heure précise, info tirée du support Google: 

https://support.google.com/googlehome/answer/7029585?co=GENIE.Platform%3DAndroid&hl=fr

moi je souhaiterais les lancer suites à une action ifttt.

**Comment by Aymkdn** [comment]
Ah OK. Ce n'est pas possible de les lancer via IFTTT.

**Comment by babassdu22** [comment]
Ouais c’est bien ce que je pensais, mais je me demandais si en passant par Pushbullet comme avec ton plugin assistant notifier ça n’aurait pas été possible...

**Comment by Aymkdn** [comment]
Non, impossible aussi... Pas de solution programmatique pour accéder aux routines (pas que je connaisse en tout cas !)

**Comment by babassdu22** [comment]
Pas de soucis merci bien en tout cas pour le travail déjà réalisé!

**Comment by Ybbet** [comment]
Petite @babassdu22 : quel type de routine désires-tu lancer ? 
J'ai mis en place des "routines" grâce à mon calendrier Google + assistant plugins + pushbullet + ifttt.
En gros, dans mon agenda, dans un calendrier dédié, j'ajoute un événement "Allumer lumière salon" à une certaine heure. IFTTT voit qu'il y a un événement de ce fameux calendrier qui débute, il envoie une notification à mon webhook qui gère la lumière.
Du même genre, j'ai besoin que Google Home diffuse des messages à des heures précises. Je crée l'événement ayant pour titre le message à diffuser. IFTTT détecte ce nouvel événement, envoie un pushbullet avec "notifier_{descriptif} title". Le descriptif de mon événement contient les noms des Google Home, et le titre est le message à diffuser sur les Google Home.

Je n'ai pas réussi de façon "simple" de recréer des routines par dates ou heures lançant une série d'actions. Par exemple, je dis "Bonjour" alors cela allume les lumières, lecture de la météo puis lecture des actualités.
Je suis encore obligé de passer par l'interface de Google Home.

**Comment by babassdu22** [comment]
C’est exactement le genre de routines que tu as pas réussi à gérer, c’est à dire le matin, allumer la lumière, me donner la météo, mes rappels et événement Google puis lancer la radio. Je cherche à automatiser ma routines réveil en fonction des mes horaires de travail, je peux soit me lever à 6:00 comme à 10:00 (les joies des horaires atypique) et je note mon plannings sur Google agenda, je cherche à automatiser l’heure du lancement de ma routine réveil en fonction de l’heure de travail déclarer sur Google agenda...
