### ISSUE TITLE
commande wait

### ISSUE THREAD

**Issue by zackcamui** [Aymkdn/assistant-plugins#244]
Bonjour

j'ai essayer d"utiliser le plugin ifttt qui fonctionne 
j'ai voulu copier ce cas :  
Création d'un applet WebHooks IFTTT qui se déclenche sur la commande AllLightsOff et qui va se connecter à Philipps Hue pour éteindre toutes les lampes
Création d'un applet Google Assistant (Say a phrase with both a number and a text ingredient) avec la phrase de déclenchement : "éteins toutes les lumières dans # $"
Cet applet enverra à Pushbullet une note avec le titre "Assistant" et le message : wait_{{NumberField}} {{TextField}}|ifttt_AllLightsOff
Si on décortique la commande envoyée à Pushbullet 👍 
wait_{{NumberField}} {{TextField}} → cela déclenche le plugin assistant-wait qui permet de mettre un timer de NumberField TextField (par exemple "3 minutes")
| → le pipe permet de distinguer les différentes commandes
ifttt_AllLightsOff → cela déclenche le plugin assistant-ifttt qui va mettre en route le WebHook AllLightsOff créé à l'étape 1 et donc éteindre toutes les lumière

mon soucis c'est que j'ai ce message
![image](https://user-images.githubusercontent.com/50505402/57562839-c3df7100-7396-11e9-8ad2-ac56031fc07d.png)

une idée? c'est le timer qui m'interesse vraiment 
en effet j'essai de couper ou remettre le courant sur les fil qui relient mon compteur à une prise connectée , ou je branche dessus mes vollets roulant qui n'ont pas de buttée pour s'arreter

je ne sais pas si je suis clair mais en gros a la fin je dirais , ok google ferme les volets
et la finalité sera que les volets se ferment, et je les arrêterais au bout de X minutes en éteignant la prise connectée.
C'est pour ca qu'il me faut absolument un timer
étonnat qu'il n'y ai pas nativement cette fonctionnalité sur google home ou ifttt non?
car le soucis avec la solution que j'utilise là, c'est que je dois avoir le pc allumée ;/
(j'ai un synology mais je n'ai pas réussi a faire les installations....)

**Comment by Aymkdn** [comment]
Première chose, concernant mon exemple, dans ton applet IFTTT, tu dois cliquer sur `Add Ingredient` au lieu d'écrire manuellement `{{NumberField}}`

Ton applet doit ressembler à ça :
![Screenshot_20190511-091545__01](https://user-images.githubusercontent.com/946315/57566494-792d1b80-73cd-11e9-99c2-19ef48fc3f5e.jpg)

**Comment by Aymkdn** [comment]
> finalité sera que les volets se ferment, et je les arrêterais au bout de X minutes en éteignant la prise connectée.

Dans ce cas tu peux définir toi-même le temps puisque tu le connais, donc un truc du genre `ifttt_closeVolets|wait_28 secondes|ifttt_stopVolets`

Par contre, tu es obligé de garder un PC allumé ou réussir à le faire fonctionner sur Syno, pour utiliser ces commandes-là. Il n'existe pas d'autres façons (à ma connaissance) de créer une attente/délai.

**Comment by zackcamui** [comment]
bonjour merci beaucoup !

j'ai réussi grace a toi!

en fait je dis a google d'allumer ma prise connectée, d'ouvrir mes volets, puis d'envoyer un mot particulier sur ifttt, qui fait le compteur et envoi ensuite l'info a webhook qui se charge d'éteindre ma prise

j'ai mis cette prise connecté sur mon compteur
et sur mon compteur j'ai mit les fils qui allimentent mes volets sur un embout de prise male branché sur ma prise connectée.


oui parceque mes volets n'ont pas de butée. Et si je les ouvre avec la voix, ils continuent à s'ouvrir indéfiniment.
Le grand n'a pas integré la fonction stop sauf en manuel sur son application mobile (pas à la voix)

sur ifttt il n'y a pas non plus la fonction stop
il n'y a que ouvre ou ferme.

du coup pas possible de faire une fonction stopVolets

mais j'ai quand meme réussi à bidouiller avec un chemin assez long!


________________________________
De : Aymeric <notifications@github.com>
Envoyé : samedi 11 mai 2019 09:57
À : Aymkdn/assistant-plugins
Cc : zackcamui; Author
Objet : Re: [Aymkdn/assistant-plugins] commande wait (#244)


finalité sera que les volets se ferment, et je les arrêterais au bout de X minutes en éteignant la prise connectée.

Dans ce cas tu peux définir toi-même le temps puisque tu le connais, donc un truc du genre ifttt_closeVolets|wait_28 secondes|ifttt_stopVolets

Par contre, tu es obligé de garder un PC allumé ou réussir à le faire fonctionner sur Syno, pour utiliser ces commandes-là. Il n'existe pas d'autres façons (à ma connaissance) de créer une attente/délai.

**Comment by Aymkdn** [comment]
Cool!
