### ISSUE TITLE
Livebox : no change pas sur toutes les chaines

### ISSUE THREAD

**Issue by pioroman** [Aymkdn/assistant-plugins#246]
Bonjour,

J'etais sur alexa avec Sonos mais je suis passe sur Google (support sur sonos!)...

J'ai reussi a faire la conversion mais on dirait que toutes les chaines ne passent pas...

Aussi avec le Synology avec les mise a jour le repertoire et executable sont effaces :-(

[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'livebox' (v1.1.2)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-05-22 10:52:19) Connecté ! Prêt à exécuter les ordres.
root@mynas:~/assistant-plugins# (node:18177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Chaine bfm inconnue
(node:18177) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Chaine 15 inconnue
(node:18177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Chaine bfm inconnue
(node:18177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Chaine 15 inconnue
(node:18177) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Chaine bfm inconnue

**Comment by Aymkdn** [comment]
Il faut soit dire **zappe sur BFM TV**, soit dire **zappe sur la 15**.

Mais pas `zappe sur BFM`, ni `zappe sur chaine 15`.

**Comment by pioroman** [comment]
super merci ... bien vu...

**Comment by pioroman** [comment]
peut on ajouter BFM avec BFM TV ?

**Comment by Aymkdn** [comment]
As-tu essayé de créer une applet IFTTT avec la commande `zappe sur BFM` et qui envoie un Pushbullet Note `livebox_zappe sur la 15` ?

Si ça ne fonctionne pas, tu peux créer le fichier `replace_chaine.json` dans le répertoire relatif `node_modules/assistant-livebox/` (donc le répertoire `node_modules` qui se trouve dans ton répertoire `assistant-plugins`) en y mettant le code suivant : 
```javascript
{
  "BFM":15
}
```
