### ISSUE TITLE
SyntaxError:

### ISSUE THREAD

**Issue by michel211** [Aymkdn/assistant-plugins#247]
Bonjour, après avoir installer les plugins, fait la configuration du fichier .json, je lance ''start.bat'' et j'obtient l'erreur: SyntaxError: C:\assistant-plugins\configuration.json: Unexpected end of JSON input, donc rien ne fonctionne.
![Sans titre](https://user-images.githubusercontent.com/22713498/58091728-5c949e80-7b98-11e9-990b-0747d80d0df3.png)
 Comme je suis novice dans tout ça, j’avoue que je ne vois pas trop ou ça accroche, si vous pourriez m'aider a résoudre ce problème

**Comment by michel211** [comment]
Bonjour, après avoir lancer ''install.bat'', configurer le fichier .json, lancer ''start.bat'', je me retrouve avec l'erreur: SyntaxError: C:\assistant-plugins\configuration.json: Unexpected end of JSON input, donc vous vous doutiez bien que rien ne fonctionne :/ Si vous pouviez me dire ce qui cloche, ça m'aiderait grandement, moi qui suis newbie dans tout ça
![Sans titre](https://user-images.githubusercontent.com/22713498/58092030-1be95500-7b99-11e9-938f-043b682ed556.png)

**Comment by Aymkdn** [comment]
Ton fichier de configuration est incorrecte. Tu as dû oublier de fermer une `}` ou quelque chose du genre.

Peux-tu le copier ici ?

**Comment by michel211** [comment]
Voila, merci pour le retour 
![Sans titre](https://user-images.githubusercontent.com/22713498/58106512-3aaa1480-7bb6-11e9-8fe6-bbfa64a47bd0.png)

**Comment by Aymkdn** [comment]
Il te manque une `}` dans le bloc `notifier`.

Tu as :  
```javascript
{
    "main": {
    },
    "plugins": {
      "notifier": {
        "host": "...",
        "voice": {
           "source": "...",
           "key": "..."
         }
      }
    }
} <--- celle là est manquante
```

Il en manque une à la fin.

**Comment by michel211** [comment]
Effectivement, merci bcp
