### ISSUE TITLE
programme qui ne se lance pas

### ISSUE THREAD

**Issue by michel211** [Aymkdn/assistant-plugins#248]
Rebonsoir, j'essais de lancer un programme sur le pc avec la commande ''launch'' sans succes. Il recoit bien ma commande, l'execute, mais rien ne s'ouvre. A tout hasard jái aussi essayer avec la commande ''control-windows_cmd exec max'', avec le meme souci, il me retourne la commande mais ne se passe...j'ai encore louper un truc??? 
![Sans titre](https://user-images.githubusercontent.com/22713498/58114343-929c4780-7bc5-11e9-87cb-704b13fb7fc9.png)

**Comment by Aymkdn** [comment]
Tu peux me montrer ce que tu as mis dans l'applet IFTTT ?

**Comment by michel211** [comment]
![Sans titre](https://user-images.githubusercontent.com/22713498/58115442-0a6b7180-7bc8-11e9-9c17-cb01bc61bb89.png)

J'ai aussi essayer avec launch_ même resultat

**Comment by Aymkdn** [comment]
Essaie de lancer manuellement la commande pour commencer, comme je l'explique dans ce commentaire par exemple :  https://github.com/Aymkdn/assistant-plugins/issues/210#issuecomment-454728106

**Comment by michel211** [comment]
si tu voulait savoir si cette commande ''nircmd.exe exitwin poweroff'' fonctionne et bien je peux t affirmer que oui (j ai tout fermer du coup) lol

**Comment by Aymkdn** [comment]
C'était plutôt la commande de lancement de Plex que je voulais que tu testes...

**Comment by michel211** [comment]
Excuse mon ignorance, mais je tappe quel commande au juste (je suis vraiment newbie dans tout ca dsl )

**Comment by Aymkdn** [comment]
Tu fais la même chose que pour `nircmd.exe exitwin poweroff` sauf que tu mets ta commande pour lancer Plex (qui ressemblera à ça) :
```
nircmd.exe exec max C:\.... 
```

Mais je viens de voir que tu n'as pas doublé les `\` dans le chemin d'accès. Remplace tous les `\` par `\\` dans ta commande IFTTT. Je pense que c'est ça ton problème.

**Comment by michel211** [comment]
control-windows_cmd exec max ''C:\\Program Files(x86)\\Plex\\Plex Media Server\\Plex Media Server.exe''...meme probleme :/

**Comment by Aymkdn** [comment]
`control-windows_cmd exec max ''C:\\Program Files (x86)\\Plex\\Plex Media Server\\Plex Media Server.exe''`

**Comment by Aymkdn** [comment]
Sinon fais ce que je t'ai dit : https://github.com/Aymkdn/assistant-plugins/issues/248#issuecomment-494522058

**Comment by michel211** [comment]
oui je viens d''essayer et ca me donne ca---> C:\assistant-plugins\node_modules\assistant-control-windows\bin> "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"

C:\assistant-plugins\node_modules\assistant-control-windows\bin> et rien de plus

**Comment by Aymkdn** [comment]
Et ton serveur Plex ne s'est pas lancé j'imagine ?
T'es sûr que c'est le bon fichier à lancer ? Quand tu cliques dessus ça lance le serveur ? 

En tout cas, si ça ne marche pas avec la commande direct, ça ne marchera pas avec le plugin.

**Comment by michel211** [comment]
Bon bizarrement, ca fonctionne maintenant, reste a voir comment lancer la page web maintenant lol. Merci bcp pur ton aide
