### ISSUE TITLE
probleme avec pushbullet

### ISSUE THREAD

**Issue by romain211289** [Aymkdn/assistant-plugins#249]
Bonjour,

J'ai un probleme que je ne sais pas résoudre : 
mes logs :
 Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...
[assistant] (2019-05-30 19:39:25) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-05-31 04:02:56) Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...
[assistant] (2019-05-31 04:03:29) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-05-31 04:29:00) Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...
[assistant] Erreur de connexion avec PushBullet:  { Error: connect ETIMEDOUT 104.154.164.*****
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.154.*******',
  port: 443 }
[assistant] (2019-05-31 04:30:03) Le flux avec Pushbullet a été déconnecté... Tentative de reconnexion...

Mon assistant est mis sur NAS synology

Merci pour ton aide !!

**Comment by Aymkdn** [comment]
Ce sont des problèmes de connexion qui peuvent être dûs à ta connexion internet. Je ne peux rien faire à ça du coup....

**Comment by romain211289** [comment]
problème de connexion ? pourtant je n'ai pas de soucis de ce côté là, j'utilise même d'autre application avec pushbullet qui ne bloque pas.. Je n'ai aucune solution alternative ? :( Merci !

**Comment by romain211289** [comment]
le soucis s'est que je dois rédémarrer le NAS afin que la connexion revienne et je ne vois pas pourquoi..

**Comment by Aymkdn** [comment]
Dans le cas d'assistant plugins, il doit maintenir une connexion en permanence avec Pushbullet. Si ta connexion merdouille le lien peut être interrompue (un time out dans ce cas). 

Tu utilises quel(s) plugin(s) actuellement? Si c'est juste pour le plugin Freebox, celui-ci est dispo en version "cloud". 

La difficulté avec ton problème est que je ne peux pas tester pour trouver une parade. 

Ensuite tu n'es pas obligé de redémarrer ton NAS. Si tu utilises `pm2` tu peux juste redémarrer le process. Si tu utilises un script au démarrage, tu peux juste relancer le script sans tout redémarrer.

**Comment by romain211289** [comment]
J'utilise majoritairement le plugin livebox et kodi de temps en temps. Comment migrer sur le cloud mon installe ? (bien que j'apprécie le faite d'utiliser le NAS pour ça)

**Comment by Aymkdn** [comment]
Il n'y a que le plugin Freebox dans le cloud
