### ISSUE TITLE
power ON allumer le freeplayer 

### ISSUE THREAD

**Issue by alexbi91** [Aymkdn/assistant-plugins#25]
salut

je suis trés curieux de savoir comment fonctionne l'applet allume la télé via la freebox.
Comment c'est possible de connaitre l'état de la freebox ? en plus la mienne est derrière mon routeur sur une autre ip. Ou alors c'est totalement une autre méthode que tu utilises ? et ça m'intéresse de la connaitre
si tu pouvais m'expliquer ça serait cool
merci

**Comment by Aymkdn** [comment]
J'en ai parlé sur mon blog il y a quelques temps déjà : https://blog.kodono.info/wordpress/2016/11/19/detecter-si-le-freebox-player-est-allume-ou-eteint-en-veille-via-les-api-de-free-programmation/

**Comment by alexbi91** [comment]
ok merci pour ton retour

dommage que je n'ai pas les connaissance pour utiliser ça ...

**Comment by ben12** [comment]
A ce propos, il faudrait indiquer quand le README que AirMedia doit être activé sur la freebox. J'ai dû regardé dans le code pour comprendre pourquoi assistant-plugins détecté toujours ma freebox comme éteinte ;)

_Merci pour le boulot Aymeric, ça fonctionne super bien sur mon PI3._

**Comment by Aymkdn** [comment]
@ben12  > c'est écrit sur la première ligne du README.... https://github.com/Aymkdn/assistant-plugins/blob/master/assistant-freebox/README.md

**Comment by ben12** [comment]
Affectivement, j'avoue m’être concentré que sur la partie configuration (juste en dessous) dans les README des plugins en suivant la procédure d'installation :/

**Comment by Aymkdn** [comment]
Pour info, la version 2.0 est en ligne : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0
