### ISSUE TITLE
Plugin livebox : Impossible de zapper sur J-one

### ISSUE THREAD

**Issue by shaavik** [Aymkdn/assistant-plugins#253]
Impossible de zapper sur J one.

Log : 
[assistant] (2019-08-19 19:35:09) Commande reçue:  [ 'livebox_zappe sur J one' ]
[assistant] (2019-08-19 19:35:09) Appel du plugin 'livebox'
[assistant-livebox] Erreur : Chaine j one inconnue

=> J'ai essayé d'ajouter la ligne dans replace_chaine.json mais sans succès:
  "cherie 25":"chérie25",
  "J one":"j-one"
}

**Comment by Aymkdn** [comment]
Dans `replace_chaine.json`, c'est l'inverse qu'il faut mettre : 
```
"j-one":"j one"
```

**Comment by shaavik** [comment]
Merci !
Cela fonctionne maintenant !
