### ISSUE TITLE
TTS aléatoire

### ISSUE THREAD

**Issue by vjooris** [Aymkdn/assistant-plugins#255]
Bonjour,
J'avais configuré Notifier 2.1.6 sur mon Synology et ça a fonctionné PARFAITEMENT pendant des mois ;-)
Depuis quelques mois/semaines, c'est aléatoire : 
J'ai 2 GH, et parfois 
- j'ai les messages sur les deux 
- sur l'un ou sur l'autre
- sur aucun des deux

MAIS, il me fait toujours le BING d'avant chaque message (donc il me semble que le script tourne bien sur le Syno), et j'ai les notifications dans Pushbullet (Assistant notifier_Le facteur vient de passer. 
Serait-ce un problème lié au service utilisé pour générer le mp3 ?
Merci pour ton aide

**Comment by vjooris** [comment]
bonjour,
Merci pour le temps consacré aux recherches.
J'ai installé ton application sur un Synology, avec Node JS 8.0.
Ce qui est TRES TRES surprenant, c'est que avec cette configuration, qui a fonctionné parfaitement pendant des mois, et sans majuscule de DSM ou Node JS, cela fonctionne maintenant aléatoirement (je dirais, ok dans 80 % des cas : parfois tout passe pendant 3 jours, puis 1 sur 2, puis ...) => je n'arrive pas à reproduire systématiquement le problème (ce qui rend d'autant plus difficile sa résolution).

Je n'utilise pas le paramètre Voice.
Mes GH ont des IP fixes, via réservations d'IP. Si l'IP n'était pas correcte, je n'aurais pas le BIP juste avant le message (qui parfois n'est pas dit).
Voici ma config  :

`{
  "main": {
    "pushbullet_token": "o.CdrZikxxxxxxxxxxxxyOqFL6"
  },
  "plugins": {
    "notifier": {
      "host": {
        "hall":"192.168.xxx.xxx",
        "bureau":"192.168.xxx.xxy"
      } 
    }
  }
}
`

**Comment by Aymkdn** [comment]
> je n'arrive pas à reproduire systématiquement le problème (ce qui rend d'autant plus difficile sa résolution)

C'est bien ça la difficulté... Sans connaitre l'origine du problème, alors difficile de trouver une solution :-)

La seule chose que je peux te conseiller, est de changer le paramètre `voice` pour utiliser la voix IBM (voir la doc https://aymkdn.github.io/assistant-plugins/?plugin=notifier) et attendre plusieurs jours pour voir si le problème est toujours là ou pas. Si c'est le cas, alors le soucis venait du Google TTS, sinon, c'est que le problème vient d'ailleurs...

En attendant, je ferme cette issue car je ne peux rien de plus pour toi. N'hésite pas à reposter ici si tu as d'autres informations à partager !

**Comment by vjooris** [comment]
ok, merci pour tes conseils.
Je mets la voix IBM, et te is quoi

**Comment by vjooris** [comment]
pour info,
voici le résultat de mes tests :
Avec la voix IBM, j'ai le même soucis.
J'ai alors installé une VM Debian avec Assistant plugin, et ça fonctionne du feu de dieu ;-)
C'était donc sur Synology que ce n'était pas fiable.
