### ISSUE TITLE
[QUESTION] Envoyer phrase à Google Home avec RPI

### ISSUE THREAD

**Issue by Naografix** [Aymkdn/assistant-plugins#256]
Bonjour,

Merci pour votre plugin, il m'a l'air vraiment top !

Par contre j'ai une petite question avant de commencer : est il possible de simplement faire parler mon Google Home avec une ligne de commande ?
J'aimerais que quand le capteur relié à ma RPI se déclenche, alors une phrase est envoyée à mon Google Home.

Merci de votre aide

**Comment by Aymkdn** [comment]
Oui c'est possible : https://github.com/Aymkdn/assistant-plugins/wiki/Utiliser-le-programme-en-ligne-de-commande

**Comment by Naografix** [comment]
> Oui c'est possible : https://github.com/Aymkdn/assistant-plugins/wiki/Utiliser-le-programme-en-ligne-de-commande

C'est parfait, merci pour cette rapidité ! Du beau travail !
