### ISSUE TITLE
Problème avec fonction livebox_soundDown

### ISSUE THREAD

**Issue by Sapasss** [Aymkdn/assistant-plugins#257]
Bonjour,
Bravo pour ce plugin génial, je configure le pilotage de ma Livabox avec Alexa grace à vous !
J'ai créé quelques trigger sans soucis pour les chaînes que je voulais, mais par contre je n'arrive pas à créer un trigger pour baisser le son d'un seul cran. Mon trigger lance la fonction livebox_soundDown, et quand je dis la phrase clé à Alexa elle l'accepte, mais aucune commande ne s'affiche dans la fenetre d'exécution de nodejs. 
J'ai vu qu'avec votre trigeer pour baisser le son de trois cran, nodejs affiche 
'Commande reçue:  [ 'livebox_soundDown*3' ]'
J'ai donc essayé dans le trigger de mettre la commande livebox_soundDown*1 mais ça ne fonctionne pas non plus.
Est-ce que je me trompe quelque-part ?

Je post cet issue au cas où le projet soit toujours vivant dans vos cartons :o)

Merci d'avance à quiconque pourra m'aider (après tout quelqu'un a peut-être déjà un triger dispo pour ça sur IFTTT 👍 

Sapasss

**Comment by Aymkdn** [comment]
> Mon trigger lance la fonction livebox_soundDown, et quand je dis la phrase clé à Alexa elle l'accepte, mais aucune commande ne s'affiche dans la fenetre d'exécution de nodejs.

Si aucune commande ne s'affiche dans NodeJS, c'est qu'elle n'est pas reçue. Le problème peut être dû à plusieurs facteurs. Regarde là : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

Concernant la commande, si tu envoies un seul `livebox_soundDown` alors ça va descendre d'un cran. Si tu envoies `livebox_soundDown*3` (avec une étoile `*` avant le chiffre), alors la commande va être répétée trois fois.
