### ISSUE TITLE
Assistant Freebox ne reçoit plus les ordres

### ISSUE THREAD

**Issue by lsenecaux** [Aymkdn/assistant-plugins#258]
Bonjour,

Je te recontacte suite à mon installation d'assistant-freebox sur mon synology.
Depuis 2 semaines environ, le serveur ne reçoit plus les commandes que je lui passe via Google Home.
J'ai même tenté une réinstall from scratch, supprimer les autorisations dans le freebox server... rien y fait.
Quand je lance le service à la main, il ne se passe rien : 

`[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 2 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.15)
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.6)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-10-18 17:47:31) Connecté ! Prêt à exécuter les ordres.
`
Aurais tu une idée ?
Merci de ton aide

**Comment by lsenecaux** [comment]
Je précise que depuis mon Google Home, j'ai bien un retour du genre "OK, j'allume la freebox, etc..."

**Comment by Aymkdn** [comment]
Regarde ce qui est indiqué ici : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas

**Comment by lsenecaux** [comment]
Merci pour cette réponse.
Dans IFTTT, j'ai effectivement une erreur "Account has not been used for over a month".
Cependant, j'utilise quasiment tous les jours l'assistant vocal pour piloter ma freebox.
Sais tu comment pallier ce problème ?
merci

**Comment by Aymkdn** [comment]
C'est expliqué là : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#10-action-failure-message-account-has-not-been-used-for-over-a-month

...

**Comment by lsenecaux** [comment]
Impecable Merci.
Désolé de t'avoir dérangé pour si peu... j'aurai du fouillé un peu plus ton wiki ;-)
