### ISSUE TITLE
plugin freebox : replace_chaine ne semble pas fonctionner

### ISSUE THREAD

**Issue by shaavik** [Aymkdn/assistant-plugins#259]
J'ai utilisé le fichier replace_chaine.json du dossier assistant-freebox mais celui-ci ne semble pas fonctionner : 

[assistant] (2019-12-06 19:12:42) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-12-06 19:13:10) Commande reçue:  [ 'freebox_zappe sur J one' ]
[assistant] (2019-12-06 19:13:10) Appel du plugin 'freebox'
[assistant-freebox] Chaine j one inconnue
[assistant-freebox] Aucune action nécessaire.
[assistant-freebox] Commande « zappe sur J one » exécutée

[assistant] (2019-12-06 19:16:41) Commande reçue:  [ 'freebox_zappe sur Chérie 25' ]
[assistant] (2019-12-06 19:16:41) Appel du plugin 'freebox'
[assistant-freebox] Chaine chérie25 inconnue
[assistant-freebox] Aucune action nécessaire.
[assistant-freebox] Commande « zappe sur Chérie 25 » exécutée

Contenu du fichier replace_chaine.json
{
  "mangas": "manga",
  "c star": "cstar",
  "nrj 12": "nrj12",
  "6ter": "6 ter",
  "numero23": "numéro23",
  "rmc decouverte": "rmc découverte",
  "cherie25": "chérie 25",
  "j-one": "J one"
}

**Comment by Aymkdn** [comment]
Je suis en déplacement professionnel là, sans accès à un ordinateur (et sur téléphone c'est pas simple). Je te réponds dimanche ou lundi quand je rentre (quand j'ai trouvé un train pour me ramener ^^)

**Comment by Aymkdn** [comment]
Essaie avec ça :
```json
{
  "chérie25":"cherie25",
  "jone":"j-one"
}
```

**Comment by shaavik** [comment]
Bonsoir,
Toujours pareil :
replace_chaine.json{  "mangas": "manga",  "c star": "cstar",  "nrj 12": "nrj12",  "6ter": "6 ter",  "numero23": "numéro23",  "rmc decouverte": "rmc découverte",  "chérie25": "cherie25",  "jone": "j-one"}admin@diskstation:/volume1/assistant-plugins/node_modules/assistant-freebox$ vi replace_chaine.jsonadmin@diskstation:/volume1/assistant-plugins/node_modules/assistant-freebox$ sudo pkill node                                                        admin@diskstation:/volume1/assistant-plugins/node_modules/assistant-freebox$ tail -f /var/log/assistant-plugi                                       ns.log[assistant] Assistant v2.0.13 : Chargement en cours...[assistant] 5 plugins trouvés.[assistant] Chargement du plugin 'domoticz' (v1.0.0)[assistant-Domoticz] Plugin chargé et prêt.[assistant] Chargement du plugin 'freebox' (v2.0.15)[assistant-freebox] Plugin chargé et prêt.[assistant] Chargement du plugin 'kodi' (v0.1.2)[assistant-kodi] Plugin chargé et prêt.[assistant] Chargement du plugin 'notifier' (v2.1.6)[assistant-notifier] Plugin chargé et prêt.[assistant] Chargement du plugin 'rappel-calendrier' (v1.0.3)[assistant-rappel-calendrier] Lancement du cron.[assistant-rappel-calendrier] Plugin chargé et prêt.[assistant] Connexion au flux de PushBullet...[assistant] (2019-12-09 21:22:13) Connecté ! Prêt à exécuter les ordres.[assistant] (2019-12-09 21:22:28) Commande reçue:  [ 'freebox_zappe sur J one' ][assistant] (2019-12-09 21:22:28) Appel du plugin 'freebox'[assistant-freebox] Chaine j one inconnue[assistant-freebox] Aucune action nécessaire.[assistant-freebox] Commande « zappe sur J one » exécutée[assistant] (2019-12-09 21:22:37) Commande reçue:  [ 'freebox_zappe sur Chérie 25' ][assistant] (2019-12-09 21:22:37) Appel du plugin 'freebox'[assistant-freebox] Chaine chérie25 inconnue[assistant-freebox] Aucune action nécessaire.[assistant-freebox] Commande « zappe sur Chérie 25 » exécutée



    Le dimanche 8 décembre 2019 à 10:43:14 UTC, Aymeric <notifications@github.com> a écrit :  
 
 
Essaie avec ça :
{
  "chérie25":"cherie25",
  "jone":"j-one"
}

**Comment by Aymkdn** [comment]
Faudra que je teste alors. C'est chiant car j'utilise la version dans le cloud maintenant 😜 Je regarde ça demain ou mardi...

**Comment by Aymkdn** [comment]
Alors, j'ai testé et voici le contenu de mon fichier `replace_chaine.json` : 
```json
{
  "mangas":"manga",
  "c star":"cstar",
  "nrj 12":"nrj12",
  "6 ter":"6ter",
  "numero23":"numéro23",
  "rmc decouverte":"rmc découverte",
  "cherie25":"chérie25",
  "j-one":"j one"
}
```

Cependant, avant de relancer l'assistant, tu dois **supprimer le fichier `chaines_free.json`** qui se trouve au même endroit que `replace_chaine.json` afin qu'il mette bien à jour les chaines correctement.

**Comment by shaavik** [comment]
Bonjour,
Cela fonctionne en supprimant le fichier chaines_free.json, ce que je ne faisais pas auparavant. Peut-être faut-il rajouter un commentaire dans le fichier replace_chaine.json à ce propos ?
J'ai finalement le fichier replace_chaine.json suivant :

    "mangas":"manga",    "c star":"cstar",    "nrj 12":"nrj12",    "6ter":"6 ter",    "rmc decouverte":"rmc découverte",    "cherie25":"chérie25",    "j-one":"j one",    "game one plus1":"game one +1",    "paramount channel decale":"paramount channel décalé"}
=> Correction sur 6 ter, suppression de numéro23 (devenu RMC story) et ajout de gameone +1 et Paramount channel décalé.
Merci pour ton aide.


    Le lundi 9 décembre 2019 à 20:01:40 UTC, Aymeric <notifications@github.com> a écrit :  
 
 
Alors, j'ai testé et voici le contenu de mon fichier replace_chaine.json :
{
  "mangas":"manga",
  "c star":"cstar",
  "nrj 12":"nrj12",
  "6 ter":"6ter",
  "numero23":"numéro23",
  "rmc decouverte":"rmc découverte",
  "cherie25":"chérie25",
  "j-one":"j one"
}
Cependant, avant de relancer l'assistant, tu dois supprimer le fichier chaines_free.json qui se trouve au même endroit que replace_chaine.json afin qu'il mette bien à jour les chaines correctement.

**Comment by Aymkdn** [comment]
J'ai modifié `replace_chain.json` pour intégrer les modifications.
