### ISSUE TITLE
Fichier configuration.json sur Raspberry !???

### ISSUE THREAD

**Issue by azalee78** [Aymkdn/assistant-plugins#26]
Bonjour,

Merci d'avance de votre grace, je suis nouveau dans le monde linux, raspberry.
je souhaite mettre en place les commandes vocales pour la freebox revolution.

J'ai installé NodeJs (version v8.9.1 en faisant un nodejs -v) mais ensuite dans le tuto il faut modifier le "configuration.json" mais ou se trouve ce put...in de fichier !!??? :)

Merci d'avance pour votre aide

**Comment by Aymkdn** [comment]
Étape 4 : télécharger l'archive zip et la dézipper... Tu y trouveras le fichier configuration.json

**Comment by azalee78** [comment]
Merci !!!!!!!! 👍

**Comment by azalee78** [comment]
Bonsoir,
J'ai téléchargé l'archive, copiée en Winscp sur le Raspberry PI3 et lancé depuis le dossier l'installation npm install
Pourtant ma version de NodeJS : "nodejs -v : v8.9.1"

Merci de votre aide !!!!


pi@raspberrypi:~/assistant-plugins-master $ npm install
npm WARN package.json assistant-plugins@1.0.0 No repository field.
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.1","npm":"2.14.7"})
/
> websocket@1.0.25 install /home/pi/assistant-plugins-master/node_modules/pushbullet/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make : on entre dans le répertoire « /home/pi/assistant-plugins-master/node_modules/pushbullet/node_modules/websocket/build »
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make : on quitte le répertoire « /home/pi/assistant-plugins-master/node_modules/pushbullet/node_modules/websocket/build »
grunt-contrib-copy@1.0.0 node_modules/grunt-contrib-copy
├── file-sync-cmp@0.1.1
└── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)

promise@8.0.1 node_modules/promise
└── asap@2.0.6

grunt-notify@0.4.5 node_modules/grunt-notify
├── stack-parser@0.0.1
├── semver@5.4.1
└── which@1.3.0 (isexe@2.0.0)

google-tts-api@0.0.2 node_modules/google-tts-api
└── isomorphic-fetch@2.2.1 (whatwg-fetch@2.0.3, node-fetch@1.7.3)

request@2.83.0 node_modules/request
├── aws-sign2@0.7.0
├── forever-agent@0.6.1
├── oauth-sign@0.8.2
├── tunnel-agent@0.6.0
├── is-typedarray@1.0.0
├── caseless@0.12.0
├── safe-buffer@5.1.1
├── stringstream@0.0.5
├── aws4@1.6.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.1
├── performance-now@2.1.0
├── uuid@3.1.0
├── qs@6.5.1
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.17 (mime-db@1.30.0)
├── tough-cookie@2.3.3 (punycode@1.4.1)
├── form-data@2.3.1 (asynckit@0.4.0)
├── hawk@6.0.2 (boom@4.3.1, sntp@2.1.0, hoek@4.2.0, cryptiles@3.1.2)
├── http-signature@1.2.0 (assert-plus@1.0.0, jsprim@1.4.1, sshpk@1.13.1)
└── har-validator@5.0.3 (har-schema@2.0.0, ajv@5.5.0)

castv2-client@1.2.0 node_modules/castv2-client
├── debug@2.6.9 (ms@2.0.0)
└── castv2@0.1.9 (protobufjs@3.8.2)

pushbullet@2.1.0 node_modules/pushbullet
├── clone@2.1.1
├── mime@1.6.0
├── node-forge@0.7.1
└── websocket@1.0.25 (yaeti@0.0.6, typedarray-to-buffer@3.1.2, debug@2.6.9, nan@2.8.0)

grunt@1.0.1 node_modules/grunt
├── grunt-known-options@1.1.0
├── path-is-absolute@1.0.1
├── eventemitter2@0.4.14
├── rimraf@2.2.8
├── exit@0.1.2
├── nopt@3.0.6 (abbrev@1.1.1)
├── iconv-lite@0.4.19
├── coffee-script@1.10.0
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── glob@7.0.6 (fs.realpath@1.0.0, inherits@2.0.3, inflight@1.0.6, once@1.4.0)
├── findup-sync@0.3.0 (glob@5.0.15)
├── grunt-cli@1.2.0 (resolve@1.1.7)
├── js-yaml@3.5.5 (esprima@2.7.3, argparse@1.0.9)
├── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)
├── grunt-legacy-util@1.0.0 (async@1.5.2, getobject@0.1.0, hooker@0.2.3, which@1.2.14, underscore.string@3.2.3, lodash@4.3.0)
└── grunt-legacy-log@1.0.0 (hooker@0.2.3, colors@1.1.2, underscore.string@3.2.3, lodash@3.10.1, grunt-legacy-log-utils@1.0.0)

grunt-replace@1.0.1 node_modules/grunt-replace
├── file-sync-cmp@0.1.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── applause@1.2.2 (cson-parser@1.3.5, js-yaml@3.10.0, lodash@3.10.1)
└── lodash@4.17.4

request-promise-native@1.0.5 node_modules/request-promise-native
├── stealthy-require@1.1.1
├── tough-cookie@2.3.3 (punycode@1.4.1)
└── request-promise-core@1.1.1 (lodash@4.17.4)

grunt-contrib-watch@1.0.0 node_modules/grunt-contrib-watch
├── async@1.5.2
├── tiny-lr@0.2.1 (parseurl@1.3.2, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── lodash@3.10.1
└── gaze@1.1.2 (globule@1.2.0)
pi@raspberrypi:~/assistant-plugins-master $ node index.js
/home/pi/assistant-plugins-master/index.js:47
              let plugin = commande.split("_")[0];
              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
pi@raspberrypi:~/assistant-plugins-master $ nodejs -v
v8.9.1
pi@raspberrypi:~/assistant-plugins-master $

**Comment by Aymkdn** [comment]
Je vais poster une nouvelle version demain. Tu testeras celle là

**Comment by azalee78** [comment]
Ok j'attends avec impatience :)

**Comment by Aymkdn** [comment]
Ça y est c'est en ligne !

L'annonce : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0

**Comment by Aymkdn** [comment]
Pas de retour depuis 4 jours, donc je ferme cette issue.
