### ISSUE TITLE
problème de chargement des modules 

### ISSUE THREAD

**Issue by Cyril56** [Aymkdn/assistant-plugins#260]
Bonjour, 

je rencontre un petit soucis avec le plugin. j'ai bien configuré IFTTT et Pushbullet (après vérification les actions passent sans problème) par contre rien ne se passe sur le serveur !

J'ai donc redémarré le service et voilà le résultat : 

![image](https://user-images.githubusercontent.com/64255424/80203531-99c6a380-8627-11ea-90b8-ca65b5d479ef.png)

Auriez-vous une solution à mon problème SVP ? et au passage un grand merci pour ce boulot qui est juste génial ;) 

Par avance merci 

Cyril

**Comment by Aymkdn** [comment]
Vous avez besoin du module "debug" apparemment!

`npm install debug`

**Comment by Cyril56** [comment]
Merci Aymkdn, 

l'installation du module "debug" à réglé mon problème me reste plus qu'à plancher sur des commandes groupées entre ma freebox et mon ampli Yamaha ;) 

Cyril
