### ISSUE TITLE
Problème IFTTT

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-plugins#262]
Bonjour,
j'utilise IFTTT depuis 2 ans  et tout marche plutôt bien.
mais j'ai dernièrement ajouté un nouvel Applet (cf PJ)
![Sans titre](https://user-images.githubusercontent.com/46280404/83456327-cb6d2e80-a45f-11ea-9654-25bf185aa4b7.png)

Le but de cet applet et de signaler via la Google Home qu'un entretien de mon poêle a été réalisé.
dans cet applet qui envoie une note dans pushbullet, j'ai inscrit 2 phrases.
"Regarde le poil"   (poil phonétiquement passe mieux que poêle) et "Entretien du poil".
La première phrase est bien reconnue par IFTTT et le retour vocal est "OK richard" puis une note est postée sur pushbullet et assistant-plugins réagit.
la deuxième phrase est reconnue également, mais le retour vocal est "OK" et non "OK richard". aucune note postée sur pushbullet, et donc assitant-plugins ne réagit pas.
Je ne comprends pas pourquoi ? je n'ai pas d'autre applet avec la phrase "Entretien du poil"... et encore plus étonnant, si je dis "Entretien jardin" (qui ne correspond à aucun des mes applets, il me dit "OK" !      
c'est comme si il existait un "entretien $" (que j'ai effectivement créé,  il y a qques jours et supprimé ensuite) quelque part avec un retour vocal "OK".... or j'ai exporté le json... analysé celui-ci.... je ne vois aucune anomalie !
Avez-vous déjà rencontré ce problème ? si oui, que faire ?

cldt

Richard

**Comment by Aymkdn** [comment]
Ce problème n'est pas du tout lié à assistant-plugins.... Avant de fermer cet issue je vais vous donner des pistes malgré tout. 

Dans IFTTT vous pouvez voir les applets qui sont triggered là https://ifttt.com/activity ce qui vous permettra de voir si c'est lié à IFTTT ou non. 

Et vous pouvez faire la même chose avec Google https://myactivity.google.com/myactivity

Vous découvrirez ainsi peut être qu'est-ce qui fait réagir Google avec cette commande....
