### ISSUE TITLE
Nouveau plugin: Cityscoot

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-plugins#263]
Hello, j'ai fait un nouveau plugin pour Cityscoot

Tu le trouveras ici : https://github.com/jzarca01/assistant-cityscoot

**Comment by Aymkdn** [comment]
OK, merci ! Je regarde ça dès que j'ai un petit moment :)

**Comment by Aymkdn** [comment]
C'est bon, je viens de le rajouter : https://aymkdn.github.io/assistant-plugins/?plugin=cityscoot

Merci ! T'es le plus actif dans la création de plugin et sûrement dans l'utilisation de Assistant Plugins aussi 👍
