### ISSUE TITLE
help assistant_notifier avec webhooks de ifttt

### ISSUE THREAD

**Issue by misterg94** [Aymkdn/assistant-plugins#265]
Bonjour,

Merci encore pour tous ces outils.
J'utilise l'assistant pour contrôler ma freebox et contrôler les devices de ma box domoticz.

Je viens de découvrir assistant_notifier.

J'arrive bien à faire le test avec ce qui est écris dans la doc : OK Google google répète la phrase xxxx... et là google répète bien la phrase (ifttt de type google assistant et le pushbullet notifier_{{TextField}}.

Par contre j'essai de créer un webhooks sur ifttt mais je n'y arrive pas.
En gros je souhaiterai lancer une diction de phrase par une requête http. Je ne sais pas si ce que j'essai est la bonne manière.

J'ai crée un webhooks (This) que j'ai nommé google_parle, en that j'ai configuré un pushbllet avec le nom "Assistant" et le message notifier_{{value1}}.

j'ai récupéré ma key sur ifttt sur la page https://ifttt.com/maker_webhooks/settings

Lorsque je lance l'url suivante : https://maker.ifttt.com/trigger/google_parle/with/key/xxxxxxx?value1=test

Sachant que mon but est de faire lire une phrase, donc avec des espaces...

J'obtiens bien la réponse dans mon navigateur "Congratulations! You've fired the google_parle event". Par contre rien ne sort de ma google home.

Je pense que je l'utilise pas la bonne méthode.

De quelle manière je pourrais procéder ?
Une idée ?

Merci pour l'aide apportée :)

**Comment by Aymkdn** [comment]
Regarde dans la console d'Assistant Plugin si quelque chose est reçu, et si oui, quoi...

**Comment by misterg94** [comment]
hum quel console ?
Je lance l'assistant-plugins via crontab -e en redirigeant la sortie vers un fichier :
`@reboot /home/pi/node-v10.22.0-linux-armv6l/bin/node /home/pi/assistant-plugins/index.js >> /home/pi/assistant-plugins/assistant-plugins.log &`

voici ce que j'ai :
```
pi@raspberrypi:~/assistant-plugins $ cat assistant-plugins.log
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 3 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.15)
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.8)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-07-30 12:59:37) Connecté ! Prêt à exécuter les ordres.
```

Lorsque je dis "OK Google répète la phrase il fait beau aujourd'hui" je n'ai rien de plus dans ce fichier de log.
Idem lorsque je demande d'allumer une lumière par exemple.

**Comment by Aymkdn** [comment]
Lance le directement, au lieu d'utiliser crontab, afin d'avoir toutes les informations visibles. Normalement ça affiche les commandes reçues.

**Comment by misterg94** [comment]
J'ai killé le process actuel et je l'ai relancé :
`/home/pi/node-v10.22.0-linux-armv6l/bin/node /home/pi/assistant-plugins/index.js`

Mais même comme ça, il n'y a rien d'autre :
```
pi@raspberrypi:~/assistant-plugins $ /home/pi/node-v10.22.0-linux-armv6l/bin/node /home/pi/assistant-plugins/index.js
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 3 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.15)
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.8)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-07-30 14:20:44) Connecté ! Prêt à exécuter les ordres.

```

**Comment by misterg94** [comment]
Par contre avec le module freebox j'ai bien des infos qui s'affiche :
```
[assistant] (2020-07-30 14:23:10) Commande reçue:  [ 'freebox_on' ]
[assistant] (2020-07-30 14:23:10) Appel du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 2993ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50404992&key=power
[assistant-freebox] Commande « on » exécutée
```

**Comment by Aymkdn** [comment]
Ce n'est pas normal… Il devrait afficher (par exemple) :
```
[assistant-notifier] (salon,bureau) Lecture du message : La température extérieure est de 32,2 degré
```

Si rien ne s'affiche, c'est que l'info n'arrive pas jusqu'à toi. Vérifie sur https://ifttt.com/activity pour voir si l'applet est bien exécutée ainsi que dans https://www.pushbullet.com/#following/ pour voir si c'est bien reçu.

Au passage, je te conseillerai de passer par https://assistant.kodono.info/freebox/ plutôt que le plugin Freebox qui n'est plus mis à jour !

**Comment by misterg94** [comment]
J'ai pas eu le temps de modifié mon post :)

J'ai bien des éléments qui s'affichent...

```
pi@raspberrypi:~/assistant-plugins $ /home/pi/node-v10.22.0-linux-armv6l/bin/node /home/pi/assistant-plugins/index.js
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 3 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.15)
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.1)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.8)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-07-30 14:20:44) Connecté ! Prêt à exécuter les ordres.

[assistant] (2020-07-30 14:23:10) Commande reçue:  [ 'freebox_on' ]
[assistant] (2020-07-30 14:23:10) Appel du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 2993ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50404992&key=power
[assistant-freebox] Commande « on » exécutée
[assistant] (2020-07-30 14:24:28) Commande reçue:  [ 'freebox_off' ]
[assistant] (2020-07-30 14:24:28) Appel du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 839ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50404992&key=power
[assistant-freebox] Commande « off » exécutée

[assistant] (2020-07-30 14:26:05) Commande reçue:  [ 'notifier_il fait beau aujourd \' hui' ]
[assistant] (2020-07-30 14:26:06) Appel du plugin 'notifier'
[assistant-notifier] (tous les Google Home) Lecture du message : il fait beau aujourd ' hui
```

Par contre je n'ai rien lorsque j'appel l'URL https://maker.ifttt.com/trigger/google_parle/with/key/xxxxxxx?value1=test .
J'ai rien dans l'activity de ifttt et pushbullet.

**Comment by Aymkdn** [comment]
Je viens de créer une applet avec l'appel https://maker.ifttt.com/trigger/test_param/with/key/dph-xxxxx?value1=bonjour et ça fonctionne : 
```
[assistant] (2020-07-30 14:45:02) Commande reçue:  [ 'notifier_bonjour' ]
[assistant] (2020-07-30 14:45:02) Appel du plugin 'notifier'
[assistant-notifier] (salon,bureau) Lecture du message : bonjour
```

Donc ton problème vient de ta configuration avec IFTTT

**Comment by misterg94** [comment]
Voici mes captures d'écrans dans un fichier PDF lors du paramétrage dans ifttt 👍
[https://www.fromsmash.com/tKQQJ8l2Bx-ct](https://www.fromsmash.com/tKQQJ8l2Bx-ct)

est-ce que tu vois une coquille, ou peut-être que tu as mis autre chose ?

**Comment by Aymkdn** [comment]
Dans ce cas précis l'appel se fera avec l'url : https://maker.ifttt.com/trigger/test_assistant_notifier/with/key/iVWuxxxxxxxqt-GEJzoWA?value1=bonjour

Sinon tout me parait correct.

**Comment by misterg94** [comment]
bon ça me rassure..... je deviens pas fou !
A tout hasard, je viens de renouveler la clé sur ifttt et ça fonctionne.
La nouvelle est beaucoup plus courte.

**Comment by Aymkdn** [comment]
Du coup je ferme cette issue :)
