### ISSUE TITLE
Rediriger l'ordre vers le bon raspberry pi

### ISSUE THREAD

**Issue by superiuspi** [Aymkdn/assistant-plugins#266]
Bonjour,
j'ai 2 pi avec assistant-launch installé , je souhaite savoir si il y a un moyen de rediriger la requête pushbullet vers le assitsant-launch de mon choix ?
Je souhaite pouvoir paramétrer mon ordre depuis ifttt pour que le script soit exécuté sur le assistant_launch de mon choix (donc le pi de mon choix )
Je sais que je peux faire du ssh de l'un vers l'autre mais bon si je peux le faire directement ...
Merci pour ton aide .

**Comment by Aymkdn** [comment]
Il faudrait utiliser deux comptes Pushbullet et donc deux comptes IFTTT dans ce cas....

L'autre solution serait de modifier Assistant Plugin pour permettre une telle chose. Je veux bien regarder mais j'ai peu de temps en ce moment pour ça, donc il ne faudra pas être trop pressé !
