### ISSUE TITLE
Changements de IFTTT

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-plugins#267]
Maintenant que IFTTT est passé à un modèle gratuit très limité (3 applets) comment on pourrait faire pour s'en passer ?

**Comment by Aymkdn** [comment]
C'est une bonne question… IFTTT est le seul service qui propose une façon simple de répondre à des commandes vocales venant de Google.

Peut-être en utilisant DialogFlow (https://dialogstudio.com/google-home-dialogflow/) ?
De quelle façon utilises-tu `assistant-plugins` ?

Sinon, il existe une astuce (que je ne veux pas trop ébruiter sinon IFTTT va sûrement la bloquer) : il est possible de créer un service depuis lequel on peut créer des applets pour soi-même, de façon illimitée…

Il faut aller sur https://platform.ifttt.com/p/PSEUDO_IFTTT/applets/published puis cliquer sur **Personal Applets** puis sur **+New Org** : 
![Capture](https://user-images.githubusercontent.com/946315/93714445-eeccfe00-fb62-11ea-8fcf-4f13c2c6044f.PNG)

Ensuite on peut entrer un truc bidon, puis cliquer sur l'onglet **Applets** puis sur **New Applet**, et de là créer pour soi-même les applis qu'on veut (pas besoin de les publier normalement) et de l'activer : 
![Capture](https://user-images.githubusercontent.com/946315/93714513-79156200-fb63-11ea-8ed8-df04c4f17098.PNG)

**Comment by superiuspi** [comment]
oui j'ai vu cela aussi et cela me permet de créer toutes les règles ifttt.
Par contre pushbullet est limité a 100 notes par mois et je suis arrivé à la limite .
Je me demandais s'il y avait un moyen d'envoyer à assistant plugin autrement que par pushbullet ... un webhook par exemple ...
Une idée ???
