### ISSUE TITLE
Problème pour activer les Applets IFTTT

### ISSUE THREAD

**Issue by Gizmo696** [Aymkdn/assistant-plugins#268]
Bonjour, 

Quand je veux prendre des applets Google Home pour IFTTT depuis https://aymkdn.github.io/assistant-plugins/?plugin=livebox
J'ai a chaque fois des pages de IFTTT en page 404. Sont ils encore d'actualité ? 

Merci à vous 

Cordialement

**Comment by Aymkdn** [comment]
Toutes les applets ont été désactivées lorsque IFTTT est passé payant (en septembre dernier). Il vous faudra créer vous-même les applets – en sachant qu'IFTTT limite désormais à 3 applets gratuites.

J'irai mettre à jour la page du plugin pour refléter ces changements !

**Comment by Gizmo696** [comment]
Ah ok, Merci de votre réponse rapide. Je vais donc essayer de les faire moi même. 

Cordialement

**Comment by Aymkdn** [comment]
Voilà je viens de mettre à jour la doc.

Désolé de ne pas pouvoir en faire plus, mais n'ayant pas la Livebox je me consacre plutôt à la [Freebox](https://assistant.kodono.info/freebox) que j'ai à la maison.

Je vais fermer cet _issue_, cependant n'hésitez pas à me poser des questions ici si besoin.
