### ISSUE TITLE
probleme de configuration 

### ISSUE THREAD

**Issue by steve59134** [Aymkdn/assistant-plugins#269]
voila se que j'ai quand j'ai fini de faire toute la configuration, si vous pouvez m'aider merci 
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Users\Steve\Downloads\assistant-plugins\configuration.json: Unexpected token : in JSON at position 10
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.exports.start (C:\Users\Steve\Downloads\assistant-plugins\node_modules\←[4massistant-plugins←[24m\index.js:4:23)
    at Object.<anonymous> (C:\Users\Steve\Downloads\assistant-plugins\index.js:1:30)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m

C:\Users\Steve\Downloads\assistant-plugins>

**Comment by Aymkdn** [comment]
Vous avez un problème avec votre `configuration.json` comme une virgule manquante, ou des accolades manquantes...

**Comment by steve59134** [comment]
comment puis-je voir ou il manque une virgule ou accolades

**Comment by Aymkdn** [comment]
En le copiant ici que je vous aide ?

**Comment by steve59134** [comment]
je n'ai pas mis mon adresse IP 
{
  "main": {
    "pushbullet_token":"o.Oae9uaVDuSqH5kGl10wE3btFObh4egfM"
  },
  "plugins": {
    "ifttt": {
      "key":"dph-clYnSzJlWAPAoblaz-Bd0Z"
    },
    "livebox": {
      "ip_box": "IP",
      "autres_chaines":[
     {"canal":"1001","nom":"ma chaine 1"},
     {"canal":"1002","nom":"ma chaine 2"},
     {"canal":"1003","nom":"ma chaine 3"},
     {"canal":"1005","nom":"ma chaine 5"},
     {"canal":"1006","nom":"ma chaine 6"},
   ]
    },
    "notifier": {
      "host": "2.32.111"
    }
  }
}

**Comment by Aymkdn** [comment]
Peut-être la virgule en trop à la fin de la ligne 
`{"canal":"1006","nom":"ma chaine 6"}`

```json
{
  "main": { 
  
  "pushbullet_token":"o.Oae9uaVH5kGl10wE3btFObh4egfM"
  },
  "plugins": {
    "ifttt": {
      "key":"dph-clYnSzJlPAoblaz-Bd0Z"
    },
    "livebox": {
      "ip_box": "IP",
      "autres_chaines":[
         {"canal":"1001","nom":"ma chaine 1"},
         {"canal":"1002","nom":"ma chaine 2"},
         {"canal":"1003","nom":"ma chaine 3"},
         {"canal":"1005","nom":"ma chaine 5"},
         {"canal":"1006","nom":"ma chaine 6"}
      ]
    },
    "notifier": {
      "host": "2.32.111"
    }
  }
}
 ```

**Comment by steve59134** [comment]
merci beaucoup je viens de refaire comme vous m'avez dit et sa marche merci.
