### ISSUE TITLE
livebox et google home

### ISSUE THREAD

**Issue by steve59134** [Aymkdn/assistant-plugins#270]
re autre problème ma google home reconnait mon APPLET créer mais aucun effet sur ma livebox
pouvez-vous m'aider. merci

**Comment by Aymkdn** [comment]
Pas évident d'aider avec 0 information....

Qu'avez-vous mis dans l'applet ? Qu'affiche la console d'assistant-cloud ? Avez-vous mis la bonne IP locale de votre box ?

**Comment by steve59134** [comment]
l' IP de ma box je l'ai prise sur MonIP.org

Qu'est-ce que tu veux dire?
allume la livebox
Quelle est une autre façon de le dire? (optionnel)

Et une autre façon? (optionnel)

Que voulez-vous que l'assistant dise en réponse?
ok, j'allume la livebox
Langue
français
Pousser une note
Pousser une note
Cette action enverra une nouvelle note dans votre boîte de réception Pushbullet.

Titre (facultatif)
assistant

Ajouter un ingrédient
Message (facultatif)
livebox_on

Ajouter un ingrédient

**Comment by steve59134** [comment]
par contre je suis un novice
assistant cloud ???

**Comment by Aymkdn** [comment]
Je voulais dire `assistant-plugins`. La fenêtre où tu lances le programme.

L'IP de la box ne peut pas se trouver avec un site internet... C'est l'IP du réseau local qu'il faut. Lis la documentation : https://github.com/Aymkdn/assistant-livebox#param%C3%A8tre-ip_box

**Comment by Aymkdn** [comment]
L'IP de ta box est probablement 192.168.0.1 ou 192.168.1.1 ou similaire. Regarde la documentation pour la trouver.

**Comment by steve59134** [comment]
c'est bon j'ai trouver l'adresse IP, je teste sa demain je vous tiens au courant du résultat. merci pour votre patience.

**Comment by Aymkdn** [comment]
Ok, donc les commandes n'arrivent pas jusqu'à Assistant Cloud visiblement.

Regarde dans IFTTT si ton applet s'est exécutée sans problème : https://ifttt.com/activity

**Comment by Aymkdn** [comment]
Steve, parle ici, dans cette discussion. N'en commence pas d'autres stp.

**Comment by steve59134** [comment]
Ah ok j’avais pas compris

**Comment by steve59134** [comment]
Oui dans ifttt l’AppleT est bien visible

**Comment by steve59134** [comment]
En faite l’Applet a fonctionner dans l’ifttt tt le dérouler est présent
mais aucune réaction de la livebox

**Comment by Aymkdn** [comment]
Dans la fenêtre noire, on devrait voir la commande arrivée. Mais là on ne voit rien à part les informations de lancement. 

Si dans les activités de IFTTT tu ne vois aucune erreur, alors le problème se passe entre Pushbullet et ton ordinateur.

Peux-tu me montrer ce que tu as dans le channel IFTTT de Pushbullet https://www.pushbullet.com/#following/uffRkDdsjAchDktfdk ?

**Comment by steve59134** [comment]
![IMG-1067](https://user-images.githubusercontent.com/78698162/107414836-d90ca500-6b12-11eb-917b-535a676804df.JPG)

**Comment by Aymkdn** [comment]
On est d'accord que tu gardes la fenêtre noire ouverte ? Et tu n'y vois que ça et rien d'autre ?
![IMG-1065](https://user-images.githubusercontent.com/78698162/107405059-33076d80-6b07-11eb-911d-bbb52f8ee871.jpg)

**Comment by steve59134** [comment]
en faite la fenêtre noire je me suis rendu compte aujourd'hui que je ne l'avait pas laisser ouverte. 
donc sa peu être a cause de ça

**Comment by steve59134** [comment]
bonjour
me revoila la fenêtre noir reste ouvert depuis hier ce matin je fait ma demande a google home il la reçois la livebox aucune réaction et sur la fenêtre noir rien ne s'affiche.

**Comment by Aymkdn** [comment]
Vérifie que ton token Pushbullet est le bon, celui que tu as mis dans le fichier de configuration.

**Comment by steve59134** [comment]
j'ai vérifier c'est le bon.

**Comment by Aymkdn** [comment]
Dans ton applet IFTTT, le titre que tu mets pour la notification Pushbullet doit être « Assistant » avec un « A » majuscule. Toi tu as mis « assistant ».

**Comment by steve59134** [comment]
ah bah voila tout fonctionne je te remercie de ta patience. la livebox s'allume tout de suite 
après avoir fait ma commande
merci d'avoir pris le temps de m'aider

**Comment by Aymkdn** [comment]
OK cool !
