### ISSUE TITLE
re même problème

### ISSUE THREAD

**Issue by steve59134** [Aymkdn/assistant-plugins#271]
bonjour
Toujours le même problème ma google home reçois bien les commandes mais ma livebox ne réagi pas 
pourtant tout est fait correctement après toutes les modifs effectuer en correction. 
quand je fais start bats il me met bien qu'il a trouver les plugins et les chargement s'effectue puis il me dit prés a être commander.

**Comment by Aymkdn** [comment]
Si c'est bien configuré alors dans la fenêtre noire qui s'ouvre avec le start.bat tu devrais voir la commande de la Livebox arriver depuis IFTTT.

Peux-tu me faire une capture d'écran de cette fenêtre après avoir donné une commande vocale ?

**Comment by Aymkdn** [comment]
Je ferme celui-ci aussi
