### ISSUE TITLE
demande d'info

### ISSUE THREAD

**Issue by steve59134** [Aymkdn/assistant-plugins#273]
bonjour
voila comment faire en sorte que ma google home active Netflix sur ma télé??
merci d'avance

**Comment by Aymkdn** [comment]
Il faut soit utiliser Assistant Cloud https://assistant.kodono.info/freebox/
Soit si tu veux utiliser le plugin Freebox d'assistant-plugins alors il te faudra créer une applet personnalisée qui simule l'enchaînement des appuis télécommandes pour te rendre dans le bon menu : https://aymkdn.github.io/assistant-plugins/?plugin=freebox

À noter que tu peux lancer Netflix mais pas lancer un programme en particulier sur Netflix.

**Comment by steve59134** [comment]
Ok sa marche merci pour les infos
