### ISSUE TITLE
Limite pushbullet 

### ISSUE THREAD

**Issue by superiuspi** [Aymkdn/assistant-plugins#274]
bonjour,
Pushbullet est limité a 100 notes par mois et je suis arrivé à la limite .
Je me demandais s'il y avait un moyen d'envoyer les infos à assistant plugin autrement que par pushbullet ... un webhook par exemple ...
Une idée ???

**Comment by Aymkdn** [comment]
Pour avoir un Webhook, il faut avoir un serveur qui tourne sur la machine. Le principe d'`assistant-cloud` est d'avoir un système simple (donc pas de serveur à installer, ni de devoir ouvrir des ports, etc).

Donc si on ne veut pas passer par tout ça, il faut trouver un service accessible depuis IFTTT et qui peut être _monitoré_ par `assistant-plugins`. Pushbullet était le plus apte à répondre à tous les critères.

Si tu me trouves un autre service, je suis prêt à regarder ce qu'il peut être fait. Sinon il faudra qu'`assistant-plugins` ait un plugin qui permet de lancer un serveur local pour recevoir des webhooks…

Puis-je te demander comment tu utilises `assistant-plugins` pour arriver à la limite ?

(Bien sûr il reste l'option de prendre l'option Pro de Pushbullet sinon)

**Comment by superiuspi** [comment]
Ok merci pour ta réponse .
En fait, j'ai fait mon propre plugin assistant("domo" je sui pas aller cherché loin !) qui me sert à piloter ma domotique . j'utilise beaucoup aussi le plugin launch_bash (utilisé avant de faire mon propre plugin)qui me permet d’exécuter mes scripts de gestion de lumière et autres sur mes raspberry pi mais aussi je commande kodi à la voix  (via pushbullet).
Et enfin j'utilise le plugin freebox ...
J'ai pensé à l'option pro de Pushbullet aussi mais j'explore d'abord les solutions gratuites ... 
J'utilise home assistant alors je vois si je peux trouver une autre solution que pushbullet.Mais il faut avouer que pushbullet est très pratique avec assistant-plugin pour tourner sur différents raspberry pi. (je l'utilise sur un pi 3 , un Pi0w et un pi 4! )

**Comment by superiuspi** [comment]
oui je m'en sert déjà mais tu ne peux pas passer de paramètres .Quand tu appelles un script de home assistant mis a dispo dans google home , tu ne peux pas ajouter  le "TextField" comme dans ifttt donc ça veux dire faire un script pour chaque commande vocale ... !!!

**Comment by superiuspi** [comment]
Je suis en train de décortiquer GoogleHomeKodi qui lui reçoit des webhoooks ...

**Comment by Ybbet** [comment]
@superiuspi : si tu utilises Home Assistant, tu peux essayer de voir l'utilisation de rest_command. 
Un exemple : https://community.home-assistant.io/t/running-a-shell-command-from-home-assistant-to-remote-linux-pc/135221/7
Tu pourrais utiliser MQTT pour ton besoin… peut-être.
Des pistes ici : https://www.home-assistant.io/blog/2017/03/28/http-to-mqtt-bridge/
https://github.com/petkov/http_to_mqtt

Pour HA et GH, perso, j'ai pris l'abonnement à Nabu Casa, cela simplifie la vie. :-) 
L'interfaçage par DuckDNS se fait aussi très bien.

**Comment by superiuspi** [comment]
@Ybbet merci .
Mais j'utilise déjà les commandes shell via HA et pour le http to mqtt il y a aussi un intermédiaire "cloud" payant.
L’interfaçage duckdns est ok pour moi mais l'api webhook me limite trop .
Je ne suis malheureusement pas assez calé pour créer mon propre serveur nodejs  alors j'essaye de trouver quelque chose d’équivalent et je le bidouille ... d'ou mon intérêt pour assistant-plugin.

**Comment by Ybbet** [comment]
@superiuspi ah mais ton serveur nodejs... Tu l'as déjà avec Assistant-Plugins :-) C'est du nodejs.
Donc, il te suffirait de suivre la démarche décrite dans la doc pour avoir du MQTT to Nodejs. Il faudrait que j'écrive un article (par curiosité) sur le sujet MQTT/HTTP/NODEJS.

Je ne cache pas, que depuis j'utilise HA (sur un RaspberryPi4), j'utilise beaucoup moins Assistant Plugins mais je garde un oeil sur son développement car j'aime le projet.
J'ai installé sur le raspberry pi 3b+ qui fait tourner assistant-plugins, le serveur MQTT. Et ça ne bronche pas. On pourrait de ce fait adapter la doc http_to_mqtt pour fonctionner avec le serveur MQTT local. Et comme tu es habitué à duckDNS, une url externe pour IFTTT. Bref, je lance l'idée en l'air comme ça. :-)
