### ISSUE TITLE
Suggestion d'idée en lien avec Google Assistant

### ISSUE THREAD

**Issue by raphpitt** [Aymkdn/assistant-plugins#28]
Dans les fichiers et dans la configuration des protocoles eux-mêmes, je n'ai vu aucune mention portant sur le simple Google Assistant présent sur nos smartphones.

J'ai été bloqué avec notifer puisque celui-ci demande à être configuré avec un Google Home.

Peut-on utiliser l'assistant sans Google Home ?

**Comment by Aymkdn** [comment]
`notifier` est pour le Google Home. Donc il suffit de ne pas l'installer si tu n'as pas de Google Home !
