### ISSUE TITLE
Google Assistant ne reconnait pas

### ISSUE THREAD

**Issue by Randwic** [Aymkdn/assistant-plugins#29]
Hello

Merci pour le boulot effectué, mais ça ne fonctionne pas pour moi, j'ai suivi je pense scrupuleusement les étapes une par une, mais google ne reconnais aucune des commandes proposés, je ne comprends pas pourquoi.

**Comment by Aymkdn** [comment]
Plusieurs choses :
- vérifie que sur IFTTT tu as associé le compte Google que tu utilises sur Google Home (ou sur ton téléphone)... Si ce n'est pas le même compte ça ne marchera pas ! 
- si tu testes sur un Google Home, alors teste aussi sur le Google Assistant de ton téléphone afin de voir s'il retranscrit ta parole correctement 
- vérifie que l'applet est bien activée dans IFTTT

**Comment by yakouz** [comment]
Bonjour,

Tout d'abord merci pour ton idée!
J'ai un petit soucis, le même que @Randwic je pense, cad mon google home repère les commandes et me répond mais rien ne se passe. Voila ce qu'il met dans cmd : 

_(node:6728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined
 (node:6728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code_

Quand je change le box_to_control de "hd1" à "mafreebox" (il me semble que hd1.freebox.fr ne marche plus sous freebox révolution mais mafreebox.freebox.fr si), voila ce qu'il me marque : 

_[assistant-freebox] Erreur : le code télécommande fourni (XXXXXXXX) est incorrect !
[assistant-freebox] Commande « off » exécutée_

Or j'ai vérifié plusieurs fois le code télécommande est bon...

PS ; J'ai bien AirMedia Video d'activé.

Merci de ton aide

**Comment by Aymkdn** [comment]
@yakouz  regarde ce que j'ai marqué ici : https://github.com/Aymkdn/assistant-plugins/issues/30

**Comment by Aymkdn** [comment]
Et non, `mafreebox` est le Freebox Serveur, alors qu'on veut commander le Freebox Player ici. Donc soit `hd1` soit `hd2`.

**Comment by yakouz** [comment]
@Aymkdn autant pour moi, l'erreur est pour moi pour _mafreebox_ ; j'ai testé _hd2_ effectivement ça a marché. Petite question ? Peut-on rajouter une deuxième freebox dans le _configuration.json_ ? En effet, je possède un deuxième player, une freeebox mini 4K player.

**Comment by Aymkdn** [comment]
La mini 4k n'est pas compatible.
