### ISSUE TITLE
erreur : cannot read property 'body'....

### ISSUE THREAD

**Issue by Wyman42** [Aymkdn/assistant-plugins#30]
Bonjour, 
L'installation et la configuration sont bonnes (sous Windows 10) mais j'ai une erreur suite à la commande, via Google home : https://www.dropbox.com/s/cga5if0yi8n1f03/nodeJS01.PNG?dl=0
![nodejs01](https://user-images.githubusercontent.com/33159735/33515361-62250ed8-d762-11e7-8254-72b72a416aea.PNG)

**Comment by Aymkdn** [comment]
Quand tu ouvres le lien indiqué dans la console dans ton navigateur (http://hd1.freebox.fr/pub/remote_control?code=86700567&key=power) qu'est-ce qui se passe ?

Car on dirait qu'il n'arrive pas à communiquer avec ta Freebox player.

**Comment by Aymkdn** [comment]
Aussi, essaie le lien avec `hd2` au lieu de `hd1` (donc http://hd2.freebox.fr/pub/remote_control?code=86700567&key=power) si le premier lien ne fonctionne pas.

**Comment by Wyman42** [comment]
Ca fonctionne... l'erreur venait que j'avais un routeur, commandé via la freebox, qui était éteint ! Merci pour l'aide.
