### ISSUE TITLE
Programmation IFTTT

### ISSUE THREAD

**Issue by Wyman42** [Aymkdn/assistant-plugins#31]
Les applets de l'auteur du plugin fonctionne bien mais on ne peut pas éditer leur PushBullet, pour voir leur construction.
J'ai testé d'un faire 1 ainsi, mais rien ne se passe... 
![ifttt01](https://user-images.githubusercontent.com/33159735/33516659-c88640b6-d776-11e7-9b71-a09b0c35f5a5.PNG)

**Comment by Aymkdn** [comment]
C'est IFTTT qui cache cette partie :-(

Dans Title tu dois mettre `Assistant` (et pas "Google Assistant Commands"), et dans Message si c'est pour zapper tu dois mettre : `freebox_zappe {{TextField}}`

**Comment by Wyman42** [comment]
Super.... ou peut on trouver la liste des commandes pour Freebox . freebox_zappe n'est pas noté dans ta page par exemple.

**Comment by Aymkdn** [comment]
Elles sont (quasi) toutes sur la page. Il manque `zappe` et `folder` je pense. Mais en l'occurrence, au lieu de faire un nouvel applet, tu aurais pu modifier l'existant en mettant les phrases de déclenchement de ton choix.
