### ISSUE TITLE
IPX800V3 et Google home

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#32]
bonjour ,
ça n'a pas grand chose a voir avec l'assistant freebox .. mais je te pose la question tout de même Aymeric ,
connais tu le serveur domotique IPX800V3 ? (de chez GCE-Electronic's)
ce la fonctionne très bien avec IFTTT  = une demande " simple phrase " et un trigger  Webhooks pour une action physique sur l' IPX ( comme fermé ou ouvrir un relais  .. )
ma question est:
peut on faire l'inverse ? a savoir qu'une action de l'IPX répercute une notification sur Google home ( une simple phrase donc )

**Comment by Aymkdn** [comment]
> peut on faire l'inverse ? a savoir qu'une action de l'IPX répercute une notification sur Google home ( une simple phrase donc )

Je dirais que oui. Si tu utilises `assistant-plugins` il te faudra installer le plugin `notifier`.
Ensuite : 
  1.  Crée une applet dans IFTTT qui prend en source un WebHook, et en sortie qui envoie une note Pushbullet
  2.  La note Pushbullet doit avoir "Assistant" dans **Title** et "notifier_Le phrase qui sera lue par Google Home" pour le **Message**
  3.  Ton serveur domotique devra alors trigger le WebHook que tu as créé

**Comment by Wyman42** [comment]
Je rajoute : notifier_"Ok ça marche du tonnerre"

**Comment by nusmiaf** [comment]
le problème c'est que je ne maitrise pas les API ,
je ne sais pas comment crée un message push via mon IPX sur chaque entrées / sorties  j'ai la possibilités d'envoyer un mail ou un push a chaque changement d’état .
mais j'ai aucune idée de comment faire
![sans titre](https://user-images.githubusercontent.com/33859641/33519100-2aab0636-d7a0-11e7-97dd-21fb791a537f.png)

**Comment by Aymkdn** [comment]
Après une rapide recherche sur le net ([ici par exemple](http://gurau-audibert.hd.free.fr/josdblog/2014/05/ipx800-fonction-push/)) je pense que dans **Server** tu dois mettre **maker.ifttt.com** et dans **Port** tu dois mettre **443**. Click la case **Enable** et **Save**.

Pour le **Push1** tu mets le path de l'url, donc par exemple **/trigger/*NomDeTonWebHook*/with/key/*TaCléQuiCommenceParDpHXXXX***

**Comment by nusmiaf** [comment]
alors j'ai essayer de crée un applet pour test , donc un IF ,Webhook  que j' appel " relais 30" , ça ok
en suite une action , un pusbullet en note comme tu le décrit plus haut , mais quel doit etre la syntaxe du message ?
![sans titre](https://user-images.githubusercontent.com/33859641/33525037-56b72458-d827-11e7-943a-b9e0065a3f64.png)

j'ai essayer title  = " relais 30 "  et message =  " relais 30 ON " 

ça me repond => 
Unrecognized Ingredient in action field: {{relais}}
Unrecognized Ingredient in action field: {{relais}}

et la clé qui commence pas PDHXXXX   j'imagine que c'est quand l' applet est crée..?

**Comment by Aymkdn** [comment]
Il suffit de relire ce que j'ai noté : 
> La note Pushbullet doit avoir "Assistant" dans Title et "notifier_Le phrase qui sera lue par Google Home" pour le Message

Là dans ton Title tu as mis `{{OccuredAt}}` et dans Message tu as mis un truc qui n'a aucun rapport...

Ensuite, évite les espaces dans le nom de ton WebHook. Donc appelle le "relai30".

Quant à la clé elle se trouve là : https://ifttt.com/maker_webhooks/settings 
![capture](https://user-images.githubusercontent.com/946315/33517365-63c50b82-d783-11e7-8c25-c041dff04d15.png)

Donc le "push1" sera : `/trigger/relai30/with/key/TaClé`

**Comment by nusmiaf** [comment]
désolé la copie d'écran était avant que je renseigne...
alors j'en suis là :
![sans titre3](https://user-images.githubusercontent.com/33859641/33525209-81f00a0a-d82b-11e7-90fc-243194d00c5d.png)
![sans titre](https://user-images.githubusercontent.com/33859641/33525218-a0cceac4-d82b-11e7-90b1-2e368e3d9e63.png)
![sans titre2](https://user-images.githubusercontent.com/33859641/33525220-a32c54c6-d82b-11e7-8a4c-312d6e65c401.png)

mais y a aucun effet au changement d'état du relais

**Comment by Aymkdn** [comment]
Pour IPX j'en sais rien. Je n'utilise pas donc tu dois te démerder....

Pour la note Pushbullet, ce n'est toujours pas correct.... dans la partie **Message** tu dois mettre `notifier_` suivi de ton message. Si tu ne mets pas `notifier_` au début du message, le plugin **notifier** ne sera pas déclenché.

**Comment by nusmiaf** [comment]
ok j'ai corriger le " notifier_XXXX

merci pour ton aide précieuse je vais creuser les paramètre global push de ma machine

j'ai ces liens si tu veux jeter un œil  
=> http://www.domotique-info.fr/script/IPX_API_M2M.pdf
=> http://www.planete-domotique.com/notices/i/p/ipx800_v3_mode_emploi.pdf

**Comment by nusmiaf** [comment]
j'ai uniquement modifier le port 443 par le 80 et là ça passe ! le push part bien ,

j'ai une notification sur l'écran du PC mais rien de l'assistant Google home

![sans titre6](https://user-images.githubusercontent.com/33859641/33525902-50dd9fd8-d838-11e7-866d-529efb804d31.png)

**Comment by Aymkdn** [comment]
Tu as quoi dans la console du plugin ? Ça doit marquer : 
```
[assistant] Commande reçue:  [ 'notifier_relais 30 on' ]
[assistant] Appelle du plugin 'notifier'
```

**Comment by nusmiaf** [comment]
![sans titre7](https://user-images.githubusercontent.com/33859641/33525967-7e7e3320-d839-11e7-8aeb-437ccb3bed80.png)

**Comment by Aymkdn** [comment]
1) As-tu bien configuré le plugin notifier en indiquant la bonne adresse IP pour ton Google Home dans le fichier `configuration.json` ?
2) As-tu bien redémarré l'assistant-plugins après avoir modifié le fichier de configuration ?
3) Ton Google Home est-il bien sur le même réseau que ton PC ?

**Comment by nusmiaf** [comment]
![sans titre8](https://user-images.githubusercontent.com/33859641/33526090-77232f84-d83b-11e7-8a6e-03e0d709fbf0.png)
le " configuration.json " c'est celui a la racine du répertoire assistant-plugins
il y a celui dans le repertoir 
assistant-plugins\node_modules\assistant-notifier\    ,, celui là on y touche pas ?   
IP : 
freebox 192.168.0.2
Pc 192.168.0.11
ipx  192.168.0.31
googlehome 192.168.0.32

**Comment by nusmiaf** [comment]
j'ai tester avec l'ancienne version de l’assistant-plugin ..
ça donne ça :
![sans titre9](https://user-images.githubusercontent.com/33859641/33526999-7cc098a6-d849-11e7-81d0-d49e8179af38.png)

**Comment by Aymkdn** [comment]
Donc oui c'est bien le configuration.json de la racine qu'il faut modifier.

Concernant ton erreur... je sèche :o) Peut-être un problème de firewall ou d'antivirus ?

**Comment by nusmiaf** [comment]
et bien il est bien modifier ( sauf erreur de ma part )
{
  "main": {
    "pushbullet_token": "o._______________________________R"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "1_________8",
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd1",
      "app_token": "C___________________________________________________________________R"
    },
    "ifttt": {
      "key": "c_________________________0"
    },
    "notifier": {
      "host": "192.168.0.32"
    }
  }
}

celui du sous répertoire " assistant-plugins\node_modules\assistant-notifier\...
je l'ai remis tel que d'origine : 
  {
  "host":""
}

je n'ai pas d’antivirus et le firewall laisse sortir/entré les requêtes puisque les applets fonctionnent
même l'applet test que tu fait faire en test  " répète la phrase " fonctionne de la même façon
j'ai bien le retour de pushbullet , avec le popup sur le pc et l'action prise en compte sur la fenêtre CMD

c'est donc forcement une erreur quelque part dans le plugin ( de ma part )

**Comment by Aymkdn** [comment]
Il faudrait déboguer de ton côté pour situer l'erreur... Mais ce n'est pas une chose que je peux t'expliquer :-/

En tout cas, je ne sais pas ce qui peut merder...

As-tu un autre PC ? Pour tester et voir déjà si ça vient de ton PC ?

**Comment by nusmiaf** [comment]
peu etre un coup de teamviewer ?

**Comment by Aymkdn** [comment]
Non, désolé, j'ai beaucoup d'autres choses à faire aujourd'hui...

Essaie sur un autre ordinateur si tu peux.

**Comment by nusmiaf** [comment]
ok j'instal le plugin et je te dit ça

**Comment by nusmiaf** [comment]
alors pareil que sur le PC fixe , les requêtes sortes et son prises en compte
 
![sans titre12](https://user-images.githubusercontent.com/33859641/33527753-65af9272-d856-11e7-804a-a980f2c02f4d.png)

les popup de pushbullet apparaissent sur le PC fixe ( rien sur le portable ) 
et googlehome ne dit toujours rien

par contre je viens de voit en suivant la procédure d'installation que le Update.bat est bien sur l'intallation du potable :
![sans titre13](https://user-images.githubusercontent.com/33859641/33527814-69147648-d857-11e7-98fa-cc696196e53f.png)

 alors que je ne lai jamais eu sur le pc fixe : 

![sans titre14](https://user-images.githubusercontent.com/33859641/33527819-815cbbd4-d857-11e7-9352-860e2ef81c7d.png)

**Comment by Aymkdn** [comment]
Le `update.bat`, ouais je l'ai rajouté tout à l'heure, pour pouvoir faire des mises à jour facilement :-)

Donc ça nous apprend que le problème n'est pas le PC. Donc vraiment là, je ne sais pas... désolé...

**Comment by nusmiaf** [comment]
Pfff  !! ( Lol )moi qui pensait que c'était résolu !  juste que j'avais mal installer du fait de pas avoir fait " update " ...     :-/
dans tous les cas la j'ai tout viré , désinstallé node et de refait tout propre

**Comment by nusmiaf** [comment]
bon voilà j’ai tout  ré-installé , node , assistant , avec les  plugin IFTTT, Notifier, Wait, Freebox
le token pushbulet ok
le code télécommande free ok
la clé Ifttt ok
l'IP de googlehome ok
update Node ok
l’appairage avec la freebox ok 

resultat identique , mais pas un mot....

![sans titre3](https://user-images.githubusercontent.com/33859641/33528168-837cee98-d85c-11e7-84dc-afef18f9ecdb.png)

**Comment by Aymkdn** [comment]
Tu arrives à pinguer ta Google Home depuis ton PC ?

**Comment by nusmiaf** [comment]
oui le ping j'ai tester dès que jai attribuer cette ip a GH en fixe sue sa MAC adresse 
ca ping sans probleme

**Comment by Aymkdn** [comment]
Je suis à court d'idées, désolé...

**Comment by nusmiaf** [comment]
ba si t'a un moment un autre jour ,
tu peut prendre la main sur mon pc ... voir de toi même  si tu veux

**Comment by nusmiaf** [comment]
alors y a un truc improbable avec un autre applet que je viens de crée par acquis pour être sûr ...
le push part bien quand le relais 31 cette fois change d'état .. mais RIEN ne se produit dans la fenêtre CMD
alors qu'il y a bien la notification  PopUp sur le PC  !?   "Chelou"  si je peux me permettre :o
1- j'ai fait " repete la phrase ...caca ..." => ça  apparait
2- relais 30 actionné => ça apparait
3- relais 31 actionné => rien nada
4- relais 30 ré actionné => ça apparait
![sans titre](https://user-images.githubusercontent.com/33859641/33528610-decd8c92-d863-11e7-9828-0eb106778b8f.png)
![sans titre2](https://user-images.githubusercontent.com/33859641/33528612-e31eaf24-d863-11e7-84cc-149360346fd9.png)
![sans titre3](https://user-images.githubusercontent.com/33859641/33528614-e5880652-d863-11e7-9bf5-1defe566af2c.png)
![sans titre4](https://user-images.githubusercontent.com/33859641/33528617-e7ee6bd4-d863-11e7-9026-9b12d4616c6b.png)

**Comment by Aymkdn** [comment]
Ta notification pour relais 31 apparait avec le titre "Google Assistant" au lieu de "Assistant". Du coup il n'est pas reconnu : 
![capture](https://user-images.githubusercontent.com/946315/33528691-c6b2d256-d864-11e7-8913-ac2df6399cef.PNG)

Quoi qu'il en soit, le problème n'est pas là. C'est le plugin notifier qui ne fonctionne pas chez toi.

**Comment by nusmiaf** [comment]
exact ! c'est dans ma tête... j'ai voulu écrire un truc et j'en ai mis un autre google assistant / assistant
comme tu dite de toutes façon ça fait pas parler google home donc , ça fonctionne pas
aller je te remercie encore pour ton aide  ( surtout que je suis un boulet :p )
et comme dit plus haut ... si tu a un moment pour voir ca de toi même
hésite pas  
Merci

**Comment by nusmiaf** [comment]
exact ! c'est dans ma tête... j'ai voulu écrire un truc et j'en ai mis un autre google assistant / assistant
comme tu dite de toutes façon ça fait pas parler google home donc , ça fonctionne pas
aller je te remercie encore pour ton aide ( surtout que je suis un boulet :p )
et comme dit plus haut ... si tu a un moment pour voir ca de toi même
hésite pas
Merci
Ps: tu a peut être en stock un applet avec Notifier fonctionnel pour me monter un exemple ?

**Comment by Aymkdn** [comment]
Tu as tout fait correctement côté applet. Le problème vient du plugin qui n'arrive pas à envoyer à Google Home.

Si tu veux tester des choses, tu peux ouvrir le fichier `notifier.js` qui est dans le dossier `./node_modules/assistant-notifier/`

Puis tu rajoutes des `console.log`. Par exemple dans la fonction `AssistantNotifier.prototype.action` : 
```javascript
AssistantNotifier.prototype.action = function(text) {
  var _this=this;
  return new Promise(function(prom_res) {
    // on génère le texte
    console.log("on entre dans action");
    GoogleTTS(text, "fr-FR", 1)
    .then(function(url) {
      console.log("Google TTS correctement effectué. URL =>", url);
      var client = new Client();
      client.connect(_this.host, function() {
        console.log("Connexion au client");
        client.launch(DefaultMediaReceiver, function(err, player) {
          console.log("Connexion suite");
          var media = {
            contentId: url,
            contentType: 'audio/mp3',
            streamType: 'BUFFERED'
          };
          console.log("lecture du MP3 produit par Google TTS");
          player.load(media, {
            autoplay: true
          }, function(err, status) {
            console.log("tout s'est bien passé");
            player.on('status', function(status) {
              if (status.playerState == "IDLE") {
                player.stop();
                client.close();
                prom_res();
              }
            });
          });
        })
      })
    })
  })
};
```

Puis tu relances le programme et tu regardes les informations qui s'affichent.

**Comment by nusmiaf** [comment]
bonjour , 
j'ai modifier le `notifier.js`  comme suit:

```
var Client = require('castv2-client').Client;
var DefaultMediaReceiver = require('castv2-client').DefaultMediaReceiver;
var GoogleTTS = require('google-tts-api');
var AssistantNotifier = function(configuration) {
  this.host = configuration.host;
}
AssistantNotifier.prototype.init = function(plugins) {
  this.plugins = plugins;
  if (!this.host) return Promise.reject("[assistant-notifier] Erreur : vous devez configurer ce plugin !");
  return Promise.resolve(this);
};

/**
 * Fonction appelée par le système central
 *
 * @param {String} text Le texte à lire (par exemple: "bonjour et bienvenue")
 */
AssistantNotifier.prototype.action = function(text) {
  var _this=this;
  return new Promise(function(prom_res) {
    // on génère le texte
    console.log("on entre dans action");
    GoogleTTS(text, "fr-FR", 1)
    .then(function(url) {
      console.log("Google TTS correctement effectué. URL =>", url);
      var client = new Client();
      client.connect(_this.host, function() {
        console.log("Connexion au client");
        client.launch(DefaultMediaReceiver, function(err, player) {
          console.log("Connexion suite");
          var media = {
            contentId: url,
            contentType: 'audio/mp3',
            streamType: 'BUFFERED'
          };
          console.log("lecture du MP3 produit par Google TTS");
          player.load(media, {
            autoplay: true
          }, function(err, status) {
            console.log("tout s'est bien passé");
            player.on('status', function(status) {
              if (status.playerState == "IDLE") {
                player.stop();
                client.close();
                prom_res();
              }
            });
          });
        })
      })
    })
  })
};

/**
 * Initialisation du plugin
 *
 * @param  {Object} configuration La configuration
 * @param  {Object} plugins Un objet qui contient tous les plugins chargés
 * @return {Promise} resolve(this)
 */
exports.init=function(configuration, plugins) {
  return new AssistantNotifier(configuration).init(plugins)
  .then(function(resource) {
    console.log("[assistant-notifier] Plugin chargé et prêt.");
    return resource;
  })
}
```


résultat en image , pas un mot de GH

![sans titre](https://user-images.githubusercontent.com/33859641/33543565-caea08e4-d8d7-11e7-9117-db3ebad31b22.png)

**Comment by nusmiaf** [comment]
Laisse tomber !
ça fonctionne depuis le début ...... !!!

le volume du sond de la voix de GoogleHome est indépendant du volume du sond pour la lecture du MP3
j'avais le sond au minimum , ( les 4 leds de GH éteintes )
je ne m'en était pas rendu compte car quand je pose des questions/requêtes a GH 
le volume de la voix en réponse est de niveau suffisant , mais le lecture  du reste apparemment non..
avec le sond augmenté ( au moins 1 led allumée sur GH ) j' entend enfin  le fameux " relais 30 on " 👍 
!!!!!!!!!!!!   💃

**Comment by Aymkdn** [comment]
Arf...

**Comment by nusmiaf** [comment]
Merci , Aymkdn 
Merci pour ta patience ( je suis plutôt nul ..les codes et moi... :/ j'ai bcoup de mal a comprendre )
Merci pour ton aide et pour ton travail avec ton "Assistant"

**Comment by nusmiaf** [comment]
bonjour, 
une question , ets il possible de demander l'etat d'une sortie a Google.H ?
avec ifttt ou autre ?

merci

**Comment by Aymkdn** [comment]
Tu veux dire quoi par "l'état d'une sortie"?

**Comment by nusmiaf** [comment]
Pardon , je veux dire ...
Savoir si une sortie est a 1 ou a 0
Toujours sur mes relais de mon ipx 800v3

**Comment by Aymkdn** [comment]
Aucune idée

**Comment by nusmiaf** [comment]
Bonjour Aymeric ,
une question au hasard ,  est il possible de récupéré les " commandes envoyées par une appli de mobile "
a partir du fichier .APK  de cette même appli ?
explication :  j'ai une alarme que je peux armé /désarmé  avec un mode partiel ou total  avec retour d'état sur l'appli 
et évidement  j'aimerai bien avoir les commandes correspondante pour mixé tout ça avec la domotique et Google Home

merci

**Comment by Aymkdn** [comment]
C'est très difficile, voire impossible selon les cas. Cherche sur Google on trouve quelques informations là dessus...

**Comment by nusmiaf** [comment]
ok merci  bcoup

**Comment by nusmiaf** [comment]
Bonjour , Aymeric
est il possible avec Webhooks d'envoyer 2 url distinctes à un interval donner ?
ex :
http://user:mdp@mon_ip/Set_relais1=1&set_relais2=1  ( temps 1 s ou plus )
et 
http://user:mdp@mon_ip/Set_relais1=1


explication , une commande de volet individuelle  demande un appuis double  haut+bas  suivi de haut   ( ou bas )  pour commander une ouverture ou fermeture générale et non individuelle ..

merci pour ta reponse

**Comment by Aymkdn** [comment]
Si ta question est de savoir si IFTTT permet de faire ça nativement, la réponse est non. 

Il faudra utiliser ces deux plugins pour y arriver : 
 https://aymkdn.github.io/assistant-plugins/?plugin=wait
https://aymkdn.github.io/assistant-plugins/?plugin=ifttt
