### ISSUE TITLE
[Error: Cannot find module 'request-promise-native']

### ISSUE THREAD

**Issue by VinceGel** [Aymkdn/assistant-plugins#33]
Bonjour

Je configure l'assistant plugin sur un raspberry P1B, je vais l'utiliser pour le moment juste avec google assistant sur mon téléphone, je n'ai pa encore de google home.
J'ai ajouté les informations sur le fichier de configuration et quand je lance l'instal j'ai :
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'freebox'
{ [Error: Cannot find module 'request-promise-native'] code: 'MODULE_NOT_FOUND' }

Qu'ai je fait de mal?

Merci

vincent

**Comment by Aymkdn** [comment]
Ce message apparait quand tu lances `start.bat`, mais il faut lancer `install.bat` en premier : l'as-tu fait ?

**Comment by VinceGel** [comment]
Sous Raspberry j'ai lancé :
7 - la commande npm install --loglevel error && npm run-script postinstall
8 - rempli le fichier configuration.json
9 - lancé la commande node index.js

et j'obtiens le message mentionné

**Comment by Aymkdn** [comment]
Bizarre alors.

Essaie d'installer le module `request-promise-native` en faisant : `npm install request-promise-native`

**Comment by VinceGel** [comment]
Merci

C'était ça...

Merci pour ce superbe travail...

Vincent
