### ISSUE TITLE
code telecommande eronné

### ISSUE THREAD

**Issue by frhx** [Aymkdn/assistant-plugins#34]
<bonjour j,ai tout installé correctement mais la console me dit que mon code telecommande est erronné alors que j'ai verifié cent fois et c'est le bon
[assistant-freebox] Commande « off » exécutée
[assistant] Commande reçue:  [ 'freebox_off' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=6255637&key=power
[assistant-freebox] Erreur : le code télécommande fourni (6255637) est incorrect !

**Comment by Aymkdn** [comment]
Quand tu essaies d'ouvrir le lien http://hd1.freebox.fr/pub/remote_control?code=6255637&key=power dans ton navigateur, qu'as-tu comme message ?

Et est-ce que la Freebox s'allume / éteint ?

**Comment by frhx** [comment]
non elle s'eteint pas et j'ai ce message quand je colle l'url dans le navigateur
You don't have permission to access this file on this server.
Cheyenne/2.2.8 Server at localhost Port 80

**Comment by Aymkdn** [comment]
Ce message apparait lorsque le code télécommande est incorrect.... Tu n'as qu'un Freebox Player chez toi ?

**Comment by frhx** [comment]
non j'en ai deux

**Comment by frhx** [comment]
mais j'ai bien attribué le nom du bon boitier

**Comment by Aymkdn** [comment]
Ah ! Donc tu essaies sûrement le code télécommande la mauvaise box. Essaie de remplacer `hd1` par `hd2` dans la configuration et de garder le même code télécommande

**Comment by frhx** [comment]
j'ai essayé... ça ne fonctionne pas :-(

**Comment by Aymkdn** [comment]
hd1 représente une box. hd2 représente l'autre box. Ensuite à toi de tester dans ton navigateur avec les différents codes télécommandes et avec hd1 ou hd2. Et de trouver la bonne combinaison.

**Comment by frhx** [comment]
ok je vais essayer mais je n'arrive plus a relancer l'install via node index.js

**Comment by frhx** [comment]
ntaxError: /Users/francoiscounil/Downloads/assistant-plugins/configuration.json: Unexpected token   in JSON at position 154
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.exports.start (/Users/francoiscounil/Downloads/assistant-plugins/node_modules/assistant-plugins/index.js:4:23)
    at Object.<anonymous> (/Users/francoiscounil/Downloads/assistant-plugins/index.js:1:92)

**Comment by frhx** [comment]
"main": {
    "pushbullet_token": "o.BRzzdEnx8Tt7aq8rALIzhxv1nJCxTEed"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "6255637" ,
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd2",
      "app_token": "DDxVAti2iVnAezvn4KPc1WKgn9+lnQTbRl8wQGGpfRZgAiBO3RLADDERL4yNsd6q"
    },
    "ifttt": {
      "key": "oXWZIn2ZI2RObfgbclgBXpLi0cq61sivnxnNSN8Gq_g"
    },
    "notifier": {
      "host": "192.168.0.11"
    }
$

**Comment by Aymkdn** [comment]
Pour le moment, teste dans ton navigateur les différentes URL pour trouver la bonne combinaison.

**Comment by frhx** [comment]
tu avais raison c'est la hd2

**Comment by frhx** [comment]
maintenant je vois pas ou est mon erreur de syntaxe

**Comment by Aymkdn** [comment]
Il manque un `}` à la fin du fichier

**Comment by frhx** [comment]
ou ça

**Comment by Aymkdn** [comment]
Fichier configuration.json

**Comment by frhx** [comment]
{
  "main": {
    "pushbullet_token": "o.BRzzdEnx8Tt7aq8rALIzhxv1nJCxTEed"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "6255637" ,
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd2",
      "app_token": "DDxVAti2iVnAezvn4KPc1WKgn9+lnQTbRl8wQGGpfRZgAiBO3RLADDERL4yNsd6q"
    },
    "ifttt": {
      "key": "oXWZIn2ZI2RObfgbclgBXpLi0cq61sivnxnNSN8Gq_g"
    },
    "notifier": {
      "host": "192.168.0.11"
    }
  }
}

**Comment by frhx** [comment]
la c'est OK ?

**Comment by frhx** [comment]
toujours la meme erreur..

**Comment by Aymkdn** [comment]
Une de trop cette fois... Ça doit être : 
```javascript
{
  "main": {
   "pushbullet_token": "o.BRzzdEnx8Tt7aq8rALIzhxv1nJCxTEed"
  },
  "plugins": {
    "freebox": {
    "code_telecommande": "6255637" ,
    "search_path": "/Disque dur/Vidéos/",
    "use_Mon_Bouquet": false,
    "box_to_control": "hd2",
    "app_token": "DDxVAti2iVnAezvn4KPc1WKgn9+lnQTbRl8wQGGpfRZgAiBO3RLADDERL4yNsd6q"
  },
  "ifttt": {
    "key": "oXWZIn2ZI2RObfgbclgBXpLi0cq61sivnxnNSN8Gq_g"
  },
  "notifier": {
    "host": "192.168.0.11"
  }
}
```

**Comment by frhx** [comment]
je comprends pas

**Comment by frhx** [comment]
desolé d'etre lourd vca ne fonctionne toujours pas

**Comment by frhx** [comment]
SyntaxError: /Users/francoiscounil/Downloads/assistant-plugins/configuration.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.exports.start (/Users/francoiscounil/Downloads/assistant-plugins/node_modules/assistant-plugins/index.js:4:23)
    at Object.<anonymous> (/Users/francoiscounil/Downloads/assistant-plugins/index.js:1:92)
    at Module._compile (module.js:635:30)
iMac-de-francois-8:assistant-plugins francoiscounil$

**Comment by Aymkdn** [comment]
Efface tout et recommence, ça sera plus simple :-)

**Comment by frhx** [comment]
je pense oui je rprends tout à zero

**Comment by frhx** [comment]
merci de ton aide

**Comment by frhx** [comment]
bon ça marche le probleme maintenant quand je lui dit zappe sur une chaine il eteint la freebox

**Comment by Aymkdn** [comment]
As-tu activé le Air Media sur la box que tu souhaites piloter ? (https://aymkdn.github.io/assistant-plugins/?plugin=freebox)

**Comment by Aymkdn** [comment]
Voir https://github.com/Aymkdn/assistant-plugins/issues/35
