### ISSUE TITLE
quand je demande à changer de chaine il eteint la freebox

### ISSUE THREAD

**Issue by frhx** [Aymkdn/assistant-plugins#35]

**Comment by skiman88** [comment]
pareil que toi

**Comment by Aymkdn** [comment]
@frhx  > il faut activer Air Media (comme indiqué [sur cette page](https://aymkdn.github.io/assistant-plugins/))

Si tu l'as fait et que ça ne marche toujours pas, alors ajoute le paramètre `check_player_on` dans ton fichier `configuration.json` qui ressemblera alors à : 

```javascript
{
  "main": {
    "pushbullet_token": "o.szVtF0V3Mntw0AbTWWIUBBJ6rBpBU5k"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "97421754",
      "search_path": "/Disque dur/Vidéos/TV/",
      "use_Mon_Bouquet": true,
      "box_to_control": "hd1",
      "check_player_on":false,
      "app_token": "fbii+YS9sGkvGQb7123E3avpDbVbaJK7SMFkX+63PZKGj0+MUM7QpKaskd0Cu1X"
    }
  }
}
```

Bien penser à redémarrer le programme une fois la configuration changée.
