### ISSUE TITLE
Pb au lancement sous NodeJS Synology

### ISSUE THREAD

**Issue by alfa4684** [Aymkdn/assistant-plugins#36]
Bonjour et merci pour cette initiative que j'attendais depuis quelques mois maintenant.
Malheureusement je ne suis pas encore au bout de mes peines ;)
J'ai ce message d'erreur au lancement

node index.js

[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'freebox'
{ [Error: Cannot find module 'request-promise-native'] code: 'MODULE_NOT_FOUND'

Une idée pour passer à la prochaine étape ?

**Comment by Aymkdn** [comment]
Dans le répertoire principal tape : 
`npm install request-promise-native`

**Comment by Aymkdn** [comment]
Normalement cette commande a dû marcher, donc je ferme cette issue.
