### ISSUE TITLE
projet applet: allume la tele et zappe sur ... quand on a check_player_on

### ISSUE THREAD

**Issue by skiman88** [Aymkdn/assistant-plugins#37]

**Comment by Aymkdn** [comment]
Ça ne veut rien dire... je ferme cette issue.

**Comment by skiman88** [comment]
je reformule excuse moi, maintenant tout marche tres bien et je t en remercie. mais quand je dis allume la tele et zappe sur la .... le google home me repond bien j allume la tele et zappe sur .... mais rien se passe
