### ISSUE TITLE
Config ifttt / notifier

### ISSUE THREAD

**Issue by Orkaelle** [Aymkdn/assistant-plugins#39]
Hello !

D'abord, merci à toi pour cette solution et ce super tuto, ça fait quelques mois que je me creusais la tête pour faire le lien freebox / Google Home mais mes compétences en informatiques étant ce qu'elles sont, je ramais...!
Donc, j'ai un petit soucis en suivant ton tuto : sauf erreur, je crois que les liens vers les configurations de IFTTT et Notifier sont cassés, ça renvoie directement à la page d'accueil du tuto. Du coup, je ne sais pas comment renseigner la "key" IFTTT et le "host" de Notifier dans le fichier de config :-( .

Merci d'avance de ton aide :)

**Comment by Aymkdn** [comment]
Ouais c'était cassé, je viens de corriger ! Désolé ^^
