### ISSUE TITLE
Installer sur MacOS

### ISSUE THREAD

**Issue by TomTomLC** [Aymkdn/assistant-plugins#4]
Hello,
La partie « Double-cliquer sur le fichier install.bat » ne marche pas sur mon Mac.
Il me demande avec quel logiciel lancer les fichiers .bat...
Comment puis-je faire ?
Merci !
Tom

**Comment by LudoMeurillon** [comment]
Les fichiers .bat sont des "scripts" à destination des OS windows.

Sous mac OS, il "suffit" de faire dans un terminal :

`node index.js`

Le système ne fonctionnera par contre qu'uniquement si cette commande est bien en cours d'éxecution.

**Comment by Aymkdn** [comment]
Exact.

Il faut lancer un terminal dans le répertoire en question et taper `node index.js` comme indiqué par Ludo

**Comment by TomTomLC** [comment]
Merci ! 👍 
J'ai lancé un terminal et fait les commandes suivantes : 
iMac-de-xx:Users xx$ cd /Users/xx/Desktop
iMac-de-xx:Desktop xx$ cd assistant-plugins-master
iMac-de-xx:assistant-plugins-master xx$ node index.js 

et j'ai l'erreur suivante : 

module.js:538
    throw err;
    ^

Error: Cannot find module 'pushbullet'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xx/Desktop/assistant-plugins-master/index.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Quel est le problème ?
Tom

**Comment by Aymkdn** [comment]
Tu n'as pas installé les modules associés.

Donc d'abord : `npm install`
Puis tu configures comme indiqué dans la doc.
Et enfin, une fois installé, tu tapes : `node index.js`

Je tâcherai de clarifier ça pour MacOS :-)

**Comment by Aymkdn** [comment]
J'ai complété le [README](https://github.com/Aymkdn/assistant-plugins/blob/master/README.md) pour MacOS et Linux !

**Comment by TomTomLC** [comment]
Ça marche impeccable, merci beaucoup pour le support ! 👍
