### ISSUE TITLE
Idée d'amelioration avec android

### ISSUE THREAD

**Issue by chewblebon** [Aymkdn/assistant-plugins#40]
Bonjour
 juste une question nous avons tous dans nos tiroirs des smartphone et je sais qu'il existe node.js sous android et comme il faut une machine allumée 24h sur 24h est ll possible d'utiliser un smartphone pour faire tourner votre requête 

merci d'avance de savoir ce que vous en pensez

**Comment by Aymkdn** [comment]
En théorie ça devrait être possible. Par contre ça ne serait pas simple à installer (alors que j'ai essayé de trouver une solution simple pour que ce soit ouvert au plus grand nombre), et ça oblige que le téléphone soit toujours connecté au réseau local (et donc dans la maison) et que cela n'impacte ni la batterie ni la mise en veille.... 

Mais si tu veux tenter, fais toi plaisir ;-)

**Comment by chewblebon** [comment]
Bonjour,

je ne suis pas encore passer a la version 2 car je n'est pas de machine qui tourne chez moi 24/24 et je ne veux pas trop investir pour le moment car entre google mini philips hue ce la commence à couter la domotique est cher .

c'etait pour cela comme j'avais un smartphone un wiko rainbows 4g dans un tirroir 

mais je regarderais un rasperry ou une autre solution aprés noel ou la v7 de la freebox pour le moment cela tourne et te remercie
