### ISSUE TITLE
Comment laisser tourner en tache de fond sur syno

### ISSUE THREAD

**Issue by alfa4684** [Aymkdn/assistant-plugins#41]
Bonjour à tous, j'ai installé les plugs sur mon syno. Je lance dans une session sous Putty et tout marche nickel !
Le pb, c'est que lorsque je kill la session putty depuis mon pc windows 10, bah... Y a plus rien qui tourne.
Connais rien à linux. Comment je m'assure que index.js tourne sur nodeJS de mon syno en continu ?

Merci à tous pour votre aide !

**Comment by Aymkdn** [comment]
Tu peux utiliser pm2. Voir en bas de la page de documentation : https://aymkdn.github.io/assistant-plugins/

**Comment by alfa4684** [comment]
marche nickel en passant en root !
MErci
Par contre au lancement freebox, j'arrive sur l'ecran d'accueil et là la fonction zappe marche pas.
Pas de souci une fois sur une chaine precise.

**Comment by Aymkdn** [comment]
Je n'ai pas compris....

Actuellement : 
 - Soit la Freebox est éteinte et tu dis : "allume la télé et zappe sur XXX"
 - Soit la Freebox est allumée et déjà sur la TV et là tu dis : "zappe sur XXX"

Si tu essaies autre chose, alors c'est normal que ça ne fonctionne pas.

**Comment by alfa4684** [comment]
ok, testé l'ensemble des commandes, nickel. Merci à toi.
