### ISSUE TITLE
Probleme allumage TV

### ISSUE THREAD

**Issue by parisano** [Aymkdn/assistant-plugins#42]
Bonjour,
après configuration, tout semble s'être bien passé. airmedia activé reboot de tout.
utilisation avec mon smartphone.
les ordres  envoyés sont bien reçus dans ok google, il répond  , mais rien ne se passe au niveau TV.
pas d'allumage

**Comment by Aymkdn** [comment]
Qu'indique la console du programme ?

**Comment by parisano** [comment]
Rien ,après avoir lancé start.bat il m'indique que les plugins sont bien chargés, par contre aucun message sur pushbullet .
 j'ai bien la réponse vocale dans l'assistant google du smartphone.
la commande dans IFTT. et pas d'action sur la freebox

**Comment by Aymkdn** [comment]
Tu as utilisé une applet que j'ai faite, ou tu l'as faite toi-même ?

Car si tu n'as rien dans ta console c'est que IFTTT n'envoie pas à Pushbullet (ou pas au bon compte Pushbullet, ou pas avec la bonne information).

Tu devrais au moins voir : 
```
> [assistant] Commande reçue:  [ 'freebox_on' ]
> [assistant] Appelle du plugin 'freebox'                                                                         │
```

**Comment by parisano** [comment]
J'ai utilisé ton applet, j'ai fait un copier /coller pour la clé de pushbullet

**Comment by Aymkdn** [comment]
Tu as connecté IFTTT au bon compte Pushbullet ?

**Comment by parisano** [comment]
c'est à dire?
J'ai mis les clés dans le configuration.json

**Comment by Aymkdn** [comment]
Tu n'as qu'un compte Pushbullet ?
Si tu vas sur https://www.pushbullet.com/#following/ tu vois bien le canal IFTTT avec des messages comme celui-ci : 
![capture](https://user-images.githubusercontent.com/946315/33616182-78339dd0-d9dc-11e7-801a-63a5b8d299d7.PNG)

Si oui, peux-tu faire une capture d'écran de ta console (si tu es sous Windows c'est la fenêtre noire avec *> [assistant] 1 plugin chargé*) ? Tu peux utiliser le lien "selection them" ou faire un drag&drop de l'image dans la zone où tu tapes ton message.

**Comment by parisano** [comment]
je reçois bien sur mon smartphone ces messages
![image](https://user-images.githubusercontent.com/34269845/33616889-90205aa8-d9de-11e7-9318-9414b4d1b72c.png)

{
  "main": {
    "pushbullet_token": "o.orMq7xAHOLeOCoe4yLTsPkBnGCgOtS5b"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "17975720",
      "search_path": "/Disque dur/Videos/",
      "use_Mon_Bouquet": false,
      "check_player_on": false,
      "box_to_control": "hd1",
      "app_token": "2mbXIk3P0zheFf8KOmut95xxBb6zj/6wTHUftZWdiVPdSbdXewEKDZk/e1wuM9NE"
    },
    "ifttt": {
      "key": "5UJOR-EEwADVFbYwnkN6bio4QVf-XHgSMfYWYrDo1d"
    },
    "notifier": {
      "host": ""
    }
  }
}

**Comment by Aymkdn** [comment]
Le message est clair .... : `[assistant-nofitier] Erreur : vous devez configurer ce plugin !`

Difficile de faire plus explicite...

Mais pourquoi avoir installé les plugins `wait`, `ifttt` et `notifier` si tu l'utilises que pour piloter la Freebox ? Surtout `notifier` qui ne s'utilise qu'avec un Google Home...

Donc si tu n'as pas de Google Home et si tu ne comptes pas utiliser les autres plugins, je t'invite à les désinstaller. Dans la console tape : `npm uninstall assistant-notifier assistant-ifttt assistant-notifier`

**Comment by parisano** [comment]
Je pensais que ce n'était pas genant;
Ok, mais pourquoi supprimer IFTT?

**Comment by Aymkdn** [comment]
Car c'est un plugin qui permet d'envoyer des commandes WebHook vers IFTTT....  et qui n'a aucun rapport avec le plugin Freebox :-)

**Comment by Aymkdn** [comment]
Ce n'est pas gênant de les garder, mais si tu les gardes il faut les configurer sinon le programme ne se lancera pas ;-)

**Comment by parisano** [comment]
probleme , j'ai voulu recommencer le fichier configuration en téléchargeant uniquement le plugin FREEBOX,
mais le fichier config n'a plus la même tête, je ne peux plus mettre les clés

**Comment by parisano** [comment]
OK erreur de ma part

**Comment by Aymkdn** [comment]
Le plus simple reste peut-être de supprimer le répertoire puis de retélécharger proprement le programme et ré-entrer la configuration.

**Comment by parisano** [comment]
oui c'est ce que je suis en train de faire; je te tiens au courant

**Comment by parisano** [comment]
La console me dit cette fois : commande on exécutée, ya du mieux.
mais la tv qui était en veille ne s'allume pas . mais là c'est peut être un autre problème du à mon TV LG

**Comment by Aymkdn** [comment]
Quand tu appuies sur le bouton ON de la télécommande Freebox, est-ce que ça allume ta TV LG ? Si non, alors c'est normal que le programme ne le fasse pas non plus ^^

Si ton téléviseur est compatible tu peux activer l'HDMI CEC : http://www.universfreebox.com/article/18200/Freebox-Revolution-Parametrez-la-fonction-HDMI-CEC

**Comment by parisano** [comment]
Merci pour ton aide, maintenant ça fonctionne  . Je vais m'amuser un peu.

J'avais  activé l'HDMI-CEC il y a longtemps, ça marchait mais un jour suite à une mise à jour de firmware de la freebox ça n'a plus fonctionné.
Je vais recreuser le problème et contacter LG.
Ce serait plus pratique si la TV s'allumait en même temps
