### ISSUE TITLE
pas d'assistant après un reboot

### ISSUE THREAD

**Issue by Wyman42** [Aymkdn/assistant-plugins#43]
Hello... j'ai fais l'install comme indiqué sur un Raspi 2 avec Raspbian  lite, tout est OK pour l'assistant ça fonctionne. J'ai installé ensuite pm2, j'ai eu ce warning mais ça c'est bien installé et démarré l'assistant.
![pm2-install](https://user-images.githubusercontent.com/33159735/33608060-8fb7aa6e-d9c3-11e7-89aa-8845605bcf59.png)
J'ai fais pm2 save, tout est OK
![pm2](https://user-images.githubusercontent.com/33159735/33608100-b921edf6-d9c3-11e7-926a-9005cb1e0a4a.PNG)
Mais après le reboot du raspi, je n'ai pas l'assistant qui démarre, je dois je faire via sudo pm2 start index.js
 ???? Merci

**Comment by Aymkdn** [comment]
Tu dois taper : `pm2 save` pour que ce soit pris au démarrage (comme indiqué sur le bas de la page https://aymkdn.github.io/assistant-plugins/)

Si ça ne fonctionne pas, je t'invite à chercher sur le Net (car ce n'est pas lié à assistant-plugins mais à pm2)

**Comment by Wyman42** [comment]
J'ai fais pm2 save...
J'ai trouvé, en rajoutant pm2 startup tout démarrage bien au reboot
