### ISSUE TITLE
connexion avec Node-Red

### ISSUE THREAD

**Issue by Wyman42** [Aymkdn/assistant-plugins#45]
Je me demandais si on pouvait profiter de cette excellent plugin  pour l'utiliser avec Node-Red. Je l'ai installé sur le même Raspi qui a Assistant-Plugins, indiqué mon token PushBullet mais ensuite, j'ai testé différente config du node... et ça marche pas. Des idées ?
![nodered01](https://user-images.githubusercontent.com/33159735/33651744-356308de-da67-11e7-9444-7866033057d8.PNG)

**Comment by Aymkdn** [comment]
Non pas d'idée. J'avais regardé Node-Red dans le cadre de Sarah v5, mais je n'avais pas trouvé ça simple ou pratique à utiliser...
