### ISSUE TITLE
Univers Canal par Freebox

### ISSUE THREAD

**Issue by Godannar** [Aymkdn/assistant-plugins#46]
Bonjour,

Merci pour ton boulot, c'est top. Tout fonctionne parfaitement.
Je voulais savoir si il était possible de se connecter directement à l'univers Les Chaînes CANAL à l'allumage de la FREEBOX. Dans ton fichier on peut apparemment se connecter à Mon bouquet.   

Merci de ton retour

**Comment by Aymkdn** [comment]
Oui, mais il faudra créer ta propre applet sur IFTTT. Va sur https://aymkdn.github.io/assistant-plugins/?plugin=freebox et descend jusqu'à la section "Personnalisation" puis suis les étapes.

Lorsque tu arrives à l'étape 9, tu peux utiliser la séquence : `freebox_on,home,down,down,ok`

**Comment by Godannar** [comment]
oui c'est ce que j'avais testé avant de poster mais j'avais zappé le "home" et du coup c'était un peu aléatoire. Ca marche.
Du coup, j'en viens à la question suivante : comment puis je adapter les chaines pour la numérotation. Actuellement, quand je demande de zapper sur la 55 par exemple. il zappe 2 fois sur la 5. 
Peut on éditer un fichier pour y "mapper" les noms des chaines et les numeros qui correspondent?

**Comment by Aymkdn** [comment]
Si tu dis : "zappe sur la 55", il va correctement mettre la chaine 55 ('5' puis '5' dans un délai assez court pour que ça compose la bonne chaine). Chez moi ça marche parfaitement.

Pour les noms des chaines et les numéros associés, en fait, il récupère le numérotage fait par Free ([sur cette page](http://www.free.fr/freebox/television.html#FreeboxTV)), à chaque démarrage du programme. Est-ce que sur Les Chaines Canal ces numéros sont différents que sur l'Univers Freebox ?

**Comment by Godannar** [comment]
Non justement. Pas du tout pareil. 
J'arrive à zapper sur la 1, 2, 3 5 et 6 mais les autres chaines ne passent pas

**Comment by Aymkdn** [comment]
En effet c'est complètement différent.... Je n'ai pas de solution simple. Il faudrait parser le site pour récupérer le numéro et chaines et ensuite utiliser ça à la place du numérotage de Free... Je n'ai pas de temps pour ça pour le moment.... 

En attendant, si tu connais le numéro de la chaîne, tu peux dire "zappe sur la 42" par exemple.

**Comment by Godannar** [comment]
ça ne fonctionne pas, même en demandant le numéro de la chaine. 
Ou sont stockées les informations des chaines récupérées du site de Free? Je pourrais les remplacer par celles de Canal? Même à la mano

**Comment by Aymkdn** [comment]
Non c'est stocké en mémoire.

Par contre je ne comprends pas pourquoi le changement de chaîne ne fonctionne pas... Je n'ai pas Canal donc difficile de tester et comprendre.

**Comment by Aymkdn** [comment]
Et si le changement de chaîne en donnant le numéro ne fonctionne pas, ça ne marchera pas non plus si tu dis le nom de la chaîne...

**Comment by Godannar** [comment]
Je n'ai pas l'option TV de Free. Peut être la cause

**Comment by Aymkdn** [comment]
Je n'ai pas vraiment de solution pour ton cas spécifique. Désolé :(

**Comment by Aymkdn** [comment]
@Godannar j'ai finalement mis à jour pour supporter les Chaines Canal. Voir là : https://github.com/Aymkdn/assistant-plugins/issues/67#issuecomment-354746494
