### ISSUE TITLE
la freebox s'éteint quand je change de chaine

### ISSUE THREAD

**Issue by frhx** [Aymkdn/assistant-plugins#47]

**Comment by frhx** [comment]
j'ai rentré la commande pour qu'il n'interroge plus la freebox pour savoir si elle n'est pas allumée mais ça ne fonctionne toujours pas ..quand je demande de zapper il check toujours et eteint la freebox j'ai pourtant relancé le programme la freebox et tout
voilà le code que j'ai soigneusement copié
  "main": {
    "pushbullet_token": "o.LoEumoG3MSvskGwEc4AZsIOS8os9tYAz"
  },
  "plugins": {
    "freebox": {
      "code_telecommande": "6255637",
      "search_path": "/Disque dur/Vidéos/",
      "use_Mon_Bouquet": false,
      "box_to_control": "hd2",
      "check_player_on":false,
      "app_token": "JQ1OJqE02hQFd458EF3p7xlyUanAKgdN05/ul/nZXTA3WOitntgjh62WbEX+L8dK"
    },
    "ifttt": {
      "key": "pGR6unelBI63_jVfubTD3fDu_S0BcVfHLQKsmqLnicg"
    },
    "notifier": {
      "host": "192.168.0.11"
    }
  }
}
 et voilà ce qu'il se passe quand je zappe :
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'freebox_zappe sur Arte' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Zappe sur arte (7)
[assistant-freebox] Durée de la vérification de la Freebox allumée : 1336ms
[assistant-freebox] La Freebox n'est pas allumée, donc on l'allume.
[assistant-freebox] Url => http://hd2.freebox.fr/pub/remote_control?code=6255637&key=power
je commence à désepérer...

**Comment by Aymkdn** [comment]
Efface tout et retélécharge la dernière version, en suivant les instructions.

Si tu ne veux que contrôler la Freebox, alors pas besoin d'installer les autres plugins.

**Comment by Aymkdn** [comment]
Pas de nouvelle donc je ferme cette issue.
