### ISSUE TITLE
Anomalie lors du postinstall

### ISSUE THREAD

**Issue by julienrames** [Aymkdn/assistant-plugins#48]
Bonjour, 

Lorsque je lance l'installation avec la commande je reçois ce message d'erreur.
L'avez-vous déja rencontré quelque part ?

pi@assistant:~/assistant-plugins $ npm install --loglevel error && npm run-script postinstall
/
> assistant-plugins-project@2.0.0 postinstall /home/pi/assistant-plugins
> node ./postinstall.js

npm ERR! assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assistant-plugins-project@2.0.0 postinstall script.
npm ERR! This is most likely a problem with the assistant-plugins-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls assistant-plugins-project
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.67+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--loglevel" "error"
npm ERR! cwd /home/pi/assistant-plugins
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/assistant-plugins/npm-debug.log
npm ERR! not ok code 0

Lorsque je lance 

pi@assistant:~/assistant-plugins $ npm owner ls assistant-plugins-project
admin party!

le fichier log donne la même chose, il s'arrête au même endroit
Les lignes 1 a 172 loguent le rapatriement des fichiers dans /node_modules
[...]
173 info install assistant-plugins-project@2.0.0
174 info postinstall assistant-plugins-project@2.0.0
175 verbose unsafe-perm in lifecycle true
176 info assistant-plugins-project@2.0.0 Failed to exec postinstall script
177 error assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
177 error Exit status 1
178 error Failed at the assistant-plugins-project@2.0.0 postinstall script.
178 error This is most likely a problem with the assistant-plugins-project package,
178 error not with npm itself.
178 error Tell the author that this fails on your system:
178 error     node ./postinstall.js
178 error You can get their info via:
178 error     npm owner ls assistant-plugins-project
178 error There is likely additional logging output above.
179 error System Linux 4.9.67+
180 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
181 error cwd /home/pi/assistant-plugins
182 error node -v v4.8.2
183 error npm -v 1.4.21
184 error code ELIFECYCLE
185 verbose exit [ 1, true ]

infos utiles :
raspberry pi v1
npm@1.4.21
node@v4.8.2

Merci pour votre aide.

**Comment by julienrames** [comment]
Résolu avec un : sudo apt-get install nodejs-legacy

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une documentation dédiée pour l'installation sur RaspberryPi : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

Pour le coup, j'explique comment installer la dernière version de Node. Dans ton cas, c'est pas forcément utile car tout semble marcher. Mais je préfère quand même l'indiquer ici au cas où ;-)
