### ISSUE TITLE
Linux - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by sportok** [Aymkdn/assistant-plugins#5]
Bonjour,

Sous linux, j'ai l'erreur suivante au lancement : 
`root@*****:/home/test/assistant-plugins-master/# nodejs index.js

/home/test/assistant-plugins-master/index.js:47
              let plugin = commande.split("_")[0];
                  ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
`

Je n'ai pas encore eu le temps de regarder en détail, mais auriez-vous une idée ?
J'ai notamment réessayé en activant seulement le plugin freebox.

**Comment by LudoMeurillon** [comment]
As-tu vérifié ta version de node ? Il se peut que le mot-clé "let" ne soit pas supporté par ta version

`node --version`

**Comment by Aymkdn** [comment]
En effet, il est possible que ta version de Node soit trop vieille.

**Comment by mikl974** [comment]
Salut,
j'ai le même problème en essayant de lancer sur un synology.
Ma version de nodejs: 2.15.11
quand je lance : node index.js
jai cette erreur: 
/volume1/homes/admin/assistant-plugins-master/index.js:47
              let plugin = commande.split("_")[0];
              ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

une idée?

**Comment by sportok** [comment]
Hello,

Effectivement OK après mise à jour de nodeJs en v8.9.1 (ARM7).
@mikl974 je t'invite à mettre également à faire la mise à jour nodejs.

Merci pour ce super boulot !

**Comment by Aymkdn** [comment]
Pour éviter les soucis avec d'autres, je repasserai à l'utilisation de `var` au lieu de `let`.

**Comment by Aymkdn** [comment]
Pour info la v2 vient d'être annoncée : https://github.com/Aymkdn/assistant-plugins/wiki/Version-2.0

J'ai enlevé les `let` qui était présent !
