### ISSUE TITLE
Freebox mini 4k

### ISSUE THREAD

**Issue by TwistJo32** [Aymkdn/assistant-plugins#50]
Hello,

Tout d'abord super projet, bravo !

Le problème ne vient pas réellement de ton application/projet mais de la récupération du code télécommande sur une **Freebox mini 4K**. Je n'ai pas la possibilité (apparemment) de le récupérer et malgré tout, mon application **Android TV** sur mon smartphone a pu le faire.

Donc par grand hasard, si tu ne sais répondre, peut-être qu'une autre personne aurait le même soucis et qu'elle a trouvé, ou on pourrait trouver une solution ?! 
De mon côté, je tente de recherche dans la configuration de l'application pour peut-être récupérer le code dedans...

**Comment by Aymkdn** [comment]
Je ne pense pas qu'il y ait de code télécommande pour cette Freebox. Je ne sais pas du tout comment elle fonctionne, mais c'est basé sur Android TV je pense et c'est complètement différent de ce que Free a implémenté pour la Révolution ! Donc peu de chance que ce plugin soit compatible un jour...

**Comment by TwistJo32** [comment]
Ha dommage... Merci pour ton retour malgré tout ! :)
Bon courage
