### ISSUE TITLE
problème d'installation assistant plugin freebox

### ISSUE THREAD

**Issue by oliviermelle** [Aymkdn/assistant-plugins#51]
bonjour, merci pour l’assistant plugin et pour les recherches faites. j'ai suivi les différentes étapes mais lorsque je fait start.bat , voici ce que cela donne.
je ne comprends pas car si je donne l'ordre à mon home mini d'alluer la tele il me répond mais rien n'apparaît sur la console .
je n'arrive pas à comprendre pourquoi .
merci pour le coup de main si c'est possible et merci encore pour votre travail.
d'autre part, il écrit sur la console que le chargement est en cours et cela ne change pas...

![image](https://user-images.githubusercontent.com/34402389/33798375-7f6589b8-dd17-11e7-89ee-29e13a5fb3f4.png)

**Comment by Aymkdn** [comment]
Tu n'as qu'un compte Pushbullet ?
Si tu vas sur https://www.pushbullet.com/#following/ tu vois bien le canal IFTTT avec des messages comme celui-ci : 
![capture](https://user-images.githubusercontent.com/946315/33616182-78339dd0-d9dc-11e7-801a-63a5b8d299d7.PNG)

Si oui, peux tu faire une copie d'écran de ces messages ?

**Comment by oliviermelle** [comment]
bonjour et merci de prendre du temps, 
je ne vois pas ces éléments et le canal IFTTT sur pushbullet. voici une copie ecran de ce que j'ai lorsque je clique sur ton lien:
![image](https://user-images.githubusercontent.com/34402389/33803988-37804806-dd9c-11e7-9878-3e2480f6bbe1.png)

**Comment by oliviermelle** [comment]
si c'est ok.
copie ecran:
![image](https://user-images.githubusercontent.com/34402389/33804310-848ab356-dda2-11e7-9bd8-67c07f82a558.png)

**Comment by Aymkdn** [comment]
OK. Tu n'as fait qu'un unique test ? Essaie une autre fois quand même ^^

Aussi, assure toi d'avoir correctement copié la clé Pushbullet

**Comment by oliviermelle** [comment]
ok pour la seconde fois le google home me dit bien j'allume la freebox et je reçois un note sur pushbullet
![image](https://user-images.githubusercontent.com/34402389/33804380-b068b4b8-dda3-11e7-85ba-19d75e9bb426.png)

**Comment by oliviermelle** [comment]
mais rien ne se passe sur la freebox, elle ne s'allume pas:
je t'envoie une copie ecran également de la configuration de l'assistant plugin:
![image](https://user-images.githubusercontent.com/34402389/33804398-19efa4d2-dda4-11e7-8098-799d8b037435.png)

**Comment by Aymkdn** [comment]
Ce qui est important est ce qu'indique la console de assistant-plugins. Si rien n'y est indiqué, ça veut dire qu'il ne reçoit pas les notifications de Pushbullet.... Possibles raisons : ton Token Pushbullet est incorrect, ou peut-être que le firewall de Windows (ou antivírus) bloque la connexion

**Comment by oliviermelle** [comment]
ok, je viens de changer le token pushbullet (il y en a un nouveau, je pensais qu'il était fixe).
je vais débloquer le firewall et l'antivirus et vais réessayer.
je me permettrai de t'envoyer une copie écran.

par contre, il y a toujours assistant v2.0.2 chargement en cours dans la console node index.js ??? et je ne vois pas ce qu'il charge ?

**Comment by Aymkdn** [comment]
"Chargement en cours"  c'est la première ligne, ensuite il indique plusieurs choses jusqu'à "prêt à écouter les commandes via Pushbullet". 

Bien penser à arrêter puis relancer le programme lorsque tu modifies la configuration

**Comment by oliviermelle** [comment]
Je dois m'absenter cet après midi. Je viens d'essayer et ça a fonctionné
pour allumer. Maintenant il faut que j'essaie sur dautres Applets

**Comment by oliviermelle** [comment]
Merci pour tout et je reviens vers toi au besoin.
