### ISSUE TITLE
scénario freebox et ifttt maker

### ISSUE THREAD

**Issue by claudecn13** [Aymkdn/assistant-plugins#52]
bonjour
bravo et merci pour votre travail..j' ai suivi votre tutoriel et maintenant "ok google " la freebox s'allume et la télé pas toujours a cause de cec anynet+.
aujourd'hui j'aimerai un conseil pour faire un scénario avec ifttt maker... demande :soirée télé et action:
  - allume la télé via la freebox
  - ferme volet avec tahoma
  - allume lumière avec yeetligh

mais je ne sais pas ramener "allume la télé via freebox"  est ce possible a réaliser ?
merci

**Comment by Aymkdn** [comment]
## 1ère solution

Pour cette solution, tu dois installer le plugin `ifttt` pour assistant-plugins.

Ensuite tu dois créer deux [WebHooks dans IFTTT](https://ifttt.com/maker_webhooks) : 

1. pour "fermer volet avec Tahoma", qu'on va nommer **"CloseVoletTahoma"**
2. et une autre pour "allumer lumière avec Yeetlight", qu'on va nommer **"LightOnWithYeetlight"**

Il faut ensuite créer un applet avec : 
- En "this" tu mets **"Google Assistant"**, qui s'enclenche avec la phrase "soirée télé"
- En "that" tu sélectionnes la création d'une note avec **"Pushbullet"**, et pour les paramètres :
  - "**Assistant**" dans **Title**
  - "**freebox_on|ifttt_CloseVoletTahoma|ifttt_LightOnWithYeetlight**" dans **Message**

Si on décortique : 

1. `freebox_on` va indiquer à la Freebox de s'allumer (via le plugin Freebox)
2. `ifttt_CloseVoletTahoma` va lancer le scénario *"fermer volet avec Tahoma"* (via le plugin IFTTT)
2. `ifttt_LightOnWithYeetlight` va lancer le scénario *"allumer lumière avec Yeetlight"* (via le plugin IFTTT)

## 2ème solution

Il existe une autre possibilité en utilisant la [platform IFTTT](https://platform.ifttt.com/maker/aymericdmdv/applets/private). Dans ce cas tu peux créer un applet privé qui enclenche plusieurs actions.

Dans ton cas le trigger est un Google Assistant. Ensuite pour le **then** tu peux créer trois actions : 

1. Une note Pushbullet qui va permettre d'allumer la Freebox : 
    - "**Assistant**" dans **Title**
    - "**freebox_on**" dans **Message**
2. La deuxième action utilisera le service associé à tes volets pour les fermer
3. La troisième action utilisera le service associé à tes lumières pour les allumer

**Comment by claudecn13** [comment]
merci pour cette réponse... super sympa
je vais tenter la 2éme solution...
bonne soirée

**Comment by claudecn13** [comment]
bonjour, 
je reviens vers vous pour a nouveau conseil
j ai appliqué la solution n° 2 tahoma et lumiere ok mais pas la freebox !! j ai essaye aussi avec "freebox_tv" dans le message ... je reçois un email dans ma boite free !!! bizarre...

**Comment by Aymkdn** [comment]
Mets une copie d'écran de l'applet que tu as créé pour la Freebox.

**Comment by claudecn13** [comment]
suis désolé , j ai refais plusieurs fois depuis hier ,je viens de le supprimer  "delete"

**Comment by claudecn13** [comment]
des que j aurai refais je mets la copie de l'écran..vraiment désolé

**Comment by Aymkdn** [comment]
OK. Bien créer une applet avec le service "Pushbullet" et sélectionner "Send a Note", et entrer les informations que j'ai indiquées.

**Comment by claudecn13** [comment]
merci pour votre patiente...

**Comment by claudecn13** [comment]
met la télé en mode cinéma

allume la télé via la Freebox, baisse les volets en position My tahoma, allume le chevet du salon Yeelight

Receive notifications when this Applet runs


Say a simple phrase
This trigger fires when you say “Ok Google” to the Google Assistant followed by a phrase you choose. For example, say “Ok Google, I’m running late” to text a family member that you’re on your way home.

met la télé en mode cinéma


mode ciné


d'accord, j'allume la télé, je baisse les volets, j'allume le chevet du salon



Push a note
This Action will push a new note to your Pushbullet inbox.

Assistant (optional)

Google Voice Simple Commands
Google Voice Simple Commands
Freebox_tv (optional)



Launch a TaHoma scenario
This action will launch a TaHoma scenario.

regarder un film


Toggle lights on/off
This Action will turn on, turn off or toggle your lights.

chevet du salon

On, off or toggle?

Save
Applet ID gDdNwSPv

**Comment by Aymkdn** [comment]
Une copie d'écran sera plus efficace... Il suffit ensuite de prendre l'image et de la déposer dans cette zone pour qu'elle soit ajoutée et visible dans les commentaires...

**Comment by Aymkdn** [comment]
J'ai seulement besoin de voir la partie qui concerne la notification Pushbullet. Pas besoin de voir le reste

**Comment by claudecn13** [comment]
![image](https://user-images.githubusercontent.com/34451169/33883941-11e459a4-df3e-11e7-8033-d49149547fff.png)

**Comment by claudecn13** [comment]
![image](https://user-images.githubusercontent.com/34451169/33884006-4eacb08e-df3e-11e7-9336-35b15c584fce.png)

**Comment by Aymkdn** [comment]
Tu as mal configuré... Tu as modifié l'intitulé du champs, au lieu d'en modifier sa valeur !!
![capture](https://user-images.githubusercontent.com/946315/33884608-a274f2f6-df40-11e7-9f86-aef2d3b2d6d6.PNG)

Quand tu configures, il faut le faire ainsi : 

![capture](https://user-images.githubusercontent.com/946315/33884702-04ea8658-df41-11e7-9cf9-1f2aa499d4cf.PNG)

**Comment by claudecn13** [comment]
bonsoir,
suis pas doué,la freebox ne s'allume pas
![image](https://user-images.githubusercontent.com/34451169/33897921-1b776cee-df67-11e7-8725-a12ca7b75dac.png)
![image](https://user-images.githubusercontent.com/34451169/33897935-26d745f0-df67-11e7-8e31-fe4ab2219c73.png)

**Comment by claudecn13** [comment]
![image](https://user-images.githubusercontent.com/34451169/33898009-5bb2090e-df67-11e7-9a88-2e3067f83d36.png)

**Comment by Aymkdn** [comment]
J'ai bien spécifié qu'il fallait mettre `freebox` en **minuscule** ...

**Comment by claudecn13** [comment]
maintenant c'est correct...tout marche 
je vous remercie pour tout le temps que vous avez pris pour moi, suis vraiment désolé d’être aussi distrait...
encore bravo pour votre travail
