### ISSUE TITLE
Problème application 

### ISSUE THREAD

**Issue by cayzacnicolas** [Aymkdn/assistant-plugins#53]
![e4757863-faab-41ff-b55a-d4ced6c5a9fd](https://user-images.githubusercontent.com/34747979/34264818-5bc8aac4-e674-11e7-937b-972ddb953ee0.png)
Tout fonctionne correctement , je demande à Google assistant « éteins la freebox «  il me répond correctement rien ne se passe ! Et l’applitation Done ceci en pièce jointe !

**Comment by Aymkdn** [comment]
Tu as réessayé ? Peut-être un problème de liaison entre IFTTT et Pushbullet ?

**Comment by cayzacnicolas** [comment]
J’ai réessayé depuis hier , avec différentes fonctions et c’est toujours le même problème ! 
![6c5a44cc-d4fa-4989-9d15-4f52f64a73c8](https://user-images.githubusercontent.com/34747979/34266593-12d67dea-e67a-11e7-8b03-22813ce99897.png)

**Comment by Aymkdn** [comment]
Ça ne vient pas de mon programme en tout cas.

D'après leur aide/FAQ, ils disent que tu peux essayer de supprimer le service Pushbullet de IFTTT, puis de le remettre:
> you may need to reconnect the service by going to its page and clicking "Settings"

Si ça ne marche toujours pas, alors [contacte-les](https://help.ifttt.com/hc/en-us/requests/new) pour leur dire que l'applet Pushbullet plante chez toi.

**Comment by cayzacnicolas** [comment]
Daccord je vais essayer de tout réinstaller de zéro ! Par ronger est ce que ça ne ci viendrais du fait que j’ai installer tout les plugins sur mon synology bien que j’ai également fait toute l’install sur mon mac et qu’en ca avais posé le même non soucis !

**Comment by Aymkdn** [comment]
Non.... Comme je l'ai dit, le problème ne vient pas de mon programme mais de la connexion entre IFTTT et Pushbullet. Réinstaller assistant-plugins ne sert donc à rien du tout.

**Comment by cayzacnicolas** [comment]
Effectivement j’ai desinstaller et réinstaller les commandes fonctionnent , plus d’erreur entre IFTTT et Pushbullet ! Malheureusement aucune action ne se réalise sur la freebox ! Décidément je n’ai pas de chance !

**Comment by Aymkdn** [comment]
Fais une copie d'écran de la console (là où ça dit "[assistant-plugins] Chargement de X plug-ins...")

**Comment by cayzacnicolas** [comment]
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.3)
[assistant-freebox] Récupération des chaines télé sur free.fr...
[assistant-freebox] Récupération des chaines sur free.fr terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Erreur : vous devez configurer ce plugin !

**Comment by Aymkdn** [comment]
Si tu sais lire tu as déjà compris ton erreur puisqu'elle est indiquée.

J'ai bien expliqué sur le site qu'il ne sert à rien d'installer tous les plugins si on ne veut que manipuler la Freebox... Surtout c'est stupide d'installer le plugin Notifier si tu n'as pas de Google Home puisqu'il fonctionne avec cet appareil uniquement, et sert à envoyer des messages vocaux dessus.

Bref, si tu ne cherches qu'à manipuler la Freebox je t'invite à recommencer ton installation en ne sélectionnant que le plugin Freebox !!! Sinon, il te faut tout configurer correctement !
