### ISSUE TITLE
Rien de se passe malgré une bonne configuration

### ISSUE THREAD

**Issue by CremeChoco** [Aymkdn/assistant-plugins#54]
Bonjour,

J'ai installé que le plugin Freebox, bien configuré Pushbullet avec mon token mis dans le fichier configuration.json et mon code télécommande, mais quand je demande à Google de zapper sur la 2 par exemple, il me répond "Je zappe sur la 2" mais rien ne se passe. 😢
![capture](https://user-images.githubusercontent.com/24397848/34319741-ea330266-e7e9-11e7-839b-3cbe6a18e891.PNG)

**Comment by Aymkdn** [comment]
Quand tu lui demandes une commande, l'assistant te répond come prévu ? 

Visiblement le programme ne reçoit aucune commande. Donc soit tu as mal copié ta clé Pushbullet, soit l'applet n'est pas activée...

**Comment by Pierrick59** [comment]
Bonjour,

J'ai le même problème, la google home dit je zap sur la 2 et rien ne se passe,  je te confirme que la clef Pushbullet est bien ok et les applets sont actif tu as une idée ?
![image](https://user-images.githubusercontent.com/34826806/34332948-fb8a55c0-e936-11e7-9b70-5b6832b6e3d6.png)
Encore merci pour ton aide

**Comment by Aymkdn** [comment]
Si tu vas sur https://www.pushbullet.com/#following/ tu vois bien le canal IFTTT avec des messages comme celui-ci : 
![capture](https://user-images.githubusercontent.com/946315/33616182-78339dd0-d9dc-11e7-801a-63a5b8d299d7.PNG)

Si oui, peux tu faire une copie d'écran de ces messages ?

**Comment by Pierrick59** [comment]
oui je vois bien 
![image](https://user-images.githubusercontent.com/34826806/34341716-9c6b4592-e99d-11e7-853f-15cd69ef0bb4.png)

**Comment by Aymkdn** [comment]
Étrange... Peut-être un firewall/antivirus qui bloque le programme et l'empêche d'écouter les requêtes ?

**Comment by Pierrick59** [comment]
Je vais test de désactiver Avira et malw...byte

**Comment by Pierrick59** [comment]
Bon cela ne fonctionne pas

**Comment by Pierrick59** [comment]
![image](https://user-images.githubusercontent.com/34826806/34342140-675c23f8-e9a7-11e7-882f-2b1c15c4b0fa.png)

**Comment by Pierrick59** [comment]
![image](https://user-images.githubusercontent.com/34826806/34342144-7770ed3c-e9a7-11e7-88ac-4bc71cb61e80.png)

**Comment by Pierrick59** [comment]
Bizarre, viens de lancer le Push effacer le deux messages et maintenant, plus rien n'apparaît comme si cela ne communiquer plus ?
![image](https://user-images.githubusercontent.com/34826806/34342162-cdba8694-e9a7-11e7-9a2b-a868e32ca92b.png)

**Comment by Aymkdn** [comment]
Essaie peut-être de "disconnect" le service Pushbullet de IFTTT : https://ifttt.com/services/pushbullet/settings 
puis réactive le et reteste.

**Comment by Pierrick59** [comment]
![image](https://user-images.githubusercontent.com/34826806/34342260-6cb2e38e-e9aa-11e7-86bc-710c03997bf6.png)

**Comment by Aymkdn** [comment]
Tu as bien réactivé le service Pushbullet ? Essaie peut-être d'activer/désactiver l'applet pour voir ? En tout cas, le soucis vient d'IFTTT là...

**Comment by Pierrick59** [comment]
j'ai disconnect le  service Push, deactiver les applets puis réactiver et toujours la même chose rien ne remonte.
![image](https://user-images.githubusercontent.com/34826806/34342307-216b8852-e9ac-11e7-9abd-2e5bf3141401.png)
![image](https://user-images.githubusercontent.com/34826806/34342310-31b61b00-e9ac-11e7-93e3-88e190b30c3a.png)

**Comment by Aymkdn** [comment]
T'as essayé d'autres commandes à tout hasard ? Genre "allume la Freebox" ou autre ?

Sinon, je ne sais pas pourquoi ça ne marche pas... Tu peux toujours réessayer demain, ou tenter de [les contacter](https://help.ifttt.com/hc/en-us/requests/new) !

**Comment by Pierrick59** [comment]
La je viens de supprimer  IFTTT oups je ne sais plus l'installer le blond dès que j'ai remis je vais test avec la commande allumer la freebox

**Comment by Pierrick59** [comment]
Bon solution trouvé je suis un boulé j'ai oublier d'allumer le node lol

**Comment by Aymkdn** [comment]
Allumer le node ? Pas sûr de comprendre ce que ça veut dire... Mais bon, si ça fonctionne, tant mieux :-)

**Comment by Aymkdn** [comment]
@CremeChoco comme tu es parti en vacances (et que Pierrick59 a pollué ton post ^^) je ferme cet issue. Je t'invite à lire mes interventions et à voir si ça peut t'aider.

Si ton problème persiste, ouvre un nouvel issue en fournissant un maximum de captures d'écran (comme Pierrick l'a fait).
