### ISSUE TITLE
Chaîne inconnue lors d'un zapping

### ISSUE THREAD

**Issue by m4xx75** [Aymkdn/assistant-plugins#55]
Bonjour,

Pour commencer, je souhaite vous féliciter pour le travail accompli, merci.

Je rencontre un problème lorsque je souhaite effectuer un zapping via mon Google Home.
J'ai systématiquement l'erreur "**Chaine XX inconnue**" et je ne compense pas pourquoi.
J'ai bien sûr essayé de reboot ma VM, même à plusieurs reprises, mais sans succès.

Voici une capture de la console node:

<img width="673" alt="sans titre" src="https://user-images.githubusercontent.com/31291478/34358345-333d257e-ea4f-11e7-95a3-e6aad5e7a771.png">

Vous noterez que celle-ci indique malgré tout avoir correctement récupéré la liste des chaines.
Pour information, toutes les autres commandes fonctionnent correctement.

Merci par avance.
Mickaël

**Comment by Aymkdn** [comment]
Bonjour,

La commande qui devrait être reçue est "zappe **sur la** 28" (ou bien "zappe sur Paris Première") mais pas "zappe 28". Il manque le "sur la".

Tu as personnalisé la commande pour que ce ne soit pas la bonne qui est envoyée ?

**Comment by m4xx75** [comment]
Ah,

Bien vue, j'ai en effet personnalisé les commandes:

<img width="270" alt="screenshot_20171226-153133" src="https://user-images.githubusercontent.com/31291478/34358807-1b767022-ea53-11e7-881b-2f11fbeae35a.png">
<img width="270" alt="screenshot_20171226-153221" src="https://user-images.githubusercontent.com/31291478/34358808-1da5f8ea-ea53-11e7-877d-b867b9f863a3.png">

J'ai refait un test en précisant **"sur la"** et en effet ça fonctionne correctement.

**PS:** Au passage, j'ai remarqué un petit détail sur le nom d'un de vos plugins. Il manque la lettre **"L"** sur le mot **"La"** :
<img width="246" alt="screenshot_20171226-154528" src="https://user-images.githubusercontent.com/31291478/34358933-39f5e734-ea54-11e7-956e-03d17428cb3e.png">
Pas très grave, mais ce ne coûte rien de le signaler. :)

Merci pour ta réactivité.
Mickaël

**Comment by Aymkdn** [comment]
Cool si ça marche :-)

Et je viens de rajouter le "L" à "La Freebox" dans le plugin. Merci !

**Comment by m4xx75** [comment]
Impeccable :)

J'ai également une question concernant le plug-in "Allume la télé via la Freebox et zappe sur une chaine".
Cella fonctionne très bien, et je me suis d'ailleurs créé un raccourci Google Home qui fait tout ça juste en disant "Allume la Freebox" (plus rapide pour moi).

Je constate que le curseur "se balade" un peu plus que nécessaire:
https://streamable.com/s/rduzt/nylkve

Est-ce normal ? 

Merci

**Comment by Aymkdn** [comment]
Oui c'est normal : selon à quel endroit tu coupes la Freebox, tu ne vas pas forcément revenir au même endroit. Ces va-et-vient vont permettre de s'assurer qu'on est au bon endroit (j'ai récemment découvert qu'il y avait une combinaison plus rapide pour arriver à la même chose, mais je n'ai pas eu l'occasion de la tester).

**Comment by m4xx75** [comment]
Ok je comprends parfaitement ! C’est ce que j'avais supposé.
Merci beaucoup pour tes réponses, je resterais donc à l’affut des "potentielles" futures mises à jour :)
