### ISSUE TITLE
ne fonctionne plus apres passage de 2.0.0 en 2.0.3

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#56]
bonjour , 
ça ne fonctionne plus après passage en 2.0.3 ,
GH prend bien en compte les actions puisque il répond  " j'allume la freebox " par exemple

mais rien ne ce passe ni dans la fenêtre DOS  ni sur la Box

![sans titre](https://user-images.githubusercontent.com/33859641/34359082-35571cc4-ea55-11e7-9978-106786032d03.png)

**Comment by Aymkdn** [comment]
Comment as-tu mis à jour ? Car apparemment ton fichier de configuration a été remis à zéro puisque je vois que la Freebox t'a redemandé de valider le plugin (ce qui ne devrait pas arriver lors d'une mise à jour).

Si tu vas sur https://www.pushbullet.com/#following/ tu vois bien le canal IFTTT avec des messages comme celui-ci ? 
![capture](https://user-images.githubusercontent.com/946315/33616182-78339dd0-d9dc-11e7-801a-63a5b8d299d7.PNG)

Ensuite, vérifie dans IFTTT qu'il n'y a pas de problème avec l'applet : https://ifttt.com/activity

Enfin, vérifie que dans ton fichier de configuration tu as bien le pushbullet_token

**Comment by Aymkdn** [comment]
Plusieurs personnes ont eu ce problème ces derniers jours...

En général je leur conseille de : 

1. "disconnect" le service Pushbullet de IFTTT : https://ifttt.com/services/pushbullet/settings 
2. puis de le réactiver,
3. de vérifier sur une applet (par exemple celle qui allume la Freebox) si l'applet est toujours active
4. et enfin de refaire quelques tests.

**Comment by nusmiaf** [comment]
j'ai fait déactivé/activé , les applet sont actif dans IFTTT
et sur l'appli IFTTT ça me dit ça;
![sans titre13](https://user-images.githubusercontent.com/33859641/34360421-fade7900-ea60-11e7-85d6-d0733d318541.png)
![sans titre14](https://user-images.githubusercontent.com/33859641/34360423-fde607ee-ea60-11e7-8703-a7e3f717316a.png)

**Comment by Aymkdn** [comment]
Le problème vient d'IFTTT/PushBullet... Tu peux tenter de [les contacter](https://help.ifttt.com/hc/en-us/requests/new).

**Comment by nusmiaf** [comment]
ok je vais essayer ça

**Comment by Aymkdn** [comment]
Tiens moi au courant stp.

**Comment by nusmiaf** [comment]
pas de problème

**Comment by nusmiaf** [comment]
Tout re-fonctionne , je n'est rien changer donc effectivement  , sans doute un problème ponctuel sur la plateforme ifttt ou pushbullet

**Comment by sportok** [comment]
Hello,

Pour info, j'ai également le même problème depuis quelques jours. 
Un ticket est ouvert chez le support ifttt. 
Si j'obtiens quelques détails, j'ajouterai ici les informations pourraient servir à d'autres.

**Comment by nusmiaf** [comment]
J'avais aussi ouvert un ticket quand Aymkdn là conseiller
