### ISSUE TITLE
La terminal ne reçoit pas les cmds de pushbullet

### ISSUE THREAD

**Issue by Kevcaus** [Aymkdn/assistant-plugins#58]
Bonjour,

Tout d'abord, un grand merci pour ton travail.
J'ai voulu installé mais ça foire au moment des tests :) je m'explique
IFTTT reçoit bien la commande de googleassistant et transmet à pushbullet.
![capture d ecran 2017-12-26 a 19 03 18](https://user-images.githubusercontent.com/34866873/34361964-7b4acdc4-ea6f-11e7-93fa-cd4a1abc7025.png)

en revanche dans la console, je ne reçois rien.. tout est bien démarré et sans erreur !

![capture d ecran 2017-12-26 a 19 04 15](https://user-images.githubusercontent.com/34866873/34361975-9a44aa88-ea6f-11e7-9dbc-159f9bd4665e.png)

J'ai bien entendu vérifier le lien pushullet avec le token que j'ai inséré dans le fichier configuration.json

Je pense pas avoir loupé d'étape.
Merci pour votre aide.

Nota : je suis sous Mac

**Comment by Kevcaus** [comment]
en complément., j'ai bien activé également le lien avec webhooks via recopie du token dans le fichier configuration :)

**Comment by Aymkdn** [comment]
Salut. Regarde si tu n'as pas le même problème que là : https://github.com/Aymkdn/assistant-plugins/issues/56

**Comment by Aymkdn** [comment]
PS : comme indiqué à plusieurs endroits sur le site, tu n'as pas besoin des plugins IFTTT, Notifier ou wait si tu ne veux que piloter la Freebox...

**Comment by Aymkdn** [comment]
Cela dit si tu vois les commandes dans Pushbullet, c'est que le problème doit venir d'ailleurs... Peut-être un problème réseau sur ta machine, ou un firewall / antivirus qui bloque ?

**Comment by Kevcaus** [comment]
Oui je sais pour les autres plugins mais j'ai préféré installer l'ensemble. Ca me servira pour plus tard ^^

pas d'antivirus sur le mac donc je sais pas ce qui pourrait bloquer .. (est-ce que d'autres users ont eu un soucis avec mise en oeuvre sur mac?) je pourrais éventuellement tester sur windows pour confirmer ou non !

j'ai bien vu le problème 56 mais ce n'est pas le même pas cas de figure, effectivement dans mon cas, pushbullet reçoit bien la commande, le soucis est donc entre pushbullet et le terminal?

**Comment by Aymkdn** [comment]
Ça fonctionne pour les autres sous  Mac en tout cas...

**Comment by Kevcaus** [comment]
Salut,

Petit retour pour dire que le problème est résolu. En fait, il n'y avait pas vraiment de problème.
J'ai remarqué que lorsque j'étais sur la page Following dans pushbullet pour regarder les commandes passées, celles-ci n'étaient pas transmises au terminal. Bug ou fonctionnement normal, en tout cas, il suffit de ne pas surveiller la console pushbullet pour que tout fonctionne !!

Merci beaucoup pour ton partage et support.

Ps : Installé sur un rapsberry, c'est parfait.
Ps2 : J'ai crée une petite commande IFTT "Allume les dessins animés sur la freebox" et ma fille 4 ans est aux anges :)
