### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by William-K93** [Aymkdn/assistant-plugins#59]
Bonjour, super tuto suivi à la lettre et qui fonctionne parfaitement.

J'ai une petite question : est-il possible de lancer un film ou une série stocké sur le disque ? en effet l'ordre donné à Google Home pour aller dans mes videos s'execute bien mais après j'ai un dossier Films et un dossier Series et là google home ne sait pas y aller.

J'ai laisser le search patch comme tel : "search_path": "/Disque dur/Vidéos/",    et même en rajoutant films : "/Disque dur/Vidéos/Films/",  google home ne sait pas faire..... dois-je modifier quelque chose ou bien ce n'est pas faisable ? Merci d'avance pour votre réponse.﻿

**Comment by Aymkdn** [comment]
`"search_path": "/Disque dur/Vidéos/Films/"` n'est pas utilisé avec la commande `va dans Mes Vidéos`, mais pour la commande `va dans le dossier XXX`

Dans ton cas tu peux essayer de dire : `OK Google, va dans le dossier films` (il risque de comprendre "film" au lieu de "films"). Ou bien : `OK Google, va dans le dossier séries` (là encore il faut que le dossier ait la même orthographe que ce que Google va comprendre).

Sinon tu peux créer ta propre applet (voir la partie **Personnalisation** [dans la documentation](https://aymkdn.github.io/assistant-plugins/?plugin=freebox)) avec, en entrée, la phrase de ton choix (par exemple : "balance mes films"), puis la commande qui doit être envoyée sera : `freebox_folder Films`.

**Comment by duch974** [comment]
Est t il possible de faire de faire tour assistant plugins, nodejs sur mon telephone s6. Parce que j essaye j ai telecharger les plugins. J ai l app termux pour les commandes mais la je bloque. Impossible de lance .bat ni meme d associé termux a es explorateur. Sa serais pratique puisque au moin mon tel et toujour allumer . Pas comme mon pc. J ai peur d une non compatibilité de plugins (.bat). Avec mon tel android poucais vous m aidez. Merci master!.

**Comment by Aymkdn** [comment]
@duch974  : c'est pas cool de polluer la question d'une autre personne :-( 
Concernant ta demande, voir ma réponse ici : https://github.com/Aymkdn/assistant-plugins/issues/40

**Comment by William-K93** [comment]
Bonjour,
effectivement en renommant correctement les répertoires cela fonctionne bien, je te remercie beaucoup. Je vais t’embêter une dernière fois : pour naviguer dans une liste de films ou d'épisodes de série puis lancer le film ou l'épisode peux-tu me confirmer qu'il faut créer plusieurs Applets avec par exemple down : envoie la commande down (flèche bas) puis applet OK : envoie la commande OK..... ou bien y-a-t-il plus simple ? merci encore pour ton aide.

**Comment by Aymkdn** [comment]
Il suffit d'une seule applet avec une suite de commandes. Voir [l'exemple en bas de page](https://aymkdn.github.io/assistant-plugins/?plugin=freebox).
