### ISSUE TITLE
Impossibilitée de faire fonctionner des Applets IFTTT créées par soi-meme

### ISSUE THREAD

**Issue by Bibnot** [Aymkdn/assistant-plugins#60]
Bonjour Aymeric,

Tout d'abord merci pour le temps passé a coder ce script.

Je rencontre un souci avec la création d'applets personnalisé pour faire des actions que tu n'as pas prevu dans les applets.

En effet, je suis bien tes explications, IFTTT retournes bien ce que je lui demande, l'envoi bien a Pushbullet, mais aucune reaction du script. Me manque t il un element qui m'echappe?

exemple de retour sur Pushbullet

> Assistant
> freebox_green,freebox_down,freebox_down,freebox_down,freebox_left,freebox_OK

**Comment by Bibnot** [comment]
Manifestement ca bloque sur freebox_down

**Comment by Bibnot** [comment]
Bon ben tout simplement parce que c'est pas freebox_down qu'il faut mettre mais down !

Desolé pour le derangement

**Comment by Aymkdn** [comment]
En effet, la commande devrait être : `freebox_green,down,down,down,left,OK`. Seul le premier `freebox` est requis dans cette séquence.
