### ISSUE TITLE
Google Home et Freebox mini 4k

### ISSUE THREAD

**Issue by bernardini63** [Aymkdn/assistant-plugins#61]
Bonjour et merci pour le tuto.

J'ai un Google Home mini et une Freebox mini 4k. Or, je rencontre un problème car je ne trouve pas le code de la télécommande (apparemment absent sur mini 4k).

L'installation n'est donc pas possible avec mini 4k ?
Merci.

Bernard

**Comment by Aymkdn** [comment]
En effet, le plugin `assistant-freebox` est pour la Freebox Révolution uniquement.
