### ISSUE TITLE
Question sur le start.bat

### ISSUE THREAD

**Issue by Pandashadow** [Aymkdn/assistant-plugins#62]
Bonjour,

Déjà merci pour le taf effectué !
Les tutos sont parfait, clairs, ça marche très bien.

Dans mon cas je n'ai rien qui tourne 24/24h a part le freebox server.
Je présume que l'on ne peut pas se servir de lui ?

En attendant, j'ai mis le start.bat dans le dossier de démarrage de windows, donc quand je lance le PC il démarre
=> Sais tu comment je peux faire en sorte qu'il démarre minimisé dans la barre de notification ?
J'ai tenté de modifier le start /k par un start /min mais sans succès.

Qu'utilises-tu qui tourne H24 ?

Merci !

**Comment by Aymkdn** [comment]
Bonjour,

Non, on ne peut pas utiliser la Freebox Server pour cela...

Moi j'utilise **pm2** pour faire tourner le programme en tâche de fond et pour qu'il se relance au démarrage (voir [en bas de la documentation](https://aymkdn.github.io/assistant-plugins/) où j'en parle).

Quant à mon cas, j'ai mon PC sous Windows 10 qui est déjà allumé 24h/24, donc avoir ce programme en plus ne change rien :-) Il y a toujours la possibilité d'acheter un [RaspberryPi ](https://fr.wikipedia.org/wiki/Raspberry_Pi) ou un [Server NAS](https://www.google.fr/search?q=synology) pour des solutions plus lights.

**Comment by Pandashadow** [comment]
Hum j'étais parti de la page principale pour faire la config et j'avais raté ce passage.

Merci !

**Comment by ABOATDev** [comment]
Pour lancer la fenêtre en caché :
CreateObject("Wscript.Shell").Run "node" & " index.js", 0, False
"Start hide.vbs"
Marche bien pour moi alors je partage ^^
