### ISSUE TITLE
Freebox veut bien s'éteindre mais pas s'allumer ?

### ISSUE THREAD

**Issue by katraplat** [Aymkdn/assistant-plugins#63]
Bonjour et tout d'abord merci pour ce travail : cela donne tout son sens à la google home.

Il me reste un point à régler : j'ai activé les 2 IFTTT allumer et éteindre la Freebox et seul le dernier fonctionne.
J'ai bien contrôler la chaine BULLETS et IFTTT : tout semble OK

Je vois bien arriver les ordres (qui sont les mêmes d'ailleurs : fonction "power") sur la fenêtre Terminal mais rien n'y fait : la Freebox veut bien s'éteindre lorsqu'elle est allumée mais ne veut pas s'allumer lorsqu'elle est éteinte. Voici le seul message apparaissant sur la fenêtre Terminal : 
"_[assistant] Commande reçue:  [ 'freebox_off' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=123456789&key=power
[assistant-freebox] Erreur : le Freebox Player ne répond pas ! Essayer de changer le paramètre 'box_to_control' dans la configuration de 'hd1' à 'hd2', ou de vérifier votre réseau entre cet ordinateur et la Freebox Player.
[assistant-freebox] Commande « on » exécutée
[assistant-freebox] Erreur : le Freebox Player ne répond pas ! Essayer de changer le paramètre 'box_to_control' dans la configuration de 'hd1' à 'hd2', ou de vérifier votre réseau entre cet ordinateur et la Freebox Player._"

J'ai bien changé la paramètre hd1 en hd2 : pas d'amélioration
J'ai ajouté le paramètre "check_player_on": "false", --> idem

Si vous avez une idée, ça serait super.

et encore merci pour tout

**Comment by Aymkdn** [comment]
Ta question n'est pas très explicite....

Quand tu dis "OK Google, allume la Freebox", est-ce que le Google Home te répond : "J'allume la Freebox" ?
Si oui, est-ce que tu vois les messages suivants dans ta console ? 
```bash
> [assistant] Commande reçue:  [ 'freebox_on' ]
> [assistant] Appelle du plugin 'freebox'
> [assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=123456789&key=power
```

**Comment by katraplat** [comment]
oui désolé, j'ai corrigé le titre et le contenu.

le google home me répond bien et oui je vois bien ce que tu indiques dans la console.

**Comment by Aymkdn** [comment]
Quand tu ouvres http://hd1.freebox.fr/pub/remote_control?code=30481655&key=power dans ton navigateur Internet, est-ce que la Freebox s'allume ?

**Comment by katraplat** [comment]
j'avais aussi fait ce test et cela a les mêmes effets : la commande fonctionne (safari) pour éteindre mais pas pour allumer la Freebox

..oups, je réalise que j'ai communiqué le code de la télécommande en copiant message, pas malin ça.

**Comment by Aymkdn** [comment]
Pas bien grave pour le code télécommande (sauf si tu as quelqu'un connecté à ton wifi en ce moment, et que tu ne connais pas, et qui voit ce message, et qui veut t'emmerder ^^)

Tu parles bien d'allumer la Freebox, et pas l'écran de télévision, n'est-ce pas ?

Aussi, si la commande entrée manuellement dans un navigateur ne provoque pas l'allumage de la Freebox, alors je ne peux rien faire de plus.... Sûrement un bug de ton Freebox Player.

**Comment by katraplat** [comment]
oui je parle bien d'allumer la Freebox.

ok et merci pour ton aide en tout cas.
