### ISSUE TITLE
Problèmes installation Raspberry PI

### ISSUE THREAD

**Issue by P0luX3882** [Aymkdn/assistant-plugins#64]
Bonjour, 
En essayant d'installer le plugin sur un raspberry pi j'ai des erreurs voilà le contenu du fichier de log : 

 info it worked if it ends with ok
1 verbose cli [ '/opt/bin/node', '/opt/bin/npm', 'run-script', 'postinstall' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink /opt/bin/node
5 verbose run-script [ 'postinstall' ]
6 info postinstall assistant-plugins-project@2.0.0
7 verbose unsafe-perm in lifecycle true
8 info assistant-plugins-project@2.0.0 Failed to exec postinstall script
9 error assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
9 error Exit status 8
10 error Failed at the assistant-plugins-project@2.0.0 postinstall script.
10 error This is most likely a problem with the assistant-plugins-project pack$
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./postinstall.js
10 error You can get their info via:
10 error     npm owner ls assistant-plugins-project
10 error There is likely additional logging output above.
11 error System Linux 4.9.59-v7+
12 error command "/opt/bin/node" "/opt/bin/npm" "run-script" "postinstall"
13 error cwd /home/P0luX/assistant-plugins
14 error node -v v0.10.28
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by Aymkdn** [comment]
Tu as une trop vieille version de Node. Mets le à jour.

**Comment by P0luX3882** [comment]
Merci je teste ça de suite

**Comment by titithebad** [comment]
Il faut quelle version de node ?

Ca fonctionne bien sur un RPi1 ou RPi2 ton appli ?

Merci

**Comment by Aymkdn** [comment]
La dernière disponible (ou la plus récente que tu puisses avoir). Et oui ça fonctionne.

**Comment by Aymkdn** [comment]
Pas de retour, donc je suppose que tu as réussi à installer en mettant à jour ton Node :-)

**Comment by Aymkdn** [comment]
Pour info, j'ai créé une documentation dédiée pour l'installation sur RaspberryPi : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

Si tu peux regarder/tester et me donner ton feedback ?

Merci

**Comment by P0luX3882** [comment]
Ça me parait correcte , juste une question pourquoi désinstaller Node.Js et pas le mettre à jour ?

**Comment by Aymkdn** [comment]
Car il n'y a pas de paquet assez récent via apt-get pour raspberry (de ce que j'ai vu). Ça s'arrête à la version 4.x
