### ISSUE TITLE
Serveur

### ISSUE THREAD

**Issue by maureen8** [Aymkdn/assistant-plugins#65]
Bonjour,
Merci pour ce tutoriel. 
Est-il possible d'utiliser le disque dur de la Freebox comme serveur ? Ou est ce que je dois obligatoirement utiliser un autre ordinateur et le laisser allumer en permanence (et non en veille)
Merci !

**Comment by Aymkdn** [comment]
Non pas possible : https://github.com/Aymkdn/assistant-plugins/issues/62
