### ISSUE TITLE
Repertoire vidéo LAN

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#66]
Bonjour ,
J'ai plusieurs Pc , un lecteur multimédia (PopCorn hour /PCH A-400) et deux NAS ( des Synology ) chez moi..
Est il possible d’ouvrir un répertoire sur une machine en réseau ? Via le menu Disque de la FreeBox ?
en paramétrant un ou plusieurs chemins d’accès , comme la commande " va dans mes vidéos "
du genre  "va dans le nas" ou "va dans le popcorn"

Merci

![20171230_210159](https://user-images.githubusercontent.com/33859641/34457022-794d54fe-eda5-11e7-8f65-96eff86cdeb6.jpg)
![20171230_210224](https://user-images.githubusercontent.com/33859641/34457023-7b86653a-eda5-11e7-8dcb-f073c2502431.jpg)

**Comment by Aymkdn** [comment]
Oui, en créant ta propre applet et en lui indiquant comment s'y rendre (par exemple `freebox_home,right,right,ok,down, etc...). Voir les explications de la page de documentation : https://aymkdn.github.io/assistant-plugins/?plugin=freebox

**Comment by nusmiaf** [comment]
Bonjour ,
Oui effectivement , ça fonctionne même si il y a beaucoup de commandes pour y arriver ...
Ça y va super 
Merci à toi
