### ISSUE TITLE
Canalsat

### ISSUE THREAD

**Issue by Taanaui** [Aymkdn/assistant-plugins#67]
Bonjour, tout d'abord merci beaucoup pour le travail effectué.........
J'ai cherché mais je n'arrive pas trouver si il est possible de gérer un appuie long dans pushbullet pour pouvoir gérer le changement de chaine dans l'univers canalsat....
Par avance merci pour la réponse

**Comment by Aymkdn** [comment]
Quelqu'un a déjà rapporté ce problème, mais n'ayant pas l'Univers Canalplus je ne peux pas tester...

Le principe du controle de la Freebox est l'appel d'une URL avec le code télécommande et la commande souhaitée. Par exemple pour zapper sur la 6 : `http://hd1.freebox.fr/pub/remote_control?code=123456&key=6`

Si on veut zapper sur la 12 on va taper 1 puis 2 dans un délai assez court (300ms actuellement), ce qui va créer deux requêtes : 
`http://hd1.freebox.fr/pub/remote_control?code=123456&key=1`
`http://hd1.freebox.fr/pub/remote_control?code=123456&key=2`

Tu peux essayer de modifier la durée entre l'envoi des commandes de changement de chaine en ajoutant le paramètre `delay_canal` dans ta configuration ([voir la documentation](https://aymkdn.github.io/assistant-plugins/?plugin=freebox)). Tu peux tenter de réduire ce délai (à `100` par exemple), mais pas sûr que ça fonctionne.

L'autre possibilité est que l'Univers CanalSat utilise l'option `long=true` de la Freebox v5. Du coup il faudrait que tu essaies dans ton navigateur d'appeler ces deux requêtes (en remplacement `123456` par ton code télécommande) : 
`http://hd1.freebox.fr/pub/remote_control?code=123456&key=1&long=true`
`http://hd1.freebox.fr/pub/remote_control?code=123456&key=2`
Pour voir si ça effectue le changement de chaine voulu.

Tiens moi au courant de tes découvertes.

**Comment by Taanaui** [comment]
Canalsat utilise bien l'option long=true. Maintenant je dois pouvoir trouver dans tes billets la solution pour installer cette commande

**Comment by Aymkdn** [comment]
Je vais faire une mise à jour pour ajouter cette option.

**Comment by Taanaui** [comment]
Je l'attend donc avec impatience ;) et encore merci pour ta réactivité et ton travail.

**Comment by Aymkdn** [comment]
Alors, arrête le programme, puis mets à jour en utilisant le fichier `update.bat` qui se trouve dans ton répertoire. Tu devrais voir la mise à jour de `assistant-freebox` vers la version **2.0.4**.

Ensuite dans le fichier `configuration.json`, dans la section du plugin **freebox**, ajoute le paramètre `"use_Chaines_CANAL":true`.

Démarre le programme et teste.

En plus du numérotage qui va utiliser le `long=true`, ça va aussi automatiquement dans le menu **"Les Chaines Canal"** (au lieu de **Freebox TV**) quand tu lui dis d'allumer la TV, et ça va prendre la numérotation des chaines de Canal au lieu de Free (donc si tu dis `zappe sur NRJ12` ça va zapper sur la 62 au lieu de la 12).

Tu peux tester et me dire si c'est bon ?
`

**Comment by Aymkdn** [comment]
@Taanaui si tu peux tester et me tenir au courant stp ? :-)

**Comment by Taanaui** [comment]
Apparement il y as un pb il me dis ça:
module.js:657
    throw err;
    ^

SyntaxError: D:\telechargements\assistant-plugins\assistant-plugins\configura
n.json: Unexpected string in JSON at position 361
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.exports.start (D:\telechargements\assistant-plugins\assistant-p
ins\node_modules\assistant-plugins\index.js:4:23)
    at Object.<anonymous> (D:\telechargements\assistant-plugins\assistant-plu
s\index.js:1:92)
    at Module._compile (module.js:635:30)

D:\telechargements\assistant-plugins\assistant-plugins>

**Comment by Aymkdn** [comment]
Tu as dû oublier une virgule ou entrer un mauvais caractère ton fichier `configuration.json`

**Comment by Taanaui** [comment]
Effectivement, et maintenant ça marche nickel, avec le bon adressage des chaines ......

**Comment by Taanaui** [comment]
Bravo

**Comment by Aymkdn** [comment]
Cool :-)
