### ISSUE TITLE
allumer la freebox et zapper sur la chaine x  

### ISSUE THREAD

**Issue by fab4u4467** [Aymkdn/assistant-plugins#69]
Bonjour, 

J'ai installé et configuré assistant-plugins et le plugin freebox (ainsi que les 3 autres plugins) afin de contrôler  la freebox avec Google Home. Tout fonctionne à merveille à l'exception d'une commande : " allumer la freebox et zapper sur la chaine x"
La Freebox s'allume, et affiche l'écran d'accueil de la freebox avec les différents menus. Même zapper sur une chaine donnée quand on est sur la page d'accueil  ne donne rien .  Pour zapper, il faut que je sois déjà sur une chaine.
Je ne suis pas certains que cela vienne du plugins ou d'un défaut de configuration, puisque de toute manière quand j'utilise ma télécommande , à l'allumage de la box je suis toujours sur l'écran d'accueil, et je dois sélectionner le menu freebox TV pour aller sur la dernière chaine regardée..

Enfin, vu la manière dont est décrite cette commande du plugins, je me dit qu'il y a peut-être quelques choses à configurer au niveau de la box elle même ?

**Comment by Aymkdn** [comment]
La commande est : `OK Google, allume la télé et zappe sur XYZ` (et non pas `allume la Freebox`). La commande `allume la Freebox` va juste allumer la Freebox et c'est tout. Contrairement à `allume la télé` qui va allumer la Freebox puis entrer dans le menu Freebox TV.

Aussi, si tu es sur la page d'accueil et que tu dis `zappe sur XYZ` ça ne va pas fonctionner (car ça n'a pas de sens de zapper sur cet écran). Il te faudra dire d'abord : `mets la télé` puis ensuite `zappe sur YXZ` une fois Freebox TV activé.

**Comment by Aymkdn** [comment]
Pas de réponse. Je ferme l'issue.
