### ISSUE TITLE
Impossible d'avoir la mosaïque Freebox. 

### ISSUE THREAD

**Issue by ChrisAnddu91** [Aymkdn/assistant-plugins#70]
Bonjour, 
je voudrais tous d'abord remercier Aymeric pour ce super boulot. 
Voici ma config; 
Un Google Home + un Raspberry PI 2 qui fait tourné NodeJS et NPM + un compte IFTTT et Pushbullet sur mon compte Gmail pour faire tourné l'ensemble. 
Tous marche a merveille avec les Applet d'Aymeric + les Applets que j'ai moi même fait selon les explications de la documentation du plugin Freebox. Exemple; j'ai fait un Applet pour mettre les chaines en PiP. 
La seul chose que je n'ai pas réussi a faire c'est de faire afficher la mosaïque de chaine en demandant la phrase suivant = OK Google Zapp sur la Zero ou encore Zapp sur la mosaïque. 
Les commandes arrivent bien a la freebox comme toutes les autres, mais impossible de la faire s'afficher réellement. Ce n'ai pas un gros problème en soit, mais se serait plus simple pour moi pour choisir mon programme le soir devant la télé!
Je joins les captures d'écrans au besoin. 

Chris
![2018-01-03_014152](https://user-images.githubusercontent.com/35049619/34506009-630bfcbe-f029-11e7-9df5-da1301d83156.png)
![2018-01-03_014244](https://user-images.githubusercontent.com/35049619/34506010-633a74cc-f029-11e7-8afb-fe114dc9796f.png)
![2018-01-03_013859](https://user-images.githubusercontent.com/35049619/34506011-638f5046-f029-11e7-887f-6d805e5e692a.png)

**Comment by Aymkdn** [comment]
Tu peux créer ta propre applet qui s'enclenche sur un truc comme `OK Google, mets la mosaïque`, et qui va envoyer l'action `freebox_zappe sur la 0`

**Comment by ChrisAnddu91** [comment]
Merci de ton aide cela marche maintenant. En fait j'avais effectivement fait l'Applet pour la mosaïque mais il ne fonctionnait pas avec la valeur "mosaïque" ou "zero" n'est pas connu de la Freebox. Comme vu sur les captures. Avec la valeur "0" dans la phrase de l'action ça marche mieux! J'étais persuadé d'avoir aussi testé avec "0" avant d'ouvrir l'issues, mais là aussi j'ai dû fait une faute de frappe dans la phrase.
Encore Merci.
Chris.
