### ISSUE TITLE
installation assistant pluggins sur raspberry

### ISSUE THREAD

**Issue by benetnat** [Aymkdn/assistant-plugins#71]
Bonsoir je viens d installer le pluggins sur mon PC tous fonctionne à merveille entre ma freebox et ma google home.
Sauf que je veux l installer sur mon raspberry pour ne pas devoir laisser le pc allumé. et voici l'erreur :
![ce](https://user-images.githubusercontent.com/35077266/34535972-0525d46c-f0c4-11e7-9709-a680e9aac24e.jpg)

Merci d'avance je Bug.

**Comment by Aymkdn** [comment]
Bonsoir. Ta version de node est trop vieille. Essaie de faire : `sudo apt install nodejs`

Une fois fait vérifie la version de node avec : `node -v`
Et pour npm : `npm -v`

**Comment by benetnat** [comment]
Voici mes versions:
node -v v0.10.29
 npm -v 1.4.21

**Comment by Aymkdn** [comment]
Donc toujours pas à jour.
Quand tu as tapé `sudo apt install nodejs` ça t'a dit quoi ?

**Comment by Aymkdn** [comment]
Il y a un article en anglais qui explique comment mettre à jour Node pour RPi : http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/

**Comment by benetnat** [comment]
Je galere pour mettre a jour.
 sudo apt install nodejs
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
nodejs est déjà la plus récente version disponible.
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  pix-icons pix-plym-splash pixel-wallpaper
Veuillez utiliser « apt-get autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

**Comment by Aymkdn** [comment]
Tu avais déjà node ou c'est toi qui l'a installé ?

**Comment by benetnat** [comment]
non deja present

**Comment by benetnat** [comment]
je vais essayer de le supprimer et de le remplacer?

**Comment by benetnat** [comment]
Je viens de faire un petit
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
c en cours....

**Comment by benetnat** [comment]
impossible de mettre une autre version!

**Comment by Aymkdn** [comment]
OK tiens moi au courant. Ça m'intéresse et me permettra de mettre à jour la documentation !

**Comment by Aymkdn** [comment]
Essaie : `apt remove nodejs`
Puis : `curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -`
Et finalement : `sudo apt install nodejs`

**Comment by Aymkdn** [comment]
Bon, j'ai bien galéré, mais j'ai réussi à installer une émulation de RaspBian sur mon Windows, ce qui m'a permis de tester et de créer une documentation dédiée pour l'installation sur RaspberryPi : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

Si tu peux regarder/tester et me donner ton feedback ?

Merci

**Comment by iPapy** [comment]
Merci à toi car moi aussi je galère un peu pour l'installation, je regarde pour ma part demain dans la journée car je travail de nuit et ferait aussi un feedback

**Comment by benetnat** [comment]
Bonsoir quel galère j'ai une erreur de segmentation maintenant.

**Comment by Aymkdn** [comment]
@ipapy : tout est bon donc ! 

@benetnat : en faisant quoi ?

**Comment by benetnat** [comment]
non j ai pas reussi, quand je fais un "node -v" pour voir la version, il me dit erreur de segmentation...

**Comment by Aymkdn** [comment]
peux-tu dire ce que tu as fait, les étapes etc ?

**Comment by Aymkdn** [comment]
En regardant sur le net, il semble que ça peut être dû à une mauvaise installation de Node.

Donc suis bien les étapes que j'ai données dans la documentation, et dis moi à quel endroit tu as un problème (si le "segmentation fault" arrive dès le tout début à l'étape de vérification de la version de Node, alors ignore cette erreur et continue le tutorial)

**Comment by benetnat** [comment]
![image](https://user-images.githubusercontent.com/35077266/34605278-4d139816-f20b-11e7-9d1b-0181613f2c3e.png)
 Voici mon erreur en suivant le Tuto

**Comment by Aymkdn** [comment]
Et si tu tapes : 
```bash
~/node-v9.3.0-linux-armv6l/bin/node -v
```

Ça donne quoi ?

(au passage, tu fais ça en **root** donc tu n'as pas besoin de taper les **sudo**)

**Comment by benetnat** [comment]
v 9.3.0

**Comment by benetnat** [comment]
oui pardon pour le sudo

**Comment by Aymkdn** [comment]
OK donc tape : 
```bash
rm -rf /usr/bin/node
rm -rf /usr/bin/npm
ln -s ~/node-v9.3.0-linux-armv6l/bin/node /usr/bin/node
ln -s ~/node-v9.3.0-linux-armv6l/bin/npm /usr/bin/npm
```

En retente ensuite : 
```bash
node -v
```

**Comment by benetnat** [comment]
juste après le node -v "erreur de segmentation"

**Comment by Aymkdn** [comment]
Quand tu as tapé les commandes avant, tu as eu des erreurs ?

Autre question : tu as bien fait un `apt remove nodejs` avant de commencer ?

Dis moi ce que la commande ci-dessous te donne : 
```bash
which node
```

(En gros tu as fait une mauvaise installation à un moment donné et il continue à prendre le mauvais `node` au lieu de prendre le bon que tu viens d'installer)

**Comment by benetnat** [comment]
oui nodejs bien désinstallé, root@raspberrypi:~# ~/node-v9.3.0-linux-armv6l/bin/node -v
v9.3.0
root@raspberrypi:~# cd node-v9.3.0-linux-armv6l/bin/
root@raspberrypi:~/node-v9.3.0-linux-armv6l/bin# node -v
Erreur de segmentation
root@raspberrypi:~/node-v9.3.0-linux-armv6l/bin# cd
root@raspberrypi:~# rm -rf /usr/bin/node
root@raspberrypi:~# rm -rf /usr/bin/npm
root@raspberrypi:~# ln -s ~/node-v9.3.0-linux-armv6l/bin/node /usr/bin/node
root@raspberrypi:~# ln -s ~/node-v9.3.0-linux-armv6l/bin/npm /usr/bin/npm
root@raspberrypi:~# node -v
Erreur de segmentation
root@raspberrypi:~# npm -v
Erreur de segmentation
root@raspberrypi:~# which node
/usr/local/bin/node
root@raspberrypi:~#

**Comment by Aymkdn** [comment]
OK va supprimer les mauvais liens : 
```bash
rm -rf /usr/local/bin/node
rm -rf /usr/local/bin/npm
node -v
```

**Comment by benetnat** [comment]
root@raspberrypi:~# rm -rf /usr/local/bin/node
root@raspberrypi:~# rm -rf /usr/local/bin/npm
root@raspberrypi:~# node -v
bash: /usr/local/bin/node: Aucun fichier ou dossier de ce type

**Comment by Aymkdn** [comment]
Ahah OK. C'est peut-être parce que t'es root.
Donc tape : 
```bash
ln -s ~/node-v9.3.0-linux-armv6l/bin/node /usr/local/bin/node
ln -s ~/node-v9.3.0-linux-armv6l/bin/npm /usr/local/bin/npm
node -v
```

**Comment by benetnat** [comment]
YES 
root@raspberrypi:~# ln -s ~/node-v9.3.0-linux-armv6l/bin/node /usr/local/bin/node
root@raspberrypi:~# ln -s ~/node-v9.3.0-linux-armv6l/bin/npm /usr/local/bin/npm
root@raspberrypi:~# node -v
v9.3.0

**Comment by benetnat** [comment]
version npm -v   = 5.5.1

**Comment by Aymkdn** [comment]
Yep parfait :-) Tu peux passer à la suite !!

**Comment by benetnat** [comment]
j essaie de suite...

**Comment by benetnat** [comment]
On y est presque:  
npm notice created a lockfile as package-lock.json. You should commit this file.
+ assistant-notifier@2.0.0
+ assistant-freebox@2.0.5
added 20 packages in 45.22s
root@raspberrypi:~/assistant-plugins# 5. Installation finale
bash: 5. : commande introuvable
root@raspberrypi:~/assistant-plugins# npm install --loglevel error

> websocket@1.0.25 install /root/assistant-plugins/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

_**sh: 1: cannot create builderror.log: Permission denied**_
sh: 1: node-gyp: Permission denied
added 69 packages in 129.187s
root@raspberrypi:~/assistant-plugins#

**Comment by Aymkdn** [comment]
OK, continue. Tu as des erreurs, mais elles ne sont pas graves.

**Comment by benetnat** [comment]
ca avance:
assistant-plugins-project@2.0.0 postinstall /root/assistant-plugins
> node ./postinstall.js

[assistant] Configuration requise pour le plugin 'freebox'.
[assistant] Configuration requise pour le plugin 'notifier'.
[assistant] Installation terminée.
root@raspberrypi:~/assistant-plugins# node index.js
[assistant] Erreur : vous devez configurer le token de PushBullet

**Comment by benetnat** [comment]
root@raspberrypi:~# npm install --loglevel error && npm run-script postinstall
up to date in 2.471s
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-05T11_40_18_865Z-debug.log

**Comment by Aymkdn** [comment]
Oui c'est bon. Il s'est installé.

Maintenant tu dois configurer le plugin freebox ET le plugin notifier. Regarde le site pour savoir quoi mettre dans `configuration.json`.

**Comment by Aymkdn** [comment]
Par contre je ne comprends pas pourquoi tu as refait `npm install --loglevel error && npm run-script postinstall` à la base de ton répertoire `/root/`... 

Tout doit se faire dans `/root/assistant-plugins/` et apparemment tu l'as fait correctement la première fois.

**Comment by benetnat** [comment]
oui erreur de ma part! je ne trouve pas le fichier configuration.json

**Comment by Aymkdn** [comment]
Tu as quoi dans ton répertoire assistant-plugins ?
```bash
ls -la ~/assistant-plugins/
```

**Comment by Aymkdn** [comment]
Si tu n'as pas de `configuration.json`, alors, toujours dans ton répertoire **assistant-plugins** tape : 
```bash
npm run-script postinstall
```

Cette fois le fichier a dû se créer.

**Comment by Aymkdn** [comment]
Impossible d'y accéder ? T'essaies d'y accéder comment ? :-)

Actuellement il est dans le répertoire **root* et seulement l'utilisateur **root** peut le modifier.

Si tu n'as pas d'interface graphique, il te faut utiliser la commande `nano configuration.json`, mais si tu n'as pas l'habitude, ce n'est pas simple.
Sinon tu peux le télécharger localement sur ton PC, le modifier, puis le ré-uploaded (mais tu dois faire cette opération avec l'utilisateur **root**).

C'est pourquoi il faut éviter te faire tout ça en root...

**Comment by benetnat** [comment]
Je suis sur fillezilla et je fais une recherche et rien c 'est dingue

**Comment by benetnat** [comment]
c bon je le fais en nano

**Comment by Aymkdn** [comment]
Non c'est pas dingue, car avec filezilla tu dois te connecter avec un autre utilisateur (comme **pi** par exemple), et donc tu n'arrives pas au bon endroit.

**Comment by benetnat** [comment]
Bravo l'artiste
root@raspberrypi:~/assistant-plugins# node index.js
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 2 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.5)
[assistant-freebox] Demande d'autorisation auprès du Freebox Server...
[assistant-freebox] Approuvez le plugin en allant sur l'écran LCD de votre Freebox Serveur et en utilisant la flèche de droite sur celui-ci.
[assistant-freebox] Le plugin a été autorisé sur la Freebox
[assistant-freebox] Configuration terminée. Vous êtes prêt à utiliser le plugin Freebox.
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Configuration sauvegardée.
[assistant-freebox] Récupération des chaines sur free.fr terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Erreur : vous devez configurer ce plugin !
root@raspberrypi:~/assistant-plugins# node index.js
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 2 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.5)
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Récupération des chaines sur free.fr terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Erreur : vous devez configurer ce plugin !
root@raspberrypi:~/assistant-plugins#

**Comment by Aymkdn** [comment]
Sauf que tu n'as pas configuré le plugin **notifier**.... Tu vas l'utiliser ? Tu as un Google Home ? Tu as regardé (la doc)[https://aymkdn.github.io/assistant-plugins/?plugin=notifier] ?

**Comment by benetnat** [comment]
oui j'ai un google home

**Comment by benetnat** [comment]
C nickel, j'ai encore quelque réglages sur les chaines à  faire mais tout fonctionne  très bien.

Un grand merci

**Comment by benetnat** [comment]
Mon système commande l'ensemble des appareils de la maison (volets porte de garage lumière chauffage et maintenant la freebox.
je crois que je prendre du poids!!!

**Comment by iPapy** [comment]
Bonsoir Aymkdn,

Alors moi je bloque à l'étape 8 quand je lance la commande "pm2 startup" j'ai le message suivant:

[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing systemctl enable pm2-root
[DONE]
>>> Executing systemctl start pm2-root
[DONE]
>>> Executing systemctl daemon-reload
[DONE]
>>> Executing systemctl status pm2-root
● pm2-root.service - PM2 process manager
   Loaded: loaded (/etc/systemd/system/pm2-root.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-01-05 14:32:33 UTC; 1min 59s ago
     Docs: https://pm2.keymetrics.io/
 Main PID: 735 (PM2 v2.9.1: God)
   CGroup: /system.slice/pm2-root.service
           └─735 PM2 v2.9.1: God Daemon (/root/.pm2)

Jan 05 14:32:33 raspberrypi pm2[438]: [PM2] Restoring processes located in /root/.pm2/dump.pm2
Jan 05 14:32:33 raspberrypi pm2[438]: [PM2][ERROR] Failed to read dump file in /root/.pm2/dump.pm2
Jan 05 14:32:33 raspberrypi pm2[438]: [PM2] Restoring processes located in /root/.pm2/dump.pm2
Jan 05 14:32:33 raspberrypi pm2[438]: [PM2][ERROR] Failed to read dump file in /root/.pm2/dump.pm2.bak
Jan 05 14:32:33 raspberrypi pm2[438]: [PM2][ERROR] No processes saved; DUMP file doesn't exist
Jan 05 14:32:33 raspberrypi pm2[438]: ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
Jan 05 14:32:33 raspberrypi pm2[438]: │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
Jan 05 14:32:33 raspberrypi pm2[438]: └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
Jan 05 14:32:33 raspberrypi pm2[438]:  Use `pm2 show <id|name>` to get more details about an app
Jan 05 14:32:33 raspberrypi systemd[1]: Started PM2 process manager.
[DONE]
+---------------------------------------+
[PM2] Freeze a process list on reboot via:
$ pm2 save

[PM2] Remove init script via:
$ pm2 unstartup systemd

Alors que en mode test "node index.js" tout fonctionne bien, as tu une idée?

Merci d'avance pour ta réponse.

**Comment by Aymkdn** [comment]
@iPapy > c'est mieux d'ouvrir ta propre issue plutôt que de polluer celle de quelqu'un ^^

Sinon, tout est correct dans la copie que tu as faite. Cela a fonctionné correctement (en tout cas je ne vois aucune erreur)

**Comment by iPapy** [comment]
Désolé j'ai pas l'habitude de github
