### ISSUE TITLE
Erreur en fin d'installation

### ISSUE THREAD

**Issue by iPapy** [Aymkdn/assistant-plugins#72]
Donc j'ouvre ma propre issue ;-) et désolé pour mon post sur l'autre issue

Donc tu ne vois rien d'anormal mais quand je lance ensuite "sudo env PATH=$PATH:/home/pi/node-v9.3.0-linux-armv6lbin /home/pi/node-v9.3.0-linux-armv6l/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi' j'ai le message "env: ‘/home/pi/node-v9.3.0-linux-armv6l/lib/node_modules/pm2/bin/pm2’: No such file or directory" et ce qui m'a surtout inquiété sur mon précédent post c'était le message "pm2 unstartup systemd" lors de la commande "pm2 startup"

**Comment by Aymkdn** [comment]
Tu n'as pas besoin de lancer cette commande dans ton cas car apparemment il a bien fonctionné déjà.

**Comment by Aymkdn** [comment]
J'ai mis à jour la doc pour être plus claire !

**Comment by iPapy** [comment]
D'accord je vais regarder ça mais je crois que j'ai encore un souci, je vérifie tout et je reviens, en tout cas super boulot que tu as fait franchement un BRAVO

**Comment by iPapy** [comment]
Bonsoir Aymeric,

Avant de passer en auto-load je suis en train de peaufiner des petites choses qui ne fonctionne pas comme j'aimerais et je voudrais avoir ton avis.

J'ai bien mis "true" derrière "use_Mon_Bouquet' mais au démarrage du player soit il arrive bien sur la ligne mon bouquet soit sur Freebox TV c'est complètement aléatoire, ensuite si je veux lancer une chaine je suis obligé de rentré manuellement dedans pour lancer une chaine et donc je voudrais savoir si il n'y aurait  pas moyen de rentré directement dans mon bouquet afin qu'il lance la dernière chaine qui était visualisé avant l'extinction?

J'ai aussi remarqué que autant la GH allume bien mon player mais qu'elle à beaucoup de mal à l'éteindre en me disant souvent "et la c'est le bug" ou encore "je ne comprend pas votre demande", as tu une idée?

Autre question, je n'utilise pas le répertoire vidéo du disque dur de la Freebox mais le disque dur de mon NAS Synology depuis le player que je vois en serveur UPnP donc j'ai essayer de changer des truc dans "search_path" mais cela ne fonctionne pas, as tu une idée?

Merci d'avance pour ton aide

**Comment by Aymkdn** [comment]
> J'ai bien mis "true" derrière "use_Mon_Bouquet' mais au démarrage du player soit il arrive bien sur la ligne mon bouquet soit sur Freebox TV c'est complètement aléatoire, ensuite si je veux lancer une chaine je suis obligé de rentré manuellement dedans pour lancer une chaine et donc je voudrais savoir si il n'y aurait pas moyen de rentré directement dans mon bouquet afin qu'il lance la dernière chaine qui était visualisé avant l'extinction?

Si tu dis "OK Google, allume la Freebox", ça va **seulement** allumer la Freebox.
Si tu lui dis "OK Google, allume la télé", ça va allumer la Freebox **ET** va aller dans Mon Bouquet (et donc sur les chaines de TV).
Tu peux même dire "OK Google, allume la télé et zappe sur M6", qui va allumer la Freebox, va aller dans Mon Bouquet, et va zapper sur la bonne chaine.

S'assurer de bien activer l'applet qui convient : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#utilisation

> J'ai aussi remarqué que autant la GH allume bien mon player mais qu'elle à beaucoup de mal à l'éteindre en me disant souvent "et la c'est le bug" ou encore "je ne comprend pas votre demande", as tu une idée?

Tu ne prononces pas assez bien ? ^^ Tu peux tester sur ton téléphone, afin de voir ce que Google Assistant comprend quand tu lui parles. Tu peux aussi éditer l'applet si tu veux changer la phrase dite.

Il faut aussi activer l'applet qui va bien, évidemment.

> Autre question, je n'utilise pas le répertoire vidéo du disque dur de la Freebox mais le disque dur de mon NAS Synology depuis le player que je vois en serveur UPnP donc j'ai essayer de changer des truc dans "search_path" mais cela ne fonctionne pas, as tu une idée?

Regarde cette réponse : https://github.com/Aymkdn/assistant-plugins/issues/59#issuecomment-354003563

**Comment by Aymkdn** [comment]
@iPapy : c'est bon ?

**Comment by iPapy** [comment]
Bonsoir Aymeric,

J'ai encore un petit souci avec mon fichier index.js qui se trouve dans le répertoire "assistant-plugins" et qui quand je lance "node index.js" alors que je suis dans la racine ne se lance pas. J'ai chercher sous WinSCP le fichier pour le déplacer à la racine mais je ne le trouve pas. Je verrais une fois tout configurer pour que cela se lance automatiquement en tache de fond une fois tout configuré en espérant ne pas avoir d'autre souci.

Autrement pour les commandes c'est tout bon, j'ai déplacé aussi mon GH car trop près de la télé et ça perturbait la compréhension des commandes ;-) 

En tout cas après explication c'est effectivement plus claire, encore merci :-)

**Comment by Aymkdn** [comment]
> qui quand je lance "node index.js" alors que je suis dans la racine ne se lance pas
Quel est le message d'erreur exactement ?

**Comment by Aymkdn** [comment]
Pas de réponse, donc je ferme le issue pour le moment :-)

**Comment by iPapy** [comment]
Bonsoir Aymeric

Désolé j'ai pas pu répondre avant. Alors quand je lance "node index.js" alors que je suis à la racine de mon Pi  (pi@raspberry:~ $) j'ai le message suivant:

module.js:557
    throw err;
    ^

Error: Cannot find module '/home/pi/index.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

Par contre si je vais dans le répertoire "assistant-plugins" (cd ~/assistant-plugins) et que je lance "node indes.js" ça se lance bien.

**Comment by Aymkdn** [comment]
C'est normal... le fichier `index.js` est dans le répertoire assistant-plugins, et c'est bien de là qu'il faut le lancer !

**Comment by iPapy** [comment]
D'accord Aymeric je vais donc pouvoir voir maintenant pour que le truc se lance en tache de fond au démarrage de mon Pi en espérant ne pas avoir de nouveau souci.

Autre petit truc que je viens de voir ce soir en rentrant, c'est que quand le player est en veille prolongé la GH n'est pas capable de l'allumé car elle n'est plus en état de veille normal ;-)

**Comment by Aymkdn** [comment]
> Autre petit truc que je viens de voir ce soir en rentrant, c'est que quand le player est en veille prolongé la GH n'est pas capable de l'allumé car elle n'est plus en état de veille normal ;-)

Ouais, mais ça je n'y peux rien :-(

**Comment by iPapy** [comment]
lool en tout cas bravo pour ton script, il m'a donner plein d'idée futur, je ne sais pas si je serait capable de les mettre en œuvre mais les idées sont là ;-)

Bon je vais voir maintenant ta procédure pour mettre en tache de fond au lancement
