### ISSUE TITLE
Probleme ifttt

### ISSUE THREAD

**Issue by crokro** [Aymkdn/assistant-plugins#73]
Bonjour, vous allez peut être m'aider quand j'active un de vos plugin depuis ma google home j'ai dans l'activity log sur ifttt : 
Action failure message: Account has not been used for over a month
Je n'arrive pas a trouver dans ifttt comment reactiver mon compte... (pas plus sur google)

Merco

**Comment by Aymkdn** [comment]
C'est donc ton account Pushbullet qui pose problème, non ?

(et merci d'avoir ouvert un issue sur Github, c'est plus simple pour moi et j'essaie de tout centraliser ici !)

**Comment by crokro** [comment]
Je ne pense pas, rien dans le channel ifttt sur pushbullet...
Copie ecran de l'activity log : 
![capture](https://user-images.githubusercontent.com/35147153/34623059-f09ff7e2-f24f-11e7-9681-fdcf27b6a726.PNG)

**Comment by Aymkdn** [comment]
À mon avis c'est Pushbullet le problème. T'arrives à te connecter sur Pushbullet avec le bon compte ? T'as essayé de le supprimer et recréer ?

**Comment by Aymkdn** [comment]
Si tu essaies de créer une autre applet qui reçoit un message de Google Home et qui envoie, par exemple, un e-mail ou autre. Est-ce que ça fonctionne ? Si oui, c'est que ça vient de Pushbullet le problème.

**Comment by crokro** [comment]
Ok j’ai supprimer et recréer mes 2 comptes ifttt et pushbullet et maintenant tout marche !!! Cool
Merci pour le taf
