### ISSUE TITLE
Changement de chaîne impossible

### ISSUE THREAD

**Issue by franck57fr** [Aymkdn/assistant-plugins#74]
Pour l'instant je ne rencontre que ce problème.
extinction allumage son + son - ok 
mais changement de chaîne impossible que ce soit en donnant
ne numéro de chaîne ou le nom de la chaîne.

![zap_chaine](https://user-images.githubusercontent.com/35191680/34649390-6fb943ee-f3ae-11e7-85ac-eacf6379a3b4.jpg)

**Comment by Aymkdn** [comment]
Il faut dire :
> zappe **sur la** 15

Et non : 
> zappe sur 15

Pour les chaines, ça devrait marcher. Si tu dis `zappe sur France 2` ou `zappe sur BFM TV`, ça te dit quoi dans la console ?

**Comment by franck57fr** [comment]
Exact cependant j'ai bel et bien changé la commande dans IFTTT fais un update et relancé le .bat
J'ai remis la commande par défaut k'ai plus d'erreur dans la console
Ma fille hurle à l'étage car elle regarde un enregistrement et ça change la timeline lol.

Je reviens plus tard pour confirmer si c'est bon ou pas après l'avoir puni de télé (lol).

Merci

**Comment by franck57fr** [comment]
Retour,
après avoir puni ma fille de télé (on c'est une blague),
je confirme que le soucis était bien entre l'écran et la chaise.
Désolé du dérangement et j'ai oublié une chose ...
Bravo pour le développement c'est vraiment top 👍
