### ISSUE TITLE
Double commande ?

### ISSUE THREAD

**Issue by francklek** [Aymkdn/assistant-plugins#75]
bonjour et félicitation pour ce projet.
Il fonctionne bien chez moi, je zappe d'une chaine à l'autre je gère le son...
Mais pour la fonction de mise en marche ou d'arret de la box ça ne fonctionne pas. Lorsque la box est arreté le voyant rouge clignote 2 fois lors de la commande.
J'ai vérifié que air média soit bien activé, j'ai ajouté la commande "check_player_on": false, dans le fichier de configuration mais j'ai toujours le même problème. Une idée ?

**Comment by Aymkdn** [comment]
Le `check_player_on` ne sert qu'à vérifier si la Freebox est allumée ou éteinte (chez certains ça déconne et donc le programme éteint la Freebox croyant qu'elle n'est pas allumée).

Toi, ce n'est pas ça ton problème.

Donc si je comprends bien, quand tu lui dis `éteins la Freebox`, la Freebox ne s'éteint pas ? Pourtant dans ta console, tu vois bien : 
```bash
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=123456789&key=power
```
C'est ça ?

Dans les menus de la Freebox, dans **Réglages > Système > Gestion de l'énergie**, tu as bien **Mise en veille** pour l'action par défaut de la touche d'extinction ?

Sinon, je ne vois pas... ça peut être dû à un bug de ta Freebox sinon ?!

**Comment by Aymkdn** [comment]
T'as trouvé ?

**Comment by francklek** [comment]
Alors étonnamment hier en faisant des essais j'ai trouvé par hasard la parade.
J'ai simplement éditer la commande IFTTT avec mon téléphone en changeant par exemple un espace sur la commande vocale puis re-valider la commande. Depuis elle fonctionne !
D’où vient vraiment le bug, mystère, mais le problème est résolu de cette façon, c'est bon à savoir.
En tout cas bravo pour ton boulot ! Merci
