### ISSUE TITLE
Installation faite ... pas de réponse de la Freebox

### ISSUE THREAD

**Issue by Zoumij** [Aymkdn/assistant-plugins#76]
Bonjour,

je n'ai pas trouvé de réponse dans les FAQ
Je souhaite piloter ma Freebox avec le Google assistant. J'ai fait l'install comme prévu.
Voici ce que la console indique
![capture](https://user-images.githubusercontent.com/35293339/34783907-13c9a58e-f62d-11e7-83d3-35b3e4f7b6ec.JPG)
Node.js est en route
IFTTT et Pushbullet communiquent sans problème (bulles IFTTT dans Pushbullet et IFTTT indique que les applets fonctionnent)
Les applets IFTTT sont installés
Quand je dis "allume la Freebox", Google assistant confirme ... mais rien ne se passe ...
Que faire de plus ?

merci

**Comment by Aymkdn** [comment]
Tu as bien fermé l'onglet de Pushbullet ? Car si tu laisses ouvert https://www.pushbullet.com/#following/ le programme ne recevra pas les notifications.

**Comment by Zoumij** [comment]
Merci pour té réponse
Oui oui, tout est fermé
Toujours rien

**Comment by Aymkdn** [comment]
Tu as utilisé les applets que j'ai créé ou tu as créé ta propre applet ?

Franchement je ne vois pas... Pour moi tout est correct, surtout si tu me dis que [tout ce qui est ici est bon](https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes#1-jai-tout-bien-install%C3%A9-mais-%C3%A7a-ne-fonctionne-pas)... Peut-être un firewall/antivirus qui bloquerait quelque chose ? :thinking:

**Comment by Aymkdn** [comment]
Essaie peut-être de recréer un [token Pushbullet et de le remplacer dans la configuration](https://aymkdn.github.io/assistant-plugins/#configuration-principale) ...

**Comment by Zoumij** [comment]
J’ai utilisé tes applets bien sûr qui sont très bien faits ;-)
J’essaie de désactiver le firewall et je te redis (je ne suis pas chez moi là tout de suite)
Pour le token j’ai déjà relancé un nouveau ... rien ...
Je te tiens au jus
Merci à toi

**Comment by Zoumij** [comment]
Recréation de token, pare-feu désactivé ... rien ne se passe ...
Je ne sais plus...

**Comment by Aymkdn** [comment]
Je ne vois pas .... Si tu as bien les bulles dans Pushbullet, c'est que le problème se passe entre ta machine et Pushbullet... mais aucune idée de pourquoi ça ne fonctionne pas pour toi... 

Quelques questions en plus : 
- c'est un compte Pushbullet tout neuf que tu as créé pour l'occasion ? Ou un ancien que tu as réutilisé ?
- si tu fais un ping de ta machine vers `api.pushbullet.com`, ça fonctionne ?
- si tu fais un ping de ta machine vers `stream.pushbullet.com`, ça fonctionne ?
- tu dois avoir un dossier `node_modules` dans ton répertoire, et dans celui-ci un dossier `assistant-plugins` : 
  * édite le fichier `index.js`
  * après [la ligne 60](      stream.connect();), rajoute cette ligne :  
     ```javascript
       stream.on('error', function(error) { console.log("ERROR: ",error) });
      ```
  * enregistre et relance le programme
  * regarde si tu as une erreur qui apparait

Si jamais tu trouves le problème, je suis preneur :-)

**Comment by Zoumij** [comment]
Alleluiah !!!!
Ca fonctionne en ajoutant la ligne que tu m'as conseillée

pour le reste, c'est un compte Pushbullet tout neuf, les ping sont nickel ...

Merci beaucoup, c'est génial tes applets !! génial pour les fainéants, mais j'adore ...

Et merci pour ton appui dans le SAV ;-)

Bonne journée et continue à imaginer des trucs intelligents ...

**Comment by Aymkdn** [comment]
Bizarre... Cette commande est juste censée afficher les potentielles erreurs, donc pas de raison que ça fasse fonctionner...

Enfin bon, tant mieux si ça marche ;-)

**Comment by Zoumij** [comment]
En fait c'est hyper aléatoire.
Ca a marché toute la matinée, en début d'après-midi plus rien et là ça fonctionne à nouveau.
Je ne sais plus trop ...
Il faut absolument que node.js soit lancé ??

**Comment by Aymkdn** [comment]
Bhein ça ne fonctionne QUE si le programme est lancé, oui...

**Comment by Zoumij** [comment]
Alors je ne comprends pas ce qui se passe ...
Tant pis, je me lèverai et irai chercher la télécommande ;-)
