### ISSUE TITLE
Allumage freebox / Switch automatique sur HDMI2 (Chromecast branché)

### ISSUE THREAD

**Issue by MathieuDuboy** [Aymkdn/assistant-plugins#77]
Bonjour,
Tout d'abord merci pour ce très bon plugin.

Lorsque j'execute la commande "Allume Freebox" + "Allume la TV" par exemple,
je suis automatiquement redirigé vers HDMI2 qui est conecté avec le Chromecast.
Aucun moyen de switcher vers la freebox branchée sur HDMI1.

Y'a t-il un moyen de pouvoir Allumer la Freebox + TV automatiquement (et etre redirigé vers hdmi1 ?)
Merci.

**Comment by Aymkdn** [comment]
Tu appuies sur le bouton Power de la télécommande de la Freebox pour allumer Freebox+TV ? Ou tu fais d'autres manipulation ?

Car le programme agit comme le bouton Power de la télécommande. Ça ne fait rien d'autre de magique :-)

**Comment by MathieuDuboy** [comment]
Sachant que le Chromecast permet de switcher de hdmi1 (ma freebox) vers hdmi2 (le Chromecast) automatiquement pour afficher des videos sur Youtube par Exemple via Google Home ("Ok Google, lis la derniere video de Peppa Pig sur Youtube") , je me demandais si c'était possible de faire l'action inverse ou bien outre-passer le fait que lorsque l'on allume la TV via Google Home, cela soit redirigé vers les Chromecast. Rien de débile, je pense, dans ma question...

Ensuite, Pour répondre à votre question qui n'en était pas vraiment une; effectivement, pour allumer la Freebox+TV, j'appuies sur 2 boutons Power.

Merci en tout cas d'avoir mis fin subitement à mes désirs magiques :-)

**Comment by Aymkdn** [comment]
Donc non, assistant-freebox ne permet pas de switcher l'HDMI. Ça reproduit simplement le comportement du bouton Power de la télécommande Freebox !

La Freebox permet d'allumer les TV qui sont connectés en HDMI. Par exemple, chez moi je n'ai qu'un seul HDMI qui est ma connexion Freebox-TV. Quand j'appuie sur Power ça allume ma Freebox ET ma TV en même temps.

Faut voir si dans la partie Réglages de ta Freebox Player il y a quelque part une option pour ton cas...

**Comment by MathieuDuboy** [comment]
Merci beaucoup.
