### ISSUE TITLE
Installation de assistant plugins sur RaspberryPi

### ISSUE THREAD

**Issue by claudecn13** [Aymkdn/assistant-plugins#78]
bonsoir
après installation sur w10, j'essaye aujourd'hui sur raspberry pi3, mais je suis novice et je voudrai des explications supplémentaires par rapport a votre tuto ..
--- pour l'installation de nodejs dois je créer un fichier : cd/home/pi ? je crois avoir compris que cela remplace la commande cd ~ ?
--- quand je décompresse la 2 eme ligne de commande " rm -rf node-v9.3.0-linux-armv6l.tar.gz"n'a aucun effet !!!
---ensuite pour taper les commandes de node et npm je dois indiquer le meme fichier "cd/home/pi ?
merci

**Comment by Aymkdn** [comment]
- Alors, en effet, `~` indique le *home* de l'utilisateur courant. Si tu es connecté avec l'utilisateur `pi`, alors `cd ~` équivaut à `cd /home/pi`
- `rm -rf node-v9.3.0-linux-armv6l.tar.gz` sert à effacer l'archive que tu viens de télécharger, donc normal qu'il ne se produise rien, à part l'effacement du fichier. Je vais l'enlever de la doc si ça rend les choses confuses !
- S'il y a des changements de dossier, je l'indique. En l'occurrence `node` et `npm` doivent se taper dans le répertoire `/home/pi/assistant-plugins`

**Comment by Aymkdn** [comment]
Pas de retour, je ferme donc l'issue.
