### ISSUE TITLE
Adaptation 

### ISSUE THREAD

**Issue by cyrilphoenix71** [Aymkdn/assistant-plugins#80]
Bonjour, je n'ai pas de PC en mode tjs allumer, en revanche j'ai une box domotique, un rasp3 avec Jeedom. 
Serait il envisageable de porter ta solution en un plugin Jeedom ? 
Merci d'avance

**Comment by Aymkdn** [comment]
Bonjour.

Non, pas de plugin Jeedom envisageable. Par contre ça s'installe sur Raspberry, donc suis le tuto 😉
