### ISSUE TITLE
freebox google home 

### ISSUE THREAD

**Issue by aussemt** [Aymkdn/assistant-plugins#81]
!
![2018-01-14 3](https://user-images.githubusercontent.com/35425725/34917387-ebe0de5e-f945-11e7-86f8-d1738245164e.png)
![2018-01-14 6](https://user-images.githubusercontent.com/35425725/34917390-ec1b39fa-f945-11e7-9cad-cdd8b6c6304f.png)

**Comment by Aymkdn** [comment]
Quelle est la question ?

**Comment by Aymkdn** [comment]
Pas de réponse. Je ferme.
