### ISSUE TITLE
Fonctionnement global

### ISSUE THREAD

**Issue by Kevcaus** [Aymkdn/assistant-plugins#82]
Bonjour et merci Aymeric pour ces contributions :)

J'aimerai si c'est possible que tu puisses me détailler le mode de fonctionnement global une fois pushbullet déclenché. Étant un peu novice je cherche à comprendre quels sont les scripts déclenchés et comment l'aiguillage s'effectue. 
En fait mon projet serait de créer un plugin myfox qui permettrai de contrôler les appareils relies à myfox. C'est possible via IFTTT mais l'intérêt serait de réaliser des actions multiples avec une seule phrase. Ex : "je quitte la maison " ,  il faudrait donc éteindre la TV (pluggin freebox), couper les lampes (pluggin myfox) etc... 

Je suis bien avancé sur les scripts avec l'api myfox. 

Merci pour ton aide 
Si j'arrive à mes fins, je reviendrai vers toi dans le but de diffuser le pluggin :)

**Comment by Aymkdn** [comment]
Tu as regardé la template https://github.com/Aymkdn/assistant-template ?

Une fois la notification reçue, il regarde le mot clé qui correspond au nom du plugin, puis il appelle le plugin. Le plugin fait ensuite ce qu'il veut de son coté.

Sais-tu qu'avec IFTTT tu peux enclencher plusieurs actions avec une seule commande ? C'est un peu caché, mais cela se fait d'ici : https://platform.ifttt.com/maker/aymericdmdv/applets/new — regarde si ça peut correspondre à ton besoin, surtout si tu me dis qu'IFTTT permet déjà de contrôler ce que tu souhaites.

**Comment by Kevcaus** [comment]
Ah non je savais pas pour ifttt ... je vais regarder. Merci !

**Comment by Aymkdn** [comment]
C'est bon, tu as trouvé ton bonheur ?

**Comment by Kevcaus** [comment]
c'est vraiment bien caché sous IFTTT..
Un grand merci pour ton retour rapide. (également pour le template..)
