### ISSUE TITLE
commande sur le pc hote d'assistant

### ISSUE THREAD

**Issue by nusmiaf** [Aymkdn/assistant-plugins#88]
bonjour ,
est il possible de lancer via l'assistant une commande du type :

c:\users\moi>taskkill /IM firefox.exe

ou tout autres bien sur ?

merci

**Comment by Aymkdn** [comment]
Oui, avec le plugin **launch** : https://aymkdn.github.io/assistant-plugins/?plugin=launch

**Comment by nusmiaf** [comment]
Super installation en 30s 
j'ai crée un fichier  "kill_firefox.txt" a la racine de mon répertoire assistant , contenant : taskkill /IM firefox.exe
puis renommer le .txt  en . bat
et le pushbullet donne  => launch_C:\Maison\Electricite\IPX800\GoogleHome\assistant-plugins\Kill_firefox.bat


ça marche (fonctionne) 💃  super !

merci Aymkdn !

**Comment by Aymkdn** [comment]
Cool 😃
