### ISSUE TITLE
Demande accès autorisation sur freebox révolution

### ISSUE THREAD

**Issue by Chris88140** [Aymkdn/assistant-plugins#89]
Bonjour,
Intéressé par la commande vocale à l'aide du google home mini avec la freebox révolution, j'ai suivi votre tuto.
Cependant, ma freebox server me demande une autorisation, dois-je l'accepter ?
A aucun moment, je n'ai trouvé cette étape sur le tuto au autres.
![start](https://user-images.githubusercontent.com/35608117/35163561-7454875e-fd47-11e7-9523-c218a3d9d968.jpg)
Mon ordinateur ne sera allumé pas 24h/24, ce sera uniquement le numéro Tokens qu'if faudra renouveler ?
Merci d'avance pour vos réponses, et de vos partages.

**Comment by Aymkdn** [comment]
Oui il fait autoriser le programme sur la Freebox Serveur en effet.

Par contre, il faut obligatoirement une machine allumée pour que ça fonctionne (celle où tourne le programme).

**Comment by Chris88140** [comment]
Merci,
![image](https://user-images.githubusercontent.com/35608117/35165583-32673ea6-fd4f-11e7-88cd-3edbc85c7c5e.png)
Mais la freebox ne s'allume pas.
C'est bien le programme node.js qui doit être ouvert ?

**Comment by Chris88140** [comment]
Super, tout fonctionne.
Et c'est génial.
Merci en tout cas pour votre partage et de votre réactivité.
Bon WE à vous.

**Comment by Aymkdn** [comment]
Cool! 😊
