### ISSUE TITLE
Astuce pour ne pas allumer la free via freebox_off

### ISSUE THREAD

**Issue by Kevcaus** [Aymkdn/assistant-plugins#90]
Bonjour,

Est-ce que tu aurais une astuce pour ne pas allumer la freebox avec la commande freebox_off.
Le soucis c'est que freebox_on ou off lance la même commande Power. 
De ce fait quand la freebox est déja éteinte, ben elle s'allume.
Je sais pas si il existe un moyen de tester son état?

Je demande car suite à ta préco précédente je suis en train de m'amuser avec ifttt maker et un petit scénario qui me met en route l'alarme, me règle le thermostat et me coupe la freebox (sauf que du coup elle s'allume :) !! )

Merci beaucoup

**Comment by Aymkdn** [comment]
Alors, suite à ta demande je suis en train de modifier le plugin pour que le `freebox_off` ne coupe la Freebox que si elle est allumée. Je ferai une mise à jour plus tard dans le week-end et je reposterai ici pour t'en informer ;-)

**Comment by Kevcaus** [comment]
Je n’en demandais pas tant :) merci beaucoup !

**Comment by Aymkdn** [comment]
Voilà la version 2.0.6 est en ligne !
Pour mettre à jour : 

1. Arrête le programme `assistant-plugins`
2. Utilise `update.bat` (sous Windows, ou `npm update` pour les autres OS) : tu devrais voir `assistant-freebox` se mettre à jour en version 2.0.6
3. Relance le programme

Tiens moi au courant !

**Comment by Aymkdn** [comment]
Cela a introduit un bug que j'ai corrigé dans la v2.0.7

**Comment by Kevcaus** [comment]
Ça fonctionne nickel. 
Dans les logs : « aucune action nécessaire » apparaît :)

Un grand merci pour ton support et te réactivité. Je pense que ça servira à d’autres ;)
