### ISSUE TITLE
launch_ sur linux 

### ISSUE THREAD

**Issue by iceempror** [Aymkdn/assistant-plugins#91]
Bonsoir Aymkdn,

Tout d'abord un grand merci pour ce code qui est juste énorme pour que la freebox fonctionne avec la google home.

Je suis en pleine installation domotique et un féru linux. Par contre je ne développe pas.
Petit question : comment lancer un programme sous linux via la commande launch ?
J'ai suivi ton tuto, mais avec guillemets, simple cotes, pas mieux. J'ai commencé a regarder la doc node js pour comprends comment ca marche.
 
- Y a t'il une modification a faire ailleurs (un ou plusieurs fichiers) ou est ce que la commande launch ne fonctionne que pour des programmes lancés sous windows ?

Ci dessous les logs 
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant] Commande reçue:  [ 'launch_\'/usr/bin/firefox\'' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : '/usr/bin/firefox'
[assistant] Commande reçue:  [ 'launch_\'/usr/bin/firefox\'' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : '/usr/bin/firefox'
[assistant] Commande reçue:  [ 'launch_\'/usr/bin/thunderbird\'' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_\'/usr/bin/thunderbird\'' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : '/usr/bin/thunderbird'
[assistant-launch] Lancement du programme : '/usr/bin/thunderbird'

bash-4.3$ 
bash-4.3$ node -v
v8.9.3
bash-4.3$ npm -v
5.6.0
bash-4.3$ 
bash-4.3$ cat /etc/slackware-version 
Slackware 14.2
bash-4.3$ 

En passant sais tu pourquoi le script lance souvent 2 voire 3 fois la commande a exécuter (ça le fait aussi pour allumer la freebox ou une toute autre action) ?

[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 3386ms
[assistant-freebox] Durée de la vérification de la Freebox allumée : 3419ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50569912&key=power
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50569912&key=power
[assistant-freebox] Commande « on » exécutée
[assistant-freebox] Commande « on » exécutée
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 814ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50569912&key=power
[assistant-freebox] Durée de la vérification de la Freebox allumée : 817ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=50569912&key=power
[assistant-freebox] Commande « on » exécutée
[assistant-freebox] Commande « on » exécutée
Dans ce cas elle ne s'est allumé que lors de la dernière commande.

Te parait il possible d'avoir un serveur linux avec node js qui tourne dessus et pourvoir lancer des applications à distance sur d'autres pc en windows et linux ?
Exemple ton pc/serveur/rasp est prêt et tu lui demande de lancer la messagerie sur ton autre pc du salon.

Par avance merci.

**Comment by Aymkdn** [comment]
Salut,

Alors je te confirme que ça fonctionne sous Linux. Voici l'exemple que je viens de tenter si ça peut t'aider : 
`launch_"/root/test.sh"`

Et le contenu de `/root/test.sh` : 
```bash
#!/bin/bash
echo "pouet" >> /root/test.txt
```

Et je l'ai mis en exécutable : `chmod u+x /root/test.sh` (et je lance mon `node index.js` en root aussi).

Essaie avec un exemple simple comme celui-ci.

N'ayant pas d'interface pour Linux, je ne peux pas tester le lancement d'un programme comme Firefox....

Comment tu lances Firefox à partir de la console d'habitude ?

Sinon, après la [ligne 23](https://github.com/Aymkdn/assistant-launch/blob/master/launch.js#L23) de `node_modules/assistant-launch/launch.js` tu peux ajouter : 
```javascript
if (error) console.log("Error => ",error);
```

Pour voir si ça retourne quelque chose.

**Comment by Aymkdn** [comment]
> Te parait il possible d'avoir un serveur linux avec node js qui tourne dessus et pourvoir lancer des applications à distance sur d'autres pc en windows et linux ?

Peut-être. Il faudra que tu cherches sur Google ([exemple](https://superuser.com/questions/734642/how-to-run-a-program-on-a-remote-pc-via-command-line)) et que tu fasses des tests.

**Comment by Aymkdn** [comment]
> En passant sais tu pourquoi le script lance souvent 2 voire 3 fois la commande a exécuter (ça le fait aussi pour allumer la freebox ou une toute autre action) ?

Oula... non c'est bizarre... Tu peux regarder le canal IFTTT sur PushBullet pour voir s'il reçoit bien qu'une seule fois la commande : https://www.pushbullet.com/#following/

**Comment by iceempror** [comment]
![image](https://user-images.githubusercontent.com/35665027/35197792-401ca77e-fee5-11e7-8951-4d2cc7b118ac.png)

**Comment by Aymkdn** [comment]
Bizarre qu'il reçoive tout deux fois... T'aurais pas merdé dans tes applets IFTTT ? Ou créé 2 comptes en même temps ? Ou quelque chose comme ça...

**Comment by iceempror** [comment]
avec l'ajout de la ligne if (error) console.log("Error => ",error);
apres la ligne 23

Starting assistant Server

[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"

Comme tu le vois  je lance le bin directement.
L'assistant freebox est lancé en root et du coup il a tous les droits.
A moins qu'il faille que je le lance avec un su -c nom de mon user dans une bash ...

**Comment by iceempror** [comment]
concernant ifttt, et pushbullet, je n'ai bien qu'un compte, j'ai par contre une fois tout réinitialisé comme tu l'explique dans ta doc pour voir si c'était mieux.
Maintenant si il le faut je peux tout réinitialiser une nouvelle fois, mais ça l'a toujours fait depuis le début.

**Comment by iceempror** [comment]
root@Hermes:/opt/assistant-plugins# node index.js 
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
Error =>  { Error: Command failed: "/usr/bin/firefox"
No protocol specified
Error: cannot open display: :0

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"/usr/bin/firefox"' }

C'est bien ca, je pense à un pb de droit pour l'ouverture de la console graphique.
Je lance le script assistant-freebox dans une xterm en root mais dans mon bureau avec mon user.
Du coup root n'a pas le droit d'ouvir avec un mode display.

**Comment by iceempror** [comment]
Yeap ! C'est ça !
En fait, il faut passer un xhost+ avant de lancer la commande.
Par contre j'ai le meme problème que pour les commandes freebox, il m'a ouvert 4 firefox ...

bash-4.3$ xhost +
access control disabled, clients can connect from any host
bash-4.3$ su -
Mot de passe : 

Please help keep the world clean: others may wish to use it.

root@Hermes:~# cd /opt/assistant-plugins
root@Hermes:/opt/assistant-plugins# node index.js 
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/firefox"

**Comment by Aymkdn** [comment]
> Par contre j'ai le meme problème que pour les commandes freebox, il m'a ouvert 4 firefox ...

Essaie de supprimer ton compte IFTTT et de le recréer ? Franchement je ne sais pas là...

**Comment by iceempror** [comment]
Ok je tente ca, je te tiens au courant.
Uniquement le compte IFTTT ou pushbullet aussi ?

**Comment by Aymkdn** [comment]
tu peux tenter les deux sinon ^^

**Comment by iceempror** [comment]
J'ai changé les droits pour lancer l'assistant-freebox avec mon compte utilisateur, du coup tout s'ouvre sans problème. It works !
Sinon, pour ceux qui lance l'assistant en root, il faudra donner les droits a root pour lancer du graphique avec un xhost+, puis passer la commande du programme avec un su -c nom_du_programme nom_du_user pour que ça marche (mais il va falloir saisir un mot de passe ou passer avec un sudo à la place de su)

**Comment by iceempror** [comment]
yeap j'essaye de renouveler les 2 comptes et je te tiens au courant.
Pour l'instant mon assistant freebox begaille, lol 

bash-4.3$ node index.js 
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/firefox"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"
[assistant-launch] Lancement du programme : "/usr/bin/firefox"

**Comment by iceempror** [comment]
je viens de refaire un essai après réinitialisation des comptes et pour une commande passé et confirmée dans ifttt, le freebox-assistant en renvoie bien 3 ou 4.

![image](https://user-images.githubusercontent.com/35665027/35198233-16edecbc-feec-11e7-92eb-7c15b995a210.png)

[assistant] Commande reçue:  [ 'launch_"/usr/bin/thunderbird"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/thunderbird"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/thunderbird"' ]
[assistant] Appelle du plugin 'launch'
[assistant] Commande reçue:  [ 'launch_"/usr/bin/thunderbird"' ]
[assistant] Appelle du plugin 'launch'
[assistant-launch] Lancement du programme : "/usr/bin/thunderbird"
[assistant-launch] Lancement du programme : "/usr/bin/thunderbird"
[assistant-launch] Lancement du programme : "/usr/bin/thunderbird"
[assistant-launch] Lancement du programme : "/usr/bin/thunderbird"

Peux tu me dire comment passer en mode debug ou plus verbeux l'assistant pour que je continue à investiguer ?

**Comment by Aymkdn** [comment]
Il n'y pas de mode debug ou plus verbeux que ça.... À vrai dire y'en a jamais eu besoin jusque là, et c'est la première fois que je vois ce problème.

Dans `node_modules/assistant-plugins` après la [ligne 65](https://github.com/Aymkdn/assistant-plugins/blob/master/index.js#L65) tu peux tenter d'ajouter : 
```javascript
console.log("debug => ", push)
```

Pour voir ce qu'il reçoit de PushBullet.

**Comment by iceempror** [comment]
Bonjour,
Bon avec le mode debug activé je n'ai rien vu de déconnant, à moins que tes yeux experts voient quelque chose qui cloche.
Et comme par hasard, il ne begaille pas en ce moment ...
Je vais suivre ça de prêt.

[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
debug =>  { active: true,
  iden: 'ujBkMjAlDXXXXXXXXXXX',
  created: 1516635139.287298,
  modified: 1516635139.310911,
  type: 'note',
  dismissed: false,
  direction: 'incoming',
  sender_name: 'IFTTT',
  receiver_iden: 'ujBkMjXXXXX',
  receiver_email: 'XXXXXXXX@XXXXX',
  receiver_email_normalized: 'XXXXXXXX@XXXXX',
  client_iden: 'udprOCXXXXXX',
  title: 'Assistant',
  body: 'freebox_on' }
[assistant] Commande reçue:  [ 'freebox_on' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 2588ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=XXXXXXX&key=power
[assistant-freebox] Commande « on » exécutée

bash-4.3$ node index.js 
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 5 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.0)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.0.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Chargement du plugin 'wait' (v2.0.1)
[assistant-wait] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
debug =>  { active: true,
  iden: 'ujBkMjAlDGKXXXXXXXX',
  created: 1516635302.6206322,
  modified: 1516635302.633482,
  type: 'note',
  dismissed: false,
  direction: 'incoming',
  sender_name: 'IFTTT',
  receiver_iden: 'ujBkMjAXXXXX',
  receiver_email: 'XXXXXXXX@XXXXXX',
  receiver_email_normalized: 'XXXXXXX@XXXXXX',
  client_iden: 'udprOCjXXXXXXXX',
  title: 'Assistant',
  body: 'launch_"/usr/bin/thunderbird"' }
[assistant] Commande reçue:  [ 'launch_"/usr/bin/thunderbird"' ]
[assistant] Appelle du plugin 'launch'
debug =>  { active: true,
  iden: 'ujBkMjAlDXXXXXXXXXX',
  created: 1516635341.6818938,
  modified: 1516635341.697796,
  type: 'note',
  dismissed: false,
  direction: 'incoming',
  sender_name: 'IFTTT',
  receiver_iden: 'ujBkMXXXXXXX',
  receiver_email: 'XXXXXXXX@XXXXXX',
  receiver_email_normalized: 'XXXXXXX@XXXXX',
  client_iden: 'udprOCjAXXXXXX',
  title: 'Assistant',
  body: 'freebox_off' }
[assistant] Commande reçue:  [ 'freebox_off' ]
[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 693ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=XXXXXXX&key=power
[assistant-freebox] Commande « off » exécutée

Je pense à une chose, j'ai 2 google home à la maison (une google home et une jbl link 20 qui sont toutes les 2 attachés au même compte). Est ce que cela pourrait expliquer le fait qu'il répète les commandes ?

En tout cas, merci pour ton aide.

**Comment by Aymkdn** [comment]
> Je pense à une chose, j'ai 2 google home à la maison (une google home et une jbl link 20 qui sont toutes les 2 attachés au même compte). Est ce que cela pourrait expliquer le fait qu'il répète les commandes ?

À priori non puisque Google gère les multiples requests et donc ça ne devrait le faire.

**Comment by Aymkdn** [comment]
Comme tout semble fonctionner, je ferme ton issue. Si jamais, tu peux continuer à poster ici :-)
