### ISSUE TITLE
Les commandes Freebox ne fonctionnent pas toutes 

### ISSUE THREAD

**Issue by taikun78** [Aymkdn/assistant-plugins#93]
Bonjour, voilà mon problème : je n’ai aucun soucis avec les commandes « zappe sur » et « allume la freebox et zappe sur » mais par contre les autres ne fonctionnent pas. Google box me dit ok je fait la dite action mais rien ne se passe. Dans certain cas comme »éteins  la freebox » elle rajoute en plus dans la phrase correspondante à l’action le mot zappe... ex: ok j’eteins zappe la freebox...

Pouvez vous m’aider ?

**Comment by Aymkdn** [comment]
Peux-tu montrer le contenu de la console (les messages qui s'affichent lorsque tu envoies une commande). Exemple : 
![capture](https://user-images.githubusercontent.com/946315/35563203-4815215e-05b6-11e8-9ae9-04f1a3e0c81b.PNG)

**Comment by taikun78** [comment]
Voilà la capture 

![6aea6fc1-ab0a-43fc-87f8-544d9b87b7a2](https://user-images.githubusercontent.com/35957444/35564378-39944282-05ba-11e8-910e-49ecf243542c.png)

**Comment by Aymkdn** [comment]
Tu as utilisé les applets IFTTT que j'ai créées, ou tu as créées ta propre applet ?

Ferme l'onglet de Pushbullet car ça peut interférer.

Arrête et relance le programme assistant-plugins pour me montrer ce qu'il charge au démarrage

**Comment by taikun78** [comment]
Déjà merci à toi d’être aussi réactif 👍Je n’ai utilisé que t’es applets IFTTT, je n’ai modifier que les phrase d’ordre genre « éteins là box etc... mais je n’ai pas touché aux phrases de réponse.
Voici la nouvelle capture 
![bb789da8-d69f-4068-8fa2-be74820840b5](https://user-images.githubusercontent.com/35957444/35565221-f3c76e66-05bc-11e8-9ddb-bf993d99f1bc.png)

**Comment by Aymkdn** [comment]
Dis :

- `OK Google, allume la Freebox`,
- puis `OK Google, éteins la Freebox`
- puis `OK Google, allume la télé et zappe sur M6`
- puis `OK Google, éteins la Freebox` 

Et montre moi tous les résultats dans ta console !

**Comment by taikun78** [comment]
Voilà : 
![81087e46-6f05-4254-a9f6-84b0c7ccb730](https://user-images.githubusercontent.com/35957444/35565471-ea81120c-05bd-11e8-868b-b250cd727464.png)

Pour info je m’absente Une petite heure 🍽
A tout de suite

**Comment by Aymkdn** [comment]
Tu peux me montrer comment est configurée ton applet "Allume la Freebox" dans IFTTT par exemple ? (je vais manger aussi ^^)

**Comment by taikun78** [comment]
Me re voilà
Voici 2 captures, une de allume la freebox et l’autre d’etein La freebox
![c3da704a-966b-43ca-baa5-a2122a011829](https://user-images.githubusercontent.com/35957444/35567784-8c32fcac-05c6-11e8-8925-13ec46096c10.png)
![5c236f4d-8a9f-4b1c-ab15-474efa038b06](https://user-images.githubusercontent.com/35957444/35567796-95aaa424-05c6-11e8-90fc-c3c8de98cea7.png)

**Comment by taikun78** [comment]
En t’envoyant les 2 dernière captures j’ai pensé à un truc, j’utilise IFTTT sur tablette (iPad pro ) ne faudrait-il pas que je les actives sur pc ? Il y a peut-être conflit ?

**Comment by Aymkdn** [comment]
PC ou appli, c'est la même chose.

C'est très bizarre tout ça quand même....

Tu as changé l'applet pour le changement de chaine ?

**Comment by taikun78** [comment]
Non ,j’ai pris ton applet, par contre je viens de m’apercevoir que je ne peux plus non plus allumer mes lumières et que la Google box me dit « ok je zappe allume les lumières « mais rien ne se passe...

**Comment by Aymkdn** [comment]
Je pense que tu as une applet avec "Say a phrase with a text ingredient" qui a merdé...  du coup ça aspire tout ce que tu dis.

Normalement l'applet "Zappe" ressemble à ça : 
![capture](https://user-images.githubusercontent.com/946315/35568784-654dddc4-05ca-11e8-8669-179236361a5c.PNG)

le `$` est très important car ça analyse ce que tu dis...

Donc vérifie tes applets ! Quitte à supprimer celles que tu as créées et à remettre les miennes par défaut, sans en changer la phrase de déclenchement

**Comment by taikun78** [comment]
Bon j’ai tout supprimé et j’ai relancé tout les applets sans les modifier. Ça fonctionne 👍. Je pense que je vais rajouter les phrases de lancement applets par applets en testant chaque applet après modif, je pense que comme ça j’arriverai a trouver le truc qui coince , je te tiendrai au courant.
Quoi qu’il en soit merci à toi pour ton aide, ça fait énormément plaisir d’avoir comme interlocuteur quelqu’un qui sacrifie son temps pour un novice comme moi. 
À bientôt

**Comment by Aymkdn** [comment]
Avec plaisir :-)

Je ferme l'issue, et si besoin tu peux reposter ici !
