### ISSUE TITLE
Aucune réaction de google home sur la Freebox.

### ISSUE THREAD

**Issue by ReLoAdEdM59** [Aymkdn/assistant-plugins#94]
Bonjour à tous.

Voilà hier j'ai installé assistant plugins pour controller la Freebox avec mon google home mini.
J'ai tous fait dans l'ordre mais lorsque je lance start.bat et que je choisis un ifft pour faire une action, google home mini répond à l'action mais ne fait rien sur la freebox.

Voici un screen de ma command 

![2018-02-02](https://user-images.githubusercontent.com/36072777/35730803-bbc2e1e0-0813-11e8-8194-66e45362de3a.png)

Après je me demande si la dernière mise à jour du freebox server n'y est pas pour quelque chose ?
Je peu me tromper mais bon je suis perdu.

Merci de votre aide.

**Comment by Aymkdn** [comment]
Comme indiqué sur [cette page](https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fr%C3%A9quentes) est-ce que tu peux aller sur le site https://www.pushbullet.com/#following/ puis cliquer sur IFTTT et faire une capture d'écran pour me montrer ce que tu as ?

**Comment by ReLoAdEdM59** [comment]
Voilà
![2018-02-02 1](https://user-images.githubusercontent.com/36072777/35732886-7fc69026-081b-11e8-9854-d7f5c47ffd5d.png)

Par contre je n'avais pas vu la FAQ sur le site. Et je viens de voir que j'ai des erreurs.
![2018-02-02 2](https://user-images.githubusercontent.com/36072777/35732994-d9ebbe28-081b-11e8-884b-43f8d8030b8b.png)

**Comment by Aymkdn** [comment]
Ah, tu utilises un vieux compte Pushbullet on dirait. Essaie peut-être cela : 

1. Disconnect ton compte Pushbullet de IFTTT en allant là https://ifttt.com/services/pushbullet/settings
2. Supprime ton compte Pushbullet en allant sur https://www.pushbullet.com/#settings
3. Recrée un compte Pushbullet
4. Réassocie IFTTT à Pushbullet

Pour info je vais partir là et conduire ces 4 prochaines heures, puis week-end au ski, donc je risque de mettre du temps à te répondre.

**Comment by ReLoAdEdM59** [comment]
Ok je vais essayer.
T’inquiète je comprend j'attendrais que tu me répond si j'ai encore des erreurs. Mais j’espère que sa sera corriger. merci beaucoup.

**Comment by ReLoAdEdM59** [comment]
Super sa fonctionne parfaitement. Je me souviens quand décembre j'avais commencer à faire l'installation mais j'avais abandonner.

Merci encore
