### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by titithebad** [Aymkdn/assistant-plugins#95]
Salut,

Si npm est déjà installé sur le RPi, faut il faire npm install --loglevel error ?

Merci

**Comment by titithebad** [comment]
Dernière version mise à jour ce matin : 5.6.0

**Comment by titithebad** [comment]
Voilà l'erreur que j'ai chez moi 

> assistant-plugins-project@2.0.0 postinstall /home/pi/googlehome_free/assistant-plugins
> node ./postinstall.js

[assistant] Installation terminée.
module.js:538
    throw err;
    ^

Error: Cannot find module 'jsonfile'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/googlehome_free/assistant-plugins/postinstall.js:34:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-plugins-project@2.0.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-plugins-project@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output a                                                                                           bove.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-04T16_43_26_741Z-debug.log

**Comment by Aymkdn** [comment]
C'est une très vieille version que tu as. Suis le tutoriel https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

**Comment by titithebad** [comment]
Pour l'instant aucun soucis avec cette version... Je regarde si il y a des versions plus récentes Pour Raspberry PI.

En attendant j'ai cela comme erreur :
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Demande d'autorisation auprès du Freebox Server...
[assistant-freebox] Approuvez le plugin en allant sur l'écran LCD de votre Freebox Serveur et en utilisant la flèche de droite sur celui-ci.
[assistant-freebox] Le plugin a été autorisé sur la Freebox
[assistant-freebox] Configuration terminée. Vous êtes prêt à utiliser le plugin Freebox.
[assistant-freebox] Récupération des chaines télé...
[assistant-freebox] Configuration sauvegardée.
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
**[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Erreur : vous devez configurer ce plugin !**

**Comment by titithebad** [comment]
Bon c'est corrigé et voilà l'errreur 👍 node index.js
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines terminée !
[assistant-freebox] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Server responded with a non-101 status: 401 Unauthorized
Response Headers Follow:
date: Sun, 04 Feb 2018 20:28:13 GMT
content-length: 0
content-type: text/plain; charset=utf-8

    at WebSocketClient.failHandshake (/home/pi/googlehome_free/assistant-plugins/node_modules/websocket/lib/WebSocketClient.js:326:32)
    at ClientRequest.<anonymous> (/home/pi/googlehome_free/assistant-plugins/node_modules/websocket/lib/WebSocketClient.js:265:18)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
pi@bureau:~/googlehome_free/assistant-plugins $

Une idée ?

**Comment by Aymkdn** [comment]
Tu as mis à jour ta version de Node comme je te l'ai dit ? Tu dois au moins utiliser la v8

**Comment by titithebad** [comment]
Non. Est-ce un soucis node ou un soucis Fbx ? Car là j'ai pas l'impression que ca soit un soucis Node.

J'ai d'autres applications qui tournent avec node donc pas simple à changer....

Ou bien je fais cela sur un autre Rpi :) !

**Comment by Aymkdn** [comment]
Si tu suis le tutoriel que je t'ai donné, la version de Node est installée localement et ne devrait pas interférer avec tes autres programmes qui utilisent le vieux Node que tu as déjà.

Le truc c'est que je ne peux pas certifier que le problème ne vient pas de là tant qu'il n'a pas été mis à jour :-)

**Comment by titithebad** [comment]
Ok ! Je fais sur un de mes autres Rpi :) !

Je te dis quand c'est fait...

**Comment by titithebad** [comment]
même résultat... Qui remonte cette erreur en fait ? Pushbullet ?

**Comment by Aymkdn** [comment]
Oui de la connexion avec Pushbullet... Essaie peut-être de créer un nouveau token Pushbullet ?

Je n'ai jamais vu cette erreur avant...

**Comment by Aymkdn** [comment]
Si le nouveau token Pushbullet ne fonctionne pas, est-ce que tu as une configuration réseau spéciale ? Genre un proxy ou autre qui pourrait bloquer la connexion ?

**Comment by titithebad** [comment]
La connexion avec Pushbullet ne se fait que via ce token ? Pas de mdp ou autre ? Comment tester que le token est bon autrement que via ton script ?

Non pas de proxy. Mon RPi est derrière un routeur qui est derrière une Fbx.

**Comment by Aymkdn** [comment]
Non pas de mot de passe, juste le token fourni par Pushbullet. Pas moyen de le tester, mais pas de raison qu'il ne fonctionne pas.

L'erreur est toujours exactement la même ? Que ce soit sur tes 2 Rpi ?

Est-ce que tu as un Windows par exemple ou un MacOS sur lequel tu peux tester et voir si ça vient de ta connexion / compte Pushbullet.... car il y a plein d'utilisateurs de RaspPi et ça marche chez tout le monde....

**Comment by titithebad** [comment]
Même erreur sur les 2 RPi mais avec le même token. Je vais changer le token. J'ai du merder quelque part... Il y a toujours l'ambiguité avec les i, I, 1 et l sous linux.... Donc je vais prendre un autre token où il n'y a pas ce soucis.

Je vais tester cela et je te dis !

Merci pour ton support

**Comment by Aymkdn** [comment]
T'as réussi ?

**Comment by titithebad** [comment]
Je vais essayer d'avancer ce WE

**Comment by Aymkdn** [comment]
Non on ne récupère pas le prompt. Tu peux le lancer avec & mais je te conseille plutôt d'utiliser un truc comme `pm2` comme expliqué sur le site !

**Comment by titithebad** [comment]
D'accord. Je vais regarder pm2 en effet.

Dans tous les cas, je n'ai plus l'erreur ;) !!!

Je regarde et je continue à tester !

**Comment by titithebad** [comment]
Alors sur l'installation de pm2, je rajouterais bien quelque chose dans ton tuto : création du lien symbolique de pm2 dans /usr/bin non ?

**Comment by Aymkdn** [comment]
Normalement non y'en a pas besoin.

**Comment by titithebad** [comment]
OK, moi j'en ai eu besoin...

Je vais tester avec la Fbx maintenant

**Comment by titithebad** [comment]
Tu peux me rappeler les plugin à installer ? JE vous dans ton tuto 2 et moi j'en ai qu'un d'installé. De plus ca ne fonctionne pas donc j'ai du en oublier un... Google home me dit "Et là c'est le bug...)

J'ai pris que freebox.

**Comment by Aymkdn** [comment]
Tu n'as besoin que du plugin Freebox. Tu peux aussi installer `notifier` mais c'est totalement optionnel.

Si Google Home dit "et là c'est le bug", c'est que l'applet IFTTT n'a pas été activée (ou alors faut attendre quelques secondes et réessayer)

**Comment by titithebad** [comment]
Comment activer l'applet IFTTT ? J'ai créé le compte et guere plus...

**Comment by Aymkdn** [comment]
Bhein c'est écrit dans la documentation.... https://aymkdn.github.io/assistant-plugins/?plugin=freebox#utilisation

**Comment by titithebad** [comment]
C'est bien ca. Exemple pour le son : ca coupe le son et ca le remet de suite apres. C'est la même chose pour les autres commandes comme eteins... Une idée ?

**Comment by Aymkdn** [comment]
Tu as dû lancer le programme 2 fois, donc ça envoie les commandes deux fois :-)

**Comment by titithebad** [comment]
Ahahahahah :) ! C'est ca ! Reboot du rpi et ca fonctionne en effet :) !

**Comment by Aymkdn** [comment]
Cool. Je ferme donc ton issue. N'hésite pas à reposter ici si tu as d'autres questions/soucis
