### ISSUE TITLE
Erreur lors du lancement

### ISSUE THREAD

**Issue by baharroth62** [Aymkdn/assistant-plugins#96]
Bonjour,

Quand je lance la commande node index.js j'obtiens l'erreur 

root@jeedom:~/assistant-plugins# node index.js
[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
{ Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /root/assistant-plugins/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/root/assistant-plugins/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/root/assistant-plugins/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32) code: 'MODULE_NOT_FOUND' }

Est ce que quelqu'un voit ou j'ai merdé ?
Je suis sur Raspberry Pi

D'avance merci

**Comment by Aymkdn** [comment]
Tuesday utilises une version trop vieille de Node. Suis le tutoriel https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi#8-mettre-en-t%C3%A2che-de-fond-optionnel

**Comment by Aymkdn** [comment]
Ou alors tu as oublié une étape en l'occurrence : `npm install --loglevel error && npm run-script postinstall`

**Comment by Aymkdn** [comment]
Tu as pu résoudre ton problème ?

**Comment by baharroth62** [comment]
Je n' ai pas eu le temps de me pencher dessus. Je regarde ça ce soir.

**Comment by Aymkdn** [comment]
Alors, ça donne quoi ?

**Comment by baharroth62** [comment]
j ai désinstallé node et refait toute l installation ca me fais pareil. je
dois avoir un problème autre part.

**Comment by Aymkdn** [comment]
Tu as quelle version de Node ? Quand tu fais `node -v` ?

**Comment by baharroth62** [comment]
J ai pris la version 9.3.0

**Comment by Aymkdn** [comment]
Tu peux me montrer ce que tu as dans ton fichier package.json ?

**Comment by baharroth62** [comment]
{
  "name": "assistant-plugins-project",
  "version": "2.0.0",
  "description": "Utilisé pour gérer le project",
  "main": "index.js",
  "repository": "https://github.com/Aymkdn/assistant-plugins",
  "private": true,
  "dependencies": {
    "assistant-freebox": "^2.0.7",
    "assistant-plugins": "latest",
    "jsonfile": "^4.0.0",
    "request-promise-native": "^1.0.5"
  },
  "scripts": {
    "postinstall": "node ./postinstall.js"
  },
  "author": "aymkdn",
  "license": "MIT"
}


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-07 21:20 GMT+01:00 Aymeric <notifications@github.com>:

**Comment by Aymkdn** [comment]
OK essaie : `npm install request` toujours dans le même répertoire. 

Puis relance le programme

**Comment by baharroth62** [comment]
merci beaucoup !

**Comment by Aymkdn** [comment]
C'est bon ?

**Comment by baharroth62** [comment]
oui ca fonctionne nickel ! merci

**Comment by baharroth62** [comment]
nickel c était ca ! le npm install request a refaire
