### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by lebonphilippe** [Aymkdn/assistant-plugins#97]
Bonsoir j’ai du mal à fermé là Freebox et à ouvrir avec la voix pourtant les changements de chaîne fonctionne aussi -et+ du son est-ce au changement apporté par free

Merci d avance

**Comment by Aymkdn** [comment]
J'ai du mal à comprendre ce que tu racontes...

> j’ai du mal à fermé là Freebox et à ouvrir avec la voix

J'imagine que tu veux dire "éteindre la Freebox" et "allumer la Freebox" ? Tu veux dire quoi par "j'ai du mal" ? C'est extrêmement vague...

**Comment by Aymkdn** [comment]
Pas de retour donc je ferme cette issue.
