### ISSUE TITLE
La commande "zappe sur une chaîne" fonctionne mal

### ISSUE THREAD

**Issue by Moustic56** [Aymkdn/assistant-plugins#98]
Bonjour,

Lorsque je demande la chaîne entre 1 et 9, le numéro de chaîne est doublé : 11, 22, 33...
J'ai essayé en disant TF1 ou M6, c'est la même chose.

[assistant] Appelle du plugin 'freebox'
[assistant-freebox] Durée de la vérification de la Freebox allumée : 1222ms
[assistant-freebox] Url => http://hd1.freebox.fr/pub/remote_control?code=13402091&key=6
[assistant-freebox] Commande « zappe sur la 6 » exécutée

et c'est la chaîne 66 qui est lancée.

Y a t il moyen d'éviter cela ?
Merci :)

PS : C'est top quand même votre assistant, j'adore :)

**Comment by Aymkdn** [comment]
Tu as bien une Freebox Révolution ?

Tu utilises Freebox TV ou les Chaînes Canal ?

Tu es sûr que tu n'as pas lancé deux fois le programme ?

**Comment by Moustic56** [comment]
Oui la Revolution, les chaînes Freebox, pas d'ado Canal+.

A priori oui , j'avais 2 consoles...je pensais qu'il fallait lancer le prog "start.bat" à chaque fois pour activer les commandes.

**Comment by Aymkdn** [comment]
Au redémarrage soit tu relances start.bat soit tu peux utiliser pm2 (comme expliqué en bas du site).

À priori je penche sur le fait que tu as lancé deux fois le programme !

**Comment by Moustic56** [comment]
Effectivement c'était bien la cause de mon problème. Merci pour ton aide.
